### ISSUE TITLE
(Bug Report) Glitched Colors

### ISSUE THREAD

**Issue by gabrielm3101456** [Backdash/MonikaModDev#1008]
I found a glitch on Monika After Story! To do the glitch you have to:

1-Start the game Then go to the settings
2-After that do alt+tab
3-Then click on the time of the computer
4-Go to the change date and time settings and go a day ago
5-Go back to the game and it will be all bugged.But if you return to the game the bug will vanish

Also sorry for my bad english i'm brazilian and don't know much english =D

**Comment by gabrielm3101456** [comment]
also here is what it looks like https://prnt.sc/ie8do4

**Comment by antimockingjay** [comment]
Considering what game this is, I'd almost say it's more of a feature than a bug, but that's just me.
