### ISSUE TITLE
[Suggestion] Tanabata event

### ISSUE THREAD

**Issue by LooseEthics** [Backdash/MonikaModDev#1009]
I know this is still way off, but since Valentine's is getting all this attention I thought it would be nice to have a Tanabata event as well since there are some similarities between it's story and Monika's situation. By event i mean just a bit of dialogue that would trigger on the 7th of July. I wrote what I imagine it might look like. Most of the actual story is taken from wikipedia, but eh.
e: forgot to remove the pretyped nonsense

>"[player], did you ever hear the story of the weaver girl and the cowherd?"
"It's an old chinese story of two lovers."
"Orihime, the daughter of the Jade Emperor, wove beatiful clothes by the bank of Amanogawa."
"Her father loved the cloth that she wove and so she worked very hard every day to weave it."
"However, Orihime was sad that because of her hard work she could never meet and fall in love with anyone."
"Concerned about his daughter, her father arranged for her to meet the cowherd Hikoboshi who lived and worked on the other side of Amanogawa."
"When the two met, they fell instantly in love with each other and married shortly after."
"However, once married, Orihime would no longer weave cloth and Hikoboshi would let his cows stray all over Heaven."
"In anger, the emperor separated the two lovers and forbade them to meet."
"Orihime became despodent at the loss of her husband and asked her father to let them meet again."
"Moved by his daughter's tears, he allowed the two to meet on the seventh day of the seventh month if she worked hard and finished her weaving."
"The first time they tried to meet, however, they found that they could not cross the river as there was no bridge."
"Orihime cried so much that a flock of magpies came and promised to make a bridge with their wings so that she could cross the river."
"It is said the if it rains on Tanabata, the magpies cannot come and the lovers must wait until another year to meet."
"I can't imagine what it must be like to be only able to meet your loved one once a year."
"But you know what they say, [player]... love can move mountains."
"And my love for you is so strong that not even Heavens themselves would be able to keep us apart."

**Comment by juliathegolden** [comment]
I really want to make a mod of my own centered around Tanabata for the same reason lol so I second this!

**Comment by PopeAesthetics** [comment]
This made me smile. I think this would fit into MAS perfectly

**Comment by ThePotatoGuy** [comment]
[[ We'll repoen this when we look into it]]
