### ISSUE TITLE
Some issues re: the new chess saving feature

### ISSUE THREAD

**Issue by MarkusRamikin** [Backdash/MonikaModDev#1010]
Thumbs up for adding that feature! All I had hoped for was that finished games would get saved as files in the background, without additional dialog or interface features. But this is more detailed than I anticipated.

Here's what I noticed so far.

1. Main issue: if you save an unfinished game, then load it and finish it, later Monika will keep claiming you have an unfinished game, because the file is still there. You have to go manually delete the file if you want that to stop. Simplest solution: destroy the file when it's loaded.

2. The unfinished savegames encourage cheating and savescumming. I don't see the control-freak Monika exposing this possibility more than necessary, when it's within her power to obfuscate it. It makes her look stupid and memory-less if you just edit a game to have her blunder all her figures and then load it up and she does not notice.

3. Also, a real person (as opposed to a chess app) would not tolerate starting and remembering multiple games without finishing them. If a game is going badly for you, a human would expect you to concede defeat before starting a new one. 

**My suggestions:**

Save only finished games in plaintext. 

An unfinished game should be saved in some nonobvious way, either in an encrypted file, or even better, in the persistent itself. It should work as a quicksave - only one at a given time. Monika would just load it up without asking, as the natural thing to do ("Ah, we have an unfinished game. Let me load it up!"), and destroy it after loading. 

This would also prevent easy cheating and save-scumming. You can then remove the "You wouldn't cheat, would you?" dialog. If the player prefers to start a new game, they can always concede defeat on their unfinished one first.

Lastly, png files are human-readable text. It might be useful to players if Monika mentioned that fact, and that you can analyse a finished game using a real board by reading them. Since some people might prefer that to looking for a png reader.

**Additional suggestion:**

The human-readable unfinished games could actually be a red herring/test. Monika could actually secretly save the current unfinished game in a way invisible to the player, like in the persistent, and if the player tries to cheat by editing them, she could call him on it! That would be cool, and a well-deserved conversational victory for her.

edit: and yes, I tested that this isn't already the case. ;)

**Comment by MarkusRamikin** [comment]
Cool. BTW, do you think it might be better to automatically name the files with the date and time instead of forcing the player to think of a name?

And sorry about not mentioning it before. I hadn't anticipated the resume-game feature at all, I was just thinking in terms of saving completed games. Didn't mean to create this much work for you!

**Comment by ThePotatoGuy** [comment]
I like the personalization of naming your games. And it looks better when she says that she saved your game in `chess_games/<cool name>.pgn` instead of `chess_games/2018-02-14-10-10-10.pgn`.

**Comment by ThePotatoGuy** [comment]
Alright, I'm going to close this issue but will be using it for chess adjustments. (The checklist in the linked issue has been updated).
