### ISSUE TITLE
Prompts not coming up in repeat conversation menu

### ISSUE THREAD

**Issue by Onion-Bubs** [Backdash/MonikaModDev#1011]
So I've noticed that sometimes Monika will talk about a topic and then I won't be able to find the prompt for it anywhere in the repeat conversation menu. Examples of this include the "owning pets" topic where Monika says what pet she'd like, the topic about the player's family where you tell Monika what your family situation is like, and the topic where Monika says her family was controlled by the script and then quotes Tolstoy.

At first I thought this might be a bug new to version 0.7.1 but I could've sworn I had the last of those topics come up before today.

**Comment by williamjcm** [comment]
Same here. I have this issue with the Repeat Convo → "Romance" → "Engagement ring" topic, among others.

**Comment by ThePotatoGuy** [comment]
Is it still missing upon relaunch?

**Comment by Onion-Bubs** [comment]
Yes, the topics are still missing from the repeat conversation menu on relaunch.

**Comment by ThePotatoGuy** [comment]
I've found the issue and will push a fix.

**Comment by williamjcm** [comment]
@ThePotatoGuy 
Thanks a lot. I even tried to add the topics to the menu with the dev console, but I couldn't do it.
