### ISSUE TITLE
A cute idea I had for the Hangman game

### ISSUE THREAD

**Issue by CommenterOfComments** [Backdash/MonikaModDev#1012]
This is really something simple I had in my mind that I felt like throwing out there. What if there was a rare chance of Monika picking your own name as a word for hangman, and saying she likes that word the most? I just thought that might be a sweet thing for Monika to do, I don't actually know how the hangman game works or if that's even possible to do.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Player name can be up to like 30 characters tho.

**Comment by CommenterOfComments** [comment]
Maybe some sort of filter to prevent it happening with longer names?

**Comment by queue5** [comment]
I love that idea!

**Comment by MarkusRamikin** [comment]
What would be the hint? "Monika would like this word the most"? ;) Would kinda give it away...

Unless we gave her a whole bunch of words, but I imagine they would overlap with Yuri quite a bit.

**Comment by ThePotatoGuy** [comment]
We'd probably make this only happen once.

**Comment by ThePotatoGuy** [comment]
I've added it in, and the length limit is 15
