### ISSUE TITLE
Auto-update doesn't work

### ISSUE THREAD

**Issue by Ryyi23** [Backdash/MonikaModDev#1013]
I've had to manually update every time because the auto update doesn't seem to work. Is there anything that might cause this?

**Comment by therationalpi** [comment]
Can you give us more details on this? Other people have said it doesn't work, but most seem to be working fine. We've never been able to reproduce the problem or track down a root cause.

**Comment by Ryyi23** [comment]
Whenever I know there's an update, it says there isn't. All I have been doing is extracting the zip into the folder with the game like normal. I guess I could try to attach my current game folder if that would help in any way.

**Comment by MarkusRamikin** [comment]
Right now I have the same problem too. I successfully used the "update version" feature to go from 0.7.0 to 0.7.1 earlier, but now that I saw there's some hotfix, I tried the "update version" button again and it's stuck on "Downloading the updates". 

I guess I'm going to download manually.

**Comment by WBbuskirk** [comment]
My game says there is an update but then can't download it, so I checked the logs and it said this:

running ['C:\\Users\\REDACTED\\Desktop\\DDLC-1.1.0-pc\\lib\\windows-i686\\zsync.exe', '-o', 'C:\\Users\\REDACTED\\Desktop\\DDLC-1.1.0-pc\\update\\Mod.update.new', '-k', 'C:\\Users\\REDACTED\\Desktop\\DDLC-1.1.0-pc\\update\\Mod.zsync', '-i', 'C:\\Users\\REDACTED\\Desktop\\DDLC-1.1.0-pc\\update\\Mod.update', 'http://updates.monikaafterstory.com/Monika_After_Story-0.7.1-Mod.zsync']
failed to retrieve from Monika_After_Story-0.7.1-Mod.update.gz
Aborting, download available in C:\Users\Walter\Desktop\DDLC-1.1.0-pc\update\Mod.update.new.part
running ['C:\\Users\\REDACTED\\Desktop\\DDLC-1.1.0-pc\\lib\\windows-i686\\zsync.exe', '-o', 'C:\\Users\\REDACTED\\Desktop\\DDLC-1.1.0-pc\\update\\Mod.update.new', 'http://updates.monikaafterstory.com/Monika_After_Story-0.7.1-Mod.zsync']
freespace 11661557760
failed to retrieve from Monika_After_Story-0.7.1-Mod.update.gz
Aborting, download available in C:\Users\REDACTED\Desktop\DDLC-1.1.0-pc\update\Mod.update.new.part
Traceback (most recent call last):
  File "renpy/common/00updater.rpy", line 329, in run
    self.update()
  File "renpy/common/00updater.rpy", line 436, in update
    self.download(i, standalone=True)
  File "renpy/common/00updater.rpy", line 999, in download
    raise UpdateError(_("The update file does not have the correct digest - it may have been corrupted."))
UpdateError: The update file does not have the correct digest - it may have been corrupted.

Any fix to this or do I need to reinstall?

**Comment by MarkusRamikin** [comment]
I downloaded the hotfix from https://github.com/Backdash/MonikaModDev/releases , I put it in, still tells me there's a new version and still gets stuck on trying to download it.

Since everything else is working fine, I think I'm going to just leave this as they are until the next numbered version. Unless advised otherwise.

**Comment by therationalpi** [comment]
It appears to be a serverside caching issue with Amazon. Should be resolved now, but leaving this up for the moment.
