### ISSUE TITLE
Why is MAS an absolute nightmare to get to work?

### ISSUE THREAD

**Issue by Periah250** [Backdash/MonikaModDev#1015]
So I got it to work before and once the large update 7 came out the auto updater broke, I figured it would. But after watching a tutorial online and reaffirming it with a step by step instruction guide I tried to reinstall it on a clean itch.io download. my first sign something was amiss was when I didn't need to overwrite or merge anything, despite following the instructions.

**Comment by ThePotatoGuy** [comment]
Auto-updater seems to be brokeded. Manual updates are your best bet, and yeah, it should overwrite files. The usual issue is that you've extracted the files in a subfolder in `game/` instead of directly into `game/`.

To report update issues or for status updates on updates, go to #1013
