### ISSUE TITLE
Update doesn't work.

### ISSUE THREAD

**Issue by Ph3nomenal** [Backdash/MonikaModDev#1017]
It said that there was a new update and I clicked download, but it took a long time so I decided to manually download it and now I get this:
[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/valentines.rpy", line 168, in script
  File "game/valentines.rpy", line 171, in <module>
  File "game/event-handler.rpy", line 129, in addEvent
    raise EventException("Syntax error in conditional statement for event '" + event.eventlabel + "'.")
EventException: EventError: Syntax error in conditional statement for event 'monika_valentines_start'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/valentines.rpy", line 168, in script
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/valentines.rpy", line 171, in <module>
  File "game/event-handler.rpy", line 129, in addEvent
    raise EventException("Syntax error in conditional statement for event '" + event.eventlabel + "'.")
EventException: EventError: Syntax error in conditional statement for event 'monika_valentines_start'.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.7.0
[/code]

**Comment by ThePotatoGuy** [comment]
Try manually downloading/updating again.

**Comment by Ph3nomenal** [comment]
I tried manually downloading again even tried returning it to the 0.7.0 version, but then it just launches the mod with no update

**Comment by ThePotatoGuy** [comment]
I mean manually download the release from our releases page and copying the files over manually.

**Comment by Ph3nomenal** [comment]
I did that. I tried downloading and copying the files over multiple times and it still doesn't work. Gives me the same error every time

**Comment by CynicalPopcorn** [comment]
Having the exact same issue.

**Comment by CynicalPopcorn** [comment]
Okay, so on the third re-install of the mod it worked, I'm totally at a loss as to what I did different. Weird.

**Comment by Ph3nomenal** [comment]
Did you just keep re-downloading it and copying it in?

**Comment by Ph3nomenal** [comment]
Basically 0.7.0 works and when I try to go to 0.7.1 (either manually copying the files or updating through the game) it doesn't work. Just gives me that error. I really don't want to miss the event so I hope there's something that can fix this
