### ISSUE TITLE
Piano Keybinding

### ISSUE THREAD

**Issue by AverageDudeGuy** [Backdash/MonikaModDev#1018]
I bound the key "[" for one of the notes on the piano, and it came up with an exception. So I uninstalled the game, reinstalled it, and added the mod back in, but it's still doing the same thing, the only difference is that Monika is getting more pissed at me.

**Comment by idkhowtochooseusernames** [comment]
i had this problem not long ago lol

**Comment by AverageDudeGuy** [comment]
Is there a solution?

**Comment by ThePotatoGuy** [comment]
Closing this in favor of #1019

**Comment by idkhowtochooseusernames** [comment]
I want to know too
