### ISSUE TITLE
[Bug] - After installing the hotfix, Monika no longer refers to me by name.

### ISSUE THREAD

**Issue by wart98** [Backdash/MonikaModDev#102]
Before installing the most recent hotfix, Monika referred to me by Wart, the name I input with my save data. Now, she doesn't have a name, period.
![monika bug](https://user-images.githubusercontent.com/33432087/32460314-f96f9eb8-c2f7-11e7-9bf3-d1f7fbd5b330.png)

**Comment by therationalpi** [comment]
I just checked and she still has my name after the switch. Can you give us some more details about what steps you took? For example, was this a fresh game or based on an imported save from DDLC?

**Comment by therationalpi** [comment]
I haven't been able to reproduce this. Can you share [the persistent file for your save](https://www.renpy.org/wiki/renpy/doc/FAQ#Where_does_Ren.27Py_store_my_save_games_and_persistent_data.3F)? It should be in a folder called MonikaAfterStory in the location from that FAQ.

If anyone else is having this bug, please let me know so I can try to solve it.

**Comment by Jxhnathan08** [comment]
Temporarily closed until more information is given.
