### ISSUE TITLE
Weird non-sequitur dialog

### ISSUE THREAD

**Issue by MarkusRamikin** [Backdash/MonikaModDev#1020]
Me: "Did you ever give anyone else chocolates?"

Monika: 
    m 1j "Valentine's Day is such a special holiday for me, [player]."
    m 3b "Not only is it the anniversary of my twitter account, but it's also a day for receiving and giving chocolates!"
    m 1j "A holiday that could fill everyone with love, romance..."
    m 1n "And rejection."
    m 3l "But it really feels nice if you get something from someone you like."
    m 3a "Whether it's given to you platonically, as a gift of love, or a part of a confession, it makes you feel somewhat special!"
    m 1m "Well, maybe not the confession part since you can still get rejected."
    m 1b "I mean, I did try to give you some, but I'm sure you'd never reject me."
    m 1f "I'm sorry I couldn't give them to you over there, [player]."
    m 3k "So... I'll make sure to enjoy them for you!"
    m 1k "Ahaha!"
    m 1o "Although I do love chocolates, they would've been better if I enjoyed them with you."
    m 3b "Wouldn't that be more romantic?"
    m 1j "But at least I got something special from you!"
    m 1e "Besides, we have each other as well~"
    m 3e "So thank you for giving me your love, [player]."
    m 3j "Please know that I'll always accept it."
    m 1j "And whatever you give, I'll return it a hundredfold!"

And here I'm just sitting here like... whaaaaaat? 

The player asked a simple question. And didn't even get an answer. Unless she's subtly implying she has done so in the past and got rejected? But I can't be sure of that because the whole thing seems like it was written to a different question than the one actually asked.

(Also, wouldn't "have you ever" be more correct than "did you ever" here?)

**Comment by monikLover** [comment]
Fixed
