### ISSUE TITLE
No more options for me to start conversation? 

### ISSUE THREAD

**Issue by Valllaion** [Backdash/MonikaModDev#1021]
I'm not sure if I've just run out of options to start conversations or if the update bugged it... I don't feel as if I've run out though it hasn't been that long that I've been playing

**Comment by Bam8647** [comment]
Same here. I barely have the game running and only 1-2 topics are brought up until she then says that she no longer knows what to talk about.. Definitely a bug.

**Comment by ThePotatoGuy** [comment]
There weren't many general random topics added in this update.
