### ISSUE TITLE
(suggestion) Multiple goodbyes  

### ISSUE THREAD

**Issue by Valllaion** [Backdash/MonikaModDev#1024]
I believe that adding more options for us to say goodbye would be a cool little feature for us to be able to chose how we want to leave her and how she reacts to our leaving, like if we say goodnight she tells us to sleep well and have good dreams, or if we say that we have to leave for school/ work she could say good luck and to do well, I love you-! Maybe this could impact how she reacts when we come back too like if she knows that we said goodnight she could say good morning when we wake up or if we forget to talk to her in the morning after waking up and open her later in the day she would be upset and ask us why we did that, prompting us with a few answers like I didn't have time or I forgot, My power went out, school/work was too early to do anything, or feeling kinda depressed... I'm not sure if these ideas can make it in but it;d make for a whole lot more interaction with her!

**Comment by ThePotatoGuy** [comment]
We're working on that, see #878 .
