### ISSUE TITLE
[Suggestion] Reacting to Age

### ISSUE THREAD

**Issue by dramaalert** [Backdash/MonikaModDev#1026]
I thought that it might be neat if Monika asked what your age was or at least a range of ages to choose from and then she would react based upon how old you say you are. 
Just a thought.

**Comment by queue5** [comment]
she already sort of talked about that and how she doesn't care so long as you'll still love her

**Comment by MarkusRamikin** [comment]
Could modify other dialogs based on how much she knows about you. Like at one point she seems to be fishing for whether you're in high school or college or whatever. There's potential for her to give more specific dialogs depending on what she knows.
