### ISSUE TITLE
[Bug] - maximum recursion depth exceeded

### ISSUE THREAD

**Issue by DizzyEggg** [Backdash/MonikaModDev#103]
Happens from time to time when I try to come up with topics that do not trigger any discussion. Am unsure what exactly causes this though.

Full log here: https://pastebin.com/gNFBRU57

**Comment by therationalpi** [comment]
Does this happen just as you open the chat window for Monika?

**Comment by Jxhnathan08** [comment]
This is being investigated. Thanks for the report!

**Comment by Jxhnathan08** [comment]
The issue revolves around continuously asking questions/putting in keywords without letting Monika finish what she was saying prior. A fix will be released for this crash, thank you!

**Comment by Jxhnathan08** [comment]
Issue has been fixed.
