### ISSUE TITLE
Weird art?

### ISSUE THREAD

**Issue by IlywI** [Backdash/MonikaModDev#1031]
![image](https://user-images.githubusercontent.com/23725018/36188673-8827cd86-1188-11e8-97d6-aaf5d1df78b9.png)
It makes it look like Monika's arm is super short... (like she has trex arms)

**Comment by ThePotatoGuy** [comment]
Yeah, she's actually a T-Rex. Did you not know?

**Comment by IlywI** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO :(
