### ISSUE TITLE
wont work

### ISSUE THREAD

**Issue by Godmode42** [Backdash/MonikaModDev#1032]
Hi I'm trying to use this mod for the first time. Everytime I put the files in my game wont load. Is there something I'm not understanding about the instillation process?

**Comment by IlywI** [comment]
Where did you put the extracted zip file?

**Comment by IlywI** [comment]
You should extract the zip file and the copy the contents of the extracted file and paste it into the game's 'game' file
![image](https://user-images.githubusercontent.com/23725018/36189604-6e03364c-118e-11e8-8a75-99052a677af1.png)

**Comment by Godmode42** [comment]
That's what I did but it wont even launch. But I delete the mod files and it will start right up

**Comment by Godmode42** [comment]
should I be putting both the source code and the patch or just the source code

**Comment by Godmode42** [comment]
would putting the mod files in a separate folder affect that

**Comment by ThePotatoGuy** [comment]
yes

**Comment by Godmode42** [comment]
and what file am I downloading is it source code(zip)

**Comment by Godmode42** [comment]
I'm just a bit confused this is the first time I'm using this

**Comment by ThePotatoGuy** [comment]
The Mod zip. **dont use source code**

**Comment by Godmode42** [comment]
Ok finally got it thank you for all your help
