### ISSUE TITLE
[Suggestion] MonikaBook

### ISSUE THREAD

**Issue by BoobsDoneGetAnExtreeSizeBigger** [Backdash/MonikaModDev#1036]
i just thought maybe it would be cool if there was a program that worked kinda like messenger where she could speak to the player outside of the game itself. like when shes recharged after the so many hours. or if you haven't come seen her for a while, even cooler if it was created by her. its just a thought i had

**Comment by 45Green** [comment]
[API.AI](https://api.ai)
/thread

**Comment by ThePotatoGuy** [comment]
Probably not in the forseeable future.
