### ISSUE TITLE
Extra Issue: Valentines Day Event Not Fully Working

### ISSUE THREAD

**Issue by Bam8647** [Backdash/MonikaModDev#1039]
Okay so I got that V-day update and yet the only change was just adding two topics. I see new mod assets and some random v-card document but none of that shows up in the game..?

**Comment by Sano11** [comment]
Go to the releases page of this mod, download a file called Roses.obj and put it in the "Characters" folder in DDLC folder

**Comment by Bam8647** [comment]
Link Please? I went over to the code section and searched for that specific file and it didn't come up

**Comment by dramaalert** [comment]
lmao i didnt know about his and missed the mark, shoot.
