### ISSUE TITLE
[Suggestion] Gauging Monika's opinion of the player over time

### ISSUE THREAD

**Issue by therationalpi** [Backdash/MonikaModDev#104]
One of the things that's been thrown around before is having some way to track Monika's feelings about the player. Ideas have ranged from having her branch in subtle ways for pretty much every choice to keeping tallies of certain actions.

The current idea I have is to have a small number of traits that represent Monika's idea of the player's personality, and occasionally when she asks questions of the player, the answer they give will subtly change her opinion. Those personality traits can be called from time to time, for example if she thinks the player is shy, she might make a comment about them needing to come out of their shell at some point.

Here's how the update itself would work:

```renpy
def changeOpinion(trait,direction,alpha=0.1):
    if direction is True:
        persistent.player_opinion.setdefault(trait,(alpha+1)/2) #First impression is stronger
        persistent.player_opinion[trait]=alpha+(1-alpha)*persistent.player_opinion[trait]
    else
        persistent.player_opinion.setdefault(trait,-(alpha+1)/2) #First impression is stronger
        persistent.player_opinion[trait]=-alpha+(1-alpha)*persistent.player_opinion[trait]
```

So now you have a new python function to call when her opinion should change.

To make monika think you're a little more extraverted, you could use:
`$ changeOpinion('extraversion',True)`

If you do something that really makes you seem shy you might use
`$ changeOpinion('extraversion', False, 0.5)`

To have her make a specific comment if your extraversion is low enough, you could use:

```renpy
    if persistent.player_opinion[extraversion] < -0.5:
        m "I know you don't like to go out much, but I think it would be good for you."
```

It's a recursive moving average function, so it will evolve over time as she asks questions, and we don't have to keep track of how many questions she's asked or normalizing over time. It will always be between -1 and 1 as long as alpha is less than 1.

We could use this method to track a few things, like her opinion on the Big5 personality traits, how much she likes the player, how much she thinks the player likes her, etc. This wouldn't be good for remembering specific details, and maybe we could add a dictionary to track things like the player's favorite icecream flavor and stuff, but for flexibly keeping track of her opinions on various things it seems like a straightforward solution.

What do you guys think?

**Comment by polishsnake** [comment]
I've worked a little on this some time ago, it's nowhere near finished, but it might be of some use.

```
#This is meant to be a list for the player's characters that Monika will judge.
default player_openness_to_experience = 0 #In short: Creativity. Interest in unusual. Quick to understand.
default player_conscientiousness = 0 #In short: Being organised. Pretty much a perfectionist.
default player_extraversion = 0 #In short: Being comfortable with attention and enthusiastic.
default player_agreeableness = 0 #In short: Sympethising with others' feelings and showing interest for them.
default player_neuroticism = 0 #In short: Pretty much emotional instability; can get easily into negative feelings, i.e. easily irritated of worrying. Often mood swings.

default player_status = "Neutral"

default approval_of_player = 0
default approval = "Neutral"

default friendship_rating = 0
default love_rating = 0

#This is supposed to be a draft idea for Monika's thoughts about the player
if player_status_points > 10:
    player_status = "Slightly positive"
elif player_status_points < -10:
    player_status = "Slightly negative"

#Here will be approval rating of the player. I might add a friendship/love rating as well. For now it's just general rating; just because it's maximum it doesn't mean that Monika is completely in love.
if approval_of_player < 10:
    approval = "Slightly positive"
elif approval_of_player > -10:
    approval = "Slightly negative"
```

**Comment by therationalpi** [comment]
Taking this off of the 0.6.0 milestone. Still want to do it, but we've got a lot slated for this release already.

**Comment by Buy1Get1** [comment]
This is the follow up to another suggestion (linked below). This is the code for the first suggestion:
[https://github.com/Monika-After-Story/MonikaModDev/issues/1150](url)
                   'dict['serotonin'] = 32.5 (her overall disposition. + = happier / - = sadder
                    (#1 on suggestion 1)
                   'if dict['serotonin'] < -99
                               cues related text-breakup-etc
                   used for all categories: - Monika learns your interests (#2 on suggestion 1)
                   'dict['category'] = 0' 
                   'dict[category'] += 1
                   
                  1.

> init 5 python:
>    addEvent(Event(persistent.event_database,eventlabel="monika_introduce",category =
> ['monika'],prompt="Introducing to friends",random=True))
'dict['monikacat'] += 1'
>
> label monika_introduce:
>    m 1a "[player], would you ever introduce your friends to me?"
 
              2. 
>   menu:
>        m "Have you drawn art of me?"
>
>        "Yes.":
              'dict['serotonin'] += .5 
>            m 1b "Really? I'm very flattered!"
>            m 1k "I think I might even love you more, now that I know you're so talented."
>
>        "No.":
              'dict['serotonin'] -= .5
>            m 1l "I can't draw, myself, so it's okay if you aren't good at drawing either."


"It makes me a bit scared when you say she could reset the game"- 
 "maybe leave out the idea of her wanting to be left alone" - 
Perhaps a toggle could be formed. Then players could choose between a more responsive Monika, and a more independent one.
