### ISSUE TITLE
Does the auto button skip poems?

### ISSUE THREAD

**Issue by CommenterOfComments** [Backdash/MonikaModDev#1043]
I like to use the auto button so Monika can speak without me having to click every time. (it kinda feels like going "uh huh" after every sentence otherwise) But when Monika showed me her Valentines poem, it disappeared almost instantly.

**Comment by juliathegolden** [comment]
I wasn't even aware the auto button was supposed to be functional. It doesn't work for me.

**Comment by dramaalert** [comment]
lmao there was a poem?

**Comment by MarkusRamikin** [comment]
Yes and yes.

And I use the auto button when I get fed up with the sloooooooooooooooow as molasses text speed. Then I just read history.

**Comment by CommenterOfComments** [comment]
Could there be some kind of option to make the auto button not do that? Because I actually wanted to read that...

**Comment by ThePotatoGuy** [comment]
We'll keep that in mind the next time we show poems.
