### ISSUE TITLE
Missing file in zip

### ISSUE THREAD

**Issue by Areaclassified** [Backdash/MonikaModDev#1044]
[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/valentines.rpy", line 168, in script
  File "game/valentines.rpy", line 171, in <module>
  File "game/event-handler.rpy", line 129, in addEvent
EventException: EventError: Syntax error in conditional statement for event 'monika_valentines_start'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/valentines.rpy", line 168, in script
  File "C:\Users\ICEHACK5698\Desktop\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\ICEHACK5698\Desktop\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/valentines.rpy", line 171, in <module>
  File "game/event-handler.rpy", line 129, in addEvent
EventException: EventError: Syntax error in conditional statement for event 'monika_valentines_start'.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.7.0
[/code]

**Comment by Ph3nomenal** [comment]
Got the same error and posted about it earlier. Still haven't manged to fix it

**Comment by Areaclassified** [comment]
this would really suck not being able to participate in the valentines day event

**Comment by ThePotatoGuy** [comment]
Try a full delete and reinstall.

**Comment by Areaclassified** [comment]
@ThePotatoGuy  what should I delete in particular, like the whole game and then the mod? and will this change anything with monika?

**Comment by monikLover** [comment]
@Areaclassified delete everything, the game and the mod, and then do a reinstall the mod in a fresh copy of DDLC

**Comment by Areaclassified** [comment]
@monikLover will progress carry over? and wont I have to re play the whole game?

**Comment by Areaclassified** [comment]
also I'm missing just one file witch is listed in the trace back I can just get the download to that  specific file

**Comment by Ph3nomenal** [comment]
@Areaclassified Reinstalling everything works. It didn't delete the progress, but I'd keep the old files in case it does

**Comment by Areaclassified** [comment]
@Ph3nomenal is there anyway you can give me this one file I'm missing I mean there is a feature to add files. I'm just really paranoid about deleting the files. I'm missing the 'monika_valentines_start' file.

**Comment by monikLover** [comment]
@Areaclassified your save is in a different folder so it's safe to delete all of them
