### ISSUE TITLE
how do you make a pull request for her?

### ISSUE THREAD

**Issue by AnIdiotsavant** [Backdash/MonikaModDev#1052]
I wanna try make something that could be added to the dialogue but I don't know how

**Comment by kaido1224** [comment]
Read the guidelines for contributing here. It also tells you how to submit a pull request. Make sure you make a pull request in content not master.

https://github.com/Backdash/MonikaModDev/blob/master/CONTRIBUTING.md

**Comment by AnIdiotsavant** [comment]
https://github.com/Backdash/MonikaModDev/commit/39423f82bbdab221071aa66e13d535b7f5d3fd41

**Comment by AnIdiotsavant** [comment]
thanks, man. Managed to write my first one thanks to you

**Comment by AnIdiotsavant** [comment]
did I do it right though?
