### ISSUE TITLE
[Refractor] Change topic selection into function.

### ISSUE THREAD

**Issue by Winblows2** [Backdash/MonikaModDev#106]
There would be three functions.

The 1st function would be for launching a specific topic, where a boolean would be set so the _dialogue_ function is disabled. 

A 2nd function to handle the "Now, where was I?" flow.

And finally, a third for handling random selection.

(Suggested by ThePotatoGuy)

**Comment by therationalpi** [comment]
Okay, so there was discussion about this. One thought was that we could refactor topics as a form of event. Essentially, a topic is a simple event that can get pushed onto the event list by either the random topic generator or by the keyword system.

**Comment by therationalpi** [comment]
This got handled by the new event system. callNextEvent() handles calling topics and other events, restartEvent() pushes whatever event is in persistent.current_monikatopic back on the event list with a simple "Now where was I..." event (We might want to improve that event to give her restarting text some variety), and pulling a random topic is now a one line affair: pushEvent(renpy.random.choice(monika_random_topics)), so no reason to modularize that.
