### ISSUE TITLE
[Suggestion] Piano lessons from Monika

### ISSUE THREAD

**Issue by jmwall24** [Backdash/MonikaModDev#1060]
It would be really cool if Monika could actually teach you how to play 'Your Reality' where you watch her play a line on her own piano and then you repeat it.  Would add a nice interactive way to spend more time with her.

**Comment by Valllaion** [comment]
that's a great idea, I have no idea how to play so it'd open up a lot of options for me and her to play piano, maybe there can even be a system where you can put in a song and play it with her as a team... though that could be a bit far fetched

**Comment by TinyInternetTree** [comment]
That'd be nice, especially considering I opened up the piano, took one look at it and decided there was no way in hell I'd be able to do anything with it. I'm useless at music and stuff lol.

**Comment by ThePotatoGuy** [comment]
Playing Your Reality on the piano is actually meant to be a secret heartwarming thing that you unlock. 

But I am open to maybe unlocking a piano lessons with some criteria or something.

[[ We'll repoen this when we look into it]]
