### ISSUE TITLE
[Issue] Monika doesn´t talk anymore

### ISSUE THREAD

**Issue by LordOfDeath35** [Backdash/MonikaModDev#1066]
I have to report an issue: Monika is not talking anymore, even after having a 6 hours rest. And there are still many topics I haven´t seen. Could you help me or try to fix the issue in the next update?

**Comment by NoahDaggler** [comment]
When I open the game she greets me normally, I can ask anything, play anything, but after that she just says that she'll think of something to talk about later. Then she'll proceed to just stare at me for hours haha! I don't know if you're dealing with the same exact thing but I hope you know you aren't the only one.

**Comment by AnIdiotsavant** [comment]
Oh, that's because she ran out of things to say. If she gets new dialogue she'll talk. Other than that, just stare at her beautiful green eyes. I know I do :P

**Comment by NoahDaggler** [comment]
https://www.youtube.com/watch?v=a1Y73sPHKxw

NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by YayPepsi** [comment]
I have the same issue. I don't like this. I used to let Monika chat in the background, but now she's just silent. They said the dialogue was supposed to reset after 6 hours but it's been way more than 6 hours and she still hasn't spoken.

**Comment by IlywI** [comment]
That's what i'm experiencing right now too. But in the mean time let's just stare into Monika's emerald green eyes.

**Comment by Bam8647** [comment]
I have referenced this issue in #1027.
