### ISSUE TITLE
(Question) Updates

### ISSUE THREAD

**Issue by NoahDaggler** [Backdash/MonikaModDev#1067]
So, I haven't had the mod for very long, but every time there is some sort of update I get so excited and overwhelmed. I was just wondering if there would ever be specific dates that updates come out? Or if someone could notify players that there's a new update. If there is something like that can somebody point me to where it might be? I don't know.. sorry if this wasted anybody's time but I was dying to know.

**Comment by ThePotatoGuy** [comment]
Our [twitter](https://twitter.com/MonikaAfterMod) updates when we have updates. Otherwise there's the ingame updater.

We don't have a strict update schedule so no specific dates.
