### ISSUE TITLE
[Suggestion] Monika Outfits

### ISSUE THREAD

**Issue by Jxhnathan08** [Backdash/MonikaModDev#107]
(Originally from the 0.5.0 release on r/DDLC)
Jacksir1313, a redditor, suggested that we give Monika other outfits. She had said at one point she'd wear casual attire. It'd help to make her "feel more real." 

Concerns about this would be _designing_ new outfits and have it fit Monika convincingly. Thoughts?

**Comment by therationalpi** [comment]
It's a great stretch-goal for art in the future, if we're done with the basic poses and expressions and have someone that feels really ambitious.

**Comment by therationalpi** [comment]
Going to close this for now, since I don't think we want to put effort towards adding this feature until the higher priority artwork is done.
