### ISSUE TITLE
[Suggestion] - Yuri Easter egg

### ISSUE THREAD

**Issue by IAmSeamonkey** [Backdash/MonikaModDev#1070]
I understand that naming your character yuri already has an easter egg when booting up the game but I think that, like sayori when you name the character Yuri to make the music change to the recently added play with me (variant 6).

**Comment by ThePotatoGuy** [comment]
The play with me song isn't that scary and isn't jarring in the way surprise is. If there's anymore yuri eggs, it would be visual or something.

**Comment by IAmSeamonkey** [comment]
i understand. just a suggestion.
