### ISSUE TITLE
[Suggestion] - New games

### ISSUE THREAD

**Issue by ACoolCat** [Backdash/MonikaModDev#1072]
I don't know if these has been suggested yet, but I'd love to see Monika take her hand at puyo, some sort of rhythm style game, and poker.

**Comment by oniigirii** [comment]
As for a rhythm game, I can imagine something like a 4-key stepmania game with a DDLC design and Monika being a "CPU opponent" that plays with you and whoever gets the best score/accuracy wins, it's just that there isn't a lot of songs to be played in the mod with the DDLC playlist in mind. I don't want to see DCMAs if we were to import other songs as other games have already done that.

**Comment by ACoolCat** [comment]
Yeah, I didn't really think that far in terms of the Rhythm game. I'm sure there's some stock, royalty free songs available that could be used, but those might get annoying fast.

**Comment by ThePotatoGuy** [comment]
An osumania style game using the piano is something I've thought about, but it's super low priority.

**Comment by kaido1224** [comment]
I see poker as being out of character for her. Just my personal opinion.
