### ISSUE TITLE
[Suggestion] Monika singing

### ISSUE THREAD

**Issue by jmwall24** [Backdash/MonikaModDev#1075]
This is kind of already there, but another twist to it.  Right now Monika sings (via text) when you play 'Your Reality' correctly on the piano.  Now I realize it would be really hard for her to actually sing the lyrics as you play piano as you don't always play at the exact tempo of the song, but it would be cool when you choose to listen to the song via the 'Music' menu to have the option to see her sing it, using the same text lyrics and facial expressions she uses while you play piano, so it's like she's actually singing it to you.

**Comment by Valllaion** [comment]
sounds like a cool concept, I hope it makes it in next update ^^

**Comment by ThePotatoGuy** [comment]
Hmm, we could actual use the audio track from the end of the game here as well. We'll look into this.

[[ We'll repoen this when we look into it]]
