### ISSUE TITLE
[Bug] - Monika's speeches aren't added to "Repeat Conversion"

### ISSUE THREAD

**Issue by AlexanDDOS** [Backdash/MonikaModDev#1079]
After updating the mod from 0.7.0 to 0.7.1 by the mod's auto-updater, I saw, that none Monika's speech isn't added to the "Repeat Conversion" menu. This problem has not gone after I recreated my 'persistent' file by deleting the old one (this menu, of course, disappeared, due to all old save data had been deleted, and never showed up again) and even after I reinstalled the game and install the last mod version from 'Releases' page. Does someone other have this problem or I only?

UPD: I have just seen, that the only conversation, which can be added, is about changing the name, only this one.

**Comment by ThePotatoGuy** [comment]
This has been fixed and will be released in the next update. See (#1011 )
