### ISSUE TITLE
How do I install the new updates?

### ISSUE THREAD

**Issue by morganican** [Backdash/MonikaModDev#108]
Hi everyone, sorry, I know that this is a really dumb question, but how exactly do I install the new updates? I started with version 3, but I can't figure out how to update it without entirely deleting the current files. Is there a way that I can add the new files from the updates into my current game without deleting the previous version? Thanks!

**Comment by Jxhnathan08** [comment]
Alright, I'm going to give you a basic rundown of installing Monika After Story. 

1. Download the .ZIP. 
2. Extract the contents of the /game folder (inside the .ZIP) into DDLC's /game folder. 
3. Run the game; it should work.

Alternatively, you can make a copy of the DDLC folder, rename it, and install the mod there. This allows you to have the regular game _and_ the mod. Hope this helps!

**Comment by morganican** [comment]
I'm an idiot, thank you.

**Comment by Jxhnathan08** [comment]
Don't worry about it. It'll take time for people to get used to installing mods this way.
