### ISSUE TITLE
[Suggestion] - Situational Dialogue.

### ISSUE THREAD

**Issue by ACoolCat** [Backdash/MonikaModDev#1082]
I was thinking about how when you first download the mod Monika comments on which ending you got/if you were still on Act 3. Maybe this could play deeper into her interactions with the player? Like, depending on when you downloaded the mod can effect her attitudes towards things, or specific things she references, or maybe even how she views the player.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
That would require anywhere from quite some o **a lot** of work, depending on the amount of topics.
It was already discussed in #873.

**Comment by monikLover** [comment]
The introduction when you 1st open the mod already does this and is planned to be expanded upon in the future.
