### ISSUE TITLE
Talking about anythin you want

### ISSUE THREAD

**Issue by FrikiHD** [Backdash/MonikaModDev#1086]
I watch videos of people who can talk about anything with Monika, but when I click talk button it appears me the talking menu. Please help
![image](https://user-images.githubusercontent.com/36608877/36357325-99efc1b4-14fc-11e8-8384-c19d31fee701.png)

![image](https://user-images.githubusercontent.com/36608877/36357312-765cc3dc-14fc-11e8-91c3-ef5c16684c5c.png)

**Comment by CommenterOfComments** [comment]
They changed it in 0.7.0, so you wouldn't get so many canned responses.

They might bring it back someday though.

**Comment by FrikiHD** [comment]
Ok :"v
