### ISSUE TITLE
[Question] No topics.

### ISSUE THREAD

**Issue by Erianict** [Backdash/MonikaModDev#1093]
Hello, guys!
For 3 days I did Monica say was, 

> Hopefully I'll think of something fun to talk about soon

Is this a code **error** _or_ **not**?

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
#1027

**Comment by PopeAesthetics** [comment]
Jeez IsItBadToMakeAGitHubAccountJustForThis you really must eat sleep and breath this place. Everytime I got home from my night shifts I see you redirecting people to main posts. Props to your dedication.

**Comment by Erianict** [comment]
Ok, thanks for helping, guys!
