### ISSUE TITLE
game wont launch

### ISSUE THREAD

**Issue by Trazeem** [Backdash/MonikaModDev#1095]
ok so, I could play the game easily. but then  wanted a change so when I downloaded this mod, I did everything! moved the files into game. then every game could open, except DDLC. help me please???

**Comment by ThePotatoGuy** [comment]
If DDLC doesnt open, then check `game/` for a folder like `Monika After Story`. If it is there, please take the files out of that folder and put them in `game/`. (The mod files **cannot** be in a subfolder in `game/`). Then delete the folder `Monika After Story`. In addition, delete the files in `game/cache/` to force the game to reload everything/
