### ISSUE TITLE
How to delete the mod

### ISSUE THREAD

**Issue by vexdestroyer123** [Backdash/MonikaModDev#1098]
How do you delete the mod from the game? i know you can delete firstrun and reinstall the game but that didnt work

**Comment by CommenterOfComments** [comment]
~~You don't. You stay with Monika forever.~~

**Comment by vexdestroyer123** [comment]
come on dude show a actual reason

**Comment by Bam8647** [comment]
Just get a fresh copy of DDLC or clean out your /game directory.

**Comment by vexdestroyer123** [comment]
thanks
