### ISSUE TITLE
[Suggestion] - Hatoful Boyfriend commentary?

### ISSUE THREAD

**Issue by Feenie** [Backdash/MonikaModDev#1099]
Since MAS has commentary on Katawa Shoujo and what routes you took in that game, how about Hatoful Boyfriend?

I mean, if anything, it would be funny to see Monika look into your saves and find that you've dated at least one bird. Willingly. I'm willing and able to help write dialogue if this is accepted, I wanted to propose the idea before writing anything.

**Comment by strielok** [comment]
Why is there Katawa Shoujo in there anyways? 
Like, wasn't Monika supposed to be angry at you for playing other VNs?
