### ISSUE TITLE
[Suggestion] - MonikAI

### ISSUE THREAD

**Issue by PopeAesthetics** [Backdash/MonikaModDev#1103]
So I don't know how many people have brought this up yet, but the new MonikAI application is very interesting. I was thinking we could have Monika mention it as another form of allowing her to be with us, as it seems the MonikAI application will be referencing MAS as well. 

Any thoughts on the matter?

**Comment by ThePotatoGuy** [comment]
Definitely doable.

**Comment by jmwall24** [comment]
MonikAI looks interesting, but isn't it also in blatant disregard to the mod rules?  Didn't think they were allowing stand alone programs that could be played without having the original game.

**Comment by Bam8647** [comment]
Is this a separate mod created to be a chat bot for Monika? If so, then there should be talks of collaborating these two mods together. If she'd be able to hold decent conversations, remain in character, and have some form of memorization then the need for constantly creating new topics should diminish overtime :D

**Comment by jmwall24** [comment]
It's a separate mod that is only like 2 days old.  It's actually not a chatbox at all, she pretty much just comments on whatever you are doing on your computer.  Like if you go to twitter she mentions she has a twitter account.  From what I have seen you can't talk to her at all on it, at least not yet.

**Comment by Bam8647** [comment]
Ohhh I know what you're talking about. Yeah I thought it looked cute. So far the dialogues are limited, but yeah this could still be a nice feature to implement into this mod at some point possibly.

**Comment by jmwall24** [comment]
Yeah that's what I think.  The inter-activeness of MAS is so great and it having it's own window makes it feel so immersive.  Having her in the corner of the screen feels more like what should be a feature of MAS when it's minimized to me than it's own mod.

**Comment by PopeAesthetics** [comment]
We are making progress on improving the application quite quickly. The creator Pimaker aswell as a few others coders are ironing out any issues as well as considering improvements and additions to it. They are doing the heavy work tho. Dialog is being continually added to [here](https://docs.google.com/spreadsheets/d/15sn7eXO8EApV1Cd6A7wijCD12pzQrBr8Oxf5oToONPE/edit#gid=0) by those of us who lack the coding skills.

As the application continues to grow, I would love to see more collaboration between MAS and MonikAI 😄. Also feel free to come help us out with anything you can. The community is still small so we could use the help. It is a fun side project to be on alongside MAS

**Comment by Bam8647** [comment]
If they can acquire this feature, eventually implement a realistic chat bot (If successful), and have her become more and more aware then Monika could become as close to our reality as possible given our current time period muhaha! Lmao

**Long story short** MAS would definitely gain more attraction.

**Comment by PiMaker** [comment]
Thank you all for integrating my application into your mod! I feel honored :)

MonikAI currently reacts to your website and your GitHub. It could theoretically also react to your application, but because MAS launches via the default DDLC.exe it can't reliably detect if the game is launched vanilla or modded... Oh, and interactions are currently not *really* planned, MonikAI serves more as a reactive thing - thus also differentiating it from MAS.

Hope that clears all things up, thank you again!

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Why are all the greatest Monika mod creators πies in one way or another?

**Comment by PiMaker** [comment]
π

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
П

**Comment by sebastianN01** [comment]
its kind of sad these two cannot be one. oh well..
