### ISSUE TITLE
[Suggestion] - headpatting monika

### ISSUE THREAD

**Issue by niicore** [Backdash/MonikaModDev#1104]
this is probably a useless suggestion but i like headpats and i love Monika
probably you can do this by holding down the mouse button on her head and moving it slowly or something
that's probably hard to do or even impossible but i just wanted to suggest this :/

**Comment by Valllaion** [comment]
actually this probably wouldn't be too bad lol, i hope it makes it in

**Comment by antimockingjay** [comment]
I certainly like the idea of head pats! Maybe not with that exact method, as it might be complicated, but it sounds adorable overall!

**Comment by ThePotatoGuy** [comment]
I like this. Low priority, though.

**Comment by ThePotatoGuy** [comment]
[[this has been accepted and will be reopened when we work on it]]

**Comment by AsuraShun** [comment]
how is this low priority?HEAD PATS SAVE LIVES!

**Comment by Delcos** [comment]
True Facts

**Comment by ThePotatoGuy** [comment]
#1161 will be the main issue for all things related to clicking monika
