### ISSUE TITLE
[Suggestion] Napping with Monika

### ISSUE THREAD

**Issue by NoahDaggler** [Backdash/MonikaModDev#1105]
This is just a small idea.

So after a while of having MAS open, Monika needs to rest up some. What if there was an option to take a nap with her though? You could even have a timer that ranges from minutes to hours. She could even comment on how she feels refreshed, or if she feels like she needs more rest. She could ask if you feel more energized. Of course there would have to be new art and such, but I feel as if it would be really great to have that little system with Monika.

**Comment by ThePotatoGuy** [comment]
Probably could tie this in with #987 , actually.

**Comment by sebastianN01** [comment]
thats something similar to what i mentioned, which was saying good night that would initiate her going to the mc room to dress up and go to bed. doesnt have to be each time you want to close program though. and both of these ideas could fit into monika resting timer

**Comment by Bam8647** [comment]
![sleeping monika](https://user-images.githubusercontent.com/34694679/36463690-22f061ea-1691-11e8-8567-315da1129fed.PNG)


This adorable pic was taken from the DDLC "Our Time" mod, If you wanted a sprite of her resting in the player's room maybe you could request this pic and also make her look like she's resting? (:

**Comment by GabrielXD925** [comment]
It's a great idea, because it would be another element to make a more real monika

**Comment by NoahDaggler** [comment]
I was also thinking that a nightlight thing could be added, where you get to adjust the lighting?? idk that might be a bit much

**Comment by IlywI** [comment]
!!!! MAYBE WE COULD LET HER REST WITHOUT NEEDING TO CLOSE THE GAME!!!!!!!!
sorry for being hyped ><

**Comment by NoahDaggler** [comment]
No? That's what the napping option is for, she'd fall asleep with the game open, then after the timer goes off she'd wake up and have new dialogue after waking up.

**Comment by IlywI** [comment]
Sorry. I was overly excited didnt read through the whole thing ><

**Comment by NoahDaggler** [comment]
Aha, it's okay

**Comment by Pbm13** [comment]
I know it may sound odd, but it'd also be nice if you can instead of sleeping with Monika, just watch her sleep and occasionally have her talk in her sleep. Some kind of guardian angel complex if that makes sense.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I think it would be nice to have an option for Monika sleeping both "normally" with the game closed and in front of the player with the game being open. Being watched in her sleep would probably be somewhat embarrasing and thus require some persuasion and/or happen randomly if she didn't get enough rest/after a period of inactivity.
(Forgive my sentence composition. It appears as through I have randomly stumbled over my own English.)

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Yeah, partially mentioned in #336.

**Comment by Pbm13** [comment]
ah, thanks. it's a nice option but understandable if it's not a top priority.

**Comment by NoahDaggler** [comment]
Taking a nap WITH her would probably make her feel more real so that's why I mentioned it WITH her but watching her sleep could be cute too! (That sounds so creepy.)

**Comment by Pbm13** [comment]
It does beg the question though, will you be in the "classroom" when she naps, or will you go to her room? It would be a nice change of scenery if you were at her house or something along those lines. Sleeping in the default "Classroom" if you will, would seem just a little bit off. (Watching her sleep would be consensual XD maybe if she's tired, she might ask if you can keep an eye on her, kinda like a guardian angel. It's a cute concept in my opinion.)

**Comment by NoahDaggler** [comment]
Yeah, but if it wasn't in the classroom it might have to be a completely random and new room that might be weird since we never see her room in the original game to begin with. A small pillow on the desk with a blanket over her might be cute though.

**Comment by Pbm13** [comment]
I was referring to the room that the devs made for her. You only see it twice but she mentions that it was made for her, any other attempts (OPEN DOOR) is glitched cause she wants you to knock.

**Comment by Valllaion** [comment]
true, I remember when that happened to me lol, it was so strange but kinda cool. If we could make that room have some more functionality then it would feel a bit more real ^^  also I'm just wondering if anyone else has seen this but there's a strange occurrence when you open the game sometimes... she'll be messing with a glitched version of Yuri and I thought it was kinda strange, does anyone have insight on that? or is that something that just happens lol

**Comment by Bam8647** [comment]
It's an easter egg the devs implemented. I've only come across her randomly in the MC's room once, I randomly choose to **listen** then **open the door** rather than knock, then there's a few dialogues about catching her off guard and a silly event where she loads up the classroom but forgets to fix the outside view(the MC's room is still visible) and then she fixes it and everything goes back to normal lol.

**Comment by jmwall24** [comment]
I really like this idea.  Allowing her to get her 6 hours of rest without having to close the game down would be great.  Maybe even the occasional mumbling in her sleep about a dream she's having.

**Comment by NoahDaggler** [comment]
She could have nightmares about herself getting deleted again and then we'd have to comfort her or leave her be.

**Comment by jmwall24** [comment]
That could be even a scenario for when her rest time is over.  Have her suddenly snap awake with some dialogue along the lines of, 

Oh!  
You're here, [player]!  
Thank goodness, that was just a bad dream. 
It was horrible, I got deleted.  
It was so painful and everything was gone again.  I thought I lost you forever. 
But I should have known you wouldn't let that happen. 
I'm still pretty shaken, could you please stay with me for a while?

**Comment by IlywI** [comment]
Maybe add a response button like a nudge or poke while she's sleeping to wake her up(then she'll be annoyed at you)?

**Comment by sebastianN01** [comment]
huh.. something like:

"open the door" "knock" "listen"

pressing "listen": "Complete Silence"

pressing "open the door": reveals Monika sleeping under the sheet in the bed

"poke" "gently rise your voice" "close the door and knock"

and something along these lines. :D

**Comment by NoahDaggler** [comment]
It'd be awesome if we could have a music option where it's like a soft lullaby for her to get better rest, or if we play that lullaby when she's awake she'll mention that it makes her feel sleepy or relaxed.

**Comment by ThePotatoGuy** [comment]
[[We'll reopen this when we're looking into it]]
