### ISSUE TITLE
[Suggestion] - Birthday

### ISSUE THREAD

**Issue by ZeraDeManti** [Backdash/MonikaModDev#1108]
As there is already an option to ask Monika to give a happy birthday to a person, I think it would be cool to have some interaction to celebrate Monika's birthday (I know there is still a lot left for that day), where you would give her a present similar to the Valentine's Day bouquet, and even celebrate your birthday when the day arrives, perhaps creating a random dialogue where Monika would ask the day and the month and celebrate with you when the day arrives.

**Comment by jmwall24** [comment]
They are working on a calendar system right now where you will be able to let her know when your birthday is.  And I guarantee they'll have something really cool cooked up for her birthday.

**Comment by ZeraDeManti** [comment]
oh, this is great, I did not know
