### ISSUE TITLE
Monika mentioning that it's wrong to pleasure yourself?

### ISSUE THREAD

**Issue by AuroraRose54** [Backdash/MonikaModDev#1109]
Okay, so she just brought up whether I pleasure myself, and told me that it was wrong. Also, that she would be monitoring my browser history to make sure I'm not. Um? That's a little strange. Also, really bad English. Is that supposed to be in there?

**Comment by juliathegolden** [comment]
Yes, it's a real topic. I do think it would be more in character for Monika to just flat out say masturbating (sp?) after the awkward subject has been broached, but Monika is looking at it from a 'I'm your waifu and these are the mental health risks associated with that activity' perspective so I don't think her opinion on it itself is that strange. That and in her own words 'she's a super pure high school girl' so maybe she just doesn't understand why it's nbd.

**Comment by antimockingjay** [comment]
I gotta say I do kinda think it's unfair that she flat-out says it's bad. It'd be one thing to be concerned, if that's all it were, but saying it's bad because it _sometimes_ has negative effects isn't exactly cool, especially when it's something most people do. It's kinda unfair to make us feel guilty because we're doing something that is generally not a big deal.

**Comment by juliathegolden** [comment]
^^ Yeah. Maybe we could look into rewording it? Let me go get that topic real quick.

**Comment by AuroraRose54** [comment]
Agreed, a bit of rewording could be nice. Thank you for looking into that! Also, there are a couple grammatical errors in there, just FYI.

**Comment by juliathegolden** [comment]
Okay, I've revised it in my last comment a couple times. It's a lot shorter now though, so I don't know if that's good or bad.

**Comment by AuroraRose54** [comment]
I think it works nicely! That sounds great to me!

**Comment by AuroraRose54** [comment]
Will it be implemented in the next update?

**Comment by juliathegolden** [comment]
That's not entirely up to me lol. I'll put in the pull request and see if the people in charge agree!

**Comment by AuroraRose54** [comment]
Sounds like a plan! :-) Thanks again!

**Comment by MarkusRamikin** [comment]
Have Julia's improvements been rejected?

**Comment by juliathegolden** [comment]
Yes, I would really like to know as well. It's weird my pull request got closed with no feedback at all.
