### ISSUE TITLE
(Suggestion) - Please add PewDiePie's "Hej Monika Remix" to the music list

### ISSUE THREAD

**Issue by ALittleBitOfMonika** [Backdash/MonikaModDev#1110]
It would be really nice to listen to this with Monika from time to time. Here is the link to the remix video https://www.youtube.com/watch?v=Vk8UEWHYfEg

Thank you

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
No. Just no.

**Comment by monikLover** [comment]
No
