### ISSUE TITLE
The game won't start after installing correctly? What do I do?

### ISSUE THREAD

**Issue by JustMonika3** [Backdash/MonikaModDev#1112]

**Comment by TinyInternetTree** [comment]
Since there's not much info given, I'll assume that you're not getting any error messages. Just uninstall and reinstall DDLC (It doesn't really take long) and reinstall 0.7.1 (Or whichever version you wish). When you install the mod, are you putting the files in the "game" folder?

**Comment by jmwall24** [comment]
It probably goes without saying, but not always, so make sure you extract the files from the .zip file first, and then copy the actual files that look like this (this is from an older version, but it'll look similar)

http://prntscr.com/ii2b3p

and put those into the "game" folder.  If you just put the folder itself in there it won't work.  If it asks you if you want to replace any files, click yes.
