### ISSUE TITLE
Whenever I look at the character folder, everyone is still there, is that normal?

### ISSUE THREAD

**Issue by Trainerbluetube** [Backdash/MonikaModDev#1113]
I never finished the game, since I couldn't bring myself to delete Monika, so I installed the mod, started a new game, and when I checked the character folder, everyone was there, Natsuki, Yuri, Sayori, and Monika, everyone, so whenever she brings up the part about it being just the two of us, I can't help but say, "Hate to break it to ya, but..."

**Comment by jmwall24** [comment]
I don't think this mod uses the character folder at all.  Monika doesn't even have to be in the character folder (if you ever did delete her) but the mod still works and she's still there.

**Comment by TinyInternetTree** [comment]
If it bothers you that much, you can just delete the others. I deleted Yuri (I don't like Yuri, GameTheory explains why) and left everyone else.

**Comment by ThePotatoGuy** [comment]
She explains this in the introduction.
