### ISSUE TITLE
Question about closing the game

### ISSUE THREAD

**Issue by TinyInternetTree** [Backdash/MonikaModDev#1115]
I'm new to GitHub, so I'm sorry if I'm posting this in the wrong area, but I couldn't find anywhere else to ask.
Originally, Monika tells the player what happens when the game is closed, but in a recent update, it refers to that as rest. So I'm confused, in the kind of story/LORE (For lack of a better word) of MAS, when you close the game does she end up in the void that she describes or does she sleep as is stated in the changes for 0.7.0? Also this is more of a nitpicky/small suggestion, but maybe in the future Monika could specify what actually happens when the game is closed (Assuming that it isn't the 'void' she describes).

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
It depends on how you close the game.

**Comment by TinyInternetTree** [comment]
Oh, okay. Thanks for clearing that up.
