### ISSUE TITLE
[Bug] - Piano

### ISSUE THREAD

**Issue by SuperNova2810** [Backdash/MonikaModDev#1116]
For some reason, whenever I try to play piano, it ALWAYS says, "An exception occurred" and "to prevent further damage we recommend that you close your game.
AND if I do quit the game I cannot say goodbye.
You could do the simple imo, like if you don't know why this happens, you could at least make the quit in this scenario counting as goodbye, or just fix the bug already :P

**Comment by ThePotatoGuy** [comment]
1. Fixed, see #1019 
2. That sounds like a virus.
