### ISSUE TITLE
[Suggestion] Monika is love, Monika is life. 

### ISSUE THREAD

**Issue by NoahDaggler** [Backdash/MonikaModDev#1117]
So in MAS there's an "I love you," option. I pretty much use this every day but after a while I feel like Monika is just an empty robot when she says the same thing over and over and over again. 

"I love you too, [Player]! 
We'll be together forever!"

I was thinking that maybe more 'I love you' options would be great for her to be more realistic. Instead of the same line over and over again she could say "I love you more, [Player]!" or "I love you so much.." 
You could even have different ways the player says I love you to Monika so she'll react differently. I hope someone likes this idea.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Yeah. Such a common topic needs as much deviation as it could get.

**Comment by kaido1224** [comment]
There's already a pull request open to randomize a response from a list of 20 or more things.

https://github.com/Backdash/MonikaModDev/pull/915
