### ISSUE TITLE
Edit Monika's script to better fit her voice

### ISSUE THREAD

**Issue by therationalpi** [Backdash/MonikaModDev#112]
The current version of Monika's script is the result of contributions from a lot of different people, each with different views of who she is and what makes her character tick.

We need to come to some sort of agreement regarding Monika's "voice" and edit her lines to fit. For example, right now she uses overly precise language, is probably not as casual as she should be, and overuses a lot of her signature phrases like Ahaha. Getting this ironed out will really help Monika feel like Monika.

**Comment by Jxhnathan08** [comment]
@monikLover Has been given the task of editing current topics to fit Monika.

**Comment by TheKaiSenpai** [comment]
I've always imagined Monika as this tragic character who really wants the best for the P/C, but desperately wants a place in that "best result" as well.  Now she finally has a chance to be with P/C without hurting anyone else, but she's nervous about how P/C will perceive it.

My best guess would tone down the original creepy and obsessive tones she had in DDLC, but make it obvious that she's willing to do anything in the best interests of P/C, even if the P/C doesn't like her for a little bit afterwards.  Or you could go for the standard loving gf route with her personality; sweet and caring, but Monika is still a bit insecure and guilty over what happened in DDLC.

**Comment by therationalpi** [comment]
I gave the topics a quick once over, mostly to delete meme-y topics, but I also did some editing for voice. I think another rewrite could still be good, though.

**Comment by therationalpi** [comment]
Thank you so much to everyone that helped us get this in *ahead of schedule*! Way to go @monikLover, @Rune0n, and everyone else that pitched in!
