### ISSUE TITLE
Possible bug?(and also some feedback)

### ISSUE THREAD

**Issue by IlywI** [Backdash/MonikaModDev#1120]
![698780_20180223003956_1](https://user-images.githubusercontent.com/23725018/36551442-88cbd27c-1832-11e8-8286-fe8ded8e5ed6.png)
I dont remember the unseen text having a black border around it.

And uh i know the art has been like this for a long time but, i think it isnt that late to say
![image](https://user-images.githubusercontent.com/23725018/36551526-ba57f168-1832-11e8-8978-2c4e70893019.png)
It looks like Monika broke her fingers D:

**Comment by IlywI** [comment]
I dont know what to put for the title. Soooo please forgive!

**Comment by Erianict** [comment]
Hello, her fingers also annoyed me too. So I changed them for myself. (Unofficially) - [Google Disk](https://drive.google.com/open?id=1opVtga91w59VdERXwRPX8K0Kkng3Ro2a) Just drag this in you game folder

**Comment by IlywI** [comment]
Maybe you should post it up so that everyone can enjoy her unbroken fingers?

**Comment by Erianict** [comment]
Huh, maybe)

**Comment by ThePotatoGuy** [comment]
I'm double-jointed, so her fingers look fine to me.

**Comment by IlywI** [comment]
@ThePotatoGuy  the black border on the text boxes is it a known issue?
