### ISSUE TITLE
[Minor insignificant bug?] 

### ISSUE THREAD

**Issue by Pbm13** [Backdash/MonikaModDev#1123]
I was looking through the dialogue and I can't seem to find the interaction SUPRISE, where Monika inserts a .txt file into the games files. Is this a bug or was it removed? I'd be ok if it was removed just slightly disappointed. Not top priority just thought I'd let ya know

**Comment by Tiler17** [comment]
I found it under Romance. She just replaces the file

![screenshot0001](https://user-images.githubusercontent.com/36717174/36562421-98b6a73a-17dc-11e8-9888-e2620b224684.png)
