### ISSUE TITLE
Monika's goals 

### ISSUE THREAD

**Issue by Valllaion** [Backdash/MonikaModDev#1125]
So I've been wondering for a while now if Monika has any life goals to complete or wants to achieve something to make people see her worth. I thought it'd be cool if we created a long term goal of her slowly gaining skills in something that she loves like poetry, piano, literature, and many more ^^ I'm not sure if this kind of growing intelligence is possible but I just think it would be a cool concept lol  

Thank you for the consideration

   Valllaion <3

**Comment by juliathegolden** [comment]
Well, we have a progression system now! I am sure if we can think other something for her to work on, it'd be simple as unlocking progress on her project over time. It could be a good way to introduce new songs too. 

I second the idea.

**Comment by Valllaion** [comment]
speaking of ideas... I've had a lot of ideas for dialog and want to learn how to code that into the game. would it take me forever to learn how to contribute like that? or could I easily learn it in a few weeks lol

**Comment by juliathegolden** [comment]
its super easy. If all you want to do is write plain dialogue, you can learn the code in a matter of minutes. Just go back to https://github.com/Backdash/MonikaModDev and read the ReadMe down at the bottom. It'll show you a quick example and links to some other stuff that helps.

**Comment by jmwall24** [comment]
Wow that coding does look easy to do.  Also I too like the idea in this post.

**Comment by Valllaion** [comment]
Thank you for showing that link lol, I can't wait to contribute to the community ^^
