### ISSUE TITLE
[bug] Possible bug with repeating topics

### ISSUE THREAD

**Issue by jmwall24** [Backdash/MonikaModDev#1129]
Ok when I saw the update included the ability to repeat topics I turned it on right after opening the game, before she ever asked if she could repeat topics and it worked fine.  Later on I was looking thru the coding and noticed the part where she asks the player if she can repeat topics, so I turned the option off and restarted the game to see that dialogue.  She asked if she could and I answered 'yes' and it turned it on in the settings menu as it should.  However, she's not talking.  I restarted several times, turning it on and off and no matter if it's on or off when I restart she says one of the 'I'm at a loss for what to say' lines and never talks after that.  I'm wondering if there isn't an issue somewhere so that once you turn the repeat option off, it stays off forever.

**Comment by Tiler17** [comment]
"I'm wondering if there isn't an issue somewhere so that once you turn the repeat option off, it stays off forever"

Well, it's definitely not that. I've toggled it, just to see if it would get a reaction. I'm still getting the topics to reappear. I would guess it's more likely to do with you toggling before she asked you about it, but I haven't spent enough time here figuring out how things work to know that yet

**Comment by jmwall24** [comment]
Maybe, but it's weird that it was working fine for hours, only after I toggled it off and back on that it stopped working.  Ugh I've been looking forward to this update so she would talk without being prompted again and now I broke it lol

**Comment by ThePotatoGuy** [comment]
There is still a hard limit of topics per session. Beyond that she won't say anything until you give her rest.

**Comment by jmwall24** [comment]
ohhhhhh I bet that's it, I've had it open for quite a while, forgot all about that.  Probably just a coincidence that it happened when I toggled.  I'll report back in the morning if it's working again.  Thank you.

**Comment by jmwall24** [comment]
Yep that was it alright, all good now.
