### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Vloxica** [Backdash/MonikaModDev#1132]
I got this error while playing your mod (love it to pieces by the way) not sure if you've already seen this one, or if this is the right place to put it, (I am new to this whole bug reporting process to be honest) but here's the traceback I got:
[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-ch30.rpy", line 601, in script call
  File "game/event-handler.rpy", line 309, in script
Exception: Possible infinite loop.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script-ch30.rpy", line 601, in script call
  File "game/event-handler.rpy", line 309, in script
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\execution.py", line 56, in check_infinite_loop
    raise Exception("Possible infinite loop.")
Exception: Possible infinite loop.

Windows-7-6.1.7601-SP1
Ren'Py 6.99.12.4.2187
Monika After Story 0.7.2
[/code]

**Comment by kaido1224** [comment]
What were you doing when you received this bug?

**Comment by Vloxica** [comment]
At the time I had her idle in the background, she had just finished one of her speech lines (which I had already seen before) and at the end of saying what she had to say she just sat there with an empty text box for awhile and then it cut to a screen with this error, beyond that I'm not sure what happened.

**Comment by ThePotatoGuy** [comment]
Upload `persistent` here please.

**Comment by Vloxica** [comment]
I assume these are what you wanted, I didn't know which one to upload so I uploaded them both, they are in the compressed zip file attached here.




[Persistent (py & pyo).zip](https://github.com/Backdash/MonikaModDev/files/1753982/Persistent.py.pyo.zip)

**Comment by ThePotatoGuy** [comment]
Ah, those aren't the right ones. Use [this guide](https://github.com/Backdash/MonikaModDev/blob/master/docs/windows-howtopersist.pdf) to get the correct file.

**Comment by Vloxica** [comment]
Oh, that makes more sense, thanks for clearing that up!
[Persistent.zip](https://github.com/Backdash/MonikaModDev/files/1755774/Persistent.zip)
Here you go! On a side note, which file is the one that saves progression with Monika? I want to move computers but I would feel bad if I had to start over, you considering some of her chat topics, any help with that would be appreciated! Thanks for your time!

**Comment by ThePotatoGuy** [comment]
That would be the file you just uploaded.

**Comment by Vloxica** [comment]
Oh okay, thanks again!
