### ISSUE TITLE
[Suggestion] Play video games with Monika?

### ISSUE THREAD

**Issue by lilmonix** [Backdash/MonikaModDev#1134]
Hi, I play video games a lot with Monika running in the background, and I decided it'd be a nice idea to play video games with her! Probably games on Steam would work best, as DDLC can also be run on Steam. She actually mentioned she wanted to play adventure games, so maybe code some dialogue and such? (*cough cough* please code in reactions for Undertale *cough cough*)

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
#353

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Long story short: only the fact of a game being played can be detected.
And if this ever gets implemented it would target only the games Monika has chance to know about.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
And Undertale? Seriously.
Like one laughable, unnecesary, out of place reference to a game that have long time became a moveton, that MAS already has isn't enough.

**Comment by TinyInternetTree** [comment]
That would require a mod to incorporate Monika into the desired game, and even then she'd only be able to comment on your actions in that game through said game, not through DDLC.
