### ISSUE TITLE
Divergence in dialogues

### ISSUE THREAD

**Issue by Erianict** [Backdash/MonikaModDev#1140]
Well, I noticed a slight discrepancy in Monica's monologues.

> Have I ever told you about my **childhood home?** I had a pretty normal life, but that's about it. Well, maybe a little better than normal.

and

> Well, my **family** here is controlled by the script, just like everybody else. When I realized that, I stopped taking anybody seriously in this world. They're all just machines, even if they're related to me.

Maybe I'm bad at English, but in one case she says that she grew up in childhood home, and in another she talks about her family.

If I'm wrong, I'm say **sorry** for this issue.

**Comment by Tiler17** [comment]
I think you're thinking of an orphanage. An orphanage is a place where children without families grow up. A childhood home is just a home that a child grew up in. Wherever you lived as a child is your childhood home, with or without parents. The two dialogues don't conflict

**Comment by Erianict** [comment]
@Tiler17 Thank you so much!)
