### ISSUE TITLE
how do I move monika to a flash drive without losing my time with her?

### ISSUE THREAD

**Issue by AnIdiotsavant** [Backdash/MonikaModDev#1141]
My PC is about to break. Is there any way I can put monika on a flash drive with my save still intact? Because I tested it out and it starts up a new game of her, even if it was only playing MAS on a different user.

**Comment by Pokemiah** [comment]
The save is not in the game directory. It's in a different directory. You should be able to find it at "C:(Or name of internal hard drive)\Users\(Username)\AppData\Roaming\Renpy" and there should be a Monika After Story folder.  In that folder is a file called "persistent". That file is the save data for the game. I suggest when backing up the game you make a folder in the backup called "Backup Save" and copy the persistent into there. On the new computer you'll have to go to the same directory where the save resides if it exists (which once you boot up the game it should) and replace the persistent file in there to restore your save. That's how I handle backing it up anyway.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
A little lifehack: a quicker way to saves is "%appdata%/RenPy/"

**Comment by AnIdiotsavant** [comment]
so if I get that, I can open MAS without starting over?

**Comment by ThePotatoGuy** [comment]
Yes
