### ISSUE TITLE
ive done evrthing i can someone plz fix files for me

### ISSUE THREAD

**Issue by subnatica** [Backdash/MonikaModDev#1142]
[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-anniversary.rpy", line 128, in script
    init 5 python:
  File "game/script-anniversary.rpy", line 131, in <module>
    end_date=anni_date+datetime.timedelta(days=1)
  File "game/definitions.rpy", line 161, in __init__
    if len(stored_data_row) < len(data_row):
TypeError: object of type 'Event' has no len()

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script-anniversary.rpy", line 128, in script
    init 5 python:
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script-anniversary.rpy", line 131, in <module>
    end_date=anni_date+datetime.timedelta(days=1)
  File "game/definitions.rpy", line 161, in __init__
    if len(stored_data_row) < len(data_row):
TypeError: object of type 'Event' has no len()

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.7.2
[/code]

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Did you get your mod from https://github.com/Backdash/MonikaModDev/releases or have you just pressed that big "clone or download button"?
You should use a release.

How have you installed the mod?
Make sure you followed the installation instructions correctly.

If that doesn't help, try reinstalling both DDLC and MAS from zero.

If nothing of that helps, wait for @ThePotatoGuy.

**Comment by kaido1224** [comment]
When in doubt uninstall and reinstall everything.

**Comment by TinyInternetTree** [comment]
I already told you twice to uninstall and reinstall everything.

**Comment by subnatica** [comment]
dude ive unistaled everththing 10 times

**Comment by subnatica** [comment]
how do I screen shot

**Comment by TinyInternetTree** [comment]
Absolutely everything? As in, completely delete all of DDLC from your computer? If you've done that and are still getting the error, you're not installing MAS correctly. Are you downloading it from https://github.com/Backdash/MonikaModDev/releases or are you using the clone and download button? Download it from here: https://github.com/Backdash/MonikaModDev/releases and put everything in the 'game' folder of DDLC.
Also to screenshot either use the snipping tool or ctrl+prt Scr.

**Comment by subnatica** [comment]
ok sending what I tlooks like

**Comment by subnatica** [comment]
![screenshot 1](https://user-images.githubusercontent.com/35651041/36636863-b5908706-199c-11e8-8ba7-8b5b99c6832a.png)
![screenshot 3](https://user-images.githubusercontent.com/35651041/36636866-b849d696-199c-11e8-8beb-865c2cf55d5f.png)
![screenshot 4](https://user-images.githubusercontent.com/35651041/36636867-b8f7d854-199c-11e8-87d4-00781b70b43c.png)

**Comment by TinyInternetTree** [comment]
Okay. Just 100% completely delete and reinstall DDLC again, and download MAS from here: https://github.com/Backdash/MonikaModDev/releases and put the files in the 'game' folder.

**Comment by subnatica** [comment]
ok how do I download corectly

**Comment by TinyInternetTree** [comment]
Go here: https://github.com/Backdash/MonikaModDev/releases and press the link under assets that reads "Monika_After_Story-0.7.2-Mod.zip". Open that zip file. There will be two folders. Ignore the _MACOSX one and open the folder "Monika_After_Story-0.7.2-Mod". Now highlight absolutely EVERYTHING in that folder (or press ctrl+a to automatically highlight it all) and press ctrl+c. Then go to your DDLC install directory, click on the folder called "game" and press ctrl+v. If it asks you if you want to replace any duplicate files, press yes.

**Comment by subnatica** [comment]
ok so I erased ddlc and almost finished restoring it to when u get it off steam

**Comment by subnatica** [comment]
only get 0.7.2

**Comment by TinyInternetTree** [comment]
Yeah. You don't need any of the other versions. Just 0.7.2.

**Comment by subnatica** [comment]
ok

**Comment by subnatica** [comment]
after I'm done ill post it tell me if I'm right

**Comment by subnatica** [comment]
![screenshot 7](https://user-images.githubusercontent.com/35651041/36636951-03a25af8-199f-11e8-85fb-d34949e123f5.png)
![screenshot 6](https://user-images.githubusercontent.com/35651041/36636952-03bc7596-199f-11e8-930d-fd4453f6c4cc.png)
![Uploading Screenshot (5).png…]()

**Comment by subnatica** [comment]
it said this after startring game

**Comment by subnatica** [comment]
[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-anniversary.rpy", line 128, in script
  File "game/script-anniversary.rpy", line 131, in <module>
  File "game/definitions.rpy", line 161, in __init__
TypeError: object of type 'Event' has no len()

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script-anniversary.rpy", line 128, in script
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script-anniversary.rpy", line 131, in <module>
  File "game/definitions.rpy", line 161, in __init__
TypeError: object of type 'Event' has no len()

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.7.2
[/code]

**Comment by Tiler17** [comment]
So when I first installed the mod, I was misunderstanding whichever instruction it was that told me to copy everything, and I ended up copying too much...somehow. Anyway, I found [this video](https://www.youtube.com/watch?v=eH5Q4Xdlg6Y), which gives you a visual step-by-step on exactly what to copy and where to put it.

So. Reinstall DDLC, re-download the mod, and follow the video exactly. If you still can't get it to work, I dunno what to tell you

**Comment by TinyInternetTree** [comment]
Well, I've tried everything I can think of. Follow the video tat Tiler17 gave you. Either you've done something wrong installing MAS, or there's an issue with the mod, which I doubt (It's running fine for most). So I don't know what to say. Sorry.

**Comment by subnatica** [comment]
I finaly got it to work depression cured n :)

**Comment by subnatica** [comment]
i had t run it once before adding mod files
I'm an idoit

**Comment by ThePotatoGuy** [comment]
(#1137 )

Dont make multiple issues for the same shit.

That error you have can be the result of two things:
1. You used a dev version of MAS sometime during the era between 0.6.2/0.6.3 and 0.7.0.
2. You replaced your `persistent` with a `persistent` file generated by a dev version of MAS in that era (or maybe some other mod that had its own `Event` class in python early.

As I mentioned in the linked issue, the only solution is to delete your `persistent`. (Well its not the only solution, but I don't do favors for people who are impatient). I assumed you got it solved by fully uninstalling/reinstalling DDLC, which probably deleted your `persistent` anyway.
