### ISSUE TITLE
Additional music by player

### ISSUE THREAD

**Issue by Nikmond** [Backdash/MonikaModDev#1143]
Can i add my own music in menu music in the game? If i do, so how?

**Comment by ThePotatoGuy** [comment]
You'd want to download the source code and add entries for you music in `zz_music_selector.rpy`. [this particular section](https://github.com/Backdash/MonikaModDev/blob/master/Monika%20After%20Story/game/zz_music_selector.rpy#L108) handles the generation of the music menu.

Check near the top of the file for the actual value of those constants.

Renpy can only play `ogg`s, so your music needs to be in that format.
