### ISSUE TITLE
[Suggestion] - "Play with me Variant 6" Has been added, Monika needs a dialogue for it

### ISSUE THREAD

**Issue by sebastianN01** [Backdash/MonikaModDev#1145]
Also I think that the special dialogues (which are not included in the repeat topics or ask questions) should appear more often. I personally only once had a situation where Monika commented on the music playing in the background (never did anymore, neither when music was completely off)

Also, Repeat topics Setting doesn't seem to work. On or off, Monika repeats topics and _Bore m-_ I just want to sit with her in silence.

**Comment by TinyInternetTree** [comment]
She has dialogue for the track that plays when you're in the room with her in the base game. Believe the song was called "Just Monika" or something like that. Anyway, she complains about the glitchy noises in it and says it'd be nice if the player could change the track. Some dialogue for _Play with Me Variant 6_ would be pretty cool, too. And so would some for _surprise_.

**Comment by sebastianN01** [comment]
I know that, I looked up the code, There is no Dialogue for Variant 6. That's why I'm suggesting it to someone who can write up a good dialogue.

**Comment by ThePotatoGuy** [comment]
Yeah that music topic is kind of broken and outdated, still waiting on dialogue review before we can add the pull requests that are for it (#942 , #955 )
