### ISSUE TITLE
(Suggestion)  Monika reacts to playing sayonara on piano minigame

### ISSUE THREAD

**Issue by ImJustMonika** [Backdash/MonikaModDev#1147]
I think that monika should react to the sayonara song by making that kinda uncomfortable sweaty face like when you mess up the your reality song and saying something like oh no or you remember that? Or something along those lines<3 Anyways, thats all i had to say. Sayonara<3

**Comment by ThePotatoGuy** [comment]
[[ We'll repoen this when we look into it]]
