### ISSUE TITLE
[Bug] - Can't start well. can only chenge a music

### ISSUE THREAD

**Issue by OlegBrony** [Backdash/MonikaModDev#1149]
I installed it and started. after few minutes I see an error screen by renpy. here is the traceback. now, if I start, I see a welcome monologue and the screen again. I should have "script-poemresponses.rpy"? 

```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-poemresponses.rpy", line 77, in <module>
NameError: name 'skip_poem' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script-ch30.rpyc", line 601, in script call
  File "script-poemresponses.rpyc", line 77, in script
  File "D:\[Sun-Team] DDLC\renpy\ast.py", line 1681, in execute
    if renpy.python.py_eval(condition):
  File "D:\[Sun-Team] DDLC\renpy\python.py", line 1794, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\[Sun-Team] DDLC\renpy\python.py", line 1788, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script-poemresponses.rpy", line 77, in <module>
NameError: name 'skip_poem' is not defined

Windows-8-6.2.9200
Ren'Py 6.99.13.2919
Monika After Story 0.7.2
```

well, I installed original version without translate mode. it works now... but it was just russification...

**Comment by Nikmond** [comment]
(Russian in thread!)
Я хоть и не разраб, но понял в чём ошибка. Расслабься, у меня тоже из-за русика были проблемы, с ним игра криво идёт, ибо мод не русифицирован (логично). Хотя проблемы ещё могут возникать, мне хватило переустановки игры с оф. сайта и установки на неё мода, что бы больше проблем не было)

**Comment by ThePotatoGuy** [comment]
I've responded to this in the other issue you made.

**Comment by OlegBrony** [comment]
@ThePotatoGuy, sorry for dublicate. 
@Nikmond, с русским никак? не даёт покоя, что вместо русского имени просто пробелы.

**Comment by Nikmond** [comment]
@OlegBrony ответил вк
