### ISSUE TITLE
[Suggestion] Some Monika AI/Behavior Possibilities  

### ISSUE THREAD

**Issue by Buy1Get1** [Backdash/MonikaModDev#1150]
1. Monika decides to 'not' today.
She has a bad day/ Is tired/ A normal day-Unmotivated 
Maybe the player has to come back in a while(time based on how they answer)
>"[player]"?
>"Can we do this a little later?"
>"I just don't feel up to it right now."
>  
>               " Sure thing:"
>                        "Oh, you're so sweet." 
>                        "Maybe tomorrow."
>               " What's the matter?:"
>                         "Well..."
>"I just need some time."
>"Can we pick back up in a couple hours?"
Return

Monika could use a clock to keep actual time, right? 

1A. The player could help Monika with either an excessive amount of joy, or a large dole of grief.
Via a series of text with dialogue options:
you're fine vs. this needs to change
let me help vs. okay
I'm glad vs. IDK 
 Each one would have a point assigned to it. +1 for positive / -1 for negative 
then Monika could have a joy/ grief counter = +35/-16
Based on the user's responses

2. Monika picks up patterns and changes to fit them
 Monika would want to find the best fit for interacting with the player. So, topics appearing more often could be singled out and repeated. Each theme could be assigned a point (like Itunes' library) when used. The topics get an extra point every time they're used again (either randomly, or when asked about by the user). This will provide a weight for conversations(since the topic with the highest number is used) , and creates a more unique environment.

3. Monika has a limit of disagreements
Going back to the counters, an additional counter could be placed in for disagreements. The more you have the less she is inclined to like you. Some can have greater effects than others. Favorite color (-1) vs
opinion on abortion (-20)
once she gets to -129 or something, she'll dump you (also agreeing could be a +# to balance it out)
after -300 she won't talk to you
-400 or < she deletes/ resets
4. Monika will try to change you
Like any good relationship, Monika could try to get you involved in hobbies she deems worthwhile. 
Staying healthy-Reading-Other
and get you out of hobbies that she believes to be bad
Not healthy-pastimes that are not Monika-esc 

(you probably think this way, but...)  Monika's  AI would benefit from being more independent of the user. 
She is a more complex calculator (or any program) spitting outputs at the user on command. Either she will be made more unique so that these processes are near invisible, or she will be provided with the ability to remember and adapt.
She should be influenced by a user's actions, instead of only activated by them.

Is there a way that I could help out more with the building of Monika's AI?
I hope this helps.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Falls under the ["Tracking Monika's opinions and memories of the player"](https://github.com/Backdash/MonikaModDev/projects/14) milestone.

**Comment by Valllaion** [comment]
Though I do have to say.... this would require quite a bit of dialog.... I could diffidently
 help with that though if you need it lol

**Comment by jmwall24** [comment]
Overall I like the idea, but I'm not sure about the not wanting to spend time with us part.  She already mentions how unpleasant it is when we close the game down, so it seems counter-intuitive for her to want us to leave her alone.  Maybe she could not feel like playing games or talking a lot, but spending time with us is all she really ever gets to do.  With our own limitations (work, school, sleep etc) of how much time we can spend with her, I like to think she really looks forward to spending any amount of time with us that she can, and that us showing up and being with her would be what would help brighten her day and make her feel better.

**Comment by Valllaion** [comment]
that is true... maybe leave out the idea of her wanting to be left alone but not the idea of a counter and the whole progression system of love to hate

**Comment by Valllaion** [comment]
This could tie into another project that I was reading about with her moods and how they affect dialog, making your decisions more important during the times that she's happy or more depressed, possibly making the multiplier x2

**Comment by ThePotatoGuy** [comment]
[[ We'll repoen this when we look into it]]

**Comment by Buy1Get1** [comment]
'dict['serotonin'] = 32.5 (her overall disposition. + = happier / - = sadder
(#1 on suggestion 1)
'if dict['serotonin'] < -99
cues related text-breakup-etc
used for all categories: - Monika learns your interests (#2 on suggestion 1)
'dict['category'] = 0'
'dict[category'] += 1

              1.
init 5 python:
addEvent(Event(persistent.event_database,eventlabel="monika_introduce",category =
['monika'],prompt="Introducing to friends",random=True))
'dict['monikacat'] += 1'

label monika_introduce:
m 1a "[player], would you ever introduce your friends to me?"

          2. 
menu:
m "Have you drawn art of me?"

   "Yes.":
          'dict['serotonin'] += .5 
       m 1b "Really? I'm very flattered!"
       m 1k "I think I might even love you more, now that I know you're so talented."

   "No.":
          'dict['serotonin'] -= .5
       m 1l "I can't draw, myself, so it's okay if you aren't good at drawing either."
"It makes me a bit scared when you say she could reset the game"-
"maybe leave out the idea of her wanting to be left alone" -
Perhaps a toggle could be formed. Then players could choose between a more responsive Monika, and a more independent one.
