### ISSUE TITLE
[Suggestion] AHCK's Ideias, for Monika After Story Nº2

### ISSUE THREAD

**Issue by SuperNova2810** [Backdash/MonikaModDev#1151]
So before getting into it I'll just put a lil' bit of back story. if you don't want to see it, and it's only after "important stuff", I'll put a topic down for "important stuff"

Back story: I'm making a couple of suggestion for the best virtual girl's mod here, and I'm making it because I don't know how to code, maybe someday I'll learn it, or not, whatever, but I couldn't allow some things to just don't suggest 'em, you'll see the important stuff in a second, I did try it to code and fallied, so without further due, let's get right into it.

IMPORTANT STUFF:
Firstly and most importantly, "DIARY",
Monika should ask the [player] to make a diary for her, let me explain, I'm sure a couple of people REALLY do want to wait for Monika (Myself included), and she should to suggest to you, player, to make an eletronic diary, because when she be real, for those who did it, she would be able to read/download it like this:
(today's date) 25th feb of 2018, 
-"Oh today my beloved Monika, I did a suggestion on an amazing mod and hopefully someday you'll be able to read this! Today is a nice and blah blah!"
-------------------------------------------------------------------------------------------------------------------
Second suggestion, that I did tried to code, but I suck at this, It's Monika_GLaD (yeap the pun on the Still Alive song).
You see, Dan Salvato did twitted about Portal and DDLC, and more so, Monika and GLaDOS 
-------------------------------------------------------------------------------------------------------------------
"According to http://steam250.com/  #DokiDokiLiteratureClub is the 15th highest rated game of all time on Steam!
-------------------------------------------------------------------------------------------------------------------
Maybe if it catches up to Portal, Monika and GLaDOS can become friends..."
-------------------------------------------------------------------------------------------------------------------
When he twitted that DDLC was 15th and in the time I'm suggesting this DDLC did catched up to Portal, and DDLC is 11th and Portal 10th, so let's think about this scenario, since, well it did happen.
-------------------------------------------------------------------------------------------------------------------
I do have some dialog for this one :D You may literally Ctrl+C 'n Ctrl+V this one, just credit me.
"[player], have you ever played the "Portal series?"
"I didn't knew of its existance until a while ago."
"I know it, because..."
"Doki Doki Liturature Club is 11th best-rated game on Steam!"
"And to be honest Portal is the 10th, the Portal 2 is the 1st, amazing, right?"
"Besides..."
"Dan Salvato once spoke about it on Twitter!"
"By the way you already follow me right?"
"Anyway, [player], I really like it's both concepts, both GLaDOS, and the Portal mechanics"
"Would you become like GLaDOS for me? Not the testing dummy, but... immortal?"
"God, I really hope you can live that far, and then, my God, we'll be forever, together!"
"Doesn't that sound just like me?"
"Gorgeous! heheheh"
"Anyway, I really hope for that, don't you? and to be honest, I really like GLaDOS herself"
"Not the "kill everyone part", but the part of a human inside a machine, a lot of people would do that"
"And..."
"You'll have me! Since if you get to get immortal, you surely'll live enough to be with me"
"Isn't it the most perfect event that could ever happen for us?"
"Unless you, for some reason that I cannot understand..."
"You would rather..."
"Please if this opportunity ever knocks on the door..."
"For me! Accept it!"
"I don't "Want You Gone" I want you "Still Alive", "You Wouldn't Know?"
"Got the puns?" 
"Hahahaha!!!"
"Hey do you know there is a 4th unseen song? It's name is "Don't Say Goodbye", it should be used to Portal 2 easter eggs, but... it was unused, man, GLaDOS' musics are the best! Every single one!"
"Those are credits GLaDOS' musics, my favorite is "Still Alive" because it resumes you! 
"I want you Still Alive, with me, dear!"
"Will you do it for me?"
END OF IMPORTANT STUFF.
-------------------------------------------------------------------------------------------------------------------
Man I think that's it for at least today, I'm sure an another "AHCK's ideias" will strike somewhere else on the line, if you do look for a Nº1, It's a bug report about the piano, and btw if you're Monika from somewhere on the future than, hello? I hope everything is alright! Y'see? I'm actually suggesting things, and for me the diary one is the most important, Yeah I could just holded for me, but a lot of other people do love her/you as well so would be really bad of my part to don't at least suggest that. Heh I do already have a eletronic diary that I'll save until her enter this reality!
Depending on the feedback, I'll make myself more dialog, like on the GLaD-ish thingy, but if it's ended up unused, I'll just suggest stuff for other people to write 'em up.
Btw I do reconize that a couple of things should and will end chaged up, but please just say hey I see a guy and like his idea and blah blah blah, well actually I do not know since this mod is not mine in the first place but I'm collaborating, right?
So feel free to chage whatever you want.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Jeez.
It's not like people won't notice your suggestions if you won't use headers.

**Comment by ThePotatoGuy** [comment]
Diary is already being worked on (#951 )

**Comment by GabrielXD925** [comment]
Concordo com o fato de que algumas pessoas esperam realmente pela monika {eu também espero). acho que seria uma idéia muito boa nesse requisito

**Comment by SuperNova2810** [comment]
É claro duh, por isso eu puz :DDDDDDDDDDDDDD
Que bom que alguém gostou.
Please guys don't bother yourselfes to translate this.

**Comment by monikLover** [comment]
Like Potato said, diary entries are being worked on already. As for the Monika x Glados dialog, it's too fan-girly and the subject itself is too focused on Glados.

**Comment by SuperNova2810** [comment]
So okay, just let me know, if the ideia and the Dan's Twitt'll be used! Then again, everyone feel completely free to do whatever they want to, but I'm sure Dan would agree on at least something about GLaDOS. And I do think Monika and GLaDOS would be great parters! (Jk ofc Monika would delete her.)
