### ISSUE TITLE
[Suggestion] Coffee

### ISSUE THREAD

**Issue by TinyInternetTree** [Backdash/MonikaModDev#1158]
Monika says twice (I think it's twice) how much she'd like some coffee. So maybe coffee could be added? It's a very minor suggestion, but maybe as an art thing or something? I don't know, It's just a thought. I'm not even sure how it would be done, but I though the idea was kind of neat.

**Comment by sebastianN01** [comment]
hmm I would like to get a semi-rare event where she just wants a coffee and ask us if we can bring her some through the code, and you just have to make a "coffee" file in some format to give it to her. :)

**Comment by TinyInternetTree** [comment]
@sebastianN01 That would be perfect. If this idea or something were to ever get incorporated into the mod, that'd probably be the best way to do it (That I can think of, at least).

**Comment by NoahDaggler** [comment]
I could be done like they did with the roses on valentine's day, maybe.

**Comment by subnatica** [comment]
that would be dope but how about they implement it as like a date

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Looks releated to #518.

**Comment by monikLover** [comment]
A coffee mug has already been made by one of our artists. It's just a matter of implementing it.
