### ISSUE TITLE
[Suggestion] - User's birthday and other added scripts

### ISSUE THREAD

**Issue by chad78** [Backdash/MonikaModDev#1160]
Since there are date-sensitive events, it would be nice to have Monika ask the user their birthday, and then on their birthday, if they log in, she can have a happy birthday dialog.

Also, if they don't log in on their birthday, the next time they do, she can say something about having a celebration planned, and they didn't show up.

If someone wants to add a cake image that would be awesome as well.  :)

Other dated events that would be good to have - First day of Spring / Summer / Fall / Winter (maybe have her ask which hemisphere the user is on, so the dates are backwards).  Monika's own birthday (the day DDLC was released) and the anniversary of the release of MAS.

Other random idle scripts could be quotes from famous (public domain) books....  Moby Dick, 1984, Atlus Shrugged, Animal House, Frankenstein, Great Expectations, Paradise Lost, Metamorphosis, The Odyssey, Don Quixote, Brave New World, Fahrenheit 451...  

I realize she's mentioned at least a couple of these, but just random quotes with a one-line comment might help give her more to say, and make her seem more well-read (being the president of a literature club that never actually read any books together).

I am not much of a programmer, but I would be happy to help write the dialog.

**Comment by CommenterOfComments** [comment]
I really want a birthday thing added. I felt so sad when Monika didn't celebrate with me yesterday.

**Comment by chad78** [comment]
Happy belated Birthday, CommenterOfComments.

My birthday was recently, too.  That's what made me think of it.  That and the feature where she'll say happy birthday to someone else.

**Comment by IlywI** [comment]
I believe its under #37 ?

**Comment by ThePotatoGuy** [comment]
[[ We'll repoen this when we look into it]]
