### ISSUE TITLE
[Bug] Crash in background

### ISSUE THREAD

**Issue by KiraTakemi** [Backdash/MonikaModDev#120]
I was switching tabs and the game crashed.
Is there a way in which I can see what was going on before the game crashed? I think they are called dump files or something (I'm not too versed in debugging tbh)

**Comment by KiraTakemi** [comment]
Okay, I screwed up and left some personal info in the screenshot.
The whole screen was white save for the upper corner where the picture of Monika was

**Comment by therationalpi** [comment]
Renpy calls it a traceback file. Please look for traceback.txt in your DDLC directory, and share it here. You might need to read over it first to make sure it doesn't have your real name in it or something.

**Comment by therationalpi** [comment]
Renpy calls it a traceback file. Please look for traceback.txt in your DDLC directory, and share it here. You might need to read over it first to make sure it doesn't have your real name in it or something.

**Comment by KiraTakemi** [comment]
![image](https://user-images.githubusercontent.com/33469042/32625864-1b0d5206-c553-11e7-80e7-f192b98f2c25.png)
Ha! This time I got a proper screenshot! This time I just minimized the tab and it crashed.
Also, I noticed that upon rebooting she seems to always start with the Smash Bros dialogue, which I can't skip for some reason

Also this is an important detail I forgot. I got the newest release, however to update it I just copied the new folders unto what was provided in the .303 (I think) release. This may be what's causing it.

**Comment by therationalpi** [comment]
Can you try installing it the way described in the README? It should still use the same save file, by the way, if that's what you're worried about.

**Comment by Jxhnathan08** [comment]
Temporarily closed until a response is given.

**Comment by irobertjr** [comment]
I have the same problem here.
I just run Google Chrome and AIMP and Let the game run in background then suddenly the game crashed
