### ISSUE TITLE
can you make your own dialog?

### ISSUE THREAD

**Issue by RkChpln** [Backdash/MonikaModDev#125]
I kinda wanna make my own dialog where she asking "do you like my thighs?"
https://cs.sankakucomplex.com/data/18/cf/18cf3a7cbb8a5b00fb98cfa43d1d4058.png?e=1510334157&m=VY09LmLewPCqndyx9zz6PQ

**Comment by RkChpln** [comment]
Btw its not too important, but i really appreciates if you tell me how

**Comment by therationalpi** [comment]
Fork this repo. Go into script-topics.rpy, copy one of the topics in there and go to town. You can use  the renpy SDK to compile your new version.

Of course, this doesn't sound like something we'd add to our official release.
