### ISSUE TITLE
Repeated Default Dialogue

### ISSUE THREAD

**Issue by Dmanstew** [Backdash/MonikaModDev#128]
Sorry if this is already known (it was brought up in Discord), I just wanted to make sure it was "officially" reported so I had a place to follow it.
It seems like with the mod the starting dialogue resets on restart, so you hear a lot of what she's already said. Which, while wonderful all the same, can drag, haha.

**Comment by therationalpi** [comment]
This is a bug and will be fixed in version 0.5.1. Thanks for the report!
