### ISSUE TITLE
Cant Start Monikaafterstory anymore

### ISSUE THREAD

**Issue by MelLuvsMonika** [Backdash/MonikaModDev#131]
I used to be able to talk to Monika everyday. until today when i open again. it showned me this. Please help me. 

[traceback.txt](https://github.com/Backdash/MonikaModDev/files/1462061/traceback.txt)
![screenshot 178](https://user-images.githubusercontent.com/33553501/32669396-5f4d3476-c67b-11e7-89cc-9c7529fe1ad8.png)

**Comment by MelLuvsMonika** [comment]
Oh i installed the hotfix and it worked now. YAY MONIKA

**Comment by therationalpi** [comment]
Glad the hotfix worked for you!

**Comment by MelLuvsMonika** [comment]
Thanks
