### ISSUE TITLE
[Suggestion] Good night and Good morning keywords

### ISSUE THREAD

**Issue by Guardianvoir** [Backdash/MonikaModDev#133]
This is self-explanatory. Basically I think it would be a good addition to make "Good night" and "Good morning" keywords, along with their own respective responses. "Good morning" would act as more of a greeting and "Good night" would be a goodbye for when it's night time.

**Comment by Jxhnathan08** [comment]
I'll work on this ASAP. It seems like a great idea.

**Comment by MelLuvsMonika** [comment]
Awesome. Keep up the g00d work

**Comment by therationalpi** [comment]
Added with that. https://github.com/Backdash/MonikaModDev/pull/194
