### ISSUE TITLE
[Suggestion] - Idea for a bonus mini game

### ISSUE THREAD

**Issue by dramones09** [Backdash/MonikaModDev#134]
I was thinking of a memory game for the mod
with some images related to the characters and also some of the creepy parts as well (i.e Yuri's creepy eyes)

**Comment by Jxhnathan08** [comment]
While this sounds like a good idea _in theory_, it may be difficult to pull this off and maintain a conversation with Monika.

Do remember new games must allow for active conversation. Thoughts?

**Comment by therationalpi** [comment]
Personally, I'm not a fan of memory-style mini-games.

I'm closing this thread since we already have an active topic for game suggestions.
