### ISSUE TITLE
[Suggestion] Expanding Knowledge

### ISSUE THREAD

**Issue by TheKaiSenpai** [Backdash/MonikaModDev#136]
I was thinking that in timed events, Monika reveals she's been using your internet to access the worldwide web when you aren't looking.  Offhanded comments about past news stories or select fanfictions (literature of all forms.  Maybe even joking references to lemons).  Maybe it could start a week after first playing and be along the lines of:
Hey [P/C]?  Don't be mad, but I found something here called "Internet Explorer"/"Safari" and it made me curious, so I looked inside.  Did you know that people all over the world write stories and poems called Fanfiction?  I even found a few about me!  You'll write about us in a happily ever after, won't you?  I'd really love that.

**Comment by therationalpi** [comment]
There are already a few comments in her random topic that imply she has access to the internet and has seen some of the community fan theories/fan art.

That said, we're trying to keep these sorts of references to a minimum.
