### ISSUE TITLE
[Suggestion] Monika asks about the player's gender

### ISSUE THREAD

**Issue by blueHuntress** [Backdash/MonikaModDev#140]
All of Monika's dialogue has her assume you are of the masculine persuasion, but I think it would be nice if you could tell her otherwise and she refereed to you by the proper title/pronouns.

**Comment by Winblows2** [comment]
I personally believe this happens because of the main character (as shown in a CG with Sayori) _being_ male. While this was great for the base game & other characters, it doesn't exactly pan out for Monika. She talks directly to the player. 

This _will_ be addressed at some point, I'm sure.

**Comment by therationalpi** [comment]
Yeah, definitely needs to be addressed.

**Comment by polishsnake** [comment]
I'll take care of it, tomorrow 14/11/17 at latest.
I just need some dialogue to it.

**Comment by therationalpi** [comment]
@polishsnake what's your planned implementation? We'll have to use this a lot, so I need to know what you're doing. Also, be sure to make your change a feature branch off of the next-release branch.

**Comment by Winblows2** [comment]
Of course it should directly have a sort of "menu choice" option after typing your name on the main menu.

**Comment by therationalpi** [comment]
I disagree, @Winblows2. I actually think it makes more sense for her to ask part-way through the game as a separate event, because the main character in DDLC is male, and so it makes sense that she would assume the same about the player until she had a chance to think about it.

Not to mention that it gives us a chance to have Monika comment.

**Comment by Winblows2** [comment]
Actually, that's true. It would make more sense for it to be mid-way rather than the start.

**Comment by polishsnake** [comment]
So far I've got a function for that and some sample (as Silmeris said that it needs work on) dialogue where Monika asks the player and responses to each.
The explanation I've made for this.
`#As in: m "Beginning of the dialogue", gender_dialogue(word used when player's gender is male, word used when player's gender is female, if player's gender is undetermined), "rest of the dialogue."`

If you want something clearer:
`gender = "N/A"
def gender_dialogue(Male, Female, Other):
    if gender == "M":
        return Male
    elif gender == "F":
        return Female
    else:
        return Other
print("Test", gender_dialogue("M","F", "O"))
gender = "M"
print("Test", gender_dialogue("M","F", "O"))
gender = "F"
print("Test", gender_dialogue("M","F", "O"))`
Just use this in normal Python (this is what I've used to test it out).
It might not be a perfect solution, but it's better than nothing.

**Comment by polishsnake** [comment]
As decided on Discord, we're scrapping my idea of the function and we're going for preset variables.
For example:
if persistent.gender == "Male":
    bf = "boyfriend"
elif persistent.gender == "Female":
    bf = "girlfriend"
else
    bf = "lover"

**Comment by therationalpi** [comment]
His, he, boyfriend, man, boy

**Comment by polishsnake** [comment]
With other examples, could you please add a female version as well as "not judging gender" one?

**Comment by Rune0n** [comment]
Hers, her, girlfriend, woman, girl, female.
Theirs, their, lover. (I'm not too experienced with this section.)

**Comment by therationalpi** [comment]
his/hers/theirs
he/she/they
boyfriend/girlfriend/partner(or lover)
man/woman/person
boy/girl/person

**Comment by therationalpi** [comment]
This is now implemented, the keywords we currently have are: [his], [he],  [hes], [heis], [bf], [man], [boy], [guy]. The event is automatically queue'd after the second day of play, and Monika defaults to assuming the player is male because that's what the MC is.

Thanks Polish for helping to implement this.

https://github.com/Backdash/MonikaModDev/pull/172
