### ISSUE TITLE
[Suggestion] More elaborative "how I'm feeling" features.

### ISSUE THREAD

**Issue by Erenussocrates** [Backdash/MonikaModDev#1422]
I definitely love this mod. Some days ago, I had some issues irl that made me angry and I just opened the "how I'm feeling" tab on Monika After Story -for the hell of it- to express her that I'm feeling mad at that moment. Though, what she said in return was just usual generic stuff like "just close your eyes and count to 10" and "just get out and take a walk if it doesn't work" and stuff like that. 

It just feels kind of dismissive, though. Like, if I told one of my friends that I'm mad right now, and this was their first response, I would think that they just don't want to deal with it right now so they are just giving general advices to send me off to my merry way or something. 
I feel like the real kind of care demands two way exchanges and a bit of curiousity on the person who wants to help. At the same time, I know it might be something hard to pull off.

What I had in mind was, actual curiousity that makes Monika feels like she is actually curious about the actual problem at hand. She could say something like:"What is the problem?" and then the chatbox below prompts player to enter text. And this text could appear at Monika's diary as the problem player had at that day, for example.

This is just a simple and very primitive implementation of what this feature could be in the future. But this might be a good start point, and who knows, might be improved in the future to gigantic proportions. Something like an actual chatbot that takes note of keywords player uses, and then figures out what the player's problem might be, and gives a response in a pool of responses accordingly. 

>there's "dad" keyword inside player's sentence, 
>give advice about dads, stuff like that

**Comment by ScreampunkArts** [comment]
I actually like this idea. It plays into something I've hoped for in a lot of other functions, that she could remember things you've told her that happened on specific days. It would feel more like building a life together that's unique to each user.

**Comment by ThePotatoGuy** [comment]
If we just have her note down the reason you're angry but still give somewhat generic responses, I think that's reasonable. Having her react depending on the text you write is difficult and complex and is why we dropped the chat bar in the first place.

Perhaps #1226 will satisfy your needs.

**Comment by ScreampunkArts** [comment]
As someone who knows absolutely nothing about writing any kind of code, is it really that complex to just have her remember a string? Even without her actually "understanding" it?

**Comment by sr229** [comment]
To be honest, the reason why #1226 exists is to revitalize that chat bar again, since I expect people to requesta more complex Monika to interact.
