### ISSUE TITLE
[Suggestion] Monika's opinions on Natsuki's cupcakes, and Libitina

### ISSUE THREAD

**Issue by jimbo4273** [Backdash/MonikaModDev#143]
I kinda feel like Monika could talk about Natsuki's baking skills, and maybe give a recipe for Nat's cupcakes? We also need Monika's opinions on Project Libitina!

**Comment by Rune0n** [comment]
I believe we already have some of those in the list of possible content.
I’m SURE that she has dialogue when anything related to Project Libitina is mentioned.

**Comment by Winblows2** [comment]
The idea of writing about Natsuki's cupcakes does exist as a python comment in script-topics.rpy, it'll be considered. No sign of Libitina.

This will be discussed.

**Comment by Winblows2** [comment]
Update: There *is* a topic on Libitina, but a topic about Natsuki's cupcakes will be written at some point.

**Comment by monikLover** [comment]
Update: Topics have been added to topics
