### ISSUE TITLE
[Bug] - monika_oneesan

### ISSUE THREAD

**Issue by Rune0n** [Backdash/MonikaModDev#157]
Repeated uses of the conversation with the key "onee san" will open up a console, and ultimately end with the message "Sending mail..."
This is not removed when the conversation is repeated, and can be stacked multiple times.
![bug1](https://user-images.githubusercontent.com/33588908/32750139-ba1481a0-c88f-11e7-8be8-1d8819de0738.png)

**Comment by therationalpi** [comment]
This looks like an easy fix. Probably just need to clear the console thingy at the end of this topic.

**Comment by Guardianvoir** [comment]
Why were you repeatedly saying onee san?

**Comment by Rune0n** [comment]
There are certain questions better left unanswered.
