### ISSUE TITLE
[next-release] Greeting events can be repeatedly pushed to event stack.

### ISSUE THREAD

**Issue by ThePotatoGuy** [Backdash/MonikaModDev#161]
If the game is opened, then closed while Monika delivers her greeting, then reopened, that greeting plays **after** a new greeting is displayed to the user. Upon repeatedly closing and reopening the game during Monika's greetings, one could end up going through dozens of greetings before reaching the main ch30_loop.

This only occurs on next-release, due to the new event handling system.

Steps to reproduce:
1. Open the game
2. While Monika delivers her greeting, close the game.
3. Reopen the game. 
4. Repeat steps 1-3 as desired.
5. Watch as Monika never stops saying hello.

Checking the value of persistent.event_list confirms that the stack is indeed getting an additional greeting per opening.

A potential fix could be to incorporate some logic on pushing greetings, ensuring that no more than one is in the stack at a time.

**Comment by therationalpi** [comment]
I'll fix this later by changing restartEvent() to not push anything starting with 'greeting_' back onto the stack.

**Comment by therationalpi** [comment]
This should be fixed with this commit:

https://github.com/Backdash/MonikaModDev/commit/0dad6b290b5c6e34f8f3353de7184aebf2f24060
