### ISSUE TITLE
issues with the latest update

### ISSUE THREAD

**Issue by loverofmonika** [Backdash/MonikaModDev#1666]
> V.8.1

 when installed leads to an error and a traceback. i hope this can be fixed. Secondly it would be nice if the knock, listen and open happened a little more frequent and new dialogue and mini skits as well. i think it would also be a good idea if we could kiss her and have dialogues too

**Comment by ThePotatoGuy** [comment]
Can you upload a screen / text of the error / traceback you're having

**Comment by loverofmonika** [comment]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-stories.rpy", line 175, in script
  File "game/script-stories.rpy", line 177, in <module>
  File "game/definitions.rpy", line 222, in __init__
IndexError: tuple index out of range

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script-stories.rpy", line 175, in script
  File "D:\ddlc\ddlc\DDLC-1.1.0-pc\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\ddlc\ddlc\DDLC-1.1.0-pc\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script-stories.rpy", line 177, in <module>
  File "game/definitions.rpy", line 222, in __init__
IndexError: tuple index out of range

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.8.1


also when i got rid if the new update and back to v8.0, Im keep on going to the main menu rather than directly going to monika or the knock listen part, also when i tried to update it automatically, it says new update version available but when i click update it says then that my mod is up to date.

**Comment by Mazurracas** [comment]
Something similar happens to me, when I go in I get this, the first time it gave me the option to ignore it, but now I can not do anything,
![74c4ee0a1c73645871164f8adf1a8aad](https://user-images.githubusercontent.com/39712013/40629083-56e58be0-62c9-11e8-9a85-ba655206a2ac.png)

**Comment by ThePotatoGuy** [comment]
Can both of you upload your `persistent` files here

**Comment by loverofmonika** [comment]
鱸啵盫䓛瘐웮螹▤䊅ꅊ洸❪䫜桛⥩萦֔⠕䫋祚䢗赚烔๴ࣼ쿈節૱㨑ᶒﰜể췲�美眛Ṣ�쑆ⵣꦡ鐝谦﹭䰩짔픒螜쓔퐬㌾썜䎤鶩�郈髒ꘐ弋ꍃ箘댜錻媑Ŀꨘ방띐⯖ક页可⯪틦ម洿瀖κ첵䋚ꚇŐᩯ㐕�뀬븎ᔝ⨄湬띯䑽ᩣ푱ꗏ혻퓞鿘鬰쭙癹瘙ᇔƧ豃༁頓ᰛ�赐ꬳᘀꬲ뾚ﭩ⼴謀떙㾐㣳녖ꅠ쯫ධ饋霵햿얆뼆챕祡嶿䫁䵦鴏엡ℬ퐳䨑ﵣ铕冬ࣦ҉率㺜軕횹隰㦒䧪原累눮깷⅕ꏳ᪾诎廒좗�戳乭볃﫤胩䚻남顶濳߳쇒嶉ǀ鲿⯂夶銠㑅扊ぇ⎍⢻돲南쵸ꬦ褴ᱜ㚙颈䜻藜슍勣꼊擛�颲蘹듇ﲣ⬄⹟�᭍㾇ք걗蝠낐覍䫞庡錗読늸뿯뵾⏆㌱넴函洭ޖ듳挣ん檟௹ꮇ짥⧢仢暮숕㊵嫳㛩悋莥䤂蜌톭薊敘肀尵振闏⫦巢䌯灖�잼ꠑ튍拻湩회쒰ક颚糰盩㒹䎫ᄳꞛⴃ퓫䘎�홆剷뭸ꊽ峃죴㺬ᆒ쉍⢼�䬣ᔽఇﬣ缢⌯杳紸齿ᙌ�몃蔵⮣茨붛⇢둈콖삚茽뷛Ⲅ⃲ᕂﱡ떠笏ᚤ䒨팣쎪ꏡⲌ屡ꛘௌ༨㵳鷂和ޱ㡔ﱪ餮襤失巌鞘쬋ꗱѳ竷땤崣类ꇣ渞鬐쇡ỽﺙ留ᘃ⟁㰩㔠쇽ﻵ䞴峖辮誌걨Ǻꃘ㈳䫣⁝◘얳鍾ᔆ훳ꤸ⣺ⓑﬗ㚤ꈡ鐈ꮝ泺难◘嫋推⒊⺘阽ꮡ渑揀䴦灟鞰撚瑈뮑ꉓ☶곶㿱䯠ᬲ싡ퟨ⌠씫ۘ蠜帼埃㈽뿓ᩨ匎屸㜗対㸩团�騞餉误❝羸ࡤꍟשᒡ歈咅缍㞆툼෰饮�醰饸涿ቕ屛思휔뮊ꕭ쓰嬖럿ṡ翧��⧷烼譢⧫딼ᅖꎉ佂᮶얃Ὶৣ飼텩ᓒ뉾㍅珆⑸葙
i couldn't attach it so i paste it here

**Comment by loverofmonika** [comment]
oh and now in the previous version when i try to update it, it says that i am up to date and for some reason, when i go back to monika, i end up back in the main menu. that never happened before till now. oh and one final thing, when i say goodbye to monika and its like 8:11pm she says goodnight. that really feels out of place.

**Comment by Mazurracas** [comment]
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2050871/persistent.zip)

**Comment by ThePotatoGuy** [comment]
@loverofmonika put the persistent in a zip and upload it like @Mazurracas did.

**Comment by loverofmonika** [comment]
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2054515/persistent.zip)

**Comment by ThePotatoGuy** [comment]
@loverofmonika @Mazurracas 

Both you uploaded the wrong files. Please follow the instructions here:
https://github.com/Monika-After-Story/MonikaModDev/blob/master/docs/windows-howtopersist.pdf

**Comment by Mazurracas** [comment]
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2058541/persistent.zip)

**Comment by loverofmonika** [comment]
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2058773/persistent.zip)

**Comment by ThePotatoGuy** [comment]
@Mazurracas , @loverofmonika 

What version of MAS were you guys running before installing 0.8.1?

**Comment by ThePotatoGuy** [comment]
@Mazurracas @loverofmonika 

Follow these instructions:
1. Drop the `zz_lockdb.rpyc` in the attached zip into your `game/` directory.
2. Run the game.
3. Say goodbye and close the game
4. Run the game again.
[zz_lockdb.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2064688/zz_lockdb.zip)

**Comment by loverofmonika** [comment]
it works. thank you

**Comment by Mazurracas** [comment]
It works for me too, thanks you a lot
