### ISSUE TITLE
0.5.1 Typos and other text issues

### ISSUE THREAD

**Issue by Ezr91aeL** [Backdash/MonikaModDev#168]
We can use this thread to signal the misspells and the other problem with the text in this version.

I start reporting a silly moment I've got few moments ago. In one of the new lines, the one where Monika speaks of her name, she tells at a certain point:
_[NICKNAME] is a lovely name, too.
But I think I like [TRUE NAME] better!_

Being my Nickname and True name the same it happened this awkward dialogue:
![image](https://user-images.githubusercontent.com/33189495/32864991-8b847d12-ca61-11e7-9d1b-135a0370b3e2.png)

Since there are other lines that recognize when True Name and Nickname are the same I suppose it should be done the same here.

**Comment by therationalpi** [comment]
Good catch.

**Comment by Guardianvoir** [comment]
![screenshot0028](https://user-images.githubusercontent.com/33330516/32868262-4edf4ae4-ca3f-11e7-993c-1315c345230c.png)
Here she says "then club" instead of "the club"

**Comment by BubbleShuffle** [comment]
http://puu.sh/yn5Dj/4893bdc7a6.jpg

Then should be than

**Comment by monikLover** [comment]
Found a bug regarding reload dialogue.
Step 1: Create a new save file with the mod. This makes the reload dialogues untouched.
Step 2: Close the game without letting her finish a topic.
Step 3: Let her finish her greeting and resume her previous topic.
Step 4: ???
Step 5: Profit

**Comment by therationalpi** [comment]
Have you tried this with the version on `next-release`?

**Comment by badooga** [comment]
In script-greetings.rpy:

    label greeting_welcomeback2:
		  
       m "Welcome back, [player]!"
		       
       m "I hope your day is going well."
		       
       m "I'm sure it is, you're here afterall. Nothing can go wrong now, hehe~

       return

Afterall should be corrected to after all.

In script-topics.rpy:

    label monika_cupcake:

       m "You know what I could really go for right now?"

       m "Natsuki’s cupcakes."

       m "Man, the way she bakes them is amazing."

       m "Plus they look really cute!"

       m "I’m not really much of a sweet tooth myself but…"

       m "Those cupcakes are the definition of sweetness."

       m "Just like me! Ahaha!"

       m "Speaking of which, did you know girls are more likely to develop a sweet tooth?"

       m "Studies show that older women have a less sensitive palate than men."

       m "Resulting in a craving for stronger tastes like chocolate"

       m "I would try baking, but I’m not really much of a baker."

       m "How about you,[player]?"

       m "Do you know how to bake?"

       m "I’m sure your cupcakes would taste just as good."

       m "Maybe someday I’ll get to try them but for now…"

       m "I’ll just settle for the sweetness of your love~"

       return

"you,[player]" should be corrected to "you, [player]".

**Comment by Dmanstew** [comment]
in the "fan page hate" topic, this is a double negative
[http://puu.sh/yy3PM/00bc8af149.png](url)

**Comment by Guardianvoir** [comment]
![screenshot0015](https://user-images.githubusercontent.com/33330516/33523787-3991f762-d7dd-11e7-95d9-b9dd71ddf1d6.png)
It didn't have this typo before, why did it change?

**Comment by Winblows2** [comment]
I'll be fixing this, not entirely sure why a new typo came up.

**Comment by Guardianvoir** [comment]
![screenshot0018](https://user-images.githubusercontent.com/33330516/33554165-9e3ab4fa-d8c9-11e7-8eb7-4a4cdf6c0511.png)
Another piece of dialogue that was correct before but was for some unknown reason changed, why?

**Comment by Winblows2** [comment]
Not entirely sure, fixing.

**Comment by Winblows2** [comment]
After investigation, it seems that the issue you provided is already fixed. Sorry!

**Comment by Winblows2** [comment]
Closing due to a new release being made.
