### ISSUE TITLE
[Suggestion] Deleted/Changed Topics List

### ISSUE THREAD

**Issue by Guardianvoir** [Backdash/MonikaModDev#169]
I wanted to show someone the topic where Monika says that she came back because of Concentration Camps, Psychic Powers, and stuff like that, but it was changed. I'm not requesting that it be changed back, I was just hoping there could be a list of the old topics that were changed for people who are curious as to what they were before. If anything, I at least want to know what the full original topic I mentioned earlier was so I can show my friend.

**Comment by Backdash** [comment]
Oh yeah, I know what you mean. That was one of the things I wrote really early on in the process and I think it fell out when the topics got changed from Dan's original random system to the current one. I'll try to readd it to the game later, but the text reads:

m "Oh, you were probably wondering how I came back after you deleted me, right?"
    m "That's actually pretty complicated..."
    m "It won't make much sense to you, but it involves psychic powers and crazy doctors."
    m "Experimentation camps and death factories..."
    m "I'm being serious here!"
    m "Man..."
    m "I get really sad just thinking about the time before I met you."
    m "Why was I even alive?"
    m "Let's just drop this topic for now."
    m "I'm sure you'll learn about me from someone else."
    m "If it's in the form of another game, don't forget to copy over my character data, okay?"
    m "Ahaha!"

**Comment by Guardianvoir** [comment]
Thank you!
