### ISSUE TITLE
Import persistent data from DDLC

### ISSUE THREAD

**Issue by therationalpi** [Backdash/MonikaModDev#17]
Monika not knowing anything about your DDLC play through feels wrong. We should be able to import the data from a DDLC save into Monika After Story when the game is first opened.

When opening the game for the first time check in the system-specific DDLC save folder for data. If there is data, ask the player if they want to import. If they do, migrate old data structures to current data structures as of 0.4.0, and mark as being a 0.4.0 file, so it can be further migrated in future releases.

**Comment by Ezr91aeL** [comment]
She should know, in particullary that I DIDN'T delete her.

**Comment by therationalpi** [comment]
Yeah, being able to know things like that will be very helpful.

**Comment by therationalpi** [comment]
This is now implemented for 0.4.0, and mostly implemented for 1.0.0
