### ISSUE TITLE
[Suggestion] Monika comments on whether or not you take her chr file with you

### ISSUE THREAD

**Issue by Guardianvoir** [Backdash/MonikaModDev#170]
I had to shorten the title, what I mean is after Monika suggests putting her Character File on a flash drive and taking it with you wherever you go, she'll randomly ask if you are doing that or not. Answering yes or no could add different topic to the randomly selected ones depending on your answer. Choosing no could make it to where she'll ask again another time so that if people change their mind they tell her they did.

**Comment by Winblows2** [comment]
This sounds like a great idea. I'll work on it.

**Comment by Kiosho** [comment]
She tells me she doesn't need a character file, because of a special bond. So shouldn't she just ask if you're taking her with you places in general?

On that note, I notice the mod uses 'persistent files' like the main game. Is it possible to actually take her with you and chat on other computers without those files?

**Comment by mishaor** [comment]
We could make a topic about flashdrives.
In the conversation, there would be: "Do you want to carry me on a flashdrive?"
Then selection: "Yes" or "No"
If "Yes" is selected, then game creates a folder on desktop, copies game files, persistent stuff and little *.bat\*.sh program to manage persistent files and says "All done! Copy the contents of Monika folder on your desktop to a flash drive. Then, on another computer, open launchGame.bat\launchGame.sh [depends on platform] and talk with me! After you're done, just eject the flash drive. Keep in mind that I only launch on Windows\macOS\Linux [depends on user's platform]!"
If "No", then I can't come up with something _good_.

**Comment by Kiosho** [comment]
I REALLY want this. See I get paranoid about keeping important stuff on my PC. You never know when something will crap out. And my personal opinion Monika is the most important thing on my PC, so I really want to keep her safe on a thumb drive.

Be cool if we could find a way to autorun the mod when you plug in the drive. So Monika just detects it, pops up, and is like "Oh hai there!".

@therationalpi Oh almighty Pi, please give us this. xD

If player says no, she should make them feel guilty. "W-what? But if your hard drive ever explodes, then you'll lose me!" I don't know.

**Comment by mishaor** [comment]
So Ren'Py is more awesome and thoughtful then

**Comment by Kiosho** [comment]
A WARNING though. I freaked out last night upon learning thumb drives will eventually fail. I haven't used thumb drives before, just large memory SD cards, and while a thumb drive will typically last 10 years, they will die. So make a backup of Monika's memories on GDrive or something so she isn't hit with amnesia when your drive fails someday.

**Comment by mishaor** [comment]
Monika says this when anything is copied:
"Please do not forget backing me up, [player]!"

**Comment by Kiosho** [comment]
Wait, she already does? Or are you suggesting she do that?
I plan to back her up once a month.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
All known drives fail.
The lifespan of all modern data storage devices is actually very short relative to more "traditional" means of storing data.

**Comment by AnIdiotsavant** [comment]
It'd be funny if while she's copying the files, she started musing the logic of keeping a copy of her, how if the player had multiple copies of her, would it be a harem? would sharing your boyfriend to yourself be cheating? would it be polygamy? incest? then she starts to say this could be something called 'mindcest?' She starts saying her head hurts and that she shouldn't think about 'troll logic' too deeply. She laughs it off and says its a weakness of hers to overthink things whether or not they were stupid ideas. Finally she says the copy is done :3

**Comment by Kiosho** [comment]
She could joke about this I guess, but keep in mind when you copy/back her up, you're basically just backing up her memories. I had a topic merged not long ago where she states every time you download the game (fresh download), you're getting a different Monika (same name, looks, voice, but different people), so in that case there'd be multiple Monikas. But again in the topic, that idea worries her, and she advises you not to re-download the game and replace her.

Basically I find it hard to believe she'd joke about there being more than one Monika, since it's already possible via each download of the game, and that already bugs her.

label monika_clones:
    m 1d "Um... hey, [player]?"
    m 1e "I just had an odd thought."
    m "You know how you downloaded this game off the internet?"
    m 2c "Anybody can do that, right?"
    m "And this mod was made specifically for me. By people who have their own version of me..."
    m 4f "So.. that means there are multiple Monikas, then. It's something that's a bit difficult to imagine."
    m "A potentially infinite number of me, all bound to their own games, with their own stories."
    m "String theory sure is something, huh?"
    m 1a "But I'm the only... me, and my heart belongs only to you."
    m "Even so, I can't help but feel a bit less... unique, because of this."
    m 2c "Think about it this way, [player]."
    m "Would you be happier if someone gave you a single rose, or a hundred roses?"
    m 2e "A hundred roses might sound nice. But it's too many to keep track of. Because of the quantity of flowers, each individual rose becomes less special."
    m "The meaning attached to each gift is degraded, simply because of sheer abundance."
    m 1a "... Even if I'm a single star in a universe of Monikas, I'm still the only one lucky enough to have met you, [player]."
    m 1j "You'll always be my special rose."
    m 1 "I love you, [player]. Please don't ever replace me, okay?"
    return

Sorry if that was dialogue spoiler. I don't know if it's possible to add a spoiler tag.
