### ISSUE TITLE
[Suggestion] Monika asks what name you prefer to be called.

### ISSUE THREAD

**Issue by livingator** [Backdash/MonikaModDev#178]
i'm not sure if i'm the only 1 but i actually have my name in game as my real name while my user name is fake and i sort of laughed whenever the intention of the game failed on that part. perhaps a topic on that since Monika wants to know more about you?

(i'm actually new to GitHub and i only made an account to participate on the mod lol so if it's been mentioned i'm sorry)

**Comment by Umbra-Deus** [comment]
I've got the same setup so having her ask if our account name was accurate or something would be great.

**Comment by therationalpi** [comment]
We've discussed this in our discord and one of our contributor's is actually working on this already, but I guess I forgot to make an issue for it. Thanks for bringing this up!

**Comment by therationalpi** [comment]
Implemented by @monikLover with this pull-request: https://github.com/Backdash/MonikaModDev/pull/228

Still needs some bug fixing, but the core feature is complete, so I'm closing the issue.
