### ISSUE TITLE
Resetting imported ddlc replay data

### ISSUE THREAD

**Issue by SetsunaAkira** [Backdash/MonikaModDev#181]
so I'm not sure how to do this, but I'm trying to re-do the mod with a new imported save I made but I'm not sure how to do it. I already tried uninstalling the game and re-installing the game on steam and adding the mod files which doesn't work, I tried deleting the mod files and re-downloading the zip and extracting the files and moving the clean mod files into the steam directory, that doesn't work. all the attempts just take's me back to where I was with Monika, which isn't an issue because of Monika, but because I was testing something and now Monika is talking to Monika. I kinda want to change it and I want to see that new dialogue when you get the true ending.

**Comment by therationalpi** [comment]
If you really want to start over with new imported data, you will have to delete your persistent data for Monika After Story. Here's a guid on how to find Renpy's persistent data. We store ours in a subfolder called "Monika After Story"

https://www.renpy.org/wiki/renpy/doc/FAQ#Where_does_Ren.27Py_store_my_save_games_and_persistent_data.3F
