### ISSUE TITLE
[next-release] Intro dialogue Outdated

### ISSUE THREAD

**Issue by ThePotatoGuy** [Backdash/MonikaModDev#185]
Intro dialogue is outdated for next-release regarding the hotkey/custom additions:
- Monika still refers to the music switcher as the old, "press 'm' until the music you want" instead of the new music menu.
- Monika only mentions Pong as a playable game. 
- Monika does not mention being able to click the buttons on the left to do the same actions as the hotkeys.

**Comment by Winblows2** [comment]
Will be fixed. I'll do what I can and have @monikLover revise it.

**Comment by monikLover** [comment]
Fixed and updated, Lord Overlords, sirs
