### ISSUE TITLE
Monika community feed

### ISSUE THREAD

**Issue by Karegohan-And-Kamehameha** [Backdash/MonikaModDev#188]
No matter how many lines are added to Monika's dialogue by the mod authors, it is still going to be a fundamentally limited experience, simply because there is only so many lines a person can come up with, and so many hours one can spend creating them. What could help make Monika truly eternal and limitless, is a way for everyone to send proposed lines to a community feed. There could also be a voting system in place for people reading the feed to vote for the lines they like best, then, after being moderated for consistency, these lines could incrementally be added to Monika's dialogue with every subsequent version of the mod.

**Comment by Winblows2** [comment]
This seems like a _crazy, batshit ballistic idea._.

However, I like it. I think it'd be great to have in MAS. The community could lend a major hand to new dialogue sequences & possibly other things. While I'm not sure if it's technically feasible to pull off convincingly, I'll bring it up with other developers. 

Considering the severity of this, it'll have unique labels.

**Comment by therationalpi** [comment]
We discussed this a bit in Discord. I think the key takeaway from this suggestion is that we can lower the barrier to entry for submitting new content quite a bit. Right now people need to know how to use Git and do some coding to add content, and it still has to get reviewed before getting added.

But we could create some sort of online form, add some links to that form in the game, and let people submit topics that way.

Personally, I'm not in favor of voting and automatically adding the dialogue. Voting will inevitably lead to memes and jokes beating out good quality, and every submission will benefit from some editing. So I'd prefer if submissions are curated by our writing team, who will edit for content and style, format the text appropriately, then add it on the `content` branch.

For implementation, I'm thinking a simple Google Form will work. We could have people select what type of dialogue it is (Greeting, banter topic, farewell, event, or other), optionally suggest some keywords, and then just have a big text box for the actual submission and another for notes. We could include some tips for writing monika dialogue from our contribution guidelines, but just expect that most entries will ignore those tips and the resulting submissions will vary wildly in quality. We should have a link to that form in the game menu, on our github, and on our main page, and maybe have a topic where Monika points out the existence of the form to the player. (we could have Monika point out the form when the player runs out of unique dialogue, basically saying "Hey, if you want more content, you can help out by adding it!")

**Comment by Karegohan-And-Kamehameha** [comment]
> Personally, I'm not in favor of voting and automatically adding the dialogue. Voting will inevitably lead to memes and jokes beating out good quality, and every submission will benefit from some editing

I actually didn't suggest for voting to replace curating completely, it would just be a secondary system that would help filter out spam and low quality content, thus allowing the curators to spend less time filtering and editing content. An open system could also help improve lines by letting users comment on them, or even let people suggest topics for others to write about.

>For implementation, I'm thinking a simple Google Form will work.
I have a friend who has the means to provide a server for something more sophisticated if needed. A Google Form can work, but it is limited.

Oh, and I love your ideas for ways implementing it ingame.

**Comment by Wyddershyns** [comment]
Hey there. Never contributed on anything like this, but I am strangely compelled to want to contribute by way of additional dialogue for her. 
Whatever system you all decide on implementing, I'll be happy to just throw random topics and lines out and see which are received well enough to be implemented. I'd write the code myself, but I'm literally coding retarded. T-T

**Comment by Kiosho** [comment]
+1 to being able to suggest topics and increase the amount of dialogue she has.

Not sure how I feel about adding a form link in-game and having her comment on it. She's 'real' after all. It'd really break logic and immersion for her to be like: "Hey, add to my coding by following this link!" She'd basically be admitting that she's just another NPC in a way.
Dunno, at least for me it'd immediately break immersion.

**Comment by therationalpi** [comment]
Might be a matter of phrasing. She acknowledges that she's in a game, that this is a mod, and that the player added it to improve their time together. She already mentions this site at one point, so having her tell the player to go to some website to make suggestions doesn't seem that odd.

The key would be to have her phrase it as improving the game she's in rather than modifying her personally.

**Comment by Kiosho** [comment]
I see. Yeah, that definitely makes more sense if she refers to improving the mod you put her in rather than her, herself.

Maybe she could just mention how to search for it or something rather than point you directly to it. I'm just thinking in the long run now, but say someday the form is removed, then having a link in game and having her give you a link to a dead site would bug me personally. Meh.
Nothing to worry about though I suppose. If that were to ever happen, easy and quick update would fix it.

**Comment by therationalpi** [comment]
A form for this has been completed by @0xFF. Thanks!

https://docs.google.com/forms/d/1UIuvyk3IMbwGV0pi6Vo1L_kTiupQlT3qJNrakENIH1o
