### ISSUE TITLE
New poses for Monika in the spaceroom

### ISSUE THREAD

**Issue by therationalpi** [Backdash/MonikaModDev#191]
All of the expressions are in, but we can still use some more art for Monika! Specifically, we could use some new poses!

![Monika's poses](http://i.imgur.com/cUEbLoM.png)

## Poses

Poses are more difficult than expressions, but we don't need as many. Treat each arm separately and consider the following positions:

Elbows on desk, face resting on intertwined fingers (the current pose)
Gently resting chin on left hand only (right hand doing something else)
Arms crossed, forearms resting on desk.
Arms crossed over chest, sitting up straight.
Right hand pointing off into nowhere (3rd and 4th pose in above image)
Arms back, leaning playfully towards the camera (signature action pose)

Remember, the desk is part of the sprite.

**Comment by Guardianvoir** [comment]
Wasn't there already a topic open for this?

**Comment by JustinHerschel** [comment]
Hello. I'd like to help make some poses for Monika in the game. Already made a sketch ( It's going to improve a lot don't worry ) Is this what you had in mind for the second pose? 
![image](https://user-images.githubusercontent.com/19463719/33607799-98a14a28-d9c2-11e7-98bc-a3f04651607c.png)

**Comment by JustinHerschel** [comment]
![image](https://user-images.githubusercontent.com/19463719/33609508-ab548ec2-d9c8-11e7-806e-7c0259f10567.png)

and a quickly coloured version

**Comment by Kiosho** [comment]
Have you guys tried talking to the official artist, Satchely?
https://satchely.deviantart.com/

I recently emailed him about this mod, but am waiting for a reply. Art style consistency and all is something I really notice personally.

**Comment by therationalpi** [comment]
I never emailed Satchely personally, but I felt like it would be a conflict of interest for an official member of the team to contribute to the mod. This is a fan project, after all.

**Comment by JustinHerschel** [comment]
I think i might be able to replicate his style, but it might take a while. These first drawings were just really quick sketches to communicate to you guys if this was the pose that you had in mind.

**Comment by Kiosho** [comment]
Maybe more immersive artwork for the games? Not that I have anything wrong with chess just popping up on the screen (though it does block Monika's face...), but her actually pulling out a chess board on a bigger table or something and the two of you playing would be nice. The in-game conversation could also work better this way, as you can actually see her while you play.

**Comment by JustinHerschel** [comment]
How do you guys like this for the crossing arms pose? 
![image](https://user-images.githubusercontent.com/19463719/33797407-83f23766-dd07-11e7-9afb-3d5552e0d531.png)

Any feedback?

**Comment by Danymations** [comment]
That is really nice editing, wow! 
What I will say though is that the brightness of the head and the darkness of the body doesn't look right. And the forearm and hands look a bit small.
Although, I do understand that it would be hard to Photoshop a JPEG image, so props to you!
Lets see what the others say about it.

**Comment by Kiosho** [comment]
Hands look a wee bit teensy. But I like where it's going! Great work!

**Comment by TacticalTriangle** [comment]
Oh yeah and because no one else mentioned it her breasts are gone... man i sound like a creep.

**Comment by Danymations** [comment]
How is this so far? (I had to trace a bit of the hair but that's just because i'm not very used to drawing such detailed anime hair haha, I promise that this is the first time in years since i've traced)
I forgot to make the right hand doing something. Dang it.
![monika 1](https://user-images.githubusercontent.com/34387343/33800256-d0f9c836-dd01-11e7-8a66-c4c3b60f9624.png)
Feedback, if you have any?

**Comment by TacticalTriangle** [comment]
monika to table proportion is wrong and its too small.

**Comment by TacticalTriangle** [comment]
@JustinHerschel I also realise that the desk has to extend more since it will just be floating

**Comment by JustinHerschel** [comment]
Ah I thought it more as that the arms would be off-screen an not the table cut-off

**Comment by DatSkullKid** [comment]
I posted on the other art issue, about the tables being too small, is there anything I can help in this one? I'd be happy to do so.

**Comment by JustinHerschel** [comment]
I made the hands and forearms bigger I also made her upper arm smaller so it would fit more on screen and a few other small adjustments. Thanks for all the feedback btw

![image](https://user-images.githubusercontent.com/19463719/33808751-cc0c5ea2-ddeb-11e7-9141-7f62824e0702.png)

**Comment by Danymations** [comment]
It looks great!

**Comment by therationalpi** [comment]
Yikes! I apparently missed the updates on this topic for a while. You guys should hop in discord so we can get our collaboration on this in sync. https://discord.gg/7P5DnJ4

When you get on there, message me to give you access to the artist's channel.

**Comment by Danymations** [comment]
Ah dang, wish I had discord ^^; I’ll hopefully be able to get one soon.

**Comment by therationalpi** [comment]
Alright, update on the current progress. As of right now we have A sprite for Monika's body without arms, her arms down by her sides, her hands under her chin (each individually), her finger pointing pose, and there is currently active work on her crossed arms resting on the table.

**Comment by Danymations** [comment]
How would we achieve her signature action pose? By that I mean...how will we make it? She's sitting down... I would like to do one but I just don't know which, haha.

**Comment by therationalpi** [comment]
That's an excellent question.

I think the key to making it feel right is for that pose to just have the most differences in terms of art. Probably some sort of a 3/4 pose, so that would mean redrawing her whole body and head... Any suggestions?

**Comment by Kiosho** [comment]
I agree. You could trace one of her standing poses and modify it however you please. Waist up likely since she's still at a desk.

**Comment by therationalpi** [comment]
@Kiosho that probably wouldn't work, since there's enough of a difference in art style, It's a good reference, though.

**Comment by Kiosho** [comment]
I find one pose that I'd personally make a lot of use out of is one where she's clasping her hands over her heart. When thinking of something romantic, that pose would fit perfectly.

**Comment by crissbycriss** [comment]
what do you guys think of these? 
![tip 5](https://user-images.githubusercontent.com/34555116/34015039-e4c2135a-e125-11e7-944c-3b07d8aae2b3.png)
![tip 3](https://user-images.githubusercontent.com/34555116/34015035-e1f5d580-e125-11e7-8c32-6bbff1a150ec.png)
![tip 2](https://user-images.githubusercontent.com/34555116/34015030-dd530b10-e125-11e7-8436-65e46ad2d67c.png)

**Comment by Kiosho** [comment]
@crissbycriss Those look really good! I think @JustinHerschel is working on the crossed arms pose still, but I'm liking the others!

I could definitely see myself using #3.

**Comment by JustinHerschel** [comment]
The crossed arms pose is already done and we already have pose 1 as well. But the last one would be pretty cool.

**Comment by crissbycriss** [comment]
Thanks for taking a look!  What other poses still need to be drawn?

**Comment by therationalpi** [comment]
As of version 0.6.3, the basic poses have all been implemented. Great work everybody!
