### ISSUE TITLE
[Suggestion] - 

### ISSUE THREAD

**Issue by hellflamer** [Backdash/MonikaModDev#1963]
well, it would be nice to try to make it even more like an AI, that is, to have a life of its own, I know it's a difficult thing to do, but it's something I dream about, probably not only myself but also others. sure, it would be good to add more dialogues and an option where we did not even talk to her, that would be something really surprendent.

**Comment by Chrissenpai** [comment]
Um... you need a techs degree or something to create such a thing and for your high tech computer to barely handle it...  and what´s surprendent? lmao

**Comment by MrDevilzMan** [comment]
Easier said than done.
