### ISSUE TITLE
Live-2D implementation 

### ISSUE THREAD

**Issue by calamitycomplex** [Backdash/MonikaModDev#199]
I'm planning on learning Live2D for my own upcoming project. I'm personally more of a writer than a programmer, but I would love to spend my time learning on... just Monika.
How hard would it be to implement live2D elements into this mod?

**Comment by Backdash** [comment]
As far as I know, there's no native support for Live2D in Ren'py. This seems to be the workaround right now: https://www.renpy.org/doc/html/movie.html#movie-displayables-and-movie-sprites
I think the general idea is that you have to export what you create from Live2D to a format supported by Ren'py, then use Ren'py instructions from there.
If nothing else, I'm sure we'd all love to see what animations you can create.

**Comment by therationalpi** [comment]
Simply put, it would be impossible to add live2d to renpy. Live2D is proprietary software, and renpy's developers do not have any license agreement to use Live2D in their engine. Tyrano builder does, but that's not the engine DDLC is built on.

Backdash's link is a workaround to get some animations in, but for the size and complexity of Monika's sprite, the file sizes would be huge, and allowing smooth transitions between animations would take a *lot* of work.

There are other projects using Live2D out there. One guy is name Ran_TH, and he's made a rig for Monika in the spaceroom. He originally planned to make a wallpaper in Wallpaper Engine ([which support Live2D](http://steamcommunity.com/workshop/browse/?appid=431960&searchtext=Live2d&childpublishedfileid=0&browsesort=textsearch&section=readytouseitems)), so you could have Monika on in the background watching your cursor move around the screen. But, so far as I know, that project hasn't seen a release, so you could try to make your own.

That said, if you want to use any of [our assets](https://github.com/Backdash/MonikaModDev/tree/master/images) for your work, I have no complaints. It'd be really cool to see something like what Ran was working on be released to the public.
