### ISSUE TITLE
New poses and expressions of Monika in space room

### ISSUE THREAD

**Issue by therationalpi** [Backdash/MonikaModDev#20]
Right now Monika is kind of a statue in the classroom. One expression, one pose. Forever smirking at the player with her chin resting daintily on her hands.

![Image of Monika](https://github.com/Backdash/MonikaModDev/blob/master/Monika%20After%20Story/game/images/cg/monika/monika_bg.png?raw=true)

It's fine for DDLC, where this whole scene has a single uncomfortable mood, but After Story needs a more expressive Monika. Preferably, new Monika art will match the original style and will allow for composites between body/hand positions and facial expressions.

Here are some expressions poses that would be nice to have.

##  Expressions
Anything similar to her expressions in the [base sprites](https://github.com/Backdash/MonikaModDev/tree/master/original_images/images/monika). Page 19 of the DDLC artbook has some really good reference images for the expressions for Sayori. It's mostly different combinations of a few eyes/eyebrows/mouths.

Specifically, there are 4 eyes (Open, half-lidded looking away, smiling closed, sad closed), 3 eyebrows (up, neutral, concerned/embarrassed), and four mouths (smile, open big, closed, open small). Here's a cheet sheet showing each expression currently in the game for the normal sprite.

![monikacheatsheet](https://user-images.githubusercontent.com/8276005/32503079-4d254456-c3aa-11e7-852c-05124f37b130.jpg)

Looking over the sprites from the first half of DDLC, Monika has a lot of concerned looking faces and a certain distance to her. She is kind of sitting on a big secret in the first half of the story, so while she can be playful, she's never really happy. With that in mind, After Story Monika should be more self-possessed and open. More genuine smiles, confidence, and less distraction. The base sprite for Act 3 (above) is a condescending power pose, so displaying that confidence and condescension in some expressions is important. That said, some expressions betraying lingering guilt, uncertainty, or regret can help with bringing out more emotion.

![Monika's poses](http://i.imgur.com/cUEbLoM.png)

## Poses

Poses are more difficult than expressions, but we don't need as many. Treat each arm separately and consider the following positions:

Elbows on desk, face resting on intertwined fingers (the current pose)
Gently resting chin on left hand only (right hand doing something else)
Arms crossed, forearms resting on desk.
Arms crossed over chest, sitting up straight.
Right hand pointing off into nowhere (3rd and 4th pose in above image)
Arms back, leaning playfully towards the camera (signature action pose)

Remember, the desk is part of the sprite.

## Colors and Formatting *(Edit: This is top priority and currently in progress)*

The spaceroom scene already has color filtering in place, but this art should be in true color, like the base sprits from Acts 1 and 2. Color filters can be applied in Renpy to make these match the current backgrounds.

Also, Monika's jacket looks blueish in the spaceroom scene. Consider adjusting her color to be more consistent with the Act 1 sprites.

To make future collaboration easier, please supply original Photoshop (or other editing tool) projects with layers. Export individual sprites as optimized png files, and (wherever possible) separate poses and expressions to be composited on the fly in renpy.

---

Adding new art will take this project to a whole new level, and raise our legitimacy in the community. I'm really looking forward to what you can do!

**Comment by polishsnake** [comment]
Later in development we might want to move outside the space classroom, if anyone's not really good with detailed art, but does have few ideas outside the classroom any sketches would be welcome.

**Comment by SS5D** [comment]
I'm no artist, so I can't help much with this, but what I can do is spend ages pratting around in GIMP and get a pretty good faceless Monika. Someone who is more of an artistic type could probably clean this up a little, but I thought it still might be useful for adding more expressions.
![monika_bg_6](https://user-images.githubusercontent.com/31480493/32135384-5cf37288-bbf6-11e7-8c3c-986c88f90f3f.png)

**Comment by therationalpi** [comment]
Thanks @SS5D That could really help for getting in some expressions quickly!

**Comment by Salad-Puncher** [comment]
[Monika Face.zip](https://github.com/Backdash/MonikaModDev/files/1434022/Monika.Face.zip)
Contains a .psd file
Here, all the elements of the face are separated in different layers and I added some quick landmarks, just in case they could help in any way.

**Comment by Salad-Puncher** [comment]
![image](https://user-images.githubusercontent.com/33268651/32276264-af6d7dea-bf0e-11e7-9711-3a32dffbfc27.png)
[Monika Face 2.zip](https://github.com/Backdash/MonikaModDev/files/1434207/Monika.Face.2.zip)
Updated version. Contains a "serious talk" mouth and two closed eyes (and all the eyes combinations)

**Comment by therationalpi** [comment]
I need to get my Photoshop license renewed before I can look these over. For some reason I'm having trouble opening the files. Very happy to see some progress on the art front!

**Comment by Salad-Puncher** [comment]
You can open .psd files with any program that handles layers, I think? You see, I'm using Paint Tool Sai here.
If you just want to check them out, and maybe do a little bit of edits, free programs like Gimp or Paint.NET* are quite good at it (This is also adressed to anyone that may want to add more content and doesn't know which software to use.)

*Paint.NET requires a plugin to open .psd files

**Comment by therationalpi** [comment]
I only said that because I usually use Pixelmator, and for some reason it's having trouble rendering some of the layers.

<img width="746" alt="screen shot 2017-11-01 at 5 26 32 pm" src="https://user-images.githubusercontent.com/8276005/32298848-d60e4dc4-bf29-11e7-880c-05498d97368a.png">

That certainly doesn't look like the image you posted.

**Comment by Salad-Puncher** [comment]
Indeed. It's just a problem of opacity, I think, tho I don't know how to fix that.

**Comment by therationalpi** [comment]
I'll let you know if using photoshop fixes the problem.

**Comment by Ezr91aeL** [comment]
If it can help knowing it I've opened the file without any problem using Photoshop CS6.

**Comment by haloff1** [comment]
I opened the file with GIMP without any problem. GIMP is basically the free version of Photoshop so I recommend using it if you don't have photoshop.

**Comment by therationalpi** [comment]
Update: Everything opened fine in photoshop. Definitely a compatibility issue with Pixelmator, and I'm the only person that would have used that.

**Comment by Salad-Puncher** [comment]
Sorry, I won't be able to help today. I can create stuff on my side, but not upload them on discord. Basically, the little fucker that my little brother is may ormay not have cut (literally, with scissors) my ethernet cable. I'm typing through the "familial" computer here, and I can't stay for long due to that. Just wanted to warn you guys, sorry.

**Comment by therationalpi** [comment]
Alright, that's fine. When you get the chance, can you upload the .psd and I can load it into the repository? Github actually has some very good tools for managing collaboration on .psd files.

**Comment by therationalpi** [comment]
There's been some serious advancement on this front. We now have a folder for image project files that are being worked on.

As of today, NotSoGiant has finished with a recolor of the original monika art, and has cut her out from the background for use as a sprite. New expressions are still forthcoming.

https://github.com/Backdash/MonikaModDev/tree/master/images

**Comment by therationalpi** [comment]
Quite a bit of progress on this front. We now have some new tools to use in the Photoshop file.

First off, there are now individual color adjustment layers for each part of Monika's outfit! I came up with a set of colors that I felt matched Monika's standing sprites, and rasterized those while preserving the layers for future use/tweaking. We now have a functional colorized image.

@TheAloofPotato has removed Monika's face, giving us a blank canvas for expressions. This was probably the most difficult part of the image editing process.

The photoshop file now has a filter for twilight, which makes Monika fit with the night-time room colors. This will allow us to port Monika's sprites between the daytime and nighttime scenes without having to do the expressions twice!

As of today, the most up-to-date version of the .psd I have is available on the `monika-sprites` branch. https://github.com/Backdash/MonikaModDev/blob/monika-sprites/images/moni.psd

All that's left are the 12 feature items:

4 mouths
3 eyebrows
4 eyes
1 sweatdrop

Once we have those ready for the daytime image, we'll be in business for expressions!

**Comment by therationalpi** [comment]
Expressions are now implemented with this commit:

https://github.com/Backdash/MonikaModDev/commit/73768adf23235cb8f09b82a838965d3a2327f7db

Thank you to @TheAloofPotato and @NotSoGiantDad for all of the help finishing up this art!

**Comment by therationalpi** [comment]
Closing this issue even though poses aren't in and starting a new set of poses.

https://github.com/Backdash/MonikaModDev/issues/191
