### ISSUE TITLE
A music track of calming rain

### ISSUE THREAD

**Issue by badooga** [Backdash/MonikaModDev#201]
> "I really like the sound of rain..."
> "Not so much getting my clothes and hair wet, though."
> "But a nice, quiet day at home with the sound of rainfall outside my window..."
> "It's one of the most calming experiences for me."
> "Yeah..."
> "Sometimes I imagine you holding me while we listen to the sound of the rain outside."
> "That's not too cheesy or anything, is it?"
> "Would you ever do that for me, [player]?"
- Monika (OG topic)

I suggest that a song of just simple, calming rain be added in addition to the music tracks already available. She canonically enjoys the sound of the rain (so it would be appropriate for her to have programmed it in), and this would create a general feeling of stress relief and calmness. What do you guys think?

**Comment by Winblows2** [comment]
I think it's a great idea. I'll bring it up with contributors/collaborators and see if we can get it done.

**Comment by Waffiez** [comment]
@Winblows2 Here, after working with badooga we ended up with this. The sound file is muffled as it would be if you were indoors. Of course, if the sound file needs to be edited I can do so, such as if it needs to be louder, quieter, less muffled etc... It is only 58 seconds long, which will require looping for it to be played over a long period of time. 
[Finished Rain.zip](https://github.com/Backdash/MonikaModDev/files/1516406/Finished.Rain.zip)

**Comment by ThePotatoGuy** [comment]
This is now being addressed with rain art provided by sebastian.
