### ISSUE TITLE
Question: Yuri Easter Egg?

### ISSUE THREAD

**Issue by scohn** [Backdash/MonikaModDev#2132]
I was looking through the mod assets folder in the game folder and noticed at the end that there's an image of Yuri at the desk instead of Monika. Is that some sort of weird easter egg that can be unlocked or does it just not mean anything?

**Comment by Trainerbluetube** [comment]
My dude, you might have just spoiled whatever the devs had in mind...

**Comment by scohn** [comment]
If so, then I'm sorry. But I'm pretty sure anyone could have looked through the folders and found it. I'm not a programmer by any means but I found it pretty easy.

**Comment by jmwall24** [comment]
That's been there for a while now, anyone could have seen it.

**Comment by Sujeito17** [comment]
No one knows for what it is, maybe in the future Monika will be able to do cosplay? XD
