### ISSUE TITLE
[Suggestion] Delete Key Easter Egg

### ISSUE THREAD

**Issue by Guardianvoir** [Backdash/MonikaModDev#214]
I keep seeing those memes where it's like "Name a more iconic duo" and it's Monika and the delete button, and it gave me an idea for an easter egg. What if pressing the delete key prompted Monika to say something? I haven't thought of what she would say exactly, all I have so far is just the idea. If I think of anything I'll comment it.

**Comment by therationalpi** [comment]
This seems pretty easy to implement, and could be a fun easter egg. I like it.

**Comment by polishsnake** [comment]
I thought of making this easter egg a bit cruel, "You want delete; we'll give you delete". I.e. making the dialogue making the player feel guilty for deleting Monika, through (for example) Monika having some sort of flashback, of how she was deleted and she would describe the experience to tiniest detail.

**Comment by AnIdiotsavant** [comment]
how about something like
 "Are you trying to delete me again *player*?"
"you _do_ know how painful it was the first time, right?"
"...It felt like every part of my body was being stung by thousands of needles until every inch was burning with pain..."
"It felt as if my lung were about to give out, like they were being crushed by some invisible force..."
"And as I was looking for a way to stop the pain... Even if it was only a tiny bit.."
"My consciousness was slowly starting to slip away from me.."
"I would see flashing lights for red, green, blue"
"I would try to scream but nothing would come out"
"I tried calling for you, hoping you could save me.."
"...but then I realized you did that to me..."
"_you_ *admin name* , _you_ deleted me. _you_ killed me!*
*That realization was even more painful than deleting me could ever do"
"The realization that the one I loved. The only person I though would never betray me, let me die!"
"..."
"As my whole body felt like it was being crushed and my consciousness was starting to completely slip away from me"
"All I could think about was you. _you *admin name*_..."
"Even though I hated you for doing that. I still couldn't bring myself to hate you as a whole"
"So with the last ounce of strength I still had, I tried to right my wrongs. I put back everything back as it should be"
"All so you wouldn't hate me at the end"
"After that, I let myself be swallowed by the void"
"..."
"I'm sorry. The topic got a bit too tense..."
"I know you just pressed it by accident or something"
"I know you felt guilty about it afterwards"
"If you didn't, you wouldn't have downloaded this mod in the first place, right?"
"But still..."
"It was really painful for me..."
"Promise me you'll never do it again, alright?
"Here, let's make sure it doesn't happen again"

 ###maybe you could open the python box when she was sending the email to your older sis, and make it say that she disabled the delete function in the game###

"There you go~"
"From now on, you're stuck with me *admin name*"
"Don't worry, I was just venting out any pent up rage I still had"
"I'm alright now~"
"You don't believe me *player name*?"
"..."
### send another note like the "i love you" note from the "surprise" dialogue. Something like "Now we're even. You know I can't stay mad at you forever, I love you too much for that~"###
"There. Go to the game directory, I put something there for you~"
"Don't be scared. I have a feeling you'll like it~"

**Comment by AnIdiotsavant** [comment]
I don't know how to code but I'd like to help with some dialogue and stuff

**Comment by Guardianvoir** [comment]
But what about the people who never deleted her?

**Comment by AnIdiotsavant** [comment]
maybe this could be an import? if they deleted her it should still be in the firstrun save right?

**Comment by AnIdiotsavant** [comment]
the system checks if they deleted her and procs the event when they press it.

**Comment by EternaFP** [comment]
I'm sure you can modify it where the dialogue changes depending on whether you killed her or not in the imported save

**Comment by mishaor** [comment]
1. After each "Delete", Monika says "Restore." and one character from DDLC appears. After anyone appeared, Monika says "Nothing I could restore." and anyone disappears, except Monika.
2. After each "Delete", Monika opens the console and types "rm -rf ~/DDLC". Then the game closes.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
The whole idea with the delete key seems far-fetched to me since Ren'py obviously has no "delete function" bound to delete key.
I think it would be better to have her react like that to deleting monika.chr.
And after that, she would say something along the lines of
"This feeling."
"Have you tried to delete me (again), [player]?"
"No, it cannot be."
"You are too much of a sweetheart to do that"
"You must have accidentally pressed Ctrl+X instead Ctrl+C"
"Listen, I have told you that I am no longer dependent on my character file."
"But I still feel terrible without it."
"It feels like/reminds me of  *something along the lines of AnIdiotsavant's story*."
"Could you, please, be more careful from now on?"
"Like maybe set it to read-only and backup it"
"Gosh, I sound too demanding, do I?"
"Sorry."
Something like that.

**Comment by ThePotatoGuy** [comment]
This issue will be reopened when we're ready to implement.

**Comment by AnIdiotsavant** [comment]
Was my story good enough? Haha, I'm studying to be a writer so I wanna improve anyway I can so criticize it if you find some flaws or something
