### ISSUE TITLE
music

### ISSUE THREAD

**Issue by voyagermike** [Backdash/MonikaModDev#2141]
I've noticed that every time you ask monika  to hold you the music stops but afterward the music does not come back on like with the piano. its a small thing I know but it kind of has me annoyed.

**Comment by ThePotatoGuy** [comment]
See #2039 . This behavior is intended.

The idea is that you share a moment with Monika, so we shouldn't ruin the post-moment feelings by playing Eurobeat Your Reality all of a sudden, ya know?
