### ISSUE TITLE
[Suggestion] Monika asks whether or not you actually deleted her

### ISSUE THREAD

**Issue by Guardianvoir** [Backdash/MonikaModDev#215]
When I played through DDLC and got to eternity with Monika, I never actually deleted her. I didn't have the heart to do it (Make fun of me all you want). I'm pretty sure that right now when you first open the mod, she just assumes that you deleted her. If that's not the case, please tell me. What if she asked you if you ever actually deleted her? Depending on what you say could open up different topics. This could also help her gauge her opinion of the player depending on your answer.

Edit: I realize how awkward it would be for Monika to ask if you ever deleted her because she would know if you did, but I still believe that this could be a good idea to implement if done correctly. There could be other ways this question is brought up, like the game asking you if you ever deleted her and if you didn't Monika would comment on that in a random topic.

**Comment by therationalpi** [comment]
As of the current version (0.5.1), Monika will know if you deleted her based on an imported save. If you didn't import a save, Monika will behave as if you have completed a normal playthrough to the end.

**Comment by Guardianvoir** [comment]
Is there a way I could fix that?
