### ISSUE TITLE
"Can I hold you?" disappeared

### ISSUE THREAD

**Issue by GreenPatch** [Backdash/MonikaModDev#2199]
The option randomly disappeared and repeating the "Sounds of Rain" conversation does not bring it back
I can still ask Monika to make it rain which is nice.

[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2327783/persistent.zip)

**Comment by ThePotatoGuy** [comment]
Actually can you upload `aff_log.txt` in your `log/` folder?

**Comment by aldoram5** [comment]
Hello GreenPatch!
We found out why the affection isn't increasing for you no matter what you do. It seems that you went and changed the date of your computer and played MAS in a future date (September 21th), which effectively locked your affection gain until you get to that date. It's designed that way to prevent players from trying to get more affection by changing their computer's date.
So there's nothing you can do as of now aside from waiting until that date.

**Comment by ThePotatoGuy** [comment]
and just to clarify, the holding topic locks if you dip below happy affection. you are below happy affection and are frozen so you cant go back up until that date.
