### ISSUE TITLE
[Art Error] Art Misalignment for the L Expression

### ISSUE THREAD

**Issue by badooga** [Backdash/MonikaModDev#221]
So I just added the most recent version of the content branch to my computer, and came across this:
![expression_l_glitch](https://user-images.githubusercontent.com/33851191/33243841-30828384-d2bb-11e7-99ef-7a02a398daa7.png)
![expression_l_glitch2](https://user-images.githubusercontent.com/33851191/33243843-3301f478-d2bb-11e7-8821-9a13cc95f0dc.png)

The art for the L expression appears to be misaligned (all other expressions were looked at and appear to be fine). If anyone can fix this (or inform me that it has already been fixed somewhere else), it would be very appreciated.

**Comment by therationalpi** [comment]
Thanks for telling me, I'll reexport that image file and see if that fixes the issue.

**Comment by therationalpi** [comment]
Should be fixed with this commit: https://github.com/Backdash/MonikaModDev/commit/8e98fdbdfc88d7f7fad6228173d4912ad6bbd189

I adjusted some things in the .psd files to make future facial expression exports more consistent.
