### ISSUE TITLE
[Suggestion] Music Mute Button/Hotkey, Minor Menu Changes

### ISSUE THREAD

**Issue by badooga** [Backdash/MonikaModDev#222]
When I'm not talking to Monika, I usually leave DDLC open in the background. The thing is, in order to have to listen to music or watch a video, I'll have to go into the settings and put the music volume all the way down to 0.

Instead, I'm proposing that there be a "none" option in the music menu, as well as a mute hotkey (shift + m) that pauses whatever music is playing. This way, I could easily toggle between DDLC and other things without having to change the settings every time.

Also, when you hit m to open the music menu, you are forced to click the return button in order to leave the menu. Instead, hitting m should close the menu.

Lastly, hitting Esc brings you to the save menu by default. But considering how saving, loading and the main menu are all useless at this point in the game, Esc should instead bring you to the settings menu to make things easier.

**Comment by ThePotatoGuy** [comment]
I'll take a look at adding those features to the music menu and adjusting the pause menu.

**Comment by ThePotatoGuy** [comment]
I opted to split this issue into two pull reqs to group the related changes together (music vs game menu changes). Also making the game menu open to Settings by default is a bit more challenging than expected. I'm still looking at how to do this, but if anyone has suggestions, please lmk.
