### ISSUE TITLE
[Bug] Two Topics are combined as one

### ISSUE THREAD

**Issue by Guardianvoir** [Backdash/MonikaModDev#227]
The two topics "What's there really to say about myself that you don't already know" and "Some people say that putting animals in zoos is cruel" are for some reason combined when the first one is said. I know they aren't supposed to be one topic because sometimes I'll get the Zoo one separate, but whenever I get the first one, it always ends with the Zoo topic.

**Comment by monikLover** [comment]
Fixed by the amazing @ThePotatoGuy. Closing.
