### ISSUE TITLE
Color Correct Classroom

### ISSUE THREAD

**Issue by therationalpi** [Backdash/MonikaModDev#23]
The "Spaceroom" is lit by a twilight tinted light, and that throws off the colors a bit. To allow for a better day/night cycle and more compatibility with future sprite work, it would be good to have a properly color corrected room.

Here is the current monika_room.png art

![Monika_room](https://github.com/Backdash/MonikaModDev/blob/master/Monika%20After%20Story/game/images/cg/monika/monika_room.png?raw=true)

Compare the colors in that to the same classroom in act 1

![Classroom](https://github.com/Backdash/MonikaModDev/blob/master/original_images/images/bg/class.png?raw=true)

The lighting is great for ambience, but that lighting should be added using filters in future versions.

A first attempt at this using a simple white balance tool is currently used as the daylight scene.

![Daytime](https://github.com/Backdash/MonikaModDev/blob/master/Monika%20After%20Story/game/images/cg/monika/monika_day_bg_eq.png?raw=true)

But the result has a noticeable blueish tinge, compared to the Act 1 background.

**Comment by instilledbee** [comment]
Hey, I took a shot at doing some color correction and lighting adjustment. I based the colors on the bg colors of the Act 1 classroom. Hope I got it right:

![image](https://user-images.githubusercontent.com/5665389/32120418-0c3be930-bb8b-11e7-90dc-8b86731ed784.png)

**Comment by therationalpi** [comment]
Looking very good! I feel like the back wall and support beam could be a little lighter still and the floor a tad more saturated, but that's definitely a better cast than the blueish version we're using now.

**Comment by instilledbee** [comment]
Thanks for the feedback! Here is attempt number 2. Let me know if I was able to address the saturation you described:

![image](https://user-images.githubusercontent.com/5665389/32136289-93225e2c-bc3d-11e7-93dd-7afb3088285b.png)

**Comment by therationalpi** [comment]
Excellent, thank you!
