### ISSUE TITLE
adding custom songs

### ISSUE THREAD

**Issue by voyagermike** [Backdash/MonikaModDev#2483]
I was trying to add a new song to the music folder and whenever i do it does not change anything about the music. some help would be very much appreciated.

**Comment by ThePotatoGuy** [comment]
Can you verify that you followed the steps [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Custom-Music#adding-custom-music)?

**Comment by voyagermike** [comment]
I could not figure out where the directory was

**Comment by ThePotatoGuy** [comment]
You have to make it.

**Comment by voyagermike** [comment]
the ddlc/ directory?

**Comment by ThePotatoGuy** [comment]
you make `custom_bgm/` in the same directory `characters/` is in

**Comment by jmwall24** [comment]
Should look like this when you are done.  Make a folder called custom_bgm in the ddlc/ directory so it's with the characters folder and the DDLC.exe file.

![screenshot_138](https://user-images.githubusercontent.com/36523761/45913379-55e23b80-bdff-11e8-8304-54ec4fbca82a.jpg)
