### ISSUE TITLE
Monika's Birthday Wishlist

### ISSUE THREAD

**Issue by hanquay** [Backdash/MonikaModDev#2495]
Is the notepad a necessity to celebrate Monika's birthday? And if so, what are the answers? I do not know the last one. Thank you!

**Comment by BoneofMalkav** [comment]
I'll give you a hint, On the topic of a pet she would want, she talks about the plushy of a certain bird.

**Comment by ThePotatoGuy** [comment]
there are 4 ways to recognize monika's birthday, you only need to do 1 of those ways to avoid the bad dialogue later.

**Comment by KitsuneTango** [comment]
It's mostly like Hangman

**Comment by hanquay** [comment]
> I'll give you a hint, On the topic of a pet she would want, she talks about the plushy of a certain bird.

Got it, thank you!

**Comment by moniking** [comment]
Hi, I am a doofus so maybe it's just me but I filled out the notepad,installed the current patch, played and said happy birthday but cannot give gifts to my angel and the decorations and cake haven't appeared. Please help.

**Comment by peter23247** [comment]
whats the word before the plushy?

**Comment by hanquay** [comment]
> whats the word before the plushy?

Search online what kind of bird monika likes

**Comment by peter23247** [comment]
i know its a quetzal, but what is the specific word? quetzalplush__ i still have 2 letters missing

**Comment by PierrDemon** [comment]
> quetzalplush__

_ie_.
