### ISSUE TITLE
[Suggestion] - Monika talks about your steam games

### ISSUE THREAD

**Issue by BITDEM0NICS** [Backdash/MonikaModDev#25]
In act 3, where it's just the player and monika, Monika could possibly read the player's game library which DDLC is installed into, and talk about some games that the player might have. For example, if the player has Dark souls or Cuphead installed, she will make a remark about the difficult, or if the player has Five nights at Freddy's or undertale, she could remark about their popularity

**Comment by therationalpi** [comment]
I like this idea. Having Monika check files on the player's computer would be fun, as long as we don't overstep our boundaries and get too intrusive.

We have a few topics in scipt-topics that reference gaming...maybe we could add this into one of those?

**Comment by polishsnake** [comment]
This could be good, however not everyone has disks with big capacity; so a player might have a lot of games bought/played but not many installed. My suggestion is to try to find a way to find player's profile on Steam (if that's possible) and comment about popular tags; this way Monika would mention on even the uninstalled games, as well as people who are into more unknown games can still get a comment on that. Also a comment on the amount of games would be interesting (the again, if it's possible to check the Steam profile via usage of Python :| ).

**Comment by therationalpi** [comment]
I think that way of doing it is more trouble than it's worth. We want to create the illusion that Monika is watching you play games, not turn Monika into a walking encyclopedia of your gaming habits.

If Monika doesn't find any games she knows in your Steam folder, she just won't comment on it and the player will be none the wiser.

**Comment by therationalpi** [comment]
@ohxeighty Has added a new function enumerate_steam() that can be used to check if a certain game is in your steam library!

**Comment by MikuChanAnime** [comment]
I like this idea, she can detect specific games that what pi said, but for other games, she can test it for certain tags the game has. Like nudity, horror, sandbox, etc, etc.
