### ISSUE TITLE
[Bug] Muting and changing music does not stick

### ISSUE THREAD

**Issue by badooga** [Backdash/MonikaModDev#254]
If you change the music from one song to another while Monika is in the middle of a topic, the end of the topic will cause the previous song to play again despite the other song being selected. Attempting to switch back to the second song at this point will not work - one must switch to a different song and then go to the originally desired one in order for it to work again.

Example: Surprise! is playing, and you decide to talk to Monika about something OR she brings up something of her own. Halfway through the topic, you switch to I Still Love You. When the topic finishes, Surprise! starts playing despite you choosing I Still Love You. Attempting to change back to I Still Love You will not work, but changing to Just Monika and then going to I Still Love You will.

Another aspect of this bug is that if you mute the music in the middle of a topic, it will become unmuted once it is finished, or visa versa.

This bug does not seem to happen if you change the music or mute it when a generic response is present, nor does it happen when you try this during the game choice dialogue.

Both aspects of this bug have a 100% reproduction rate as of the pre-release for 0.6.

**Comment by ThePotatoGuy** [comment]
Damn, this is another side effect of context issues. I'll figure something out for this.

**Comment by therationalpi** [comment]
Fix for this has been merged and should be available in the the next beta build.
