### ISSUE TITLE
Monika Left me after chess and I can't seem to get a new start in after story.

### ISSUE THREAD

**Issue by alphabeowolf** [Backdash/MonikaModDev#2598]
So let me be clear, I know she is gone, and that the save file of that game is gone. Though my problem isn't getting her back. The problem is that I can't start a new game or move one. So I always a side copy of DDLC when I mod, but to make sure I did use a steam version and I have countlessly uninstalled and reinstalled and tested out the games prior and after I put the mod back in. And I have deleted everything I can think of even remotely related to DDLC. I know there some hidden file somewhere that states "If Cheats at 3 times and chooses "..." then delete files and crash game." though I cant find it. 

Is there any reason I can't seem to start a new Monika After story game? What exactly am I doing wrong?

**Comment by MonikaWiafu** [comment]
well delete these files to reset everything if you already have i'm sry but i can't help you....
![dis boiiii](https://user-images.githubusercontent.com/41130387/45993329-6a6f3f80-c05c-11e8-8472-145e84999459.png)
