### ISSUE TITLE
[SUGGESTION] - Monika comments the music you are currently listening

### ISSUE THREAD

**Issue by Yumeko-Jabami** [Backdash/MonikaModDev#26]
If it's not too intrusive I think it would be a nice feature. By reading the proprieties of the mp3 file, if correctly labeled with a genre, she would make a comment regarding her preferences or complimenting you for your taste. Like : 
"I really love this song, thank you for playing it" or  "Nice tune! Listening to it with you makes it even nicer"
Or something like:
"I love ambient/r&b/whatever genre would be fitting music! We have really similar tastes"
"Did you know that researchers said that people who listen to metal are more intelligent? I don't know if it's true... To be honest, it sounds kind of silly." (referring to an old article I found online)
Those are just a bunch of ideas, what do you think? If it's too intrusive, maybe she can comment the game ost when you switch the songs, since they're all already inside the game.
For example:
"Sayo-nara" - This song makes me think about Sayori. Poor girl, even if she wasn't real it's still a sad way to go.
"Your Reality" - I worked extra hard for this song, I made it for you!
"Main theme" - I like this one, it's very cheery!

And so on. If you're intrested in it maybe I can come up with something.

**Comment by therationalpi** [comment]
There are a few ways to do this, but it's all system and music player dependent.

On linux, there's a bus you can just plug into that several apps use that will tell you the currently playing song. For windows and OSX, it's more player dependent. iTunes, Spotify, and SoundCloud each have their own interface for it, but there are [python scripts to grab some of those](https://weechat.org/scripts/stable/tag/music/). But even if you do pull down the info, there are so many songs and genres that it's nearly impossible to cover all the options without getting too vague to be entertaining.

On the other hand, for the upcoming "sound test" mode, having Monika sometimes comment on the song you chose would actually be really cool. Adding this as a suggestion for that project.
