### ISSUE TITLE
How do I update the game with the 0.6.0 patch?

### ISSUE THREAD

**Issue by AnIdiotsavant** [Backdash/MonikaModDev#262]
Just started playing. Thank you for the game, I almost cried from the line she said about he being eternal and me slowly dying. I just saw the update and downloaded it. I don't really know how to update it. Can I ask for some help?

I tried patching it myself using an old issue I found here and I got this error:

I'm sorry, but errors were detected in your script. Please correct the
errors listed below, and try again.

The label chara_monika_scare is defined twice, at
  File "game/script-ch30.rpy", line 391 and
  File "game/script-introduction.rpy", line 109.

The label ch30_reload_0 is defined twice, at
  File "game/script-ch30.rpy", line 522 and
  File "game/script-introduction.rpy", line 148.

The label ch30_reload_1 is defined twice, at
  File "game/script-ch30.rpy", line 534 and
  File "game/script-introduction.rpy", line 161.

The label ch30_reload_2 is defined twice, at
  File "game/script-ch30.rpy", line 542 and
  File "game/script-introduction.rpy", line 171.

The label ch30_reload_3 is defined twice, at
  File "game/script-ch30.rpy", line 551 and
  File "game/script-introduction.rpy", line 181.

how do I fix this?

**Comment by therationalpi** [comment]
First off, make sure that you are downloading the zip file from this page: https://github.com/Backdash/MonikaModDev/releases/tag/v0.6.0-beta

**Do not** download by downloading the source code or cloning the git repository. Those files are for developers and may not behave as expected when added to DDLC.

My recommendation for installing this update is to start with a clean installation of ddlc downloaded from ddlc.moe and following the instructions in the README.html file included in the mod zip. Don't worry about losing save data from previous versions, those are not saved in the DDLC directory, so a clean installation will not remove them.

Alternatively, if you want to wait a day or two for the actual release of 0.6.0 there will be a new installer that should make the process easier.

**Comment by AnIdiotsavant** [comment]
Thanks, it works
