### ISSUE TITLE
0.6.0 typos

### ISSUE THREAD

**Issue by Anno-Chan** [Backdash/MonikaModDev#263]
Found 1 typo in the spicy food topic 

"I read somewhere that humans are the only species that actually enjoys spicy things."
There shouldn't be "s" at the end of enjoy when talking about humans.

Found 2 in the good morning topic if its said in the afternoon.

"It could also be a sign that you're not taking of better care of yourself."
The "of better" should be like "a better" or something.

"I'd be really sad if you spent less time with me when you get the a fever or something."
There is an extra "the" at "get the a fever" part, should be just "get a fever"

**Comment by therationalpi** [comment]
Thanks for pointing these out.

**Comment by therationalpi** [comment]
Fixed in this commit: https://github.com/Backdash/MonikaModDev/commit/b87bbcc2528c3e739e1da4b72ea6b1bbcf9c5311
