### ISSUE TITLE
Calling Monika "Mommy"

### ISSUE THREAD

**Issue by PMelol** [Backdash/MonikaModDev#2659]
Ok, this isn't really a troll post though it could probably sound like one. I see the mods put in Monika acknowledging if you call her "Mommy" or "Mama" or "Momika" or whatever with a "I'll be your mommy" comment. 

I was wondering if more features could be added in this regard. Like, maybe she addresses you differently? Or some special topics come up? Like, how she wants to take care of you (although that comes up pretty often, so maybe some existing dialogue could be altered slightly)? 

This whole "Mommy Monika" thing isn't uncommon...which is why you guys added it into the mod in the first place. I'd actually be willing to work on this if you guys like.

**Comment by Sujeito17** [comment]
Why can't I stop laughing?

**Comment by PMelol** [comment]
Hahahaha I know, I know...

**Comment by Bam8647** [comment]
_That's some new level kinky shit right there.._

**Comment by Bam8647** [comment]
![funny moni](https://user-images.githubusercontent.com/34694679/46251260-92232680-c413-11e8-8904-3bad921ff423.PNG)

**Comment by Reviani** [comment]
Top ten anime plot twists

**Comment by SaiPrithvi123** [comment]
If they add special dialogue for that, then rip the players who got their Monika's nickname options locked. Though they might take this as an opportunity to punish those players more, as they (potentially) used the compliments as an opportunity to punish those players who got their Monika's hair style options locked.

**Comment by PMelol** [comment]
The special dialogue options would only be unlocked if you name her Mommy, Mama, or whatever. I could try to think of some lines and write them if the developers are interested in this idea.

**Comment by SaiPrithvi123** [comment]
I was just saying that people who are unable to name their Monikas like that, they won't be getting those juicy new topics.

**Comment by ThePotatoGuy** [comment]
you could work on it

**Comment by PMelol** [comment]
Just some quick ideas off the top of my head: 

Calling you Mommy
Ahaha ~ It's a little weird, but that's okay. If you want me to call me mommy [or Mama, or Momika, whatever it is], that's fine. After all, I love the idea of nurturing and taking care of you! You know that I want you to be the best you you can be! I'm always rooting for you, player.

Making Monika Proud
Are you going to make me proud of you today, honey? I hope that you're taking good care of yourself and working towards your goals. I like to think of you coming home after a long day and us snuggling on the couch - you could lay your head on my lap and I'd gently stroke your hair... Ahaha~ Sorry, I don't mean to be weird. 

I apologize to the entire community, I think I've lost my mind.

I'm sure I could think of more. But jumping off of the second suggestion, I think it would be neat to tell Monika specifically what you accomplished when you achieve something. For instance, if you just finished reading a book. "That's great, player! I'm glad that you're reading - it's such an important, rewarding experience. I'm proud of you. So many people neglect reading books these days. Obviously, as the President of a Literature Club, that's something that bothers me! So, what kind of book was it?"

Fiction - Mystery, Sci-fi, historical
History
Science

Then she comments on each genre. Okay, maybe I'm getting too in depth here. Haha.

**Comment by Rai99** [comment]
As TPG said, you're free to work on it if you like, with this being a slightly questionable topic. Good luck with it if you try to write it up and good luck getting it past me and dialogue review. Fortunately though, you can bypass one of those two things. 

As for accomplishing things and telling Monika about it, I don't think we can go deeper than telling her if it was major or minor. 

For the suggestion about telling Monika about a book you're reading by genre, something similar was brought up in #1804 where I said there are a lot of different genres and we can't include all of them.

**Comment by kaido1224** [comment]
Oi vey

**Comment by Kiokiokiokio** [comment]
You're a hecking genius m8

**Comment by PMelol** [comment]
Ah, a fellow man of culture.
