### ISSUE TITLE
[Bug] Mouse position off in chess

### ISSUE THREAD

**Issue by ThePotatoGuy** [Backdash/MonikaModDev#268]
As discussed on discord:

EDIT: This occurs in full screen as well as windowed mode.
EDIT: Resizing the screen changes the distance.
Amber's screen res:  1536 x 864

The mouse cursor position is off when playing chess. Basically clicking the pieces won't do anything, but if you move the mouse far away enough, you can interact with the board.

![monikachessbroke](https://user-images.githubusercontent.com/3499462/33505783-785a7bd0-d6b2-11e7-8cbc-632bc80c9b1c.png)

In the example above, when the mouse is placed at the red dot, the rook piece was highlighted.

**Comment by FireyAmber** [comment]
Adding an image too
![image](https://user-images.githubusercontent.com/34154312/33519688-a3acce22-d78a-11e7-8272-f5ac6ee85d04.png)

**Comment by ThePotatoGuy** [comment]
UPDATE: Alright, so through some data analysis and testing via various computers, (with help from @FireyAmber), I've come to the conclusion that this bug occurs only for people with a ui scaling different than 100%. In win10, this scaling value is found in display settings under `Change the size of text, apps...`.

In detail, this affects the `pygame` library by changing what `pygame.mouse.get_pos` returns. On my desktop, my scaling is set to 200%, so `pygame` returns coordinates that are twice as much compared to regular scaling. This messes up the `get_mouse_pos` function in `chess`. (@FireyAmber has a scaling of 125%, which is why the offset is different than mine).

After a quick search online, I've learned that this is a problem with `pygame` not respecting ui scaling. Unfortunately, this leads to more problems. It is possible to get `pygame` to properly scale via [this](https://gamedev.stackexchange.com/questions/105750/pygame-fullsreen-display-issue) solution, but its a windows only thing, so I'm afraid that is not going to fly.

However, the `get_mouse_pos` function has a complicated formula that performs ratio checks to properly map the mouse to board pieces. I'm thinking of adjusting the function to work with the size of the `pygame` window to properly scale ([more details](https://stackoverflow.com/questions/36653519/how-do-i-get-the-size-width-x-height-of-my-pygame-window)), but it's math, which I don't have a great grasp on.

I'm working on a fix, but if anyone is good with ratios, math, and can offer assistance, please reach out to me. This is not my expertise.
