### ISSUE TITLE
Talk function only works when cursor is within the dialouge box

### ISSUE THREAD

**Issue by SetsunaAkira** [Backdash/MonikaModDev#272]
Yeah, not sure why but when I type something in the dialogue box, pressing enter won't do anything until the cursor is within the dialogue box

**Comment by SetsunaAkira** [comment]
UPDATE: it does work when the cursor is outside the box, im am now unsure of the cause of the times pressing enter results in nothing

**Comment by ThePotatoGuy** [comment]
This can happen if the mouse is hovering over the buttons on the left. I'll look into a fix, but it may not be possible because of renpy limitations with screens.

**Comment by ThePotatoGuy** [comment]
Since renpy proiritizes mouse interactions over keyboard, this is practically impossible to fix.
And this really is a minor issue. Especially since it's not that big a deal to move the mouse away from UI elements anyway.
