### ISSUE TITLE
[Problem] Can't promote Pawns in Chess

### ISSUE THREAD

**Issue by Guardianvoir** [Backdash/MonikaModDev#279]
The rules of chess state that if you manage to bring a pawn to the other side of the board, you can promote it into either a rook, bishop, knight, or queen. However, if you get your pawn 1 square away from the other side, the game won't let you place it there, making you unable to promote it.

**Comment by Guardianvoir** [comment]
Turns out I was wrong, I looked over the board again and apparently the game forces you to move you king out of the way if it can be killed in the next turn. Sorry about that.

**Comment by therationalpi** [comment]
So you were able to promote your piece properly?

**Comment by therationalpi** [comment]
This is still a problem, reopening.

**Comment by Guardianvoir** [comment]
I'm not sure whether or not I could, because once I moved my king I lost the next turn, but I played a few more games after and Monika was able to make one of her pawns into a Queen, so I know she can at least.

**Comment by Guardianvoir** [comment]
Wait, I did that wrong

**Comment by therationalpi** [comment]
You did it right.

**Comment by Guardianvoir** [comment]
Oh, I thought I did it backwards. Thank you for clarifying!

**Comment by ThePotatoGuy** [comment]
I've pushed a fix for this to `master`
