### ISSUE TITLE
Is it still possible to proc what monika says when you look into her files?

### ISSUE THREAD

**Issue by AnIdiotsavant** [Backdash/MonikaModDev#280]

**Comment by NotSoGiantDad** [comment]
Apologies but what do you mean?

**Comment by AnIdiotsavant** [comment]
you know how if you look into her code in arc 3 she'd start saying something? would you be able to proc it again in the mod?

**Comment by MadHaetter** [comment]
If you are referring to the unsaid line she has, its specifically for looking into her code and looking at all her lines and it assumes you have to read it. I see no reason to have this spoken normally as it still works here and fits 'incanon' with what we are doing. If you really want to see  the line do what it assumes you do, go look at the code, its in https://github.com/Backdash/MonikaModDev/blob/master/Monika%20After%20Story/game/script-topics.rpy on this website (thats click code > Monika After Story > game > script-topics.rpy).
Other then that I can think of no line she says when you look into the code-y stuff except when you delete her.

**Comment by therationalpi** [comment]
Yeah, so far as I know, there's no specific line when you go into the script files because Monika has no way of knowing if you did access those files.

The secret topic is still in the files, though.
