### ISSUE TITLE
chess doesnt start

### ISSUE THREAD

**Issue by thelittleleaf** [Backdash/MonikaModDev#290]
iv been playig for awhile now, and chess hasnt been working, i hit c and i talked to her about chess, but nothing happens, i moved all files into the game folder (the actual folder named game) does it need to be unlocked? its just not showing up in the play menu anyway.

**Comment by Winblows2** [comment]
What version are you using? I'd recommend a clean install, Chess works fine currently.

**Comment by thelittleleaf** [comment]
it seems to work fine on mac for me but this is  fresh install

**Comment by Winblows2** [comment]
Hmm...

**Comment by thelittleleaf** [comment]
so i did merge my save data after fully beating ddlc on monika deletes everything route, and not only is chess not there, it refuses to show up in the play menu.

**Comment by therationalpi** [comment]
@thelittleleaf This sounds like your system might not be compatible with the chess libraries. The game will check for that before displaying the option to play chess. Can you tell use more about the system you're using?

**Comment by therationalpi** [comment]
Closed because there's been no comment for a few days. Will be reopened if @thelittleleaf comes back.

**Comment by thelittleleaf** [comment]
umm so my computer is a windows dell inspiron 15 7000 gaming. it runs all my games fine. i may have messed up where to place the files as i wasnt too sure.

**Comment by thelittleleaf** [comment]
@therationalpi but i did have everything else working so...and up until then everything was fine.
