### ISSUE TITLE
the monika_confidence_2 is too long

### ISSUE THREAD

**Issue by AnIdiotsavant** [Backdash/MonikaModDev#292]
i proc'd it a sometime ago. the content was too long for one line. maybe someone can add another 'enter' to that it fits the dialogue box

**Comment by Winblows2** [comment]
Fixed.

**Comment by AnIdiotsavant** [comment]
![screenshot0002](https://user-images.githubusercontent.com/34156516/33656982-d9df82f2-dab2-11e7-8ae6-77a200e16f43.png)

**Comment by Winblows2** [comment]
I'm not sure the fix was included in the initial 0.6.0 release, nor has a new minor release come out including the fix.

It's there, you'll just have to wait.
