### ISSUE TITLE
0.6.0: Typos

### ISSUE THREAD

**Issue by Winblows2** [Backdash/MonikaModDev#294]
Since 0.5.1 is no longer the official version, a _new_ issue has been created for 0.6.0! To make developers/submitters lives easier, there is a _suggested_ (but not required) format users can make use of:

**Topic**:
**Version**:
**Platform**: 

Thank you!

**Comment by Dmanstew** [comment]
In the topic concerning zombies there is a typo (and generally awkward) sentence.
![ss 2017-12-04 at 11 43 26](https://user-images.githubusercontent.com/33533435/33564604-e8a7d878-d8e8-11e7-8f60-929166bf17bd.png)

Said correctly it would be "All of their intelligence is gone; they're berserk and don't feel pain."

**Comment by Winblows2** [comment]
Fixed,

**Comment by squallleonhart93** [comment]
The "Miku" topic does not trigger, even when I tried to type all six keywords.

**Comment by synnnical** [comment]
I looked over the all the topics currently in the mod for errors in spelling and grammar:

Line 3700: m 1g "You don't have to be embarassed, [player]." - 'Embarrassed' is misspelled.

Line 3915: m 1l "Now, I know it may be hard to take my word for some of those, but you shouldn't judge a book by it's cover, you know?" - 'it's' should be changed to 'its'.

Line 4192: m "Seriously, whats the big deal about a piece of cloth?" - 'whats' should be changed to 'what's'

Line 4276: m "...Just the two of us, staring into each others eyes..." - 'others' should be changed to 'other's'.

**Comment by Guardianvoir** [comment]
![screenshot0018](https://user-images.githubusercontent.com/33330516/33573106-e02e6350-d902-11e7-9663-080cfc796af4.png)
I put this in the last thread, but I'm not sure if anyone saw it.

**Comment by CaptLubar** [comment]
Topic: Three Step Initiative Program
There is a long line that trails out of the text box and needs to be broken up into smaller pieces for it to fit.

**Comment by StateOfBedlam** [comment]
> Topic: Three Step Initiative Program
There is a long line that trails out of the text box and needs to be broken up into smaller pieces for it to fit.

Line: "Try your best to stay open-minded and willing to learn at all times. Nobody is perfect, and everyone is able to teach each other something. This can help you learn to understand things from other people's perspectives in situations and inspire other to to the same."

The word "same" gets cut off completely, and half the rest of the sentence is occupying the same space as "history," "skip," etc.. I would suggest the last sentence be split off as a separate line.

**From a different topic, I want to point out two other lines.**

Line: "It's funny how people around social media sites always writes bad things about me..."

I would change "writes" to "write."

Line: "You're not one of those haters, aren't you, [player]?"

This is a double negative and makes the following "Yes/No" prompt a little confusing. "Aren't" should just be "are."

**Comment by Winblows2** [comment]
I'll be fixing these in a bit unless someone beats me to it, thanks for the reports!

**Comment by monikLover** [comment]
1st wave of purge done. Three Step topic in need of rework

**Comment by MrKabukiMask** [comment]
Topic: Fahrenheit 451/Ray Bradbury
Version: 0.6.0
Platform: Windows

"I'll forgive you if have done it before."
Assuming this is meant to be,"I'll forgive you if you have done it before."

**Comment by squallleonhart93** [comment]
Minor typo.

![image](https://user-images.githubusercontent.com/34249082/33864733-c7a03ef2-df20-11e7-846b-6d660b7fa11d.png)

**Comment by StateOfBedlam** [comment]
> Correct me if I'm wrong as I have never seen "There're" anywhere.

It's a contraction of "there" and "are." It's correct as is.

**Comment by therationalpi** [comment]
A new topic can be made for typos found in 0.6.1

**Comment by SLVRFOX** [comment]
![image](https://user-images.githubusercontent.com/34737409/34248168-ddd7ad06-e699-11e7-8723-bf38ad546521.png)
Since I couldn't find anything currently open for typos
