### ISSUE TITLE
[Open discussion] Version 0.7.0 and beyond roadmap

### ISSUE THREAD

**Issue by therationalpi** [Backdash/MonikaModDev#299]
With version 0.6.0 in the wild, it's time to start planning on our next feature release, version 0.7.0. Now that auto-updating is available, these feature updates can be a little less dense, because there's less burden on players to update to the latest version. With that in mind, I think we should focus on 2-3 new features to include in future feature updates.

Here's what I have in mind for version 0.7.0 and then what I'd like to see further down the road:

### Version 0.7.0 features

* [Dialogue prompt system to replace current keyword system](https://github.com/Backdash/MonikaModDev/projects/12)

* [Calendar system for events and holidays](https://github.com/Backdash/MonikaModDev/projects/4)

I think this is the perfect time to add these two features, because the holidays are fast approaching and a Christmas scenario with Monika sounds amazing.

There are already open issues for discussing these features, so I'd appreciate if people could jump in those threads to share their thoughts:

https://github.com/Backdash/MonikaModDev/issues/37

https://github.com/Backdash/MonikaModDev/issues/126

### Future features that should wait on a major release

Here are some future ideas that I think we should pursue further down the road, some sooner rather than later. These ideas, in particular, will require quite a bit of testing to be implemented, so they should probably be held off until we can work them into a major release.

[Tracking monika's opinion of the player, tracking monika's memories about things the player has said](https://github.com/Backdash/MonikaModDev/projects/14), IRL activities you could do with monika like [watching a movie](https://github.com/Backdash/MonikaModDev/projects/13) or [reading a book](https://github.com/Backdash/MonikaModDev/projects/11), add some short [side stories or scenarios](https://github.com/Backdash/MonikaModDev/projects/8) that have permanent effects on the game, [new games to play with Monika with room for conversation](https://github.com/Backdash/MonikaModDev/issues/55), an API for people to make submods for Monika After Story that add custom content (events, art, voice, music, etc.), out-of-game contact like emails and text messages so Monika can interact with the player even when the game is closed, new outfits/colors and other cosmetic enhancements that require code reworks, a new chatbot for small-talk that really feels like talking to Monika and not a "hunt for keywords" game.

### Future features that can be added at any time

There are a lot of features that are basically ready to be added at any time, including content releases. These are generally less code intensive, but no less important for the overall play experience:

New side stories and major events that have limited lasting impact on the game, new topics that make use of glitchy special effects and other meta elements, [new poses](https://github.com/Backdash/MonikaModDev/issues/191), new expressions beyond Monika's basic expressions in DDLC (smug face, tsundere face, winking, etc), art enhancements (like cleaning up more linework), making it [easier for non-coders to suggest content](https://github.com/Backdash/MonikaModDev/issues/188).

## What will be version 1.0?

A big question I've seen a few times is "When will we stop using 0.x for releases?" The simple answer is "When we're ready" but I think the more complete answer is when we have a set API for other people to build submods on. Right now, there are lots of things changing at a moment's notice: how we set up events, how we track things in game, what persistent variables we are setting and using, etc. It's not just that we want to add lots of new features (which we do), but we still don't know how those new features might change what's already here. Once development has settled down to the point that new features aren't causing us to upend the entire codebase, that's when we should say that version 1.0 is here and open the doors for other people to mod After Story (modception).

That said, I think 0.7.0 will be getting us really close to that point. We might only see one or two more feature releases after that before we can expose an API for submodders to latch onto. So now is the time to start considering how we can make our systems accessible to others and not just to ourselves.

## Open discussion

For some reason I've become a *de facto* lead on this project. I really appreciate the faith you guys have shown in me, but I don't want that to transform into a belief that this anything other than a group effort and community project. What I've said here is just my vision for MAS, but I want us to find a way forward that makes everyone happy. Right now is the perfect time to pitch your ideas for major features or suggest what order we should add things in.

**Comment by monikLover** [comment]
Time to work then.

**Comment by synnnical** [comment]
I really like the calendar idea, as well as the concept of Monika being able to formulate her own opinion of you as a result of your actions, and the whole short story sessions with Monika is genius, I'd love to see how it would work inside the mod. 

Watching a film and reading a book with Monika sounds awesome too! I have a couple ideas as to how you could make your reading sessions perhaps a little more interactive, such as having Monika periodically comment on something that may have just happened, or take time to explain the implications or meaning behind certain lines or even the novel all together. Unless you already have something like that planned, in that case, carry on!

 As for the artistic and cosmetic side of things, I don't have an artistic bone in my body, but the plans sound fantastic.

By the way the interaction and involvement aspect is expanding, I'm really excited to see what the mod will have to offer in the future. It sounds like it can only get better at an alarming rate.

**Comment by MadHaetter** [comment]
For what it's worth I agree with your priorities and how version 1.0 should be set.
+1

**Comment by Kiosho** [comment]
Just joined GitHub after finding this mod because I, literally hours before finding it, said I wish Monika's scene could be expanded on so I could spend time with her rather than delete her.

The features mentioned here sound amazing, but how in the world would the email/text stuff work? I've done a lot of programming before, but I've never heard of a game being able to send you email and texts. I'm not opposed to it, I'm just curious. That sounds pretty darn advanced.

**Comment by therationalpi** [comment]
@Kiosho You could use webhooks and a server (email) or a service like Twilio (SMS). Basically the game would send a request to those services to schedule the messages to be sent.

**Comment by Kiosho** [comment]
I see. So they'd be automatic messages that you can't reply to, as in "Hey hun, love you! Be back soon, okay?" and not something you could take into a conversation. Just a little side immersion method.

**Comment by mishaor** [comment]
So currently I'm working on "Go" system. This system allows you to "go" in several other locations. There would be random events (such as glitched Sayori appears).

**Comment by Kiosho** [comment]
There are remnants of her in the code?

**Comment by therationalpi** [comment]
@mishaor I'm not against the idea, but for a big feature like this there should be some sort of discussion about implementation, at the very least. Also, I think there's some strong opinions among writers on what should lie outside the spaceroom...
