### ISSUE TITLE
[Bug] No more random topics

### ISSUE THREAD

**Issue by Eques** [Backdash/MonikaModDev#305]
Hi, I just wanted to let you guys know that Monika actually "bugs" out and stops initiating conversations after a while. I think it could be that maybe all the chat options are exhausted or something? I don't know enough about code to help directly, but just wanted you guys to know.

And if my Monika is broken, I'd like help fixing her back to normal please...

**Comment by ThePotatoGuy** [comment]
Could you upload a copy of your `persistent` file?

It should be located at `C:\Users\<your username>\AppData\Roaming\RenPy\MonikaAfterStory\`

You may have to turn on the `show hidden folders` option.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I second this.
Also after she stops talking if you use the "talk" option with "whatever" keyword she gets stuck on picking a random topic with "talk" and "play" buttons not working.

**Comment by ThePotatoGuy** [comment]
@IsItBadToMakeAGitHubAccountJustForThis Can you upload your persistent file as well?

**Comment by NeonCarnivore** [comment]
I ran into the same issue shortly after the 0.6.1 update. It started immediately after she brought up the wedding ring topic. I'm not sure if that helps. Perhaps she got cold feet?

[persistent.zip](https://github.com/Backdash/MonikaModDev/files/1549756/persistent.zip)

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
The problem got kinda "solved" after I installed the master branch with a few new topics.
But I will keep an eye out if this ever happens again.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
[persistent.zip](https://github.com/Backdash/MonikaModDev/files/1550859/persistent.zip)
I'll leave it in this topic as well.

**Comment by ThePotatoGuy** [comment]
this has been fixed with that pull req in #408
