### ISSUE TITLE
[suggestion]

### ISSUE THREAD

**Issue by thelittleleaf** [Backdash/MonikaModDev#306]
umm i feel a bjt bad about asking about this, but can you tone down the chess please? i feel like monikas a bit too talented, shes literature club president not chess club.

**Comment by ThePotatoGuy** [comment]
Everytime she wins, her difficulty level drops a bit. However, the minimum difficulty level might be too hard for chess beginners.

Unfortunately, this is a "feature" of the chess engine we are currently using. There are plans to transition away from this engine (to one that could _potentially_ be easier) but as of now, you'll just have to `git gud`.

**Comment by thelittleleaf** [comment]
i'm not a beginer iv won multiple times i just have alot of friends i told about this complaining, may i refer them here?

**Comment by ThePotatoGuy** [comment]
Sure
