### ISSUE TITLE
[Suggestion] - Allow players to add their own music to listen with Monika

### ISSUE THREAD

**Issue by StickReverb** [Backdash/MonikaModDev#309]
Add a feature where players can add their own music, either in-game or directly into the game directory. Monika can respond by saying she's happy you're sharing your own taste in music with her!

**Comment by ThePotatoGuy** [comment]
I'll look into the possibility of implementing such a feature, but for now its low priority.

**Comment by therationalpi** [comment]
I don't think we should implement this. You can always mute the music in game and use your own music player, and Renpy is weird about support for MP3 and other standard music codecs so troubleshooting people adding music would be a headache.
