### ISSUE TITLE
Monika should comment on why the Main menu button doesn't work

### ISSUE THREAD

**Issue by SS5D** [Backdash/MonikaModDev#31]
Self-explanatory really. When you use the History, Save, Load, or Settings button to get into the menu, the Main Menu button doesn't function. This might be intentional, but if it is, it should probably bring up a message of some sort so it's more clearly a feature. If not it just needs fixing.

**Comment by therationalpi** [comment]
Ah, that's intentional from the original game. I agree it could use some dialogue, like trying to use autoskip.

**Comment by therationalpi** [comment]
https://github.com/Backdash/MonikaModDev/commit/d5a2453c791bb34927af93a4564cd30e68dc5b39

Alright, Monika will now say something.
