### ISSUE TITLE
Monika sprite not long enough

### ISSUE THREAD

**Issue by KiraTakemi** [Backdash/MonikaModDev#310]
![mas](https://user-images.githubusercontent.com/33469042/33691175-8b629c32-daac-11e7-80e9-499702c70c7e.png)

As you can see the bottom of the table looks as if it were floating

**Comment by therationalpi** [comment]
Noted. This definitely needs a fix.

For any artist that wants to tackle this: we should extend the art on monika's desk to the bottom of the layer in the photoshop. Animations and sprite placements in DDLC are written assuming the character extends a bit beyond the bottom of the frame, so hopping up doesn't expose the bottom of the sprite. If we extend the desk down, we can do more of this stuff with Monika and also fix this display error.

**Comment by DatSkullKid** [comment]
Hey there. I'm a digital artist / illustrator and it would be really easy for me to do so, I also plan on doing some more poses for Monika if you guys still want them and I'll fit them between the time on my projects and comissions. This is my favorite game to come out this year and I want to help.

Is there any way I can get the base image to extend it, like on a game file or somewhere online? I'm afraid I don't know much about programing so all I can help is in drawing but I guarantee you it'll look as good as the original cgs. I could also do just a bit more of table as clear bg png and the development team adds it to the sprite? I'll wait for a reply and we can get on with it :)

**Comment by DatSkullKid** [comment]
Ok here's a try at it tell me what you think, hope it helps out, I can send just the table extension as a separate file if it's found adequate. 

![tablesprite01](https://user-images.githubusercontent.com/34406908/33801493-ea2f28ac-dd54-11e7-86c0-360f6cc88dcf.png)
![tablesprite02](https://user-images.githubusercontent.com/34406908/33801494-eb33ccb2-dd54-11e7-8020-be7644e95ed5.png)

**Comment by therationalpi** [comment]
Thanks for the help @DatSkullKid that looks really nice! though on the same day you posted that we got another submission of a similar fix along with one of the poses. So I'm not sure if your exact art will be used.

Marking this as closed since we now have at least two pieces of usable art.
