### ISSUE TITLE
[Suggestion] Monika asks whether or not you want her to keep bringing up a specific topic

### ISSUE THREAD

**Issue by Guardianvoir** [Backdash/MonikaModDev#311]
This is the topic I'm talking about.
![screenshot0009](https://user-images.githubusercontent.com/33330516/33694051-ff15c606-dac3-11e7-9200-80364ebb9390.png)
Some people don't like to think about stuff like this, so maybe the topic could be changed to have it end with her asking the player whether the player would be okey with her bringing it up again in the future.

**Comment by TacticalTriangle** [comment]
Yeah and maybe group a bunch of topics that are similar to this one so that you can avoid these types of topics.

**Comment by therationalpi** [comment]
From Dan Salvato's AMA:

>Monika's end dialogue was written to finalize her breaking from the confines of the game, forcing the player to reflect on themselves and real-life issues, often things that make them uncomfortable to think about. I didn't expect people to get so attached to her because of that.

So, dialogue like this is kind of the point of her character.

**Comment by Guardianvoir** [comment]
In one of Monika's other topics (I'm pretty sure it had something to do with Extroverts and Introverts, I don't have a screenshot with me) she tells the player to let her know of any of the player's unique needs. As far as I've seen, there hasn't been any scenario where the player can actually do so. I'm not saying to remove stuff like this entirely, just have her ask the player if they're okey with her bringing up the fact that she's eternal after this topic is said.

**Comment by therationalpi** [comment]
Ya know, this might be good to roll into the planned system for Monika forming opinions about the player. In this case, when she asks the player's opinion on things like this it could tweak her feeling on the player's neuroticism (Big 5 personality trait), and that could subtly impact the sorts of things she says to the player.
