### ISSUE TITLE
Quetzal's name

### ISSUE THREAD

**Issue by Fuflyaaa** [Backdash/MonikaModDev#3140]
Usually toys are given names. So I wonder, how would Monika call her plushie? Maybe she could ask player for some suggestions, or call the bird after them.
Sorry for my English if it's bad.

**Comment by Onion-Bubs** [comment]
[player] Jr.

**Comment by BigPoofyRibbon** [comment]
Polly

**Comment by MrDevilzMan** [comment]
Green Bird

**Comment by Dovahkun** [comment]
I'd name it Dan.

**Comment by Secretmanguy** [comment]
Add a cute little name tag around the bird with the name you and Monika agreed on...How cute.
