### ISSUE TITLE
[Suggestion] Option for respect estimation

### ISSUE THREAD

**Issue by Secretmanguy** [Backdash/MonikaModDev#3145]
Before you say anything. I know this has probably been asked ALOT. But hear me out. Iv'e been chatting with quite a few loyal Monika fans and we've been wondering about an option that gives you a hint at your level of respect. A question option as simple as "How do you feel about our relationship so far?" or maybe a smaller sum up of that. Which she will then reply by giving an answer based directly on your respect. Maybe an explanation on improvements that could be made perhaps? A possible apology even? It to me as well as quite a lot of other fans think that it would be really neat and helpful to get the straining off our backs and be revealed my talking a little deeper with Monika on everything even if it's just a quick explanation on how far you've gone so far. Anyone wanna help add on to this? Don't get me wrong, I really, REALLY enjoy everything that's been put in. Just you taking the time out of life to read and give input on our suggestions and questions is excellent enough. I just thought it would be helpful to most of us...anyway, feel free to add on to this before it's closed.

**Comment by ThePotatoGuy** [comment]
by respect estimation, do you mean affection?

**Comment by Secretmanguy** [comment]
Sorry, people call it all kinds of things. But yes, affection.

**Comment by Foxinsunglasses** [comment]
Reminds me of Fallout 4

**Comment by Secretmanguy** [comment]
How so?

**Comment by AsuraShun** [comment]
this made me think of the gta san andreas respect meme

**Comment by Secretmanguy** [comment]
Hmm...Interesting

**Comment by Foxinsunglasses** [comment]
Well companions could be asked how they felt about you romantically or otherwise. Sometimes they said negative or positive response based on how the pc has been acting

**Comment by Foxinsunglasses** [comment]
https://www.youtube.com/watch?v=DoAiczZYl2I

0:55
