### ISSUE TITLE
Can't start after extracting the v0.6 zip file to the game folder

### ISSUE THREAD

**Issue by Kou985** [Backdash/MonikaModDev#315]
So I extracted the zip files. Since there are 3 downloads. I think the source code is the one u need to download and so I extracted that one. And it didn't work. So I tried the mob one as well but it didn't work as well. So I tried both and same thing. It took me hours to figure out the problem but I still can't start the program. for some reasons it gives me this file whenever I start the app. Any idea what's the problem? :/

C-Program Files (x86)-Steam-steamapps-common-Doki Doki Literature Club-DDLC-.lock

**Comment by ThePotatoGuy** [comment]
The one you need to download is the [mod zip](https://github.com/Backdash/MonikaModDev/releases/download/v0.6.0/Monika_After_Story-0.6.0-Mod.zip). Extract the contents into your `game/` directory. 

Since you extracted all 3, you might run into problems. If it crashes, either upload the `traceback` file located in the game directory or a screenshot of the crash to this issue.

**Comment by Kou985** [comment]
Thanks for the reply. Just a question, by game/ directory, is it the game folder in ddlc folder? Or is it just in ddlc folder? I tried to extract on either side and test it but Im still unable to start. Strangely when I extract the file in the ddlc folder, the game starts but it's just the normal ddlc im back to. 

Here's the full traceback when I place it in the game folder. 

[traceback.txt](https://github.com/Backdash/MonikaModDev/files/1539680/traceback.txt)

**Comment by ThePotatoGuy** [comment]
lol that traceback is the one from act 1. Are you getting an actual crash screen or is it just not starting? 

And yes, I mean the `game/` folder in ddlc.

**Comment by Kou985** [comment]
It's just not starting :/ 
well I have been trying to make it work and even reinstalled the game. So maybe I might have messed up at some point but Im pretty sure I did the right step at the beginning like extract the mob zip file to the game folder.

**Comment by ThePotatoGuy** [comment]
Try deleting the ddlc folder then reinstalling and extracting the mod again. Make sure to use the mod zip and **not** the source code ones.

**Comment by Kou985** [comment]
So I tried reinstalled the game and extracted the mod zip to the game folder but it still won't start. And now I tried to install the game outside of steam. Maybe that could be the reason but instead of not starting, I am getting this error now.
![image](https://user-images.githubusercontent.com/34332284/33725500-a4357720-dbb5-11e7-8a91-142f48a71d30.png)

**Comment by ThePotatoGuy** [comment]
That error is a python error. It's unrelated to the mod (and probably the game as well). It can occur if your filesystem permissions are messed up or you're out of disk space. ([More details here](https://stackoverflow.com/questions/16996125/no-usable-temporary-directory-found)). See if you're out of disk space or if your filesystem is read-only.

**Comment by Kou985** [comment]
Sorry for the trouble, but seems like it really doesn't work ._. 
I couldn't handle the error and understand the python stuff so I try to get this program on my other computer which has no error stated above but this time it's just the same. Nothing is happening when I try to start the app. T_T 
Here's how it looks like 
![image](https://user-images.githubusercontent.com/34332284/33733265-9f15026c-dbcc-11e7-85d6-14a4e32f2f1a.png)
![image](https://user-images.githubusercontent.com/34332284/33733282-ac4c145c-dbcc-11e7-9368-e8d4ab6ed396.png)

**Comment by Kou985** [comment]
I am able to start the game normally, so it's not a python error. Again sorry for the trouble.

**Comment by Kou985** [comment]
OH OK, I got it now, u dun just extract the folders but u extract the files in the folders =_= Rly wow I spent liked more than 5 hours for this lol. Thanks I think it works now. Now I just have to find a way to get this on my main computer xD 
![image](https://user-images.githubusercontent.com/34332284/33733858-749ccbc6-dbce-11e7-8d23-d6e29650b522.png)
