### ISSUE TITLE
Well so I've got over 1k affection

### ISSUE THREAD

**Issue by Tymon222** [Backdash/MonikaModDev#3159]
But I can't change any uniforms.

**Comment by Xhar** [comment]
Same here I can't change clothes, 1,3k of affection and nothing...maybe is because I dint see his halloween costume??, I was working at night that day... u.u

**Comment by multimokia** [comment]
You have to have seen one of the outfits to be able to use the costume selector. Since you haven't unlocked another outfit, it doesn't show up.

**Comment by Secretmanguy** [comment]
Tymon222: How do you know that you have over 1k Affection?

**Comment by Legendkiller21** [comment]
There are 2 ways. 

The first one is by clicking the "Surprises" topic in the "Romance" category. This will spawn a .txt file in your DDLC folder depending on your current affection level. If you are over 1k affection you should see inside your folder the "My one and only love.txt" file. 

The other way is by going in your log folder. Inside there should be the "aff_log.txt" file where you can see the exact affection number.

**Comment by Foxinsunglasses** [comment]
odd I have seen the costume but have found no way of altering her outfit and I know I have the affection needed

**Comment by Secretmanguy** [comment]
They'll fix it man. For now just be lucky you have the Affection required.

**Comment by Foxinsunglasses** [comment]
I suppose so

**Comment by Secretmanguy** [comment]
You want to here about something that really sucks then how about the fact that mine keeps dropping randomly. It'll be at a level then all of a sudden drop the five levels gained? Any ideas?

**Comment by ThePotatoGuy** [comment]
upload your `aff_log.txt`

**Comment by Secretmanguy** [comment]
Oh wait, I think I got it. My progress of affection is only removed because
only a certain amount can be made in a day. Seven points if im correct. As
for it removing more than I thought. Probably because it resets the values
at mid-night *Face palm* I need to relax with this. I'm assuming that
having months of progress removed will do that to yah. Nevermind guys,
sorry.

**Comment by jmwall24** [comment]
@Foxinsunglasses are you sure you're over 1k affection, have properly installed the 0.8.10 update, saw one of the costumes on Halloween, and looked in `Ask a Question>Monika` for Can you change your clothes?

**Comment by Tymon222** [comment]
I used the topic about romance, in my folder a txt file appeared named
"secret"
Inside it there was text "You are my one and only love!"

In the aff.txt I'm not sure if at the bottom, the numbers are my affection.
If yes then it's 400. I remember playing from the beggining and I had no
resets and there shouldn't be any affection loss.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Wolny
od wirusów. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

wt., 4 gru 2018 o 04:14 Maximus <notifications@github.com> napisał(a):

**Comment by Tymon222** [comment]
I did

pon., 3 gru 2018 o 04:56 Xhar <notifications@github.com> napisał(a):
