### ISSUE TITLE
Please cut the nihilism topic

### ISSUE THREAD

**Issue by CGanimated1227** [Backdash/MonikaModDev#317]
While it is an original topic not from the mod, I think it should be cut from the mod. Monika is supposed to be a good girlfiend and give good advice, but it's contridictiory that she implies that you should be a selfish person or kill yourself for the common good. I personally don't think a good girlfriend would say that, and I don't think anyone else would.

**Comment by monikLover** [comment]
That topic is indeed an original topic. It also does not imply that you kill one's self for the greater good. Monika is an optimistic nihilist and this topic gives light to it by having her giving her point of view of what you should doing to benefit your life.
