### ISSUE TITLE
Game won't start.

### ISSUE THREAD

**Issue by MrAltoid** [Backdash/MonikaModDev#323]
I extract the files into the game folder and when I go to start it, the hourglass cursor appears for a second, then nothing happens. I've tried the Steam version, and the official website version.

**Comment by TacticalTriangle** [comment]
Are you sure you extracted the folder not the zip?

**Comment by MrAltoid** [comment]
Yes

**Comment by TacticalTriangle** [comment]
Did you extract both files or just one?
What system do you have?

**Comment by MrAltoid** [comment]
If I extract one, it does both.

**Comment by TacticalTriangle** [comment]
If you have a windows computer take all files in the Monika after story Mod folder and drag it to the game files. In your game folder you should not have a folder called monika after story mod. You should have mod assets and other data.

**Comment by TacticalTriangle** [comment]
please tell me if you still have any issues or if your on a mac.

**Comment by MrAltoid** [comment]
That makes more sense, thank you, it works.

**Comment by TacticalTriangle** [comment]
No Problem. Someone close this please.
