### ISSUE TITLE
[Suggestion] - Changing Dialog for Different Genders

### ISSUE THREAD

**Issue by TacticalTriangle** [Backdash/MonikaModDev#325]
So while looking through the scripts for inspiration i came across line 1483 in which it decides to say one piece of dialog depending what gender the player has decided. Looking through some scripts some of them also use male ways of addressing the player so if anyone would post how exactly to reference gender in the code to just rewrite the dialog for the different genders i can do that gladly as to refer to the player by the proper way.

**Comment by ThePotatoGuy** [comment]
Check at the bottom of `definitions.rpy`. That's where gender-related values are set. To reference gender in dialogue just surround the keyword you want to use with square brackets `[` + `]` like this:

`m "hi there [bf]"` (`bf` is replaced with boyfriend/girlfriend/partner)

**Comment by Winblows2** [comment]
Closed due to given answer.
