### ISSUE TITLE
[SUGGESTION] Readme Edit

### ISSUE THREAD

**Issue by Kiosho** [Backdash/MonikaModDev#326]
Brand new to this mod, but I can't find an answer to when I'm supposed to move the mod's files into the game folder. Is whenever okay, or do you have to play through the entire game (deleting Monika in the process) first?

The Readme may want to have a warning if so, to only add them in after the credits roll.

**Comment by TacticalTriangle** [comment]
you can do it when ever but then your game will be unplayable after words so its recommended to finish the game since the mod will reference your choices in the game.

**Comment by Winblows2** [comment]
You can add it whenever, as Monika After Story _only focuses on Act 3. The other acts don't exist and will be overwritten by the mods files._

My recommendation, personally, is to make a clone of the original game folder to keep the base game in-tact. Then you'll have a folder for DDLC and a folder for Monika After Story. 

I'll personally add on a note to the README about when is the time to add the mod files, thanks. (Closing)
