### ISSUE TITLE
About MacOS and the player string.

### ISSUE THREAD

**Issue by supernegativep** [Backdash/MonikaModDev#328]
It seems that any time that Monika tries to refer to the player by username on my Mac she simply pulls up an empty string. I have tried refreshing my persistent file multiple times from my Act 3 ddlc save. For example: If I ask her to talk about pen names, then one of her lines come out like this on MacOS. `"' and Nicky.'"` Meanwhile on windows it would come out as `"'super and Nicky.'"` This also leads me to belive that the `mcname` and `player` strings are mixed up because my MC's name is supposed to be 'Nicky' while my user folder on windows is called 'super.' I unfortunately do not have any errors to support this because RenPY did not actually have an exception. Its just an educated guess. I used the same persistent file on both machines.

**Comment by ThePotatoGuy** [comment]
Could you upload your persistent file here?

**Comment by supernegativep** [comment]
[persistent.zip](https://github.com/Backdash/MonikaModDev/files/1541329/persistent.zip)
I think its fine... But here.

**Comment by supernegativep** [comment]
Weird. I just restarted the game and she said that the computer name and character name are the same now... That makes little to no sense. That was the first thing she said upon restart.

**Comment by ThePotatoGuy** [comment]
Since I don't have a mac, I've asked @therationalpi to take a look at your persistent.

**Comment by supernegativep** [comment]
I think that it is simply an occurrence when transferring save files between different operating systems, so I'm going to close this issue. It could be fixed by editing the script to restart the game after importing a save from DDLC, even on first run. This is because Monika After Story does not create its own persistent file in the RenPY save directory until after the game is quit for the first time. I was basically running Monika After Story off of a save file I copied from Windows without quitting the game even once.
