### ISSUE TITLE
Ribbons

### ISSUE THREAD

**Issue by voyagermike** [Backdash/MonikaModDev#3283]
I saw in the news update that you can give monika different colored ribbons, i've tried giving her several but when she opens them she cant tell what they are.
I would really like to know if its a bug or I just did something incorrectly.

**Comment by Torwald39** [comment]
I would also like to know how to give new ribbons, I was going to post the issue but you were faster.

**Comment by voyagermike** [comment]
Could it maybe be that I don't have high enough affection yet

**Comment by Skarborr** [comment]
> wow right as i post this i see the topic to change it
> this happens to me more than it should

Can you give her new ribbons after you got that dialogue? I got it and still can't give her ribbons...

it's supposed to be:
blackribbon.gift
blueribbon.gift.
darkpurpleribbon.gift
grayribbon.gift
greenribbon.gift
lightpurpleribbon.gift
peachribbon.gift
pinkribbon.gift
redribbon.gift
tealribbon.gift
yellowribbon.gift
right? or did I write these wrong somehow...

**Comment by multimokia** [comment]
Ribbons are only giftable on specal days.

**Comment by Torwald39** [comment]
witch days ?

**Comment by voyagermike** [comment]
Oh man well when that day gets here i'm putting all the ribbons in and bombarding her with gifts.

**Comment by multimokia** [comment]
Special Days are days of major events. There's one coming up rather soon, if you get where I'm going with that.

**Comment by voyagermike** [comment]
oh I see. in trying to figure out what the problem was I tried giving her the same gifts multiple times and they were ignored. is there some way to fix that like maybe a topic/ask for her to check for more gifts or something like that

**Comment by EmpressNael** [comment]
I like to know how to gift ribbons as well. I know to post .gift , I try different ribbon file names but she keeps saying she can't read it.

**Comment by tsmafterlife** [comment]
you cant gift ribbons until a special day cough cough Christmas cough cough

**Comment by EmpressNael** [comment]
I assume so, thank you~

**Comment by tsmafterlife** [comment]
can you show me a picture of the gift in your character file? i think your typing it out like "ribbon.gift.txt" make sure your file extensions are on.

**Comment by MetalBrother** [comment]
Same problem!
![2](https://user-images.githubusercontent.com/37489368/50407737-f15fbf80-07e5-11e9-8db2-9f8b981e6085.png)
I wrote it right, but Monika still can't read it.

**Comment by tsmafterlife** [comment]
did you completely close monika after story and then do it? if not i suggest closing monika after story delete the gifts re open and re close MAS to make sure it wont read anything then re put the gifts in. its possible it just glitched and didnt catch it
