### ISSUE TITLE
[Suggestion] - List of keywords

### ISSUE THREAD

**Issue by TacticalTriangle** [Backdash/MonikaModDev#333]
While looking through the keyword system i realized that some keywords repeated all have been fixed. Would it be possible to create a list in like a google doc so that new scenarios that don't conflict or we can find others that are currently conflicting. Lewd keyword is conflicting but i dont know with which one.

**Comment by Winblows2** [comment]
I'll look into this and bring it up with contributors, but I'm not entirely sure. Thank you!

**Comment by therationalpi** [comment]
Keywords are allowed to be shared, and it's actually encouraged. Also we're removing the keyword system.

**Comment by Winblows2** [comment]
Oh... So _that's_ what he meant.

Oops, guess I'm so tired I dunno what I'm reading. :P
