### ISSUE TITLE
I can't open the mod on my Mac

### ISSUE THREAD

**Issue by Albertix2300** [Backdash/MonikaModDev#334]
Im downloading the zip, extracting the Monika_After_Story-0.6.0-Mod and putting it into the game folder of the package, but the game doesnt run. How should I do it? (Sorry for my shitty english, Im Spanish)

**Comment by TacticalTriangle** [comment]
if you'd prefer me talk in spanish i would.
Open up the folders and drag the files into the game Folder.

**Comment by TacticalTriangle** [comment]
https://github.com/Backdash/MonikaModDev
On the bottom part of this page there is what the folder should look like

**Comment by Albertix2300** [comment]
Muchas gracias, ya está resuelto
