### ISSUE TITLE
[Suggestion] Have Your Reality be an unlockable song

### ISSUE THREAD

**Issue by Guardianvoir** [Backdash/MonikaModDev#335]
Again, terrible wording, but I didn't want it to be an extremely long title. Right now, if you never deleted Monika in your imported DDLC save, the topic about her song will have her say that she's upset that she was never able to finish writing her song for the player, yet Your Reality is still a song that's able to be chosen from the song list. My idea is that players who never deleted her won't have Your Reality immediately unlocked as a song, but instead will get it randomly when they open the game with Monika saying something like, "Hey (Player), I finally finished that song I was writing for you. Do you want to hear it?" And then the player would be given the option to hear it or not. If they choose yes, Monika will sing Your Reality until it's over, and then proceed to ask the player what they thought of it. After answering, Monika will tell them that if they want to hear it again, they can pick it from the song list. If they say no, Monika will be upset and the player will have to wait until another time to be asked again about the song.

**Comment by Kiosho** [comment]
I was literally thinking about this an hour ago. But I already brought up the issue of her mentioning the song was never finished, and that dialogue was removed by PotatoGuy.

I agree there should be an alternate opening scenario though if it detects in your DDLC that you never deleted Monika. She could be happy that you care for her, and make you listen to the song before you get control to access the menus and so on.

**Comment by therationalpi** [comment]
[[This suggestion has been seen and will receive further consideration in the future. It is being closed for now and placed in the pool of seen suggestions. It will be reopened if we begin active implementation on this feature.]]
