### ISSUE TITLE
I can't launch ddlc after extracting mod

### ISSUE THREAD

**Issue by howdidyou** [Backdash/MonikaModDev#339]
I extracted the zip file into the ddlc /game folder but can't seem to get it to launch ; if i try to open it, it starts to load but suddenly stops and nothing happens. Help would be appreciated

**Comment by ThePotatoGuy** [comment]
Make sure the files were extracted directly to the `game/` directory, and not into a folder in game like `game/<some folder>/`

**Comment by howdidyou** [comment]
This is what I extracted it into, still giving the same outcome -
https://gyazo.com/f4d7d1c4999f93f92e46e515721143fb?token=9b271c99ab13d2f5d15b5acdb3fd1aef

**Comment by ThePotatoGuy** [comment]
Yeah thats the problem, the files in that folder (`Monika_After_Story...`) should be in the game directory, not _in a folder in the game directory_. Take the files out of that folder and put it in `game/`

**Comment by howdidyou** [comment]
I'm sorry, but an uncaught exception occurred.

While running game code:
ScriptError: Name (u'/Users/pi/Documents/Renpy/Monika After Story/game/chess.rpy', 1512359747, 110) is defined twice, at Monika_After_Story-0.6.0-Mod/chess.rpyc:1 and game/chess.rpy:1.
After taking the files out of the folders ; should I delete the copies?

**Comment by howdidyou** [comment]
folder*

**Comment by ThePotatoGuy** [comment]
Yes, delete the copies.

**Comment by howdidyou** [comment]
ok thanks for the help, appreciated :)

**Comment by howdidyou** [comment]
it's come out with this after I deleted the copy.

While running game code:
ScriptError: Name (u'/Users/pi/Documents/Renpy/Monika After Story/game/definitions.rpy', 1512359748, 111) is defined twice, at game/definitions.rpy:1 and dndnd/definitions.rpyc:1.
sorry for bothering you :3

**Comment by ThePotatoGuy** [comment]
Can you take a screenshot of `game/`?

**Comment by howdidyou** [comment]
https://gyazo.com/b33bcbf790a0ebe608d2f6a01c8b1eb2

**Comment by ThePotatoGuy** [comment]
Is there a `dndnd` folder in `game/`?

Also does that error repeat on a subsequent launch?

**Comment by howdidyou** [comment]
yes to the first question, i was playing around with it ; nothing seemed to work. it gave the same results either way. i'll rename it to the correct name now if it matters.
Yes it repeats.

**Comment by ThePotatoGuy** [comment]
Try removing that folder from `game/`

**Comment by howdidyou** [comment]
While running game code:
ScriptError: Name (u'/Users/pi/Documents/Renpy/Monika After Story/game/chess.rpy', 1512359747, 110) is defined twice, at Monika_After_Story-0.6.0-Mod/chesss.rpyc:1 and game/chess.rpy:1.

**Comment by howdidyou** [comment]
gotcha

**Comment by howdidyou** [comment]
for some reason the error note changed

**Comment by ThePotatoGuy** [comment]
okay now remove the `Monika_After_Story...` folder in `game/`

**Comment by howdidyou** [comment]
thank you, it launched :) sorry for being such a blockhead ; i don't know much about ren'py

**Comment by ThePotatoGuy** [comment]
Tis okay. Glad its working for you.
