### ISSUE TITLE
 [Suggestion] changes to chatbot

### ISSUE THREAD

**Issue by howdidyou** [Backdash/MonikaModDev#348]
We can all agree the chatbot isn't working as intended -  the only thing Monika will react to is 'I love you' otherwise just telling you to elaborate or "Why do you think that...".
You could work in a algorithm into the chatbot which would make Monika react to certain words - e.g
'Siblings' then she would talk about her siblings.
It's been mentioned before - but it would be good if you selected certain topics to talk about before you talk to her - you'd press T and a list of topics would come up, you'd select one e.g Sports and if you gave your opinion on football for example she'd give her opinion on it.

**Comment by ThePotatoGuy** [comment]
We have been discussing replacements to the chatbot. That discussion is located at #126
