### ISSUE TITLE
[Bug] Monika repeats topics

### ISSUE THREAD

**Issue by EternaFP** [Backdash/MonikaModDev#349]
For example, she'd talk about the topic referring to how the VN takes place in Japan, then comments it out so she doesn't say it again so she wouldn't repeat this topic. This isn't a really big issue, but ruins the immersion for me a tad.

**Comment by ThePotatoGuy** [comment]
Does this occur when she randomly brings up topics? The keyword system ignores topics you've seen but the random chatter shouldn't start ones that you've seen.

**Comment by EternaFP** [comment]
Yes this happens when she's randomly bringing up topics, i've gotten the previously mentioned "VN takes place in Japan" topic at least 4 or 5 times now

**Comment by ThePotatoGuy** [comment]
Could you upload a copy of your persistent file here?
It should be located in `C:\Users\<your username>\AppData\Roaming\RenPy\Monika After Story\`.
You might have to turn on `show hidden files/folders`

**Comment by therationalpi** [comment]
@EternaFP You may have ran out of unread topics.

**Comment by EternaFP** [comment]
I doubt that, I was looking through some of the topics and i've never read them before.
Here's my persistent file:
https://expirebox.com/download/d47ef5a6f4887e03b7cdc65fe861ed5f.html

**Comment by ThePotatoGuy** [comment]
According to your persistent, there are in fact topics you have not seen.

Seen topics seem to have been added to `monika_random_topics` somehow. I'll look into a fix.

**Comment by EternaFP** [comment]
Thank you greatly!
