### ISSUE TITLE
Game not opening after installing mod

### ISSUE THREAD

**Issue by enderflandre** [Backdash/MonikaModDev#350]
After I extracted the zip file to the game folder, the game would not open when I tried to start it. Is there something that I'm missing? If so, can someone please explain what I'm doing wrong? Thank you and have a nice day.

**Comment by ThePotatoGuy** [comment]
Does your `game/` folder have a folder `Monika_After_Story`? If so, take the files out of `Monika_After_Story` and put them in `game/`. Then delete the `Monika_After_Story` folder.

**Comment by Danymations** [comment]
I had the same issues.
Here's what I did to get it working:

1) Have you completely finished the game? By that, I mean you got to the part where it uninstalls the game. If not, you have to completely finish the game before installing this mod.

2) When you extract the files, don't put it as a folder in the game/ folder in the original DDLC files. It is supposed to look like this:
![image](https://user-images.githubusercontent.com/34387343/33797166-d457266a-dcc8-11e7-978a-b70991f724fa.png)
All the files are supposed to be in the game folder, not in a folder in the game folder. 
Hopefully that makes sense!
Have a good day.

**Comment by enderflandre** [comment]
Thank you both! The mod is working now. I can't believe I didn't try that! Thank you for the help! :) Have a nice day and happy holidays!

**Comment by Danymations** [comment]
You're welcome~ Glad we helped :)
Have a good day/holiday as well!
