### ISSUE TITLE
[Suggestion] - Auto is turned on and you put the game in the background

### ISSUE THREAD

**Issue by Danymations** [Backdash/MonikaModDev#351]
What I mean by that, is when you're chatting with Monika but you put it on auto and minimize the game.
Maybe she could realize that somehow after a while, and comment on that? Like, turn off the auto and ask you a question. If you don't reply within - I don't know maybe a min or two, she closes the game, assuming you're busy. 
When you re-open the game she says something like 'I didn't want the game to slow down your computer if you were busy" (But of course, sounding more like her and more in depth than that haha.)

**Comment by TacticalTriangle** [comment]
This topic was brought up prior on #336 i do believe that they are thinking of doing something of this nature.

**Comment by Danymations** [comment]
Oh, really? Awesome! Glad to know i'm not the only one thinking about this haha.

**Comment by TacticalTriangle** [comment]
oh right close this issue since there is an issue open for this already.

**Comment by Danymations** [comment]
Thanks for reminding me!
