### ISSUE TITLE
[Suggestion] Monika detecting other games

### ISSUE THREAD

**Issue by Kreikon** [Backdash/MonikaModDev#353]
So I had this idea of Monika commenting on the games you play, kind of like Psycho Mantis from Metal Gear Solid 1.

Say for example you open up Counter-Strike: Global Offensive and she comments _"Oh are you playing that one terrorist game?"_. She could also praise or scold you for the type of games you play too.

**Comment by TacticalTriangle** [comment]
I know there is code in there to detect another visual novel like Katawata Shoujo so i think that this would be somewhat possible i'm not sure though. I would be happy to see something like this added since we can get even more immersion from monika.

**Comment by ThePotatoGuy** [comment]
Praising/scolding would definitely **not** be a good idea. Games are too subjective and everyone has different tastes.

**Comment by TacticalTriangle** [comment]
Well thats the thing... Monika is a "person" her having opinions is something we should add in even if it conflicts a bit with the player because that is what a person is or at least thats what i think.

**Comment by ThePotatoGuy** [comment]
She can have an opinion like `I'm not into games of type x`, but praising/scolding like `Good on u for playing x` or `I cant believe youve played this` would be like a personal attack.

**Comment by Kiosho** [comment]
I like this. Monika says she can see everything on your computer after all. Something in depth like the original post though is insane. It'd take infinity to have her comment on every game. She should have more generic but still immersive comments. A selection of comments for when you're gaming, when you're using a web browser, and so on.

If you're playing another dating sim, she should tell you off. xD

**Comment by TacticalTriangle** [comment]
If your watching porn since she already has dialog about you watching porn... Yes this needs to be a thing. We need monika telling us off about watching porn then closing the game cause she is flustered about you maybe jackin it.

**Comment by Kiosho** [comment]
@TacticalTriangle That would be amazing, ha.
Super immersive if anything.

**Comment by Kreikon** [comment]
Yeah should have Monika have opinions on the games you play. She would probably favor casual games than hardcore games like doom and dark souls.

**Comment by AnIdiotsavant** [comment]
She could tell you how mechanically skilled you must be because you play mobas like league or dota. But points out the toxicity of those communities and tells you to be above them.

**Comment by mishaor** [comment]
This was possible in original version of DDLC.
There was an OBS and XSplit detection, if they are open, then [I would spoil the game].
Somewhere in original-scripts/script-ch30.rpy

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
It was implemented by checking the process name tho.
I can imagine guessing a game by its process name not being very reliable.
And then there are games like literally any Source game which are listed as hl2.exe.
And you wouldn't be able to detect much rather than the fact of the game running which would make it kind of hard to make her comments seem plausible.

**Comment by therationalpi** [comment]
Alright, this has been at least somewhat implemented already in the sense that there are hooks in the game for searching a player's steam library by product id. We just need someone to actually write a few topics that take advantage of this feature in the engine.

[[This suggestion has been seen and accepted. It is being closed for now and placed in the pool of accepted suggestions. It will be reopened once we begin active implementation on this feature.]]

**Comment by AnIdiotsavant** [comment]
maybe we should narrow it down to a few for now. Like 5 for now, just for the commonly played games in pc's like, league/ dota. GTA, CSGO, Minecraft and assassins creed. Maybe thief too since I've lovethat game since I first played dark project

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
It really should be narrowed down to what an ordinary schoolgirl not concerned with video games may know about.
She is a literature club president after all, not gaming.

**Comment by AnIdiotsavant** [comment]
Yeah, so that means we should use games known worldwide. Like League, DoTA, CSGO and GTA since they're so well known you'd me more surprised she doesn't know about them. While she _is_ a literature president, she also has a twitter account, hangs out with friends (before deletion) and really extroverted in general. It wouldn't be surprising if she heard of them from facebook, twitter or her friends (before deletion), right? Correct me if I'm wrong though

**Comment by Kiosho** [comment]
She has topics where she mentions she doesn't know a lot about video games, considering she's been trapped in one.
I think she'd only have heard of more casual games. Like... minesweeper.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Maybe this could somewhat work if she said something along the lines of
"Hey. Is it that *Your average Steam top 10 game every edgy schoolboy likes*?"
"I have heard about boys in our class talk about it a few times."
"If they even ever existed."
In short, making it seem like she is bringing up a topic she thinks you'll like just to support a conversation seems like the right way to go.
`"At this point, Yuri might as well have a conversation with a rock".png`
And if this is ever done limiting the number of times she can bring this up so even if she has topics for like steam top 10 games she will only mention one or two at max seems like a good idea.

**Comment by thelittleleaf** [comment]
i honestly feel like they should just say game specific things for a few worldwide known things like league, dota 2, minecraft, games as well known as that. and for others just detecting them running could give a randomn canned response such as "oh are you playing a game?" or "noone will beat you!" or maybe even "i hope you dont spend more times playing those games than mine"
