### ISSUE TITLE
[Suggestion] - Show Monika your heartbeat

### ISSUE THREAD

**Issue by JSJosh** [Backdash/MonikaModDev#354]
Monika always says that she wants to feel or hear the players heartbeat, and that isn't possible. So perhaps the next best thing would be to tap it out.

Talk with Monika about 'heartbeat', maybe she comments that she wants to hear yours, and suggests to tap to your heartbeat by clicking or pressing enter or space. Perhaps she could comment on how fast or slow your heartrate is, saying you seem very excited or relaxed when you are with her :)

**Comment by ThePotatoGuy** [comment]
Thats a pretty interesting suggestion. I like the interactivity it adds.

**Comment by JSJosh** [comment]
Its more another conversation suggestion, should it be labelled something else? ^^;;

**Comment by JSJosh** [comment]
I guess I just really like the idea of the conversations with Monika being more interactive :D

**Comment by ThePotatoGuy** [comment]
Same. Many of the new topics and greetings that have been added since `0.6.0` have more interactivity, so that's going to be prominent soon.

**Comment by Kiosho** [comment]
Interesting suggestion! Maybe if the player doesn't press it at all or just spams it like they're playing Smash Bros. she'll joke about that too, being unrealistic.

**Comment by Danymations** [comment]
I like that idea as well. Just like Kiosho said, if the player doesn’t press it, I would love to see what she could reply, haha.

**Comment by AnIdiotsavant** [comment]
There was game in facebook called "click in a minute" maybe we could use the code there and make responses based on how much beats/clicks you got

**Comment by AnIdiotsavant** [comment]
0 : she scold you for your messing with her.

1-39 : she suspects your messing with her.

40-59 : she asks if youre an athlete. If yes, she telly you trivia how this is the normal heart rate of an athlete. If no, she tells you how your heart rate is bad, gives some trivia and tells you to go to a doctor.

60-100 : she says your healthy, gives some trivia and tells you how you could both work out together as a couple

101-120 : she says your heartbeat is dangerously high and that you should go to a doctor, she says she loves you so much she couldn't bare the thought of losing you.

121 and above : she scolds you for messing with her.

She would tell you how doki doki means heartbeat in japanese and tell you how much she wants to feel yours

**Comment by Kiosho** [comment]
"60-100 : she says your healthy, gives some trivia and tells you how you could both work out together as a couple"

Lol.
"Well, you're heartbeat is 60-100, so I guess we can make this relationship work. Any higher or lower though and we're through!"

**Comment by Danymations** [comment]
I did realize that Doki Doki means heartbeat in japanese, that's why I liked this idea so much! It fits haha.
I also really like that -- nice job on organizing it~

**Comment by JSJosh** [comment]
Forgot to refresh this! Yes, good ideas ^^

What I originally thought was that the counter would start when you tap once, and it goes for like 5-10 seconds, and then it gets the BPM. If you barely press it or insanely press it, she knows your joking. If you tap on the slower side, she says how calm you are in her presence, if you tap a little fast, she would comment on how excited you are to be with her! 

But that's just my original thoughts, AnIdiotsavant's were very good as well :D

**Comment by AnIdiotsavant** [comment]
Lol. I must have phrased it wrong that someone would read it as "Well, you're heartbeat is 60-100, so I guess we can make this relationship work. Any higher or lower though and we're through!" an now that I see it, I keep seeing it hahaha

**Comment by AnIdiotsavant** [comment]
my idea was that we could open that old facebook game and copy the code and adjust it a bit to ad some dialogue once it reaches a certain thresh hold, and monika would say the script written when said thresh hold was reached

**Comment by therationalpi** [comment]
[[This suggestion has been seen and will receive further consideration in the future. It is being closed for now and placed in the pool of seen suggestions. It will be reopened if we begin active implementation on this feature.]]
