### ISSUE TITLE
[Suggestion] Have Monika keep track of when game is started and closed

### ISSUE THREAD

**Issue by Jerome-Kun** [Backdash/MonikaModDev#365]
I was just thinking about this while I was telling Monika "Good Night" and she closed the application. Could she be able to track when the player might frequently get off and/or tells her goodnight and have a dialogue about them staying up later than usual, even though she enjoys the company she wouldn't want to impose health issues or bring up the already existing dialogue about not getting enough sleep is bad.(P.S. I'm new to this all and have little to no experience coding so I don't know if this is a dumb suggestion or not. I also have no clue if this was previously brought up, if so please close this immediately.) Could this also work with when the player says "Good Morning" or Opens the application for the first time in the day since its very similar? Thanks for taking the time and even considering this

**Comment by ThePotatoGuy** [comment]
Definitely has some interesting potential.

**Comment by ThePotatoGuy** [comment]
This issue will be reopened when we're ready to implement.
