### ISSUE TITLE
Accidentally added a pull request

### ISSUE THREAD

**Issue by Danymations** [Backdash/MonikaModDev#367]
I was looking through some issues when I saw the Age [Discussed on Discord] forum. I accidentally pressed a pull request to set it back to normal.
![image](https://user-images.githubusercontent.com/34387343/33801344-7d79ecb4-dd1e-11e7-8258-734bf0c6c6fe.png)
How do I take that back?? Apologies!

![image](https://user-images.githubusercontent.com/34387343/33801337-338d4452-dd1e-11e7-85bf-232880626a39.png)

**Comment by Kiosho** [comment]
Noooo my topic.
Looks the same in the code, but just in case.
@ThePotatoGuy

**Comment by Danymations** [comment]
Ahh yes i'm sorry!
When I clicked it, I pressed the back button right away, but I just want to make sure. I just started out, don't want to break things already, haha.

**Comment by ThePotatoGuy** [comment]
Yeah even if you click it, you shouldn't have the permission to actually do a revert. It looks like what happened was a revert patch branch was added to your repo.

**Comment by Danymations** [comment]
Phew! Takes some weight off my back, haha. Thanks.
