### ISSUE TITLE
[Suggestion] Give Monika an ability to blink.

### ISSUE THREAD

**Issue by IsItBadToMakeAGitHubAccountJustForThis** [Backdash/MonikaModDev#375]
(I am not a native English speaker so please excuse my terrible sentence composition and probably punctuation.)
I have seen such feature a long time ago in some other VN (tho I cannot remember which one) and I do believe that it would add a lot of immersion to MAS since looking Monika in the eyes is the very important part of a whole Monika experience and also because of how blinking (time between blinks, their duration) says a lot about person's state (tiredness, mood) and thus could be used as a tool to convey Monika's feelings.
I am not much of a programmer myself but a quick googling reveals that it is a simple technique [described in a Ren'Py cookbook in like 2013](https://www.renpy.org/wiki/renpy/doc/cookbook/Blink_And_Lip_Flap), so it shouldn't be hard to implement codewise.
The only problem is finding an artist willing to redraw all of Monika's face sprites.

**Comment by Danymations** [comment]
oo nice idea suggestion. I really like this one!

**Comment by TacticalTriangle** [comment]
Oh yeah i think the vn you are talking about is Tokyo School life something like that. I think that would be great but, i think we would also need some setting to turn it off in case it adds any extra lag or if the player doesn't want it.

**Comment by Hooddies** [comment]
something similar to the application " Just Monika " on mobile ?
the blinking of eyelids.

**Comment by Kiosho** [comment]
https://www.renpy.org/wiki/renpy/doc/cookbook/Blink_And_Lip_Flap

I found this. Easy enough from the looks of it, but this article is out of date.

**Comment by Danymations** [comment]
Wow, it does look easy! Too bad it's out of date. We can dig around on their new website, maybe they have an updated version?

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I do believe it would be better for somebody who really has some experience with Ren'py to write something similar but with maybe a feature to set 
> (time between blinks, their duration)

and we also obviously don't need this wonky lip flap.

**Comment by Winblows2** [comment]
An interesting idea, which will probably come with new physical poses we'll be working on. Low priority until new poses are in.

**Comment by therationalpi** [comment]
[[This suggestion has been seen and will receive further consideration in the future. It is being closed for now and placed in the pool of seen suggestions. It will be reopened if we begin active implementation on this feature.]]

**Comment by ZaunAura** [comment]
HOW DOES MONIKA NOT BLINK YET THIS PROJECT HAS BEEN OPEN FOR OVER A YEAR THATS THE FIRST THING I WOULDA ADDED!!?

**Comment by ThePotatoGuy** [comment]
Blinking would mean adding ATL image statements for every open eye expression. That is a large change and definitely not high priority.

**Comment by softombre** [comment]
When I tried to make the dokis blink in my ddlc mod i just made a new character for each doki and i just made some closed eyes sprites w/ an animation that chose between a few different lengths of time to put them above the normal sprites
So i just had 2-3 blinking sprites (1 for each pose)

**Comment by ThePotatoGuy** [comment]
we literally have hundreds of poses. its not a simple change.

**Comment by AsuraShun** [comment]
I doubt python reads gifs

**Comment by softombre** [comment]
Her eyes only have 2 different positions tho, normal and leaning

**Comment by ThePotatoGuy** [comment]
We have 528 expressions that are not closed eyes or winking. Each one would need to be ATL'd with a closed variant (which may need to be added cause we don't have every combination enabled by default).

Not to mention testing each expression if it looks correct when blinking. This is a large change. You're welcome to attempt to make the changes yourself and create a pull request in the meantime. We'll look into blinking after the holiday season and other higher priority planned additions have been implemented.
