### ISSUE TITLE
Monika failing to pick up my Windows username. Displays blank instead.

### ISSUE THREAD

**Issue by NotShige** [Backdash/MonikaModDev#377]
Title self-explanatory, screenshots below.
![ddlc_2017-12-10_19-29-13](https://user-images.githubusercontent.com/20384051/33804508-78ec768a-dde1-11e7-87dc-f57238daf44b.png)
![ddlc_2017-12-10_19-30-25](https://user-images.githubusercontent.com/20384051/33804511-85ab34ce-dde1-11e7-8f02-59a22985cf7c.png)

**Comment by Danymations** [comment]
Hmm weird. @ThePotatoGuy ?

**Comment by Winblows2** [comment]
Closing due to above duplicate. Move there.
