### ISSUE TITLE
Monika can't read my windows PC name??

### ISSUE THREAD

**Issue by JustMonika1** [Backdash/MonikaModDev#381]
So, this happend. How does this happen?
![ja lovley name](https://user-images.githubusercontent.com/34420778/33806787-66d95238-ddcd-11e7-84ae-3f9f28a00975.png)

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Already reported. #377

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Are you playing a release version or the latest master branch commit?

**Comment by JustMonika1** [comment]
@IsItBadToMakeAGitHubAccountJustForThis  I'm playing the release version

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Then I have no idea.
Try backing up your saves and replaying first the original game and replaying first the original game then MAS to see if the problem persists.
That way we will at least be able to determine whether the problem is in MAS or DDLC itself.

**Comment by JustMonika1** [comment]
@IsItBadToMakeAGithubAccountJustForThis Wait so the problem is that i didn’t finish the game? Bcs i didn’t, i finished it on another PC.

**Comment by ThePotatoGuy** [comment]
Can you upload your `persistent` file here?
It should be located at `C:\Users\<username>\AppData\Roaming\RenPy\Monika After Story\`
You may have to turn on the folder option for showing hidden files/folders.

**Comment by ThePotatoGuy** [comment]
actually nvm, just added a fix
