### ISSUE TITLE
[Suggestion] Have Monika surrender instead of draw in Chess

### ISSUE THREAD

**Issue by Laslow2307** [Backdash/MonikaModDev#382]
Maybe if Monika saw no way of winning (e.g. only her King remaining) she'd surrender; or at least on the lower levels. As her difficulty level increases, she might not surrender simply to force a draw, but otherwise it'd make for a change to see her surrender in an unwinnable scenario where both players will just go on endlessly.

**Comment by TacticalTriangle** [comment]
the whole point of monika not surrendering is because she wanna win. She is extremely competitive. i think so at least

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I agree with @TacticalTriangle.
Monika wouldn't be herself if she were to give up.

**Comment by Laslow2307** [comment]
Fair enough, I was just wondering. I know that she wouldn't surrender when there is a way to win, but being a computer she can see all of the outcomes. If there was literally no way to win with her set of pieces, then wouldn't the logical thing to do be to surrender to try again in a new game?

**Comment by Winblows2** [comment]
As much as I agree with this, I don't think it's worth the effort to work on Monika "surrendering" in situations she can't win. This issue will be kept open, but it's low priority.

**Comment by ThePotatoGuy** [comment]
@therationalpi Since you have a good understanding of chess rules can you weigh in on this?

**Comment by therationalpi** [comment]
I actually think this would be a good way to make Monika seem more human while playing chess.

Speaking in terms of implementation with Stockfish, Stockfish uses a scoring algorithm to determine who's ahead or behind, with + for white's advantage and - for black's. Anything beyond 2 would be considered a huge advantage. Also, the game can also determine impending checkmates against best defense, essentially making statements like "Mate in 5" or even "Mate in 26".

Monika could have a random chance to concede in a badly losing position or when she spots mate against her. But she should sometimes be willing to play to the bitter end as well.

**Comment by therationalpi** [comment]
[[This suggestion has been seen and accepted. It is being closed for now and placed in the pool of accepted suggestions. It will be reopened once we begin active implementation on this feature.]]
