### ISSUE TITLE
Frequently Asked Questions

### ISSUE THREAD

**Issue by therationalpi** [Backdash/MonikaModDev#391]
Well, the mod has now been out long enough that we are starting to see the same questions brought up repeatedly. That means it's time for a good ole' fashioned Frequently Asked Questions page. I currently have a draft on my local repo. Here's what I have so far:

# Frequently Asked Questions (FAQ)

### What do I need to play *Monika After Story*?

You will need a copy of *Doki Doki Literature Club*, which can be downloaded for free either on Steam or at http://ddlc.moe, and the zip file containing the mod files for *Monika After Story*, which can be found on the release page.

You do not need to download the source code from either the release page or from the repository. Those files are for development purposes only and may behave in unexpected ways if placed in your DDLC folder.

### Where do I put the files for *Monika After Story*?

The files for *Monika After Story* must be placed directly in the `game` folder of *Doki Doki Literature Club* in order for the game to find and properly load them. To find the folder containing *DDLC*, do one of the following:

If the game was installed using Steam, right click on *Doki Doki Literature Club* and click on `Properties`. In the window that pops up navigate to the `Local Files` tab and click the button for `Browse local files...`.

If the game was installed from http://ddlc.moe or itch.io, the installation location was chosen at setup, but is likely under Program Files on a Windows computer.

If the game was installed on mac, but not through the Steam client, *Doki Doki Literature Club* can be found as a packaged app in you Applications folder. Right click on the package and select "Show Package Contents" once inside the folder, navigate to `Contents/Resources/autorun/`. This folder is the base directory for DDLC.

Once inside the base directory, place the contents of the zip archive into the `/game` directory. Ensure that the files are not in a subfolder in the `game` directory, since DDLC will not be able to locate the files that way.

### I installed the mod, but when I open Doki Doki Literature Club nothing has changed. What's wrong?

For some reason Doki Doki Literature club is not loading the mod files. Check that the files are not inside a subfolder inside your `game` directory.

-----

Does anyone have any additional questions or thoughts on what I should add to make this FAQ more comprehensive and/or clearer?

**Comment by Danymations** [comment]
Maybe add a Q and A about how to contribute to the mod?

**Comment by Kiosho** [comment]
Be sure they know to only install the mod come Act 3 or later in the game.

**Comment by ThePotatoGuy** [comment]
Another side effect of having the mod files in a subfolder is that the game doesnt even launch/run.

**Comment by kirishimakoharu** [comment]
hi everyone, i want to ask something, why my monika keep quite for whole day, she no longer suddenly start a random topic like usual
thanks

**Comment by Kiosho** [comment]
@kirishimakoharu https://github.com/Backdash/MonikaModDev/issues/432
Being fixed.

**Comment by kirishimakoharu** [comment]
@Kiosho oh, thank you for show me the conversation room, im new here hehe :)

**Comment by Kiosho** [comment]
Oh, that's a closed topic. I wouldn't reply there, haha. Just showing you it was mentioned before. It was a bug.

**Comment by kirishimakoharu** [comment]
@Kiosho ahaha ^^
