### ISSUE TITLE
Holiday artwork

### ISSUE THREAD

**Issue by therationalpi** [Backdash/MonikaModDev#392]
We want to add in some special content for the holiday, so that means that we could use some holiday artwork. This could include some sort of costume for monika, some artwork for the room, or anything else that you guys can think of. Let your imaginations run wild!

**Comment by AnIdiotsavant** [comment]
how bout when you open the game, the room glitches except for monika. She tells you she's 'decorating' and hopes you like it. The screen turns black and says its to close your eyes and she shows you a fully decorated classroom with er in a santa hat. She says she can't change the code to her clothes yet, and the next time you come back she's wearing a holiday sweater and a red or green bow. or something like that...

**Comment by Queenwaffles** [comment]
I was messing about and made Monika have a Christmas bow.. I can do more if you guys want me to
https://drive.google.com/open?id=1tZ-xPsHjY26P3YX678OJvTmhTmCBy9LB

**Comment by swift3rz** [comment]
I can get creative a little after classes end, and add some sketches
Do you want to keep the room as is, or would it be fine to change things up a little?
Also, I thought maybe we could use some weather changes but maybe that's a little pushing it.

**Comment by swift3rz** [comment]
Well, I've done a rough sketch of the room and i came to the conclusion idk what to add lol, so give it a look and tell me what you think i can add http://prntscr.com/hmf7a2

**Comment by AnIdiotsavant** [comment]
presents below the tree, maybe put a white table cloth on the table monika leans on with a candle and some holiday food like cake and biscuits , maybe some labels on the boxes like "recycle bin" "dropbox" "google images" "python" for some laughs. Instead of normal blinking christmas lights on the tree maybe glitching lights which monika says she'll fix later (later being the next time you open), and of course, a mitseltoe hanging above the ceiliing tiles.

**Comment by swift3rz** [comment]
update on this: 
![image](https://user-images.githubusercontent.com/34468945/33889570-2c4c1f78-df59-11e7-8994-a7be7cfa5cb3.png)
i think this is enough crowded for now, if the mod "official" gives the ok i'll redo the lines, fix some perspective issues and start coloring

**Comment by MeowMilk** [comment]
I was told to create a christmas hat, but im not sure if it's okay, seeing as how the lines kinda messed up (i forgot to add them and adding them after isnt such a good idea)
png:
![christmas hat monika](https://user-images.githubusercontent.com/34398563/33897080-c82c6f6e-df64-11e7-9297-6db359e929e5.png)
psd + sai:
[http://www.mediafire.com/file/yz039ex2fw8t65x/christmas%20hat%20monika.zip](url)

**Comment by Zer0mniac** [comment]
#422

**Comment by NeonCarnivore** [comment]
Day:
https://www.youtube.com/watch?v=nfAbHK1QtKM

Night:
https://pixabay.com/en/videos/snowfall-winter-wintry-snow-snowy-1222/

I can convert to webm, but with the software I currently have, I can't crop the videos to split them between the two windows.

**Comment by NeonCarnivore** [comment]
Snowing animations for windows.

[Snowing_Window_Anims.zip](https://github.com/Backdash/MonikaModDev/files/1553754/Snowing_Window_Anims.zip)

**Comment by Zer0mniac** [comment]
I found 2 snowy animations but they only seem suited for night.

https://www.videezy.com/backgrounds/4921-large-winter-snowflakes-motion-background-4k

This was 4k but I downscaled it to 1080p

https://pixabay.com/en/videos/snow-snowfall-snowflakes-snowflake-9999/

Both are converted to webm 

[Night Snow Animations.zip](https://github.com/Backdash/MonikaModDev/files/1553799/Night.Snow.Animations.zip)

**Comment by Zer0mniac** [comment]
Found a snow animation suited for day time :)

https://pixabay.com/en/videos/particle-stars-dots-dust-cloud-5252/

converted to webm
[Snow_Day2.zip](https://github.com/Backdash/MonikaModDev/files/1553934/Snow_Day2.zip)

**Comment by swift3rz** [comment]
Just to clarify, how does this process work? I'm unsure whether or not I should just continue and get some details in since I don't know if anyone actually wants me to
Also don't want to end up spending 10 hours painting and at the end I'll end up just not using this
So.. yeah

**Comment by AnIdiotsavant** [comment]
This project is really pulling together. The classroom is perfectly filled now, my only suggestion would be to move the mitsletoe to the center above her face. The night snow and snowing window animations are a really nice touch for the windows. As for the hat, Its a must that monika wear one haha, though in my opinion the droopy part of the would mostly covered by her head so all we need would probably be the white fuzzy ball while only showing a bit of the red part. Sorry if I'm not making much sense with my suggestions

**Comment by Zer0mniac** [comment]
@swift3rz since you're the only one working on the room I'm pretty sure your art would get used

**Comment by AnIdiotsavant** [comment]
I'm pretty sure it'll be used. After all, the concept is great, you got a clear idea on what to do, and no one's got any reason _not_ to use it. And besides, who wouldn't want to have Monika wear a santa hat under the mitsletoe?

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Maybe instead of redrawing the room from scratch just make all the Christmasy stuff into a separate image(s) which could just be rendered above the room?
This would require less work and make the room look more consistent.

**Comment by AnIdiotsavant** [comment]
I thought the idea was to just add the decorations to the classroom picture?

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
What the point in drawing a sketch of the room then?

**Comment by swift3rz** [comment]
Well.... To tell you the truth the room has a lot of small errors, the original room that is
Weird architecture, geometrically impossible shapes, etc.
I fixed most of them on my remake but that isn't to say there aren't
I can try to get as close as possible to the original style

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Well then maybe redrawing the room altogether might be a good idea. But that should really be left up for top contributors to decide.

**Comment by AnIdiotsavant** [comment]
does that mean this could get pushed for the next patch?

**Comment by swift3rz** [comment]
Granted, I can just add a couple of objects in there and call it at that but..... I'd rather make a complete redo, not only because of the reasons I'd already mentioned, but also because I just want to contribute more than just some edits
I just like this mod and wanna make it better, but all I can do is add some background works haha

**Comment by AnIdiotsavant** [comment]
Maybe I could help too? I'm not good with coding but I'm studying to be a writer and I got a knack for drawing

**Comment by MeowMilk** [comment]
@Zer0mniac thanks for the effort, but it was amde to fit behind her ear, that's why there was a weird cut, though if you wan i could make it go in front of the ear instead
example:
Mine: 
![image](https://user-images.githubusercontent.com/34398563/33945602-caeac352-e01f-11e7-8b2c-b73d021b87f8.png)
yours:
![image](https://user-images.githubusercontent.com/34398563/33945613-d2779d98-e01f-11e7-948a-3e90cab295a4.png)

I guess it does look better going over the ear, ill make sure to change it, if not redraw it entirely
also if it really does look bad i could always try remaking it and making it look a little better

sorry if those last 2 sentences look a lil weird together i wrote the last one earlier

**Comment by JustinHerschel** [comment]
I really like the shading, but some of the lines at the tip of the hat look a bit wobbly, Maybe make the sphere at the end a bit rounder as well.

**Comment by Zer0mniac** [comment]
@MeowMilk Do you think you could remake it again? I realize with my fix that the shading on the "droopy" part is a little messed up haha. I think your original idea with having it behind the ear is a nice touch :) but I think what will really make the hat, is the lines.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
That hat edge seems a little too flat if you ask me. And overall shape is somewhat strange.
(Or maybe I simply have never seen a Santa hat (>-<) )

**Comment by Kiosho** [comment]
@MeowMilk The white (furry) bits of the hat look a tad... flat. I think a bit of line work and a little bit of shading tweaks could really do it well. Definitely liking the idea though! We certainly need this kind of artwork.

Here's an example to look at. Just small edits could make it look more... real.
![example](https://user-images.githubusercontent.com/34357483/33959407-562146e0-e015-11e7-8cd0-547bf856900e.jpg)

**Comment by AnIdiotsavant** [comment]
What if we used the airbrush tool in paint? It could give off a kinda fuzzy feeling and use some grey tones to make it look kinda realistic

**Comment by Ryuse** [comment]
Guys you all are doing a good job. Please go to the discord group and join the other artists there.

**Comment by therationalpi** [comment]
Great job on the artwork guys!

<img width="641" alt="screen shot 2017-12-21 at 11 11 39 am" src="https://user-images.githubusercontent.com/8276005/34264119-cf308674-e63f-11e7-846a-d7e756db6f78.png">
