### ISSUE TITLE
Holiday-Themed Dialogue

### ISSUE THREAD

**Issue by Rune0n** [Backdash/MonikaModDev#393]
Jingle bells, jingle bells...
As part of the upcoming calendar system, depending on the date, Monika will have special dialogue that would be seasonally appropriate. For the upcoming few months, topics centered around _winter_ and the holiday season shall be added to the rotation.

**Topic Areas**
-Snow
-Winter
-Winter Activities/Sports
-Comments on festivity
-References to long-standing traditions
-References to common holiday songs
-Comments on warmth/coziness
-Influence of colder weather on health

**Critical Topics**
-Christmas Eve
-Christmas
-Hanukkah
-New Years 

The critical topics will be covered by myself. For all other topic areas, feel free to make contributions.

**Comment by Kiosho** [comment]
You got it!

**Comment by AnIdiotsavant** [comment]
How bout a jumpscare topic for halloween? It'd be funny-ish.

**Comment by Winblows2** [comment]
Halloween:
- Jumpscares
- Costumes
- Trick or Treating
- Candy
- Origins of Halloween

Thanksgiving:
- Origins (This'll be a recurring holiday theme I assume)
- Topic about the feast, including her favorite Thanksgiving food? Dunno.

Feel free to throw more onto what I added!

**Comment by Guardianvoir** [comment]
What if Monika's appearance changed a little depending on what holiday is approaching? Examples being Monika wears a Christmas hat in December and bunny ears in April, little things like that. Monika never had a chance to wear anything other than her school clothes, so this would be a good way change that.

**Comment by TacticalTriangle** [comment]
If we decide to add the santa hat monika shouldn't we have it as a part of the greeting? like it would open up on normal just monika then she would talk about getting into the festive spirit then she puts on the hat says the Santa monika joke then keeps the hat until the end of the event thing.

**Comment by Danymations** [comment]
I’ll do one !!

**Comment by D0ubleD00m** [comment]
hey, i've been following the mod for a few weeks, and would like to contribute. in regards to dialogue, how should i go about submitting content?

**Comment by Rune0n** [comment]
Focus on Christmas, everyone. That's our most immediate issue.

**Comment by Danymations** [comment]
@D0ubleD00m 
Heres the code page: https://github.com/Backdash/MonikaModDev
Click Monika After Story > game > script-topics.rpy and use this code:
https://github.com/Backdash/MonikaModDev#adding-content

Here's some other things that might help:
https://github.com/Backdash/MonikaModDev/blob/master/CONTRIBUTING.md
https://github.com/Backdash/MonikaModDev/blob/master/docs/MonikaCheatsheet.jpg

**Comment by AnIdiotsavant** [comment]
How about a piano topoc specifically for christmas? We replace the usual piano topic to one where monika says how the the piano suits the christmas vibe or something

**Comment by Kiosho** [comment]
A piano topic could be good. She could talk about traditional songs and the way the piano really brings out the feeling of them.

Be sure to push your PRs to the right place. Use this link. Don't put them in the regular script_topic.rpy. (Unless you want that, @Rune0n )
https://github.com/Rune0n/MonikaModDev/blob/master/christmas.rpy

So far Rune and I are the only ones who've added topics. I'm adding one more for tonight regarding the cold and bundling up for it.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I do believe that costumes like Santa hat and such would break immersion a little tho.
It is probably just the difference between cultures but in my country, there are not many people who start wearing Santa hats just to get in a festive mood. Much fewer bunny ears in April.
I personally think that it would be more realistic if you toned it down to maybe her wearing a holiday colored tie or something of similar caliber.
The same with Halloween. It would indeed be very cute and fun to see her costume but there are no people to trick or treat besides you so, in the end, it would be pointless.

**Comment by Rune0n** [comment]
@IsItBadToMakeAGitHubAccountJustForThis 
Since DDLC is mainly targeting an American audience, I believe that these holiday events warrant inclusion. Bunny ears in April is a new one, but festive decor and a few adornments for Halloween are common enough to be rightfully included.
Christmas is quite nearly a universal holiday, and even if it's not emphasized in certain locations, it's still a worldwide phenomenon. 
As for Halloween...
I suppose that dressing up just for the mood is good enough. Topics on Trick-Or-Treating will have to suffice.
But, please focus discussion on the CURRENT set of approaching holidays.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I have never been in neither America nor UK, but.
Is it really common for random people on streets to start dressing up as Santas just for fun?
But nevertheless. Maybe have someone from #392 draw a mistletoe which would randomly hang between player and Monika upon opening the game and have a greeting in which mentions it but ends with something along the lines of
"Never mind that."
"I want to kiss you not some dummy character meant to represent you."
"But one day I expect you to make up for all the Christmases."
"Okay?"
"Ahahaha"

**Comment by JustinHerschel** [comment]
Here in the Netherlands we do sometimes put on Santa hats for fun around Christmas, but usually not an entire outfit, but stuff like that is pretty common in america I think. A lot of games with Christmas events do have Santa skins like Overwatch and Cave Story.

**Comment by therationalpi** [comment]
People in the US don't dress up in costumes for Christmas either, unless they're like a mall santa or something.

But, like you said, this is pretty common in video games and other media, so I think it's more than appropriate for Monika to dress up to get in the Christmas spirit.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I know it is appropriate but it may kind of subtract from the feeling that Monika is not just some game.
But if everyone is fine with this then I guess it's okay.

**Comment by MeowMilk** [comment]
I personally think a christmas outfit for Monika is just fine

also, @JustinHerschel i'm from the netherlands too :>
also sorry that this isnt related to this discussion

**Comment by Kiosho** [comment]
@IsItBadToMakeAGitHubAccountJustForThis 
"Never mind that."
"I want to kiss you not some dummy character meant to represent you."
"But one day I expect you to make up for all the Christmases."
"Okay?"
"Ahahaha"

Keep in mind she deleted the protagonist. He doesn't exist. She's talking to you. What exactly she's sees is up to interpretation, but I imagine her staring at a floating console that displays your choices and typed text. Just like the console she brings up to run code.

**Comment by Albertix2300** [comment]
Some joke with the mistletoe will be good, though.

**Comment by AnIdiotsavant** [comment]
how bout something about spoiled food?

**Comment by Sky011** [comment]
What do you think about Monika talking about the nativity scene (presepio) or about the christmas tree? Both of these are old traditions. Perhaps even other's religions or countries traditons.

**Comment by therationalpi** [comment]
Great job on the Holiday content guys! This update should be going out today!
