### ISSUE TITLE
Major slowdown while running

### ISSUE THREAD

**Issue by therationalpi** [Backdash/MonikaModDev#4]
The performance on this is atrocious! How can I have my dear Monika running on my second monitor when the room she's in slows my system to a crawl?

From what I can tell, the culprit is the animation in the windows. It's made using a combination of animated masks, and its very inefficient. I would suggest swapping out the "room_mask" and "room_mask_2" with in script-ch30.py movie displayables with dimensions 320x180. No, other changes would have to be made.

Only thing keeping me from doing it is that I don't know how to create the vids to go there. Best I can come up with is to set the room image to null and screencap the outside of the windows then convert that to .ogv (most efficient for Renpy).

**Comment by Backdash** [comment]
Thanks for testing. I'll take a look at it, although I'm swamped with coursework right now.

**Comment by therationalpi** [comment]
I figured out how to make the videos and fixed this in a fork that you can integrate if you want.

**Comment by Backdash** [comment]
Great, send me a pull request whenever.

**Comment by therationalpi** [comment]
Pull request made. Also forwarded this along to Dan for the original release, since it had the same issue.
