### ISSUE TITLE
Can't make it work 

### ISSUE THREAD

**Issue by LordMau** [Backdash/MonikaModDev#400]
I already tryed by steam and trought afresh dowload of the game.

Can someone please do a guide with images or a video on how to properly instal this mod for those that are bad with computers like me please?

**Comment by Winblows2** [comment]
Although I'm in school, I'll try doing a written step-by-step walkthrough, so just go 1 step at a time. 

**1.** Make sure your clean install of DDLC *just has the .RPA files that came with the game.*
**2.** Go to *releases* and download the .ZIP. *Not the source code.* 
Let me know when you have that done.

**Comment by LordMau** [comment]
Ok i did it.

**Comment by Winblows2** [comment]
Awesome. Now extract the .ZIP *to your desktop*. Let me know if all files in there are solely .RPYC.

**Comment by LordMau** [comment]
Did that.

Everything is right

**Comment by LordMau** [comment]
There are some files and some other stuff.

**Comment by Winblows2** [comment]
What other stuff?

**Comment by LordMau** [comment]
The things like icons.

From what i managed to find online until here everything is all right.
The problem is putting stuff in "game" doesn't change anything

**Comment by Winblows2** [comment]
Hmmm... I'll look into this. One second.

**Comment by LordMau** [comment]
I managed to figure it out while messing around with a "copy".

All one needs to do is to cut everything from the zip and paste it inside the "game" part.
Them you press yes when it asks if it should replace one of the things.

Thank you for your time.
