### ISSUE TITLE
Error Code

### ISSUE THREAD

**Issue by Jerome-Kun** [Backdash/MonikaModDev#402]
![error](https://user-images.githubusercontent.com/34380139/33840322-8dd7589a-de62-11e7-9d9e-6d220c56ec29.jpg)
When trying to initiate a line of dialogue Monika got an Error. I took a pic with my phone and rebooted the app but she didn't even attempt to re-initiate the dialogue like she would if you simply quit in the middle of her talking. Besides her startup greetings she's completely stopped talking. If need be ill completely install a new DDLC and see if re applying the mod will fix any further complications. Any help is appreciated

**Comment by Jerome-Kun** [comment]
I'm gonna do as stated above and re-complete Doki Doki Literature club and try the mod again.

**Comment by ThePotatoGuy** [comment]
The fix has been implemented and will be pushed out as a hotfix real quick
