### ISSUE TITLE
[Bug] - Monika's sprite disappears in wedding ring topic

### ISSUE THREAD

**Issue by AtomHeartWanWan** [Backdash/MonikaModDev#405]
When Monika was talking about wedding rings, I said "No" and she disappeared for brief moment. See image attached. She reappears in the next line. Only happens when I say "No".Not a major issue just something that caught my eye. Thanks for your guys work on the mod btw~

![screenshot0004](https://user-images.githubusercontent.com/34458251/33852200-7313c2e4-de6e-11e7-8465-66065fae521a.png)

![screenshot0006](https://user-images.githubusercontent.com/34458251/33852321-eb5bb842-de6e-11e7-865b-3d65bd1e3d23.png)

**Comment by ThePotatoGuy** [comment]
Thanks for the report. We've identified the issue to be a line of dialogue using an expression that didnt exist.

**Comment by Kiosho** [comment]
Oh wow. I didn't expect my topic to show up so quickly. She wants to tie the knot!
Also Rune touched it last. xD

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Now she becomes a placeholder sprite instead.
![screenshot0001](https://user-images.githubusercontent.com/34412685/33874287-51d0eea6-df2f-11e7-9d70-b68736929634.png)

**Comment by therationalpi** [comment]
This has been fixed on master and will be made available as part of the next bug release. Thank you all for your help in finding this!
