### ISSUE TITLE
[Bug] - Monika stops talking after new topics

### ISSUE THREAD

**Issue by Zer0mniac** [Backdash/MonikaModDev#408]
It seems like after Monika is done talking about the new topics, she just stares at you. She only talks when I start the conversation. I don't know if I'm the only one facing this issue but I waited 10mins and still nothing. I closed and re-opened the game and she just stares. not that I mind her staring at me but it would be nice if she conversed again. <3

I appreciate you guys for this mod~

**Comment by NovaCo1** [comment]
i'm having the same problem I've been siting here for a good 15 20 min of dead silence from her

**Comment by Jerome-Kun** [comment]
I had the same problem after I had a script issue from downloading the first version of 0.61 so I downloaded a new DDLC and finished it. I reinstalled the Mod and I haven't seen a problem yet. Its been a mixture of Old and New topics , but lets hope that's not the only solution to her silence  :(

**Comment by Zer0mniac** [comment]
@Jerome-Kun did you uninstall DDLC and delete the game folder then reinstall the game and the mod? I did the same thing and it still didn't work for me D:

**Comment by Jerome-Kun** [comment]
@Zer0mniac  Yea but I imported the new data from the run I did today. She said "You didn't change at all [Player]" when I deleted the Previous Monika After Story data then she rebooted the game and I got to choose my preferred name and gender and stuff. Its been normal so far, but id hate for you to go through the long, perilous, and scary  journey that is DDLC all over again. I'm sure there is a much simpler solution that hasn't been unveiled yet

**Comment by Zer0mniac** [comment]
@Jerome-Kun Guess I'll stick with Monika 0.60 for now :/

**Comment by Jerome-Kun** [comment]
@Zer0mniac I'm sure one of the others will have a solid solution for you, I'm sorry I wasn't actually able to assist you. But don't give up :)

**Comment by Zer0mniac** [comment]
@Jerome-Kun I wont don't worry :) thanks for trying though

**Comment by ThePotatoGuy** [comment]
Can you upload your `persistent` file here?
It should be located in `C:\Users\<username>\AppData\Roaming\RenPy\Monika After Story\`
You may need to turn on `show hidden files and folders`

**Comment by Zer0mniac** [comment]
Whoops O_O

@ThePotatoGuy It's telling me that file type isn't supported :/

**Comment by Zer0mniac** [comment]
JUST KIDDING IM DENSE

here ya go

[persistent.zip](https://github.com/Backdash/MonikaModDev/files/1550421/persistent.zip)

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I'll just mention #305 in here as it seems to be at least relevant if not the same issue.

**Comment by Zer0mniac** [comment]
@IsItBadToMakeAGitHubAccountJustForThis did you have the same issue with .61? and if you did, did you try the same fix?

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Not yet. I had a similar problem in 0.60 where when exhausted all the possible topics but I downloaded a later commit with some new topics and it worked as a temporary solution.

**Comment by Zer0mniac** [comment]
@IsItBadToMakeAGitHubAccountJustForThis Your problem is basically mine and others...

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
[persistent.zip](https://github.com/Backdash/MonikaModDev/files/1550856/persistent.zip)
And here is mine as she seems to be at it again.

**Comment by NeonCarnivore** [comment]
[persistent.zip](https://github.com/Backdash/MonikaModDev/files/1551574/persistent.zip)

**Comment by ThePotatoGuy** [comment]
I've identified the error and a fix will be implemented soon. Just note that since you've seen all the topics, they _will_ repeat (until the next batch of new topics are added).

**Comment by ThePotatoGuy** [comment]
Fix implemented. Await the next minor update for the changes.

**Comment by NONIDOG** [comment]
I have the same bug, i'm on 0.12.2. She just stares at me. I'm on affection 294.5, maybe on this affection level she is run out of topics. She said only 1 new topic that i never seen with "Repeat Topics". When it happened, i tried updating to 0.12.2.1-unstable.
