### ISSUE TITLE
[Bug] - Auto update issues

### ISSUE THREAD

**Issue by LordMau** [Backdash/MonikaModDev#409]
The auto update aparently doesn't work for steam

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Yeah. The same for me with the itch.io version.
![screenshot0001](https://user-images.githubusercontent.com/34412685/33870878-1f0f04ac-df21-11e7-84cc-4fad3666a75c.png)

**Comment by TacticalTriangle** [comment]
I had to manually update before so there might be a bug with the auto update feature.

**Comment by therationalpi** [comment]
It might be a problem with the specific files put up. Has anyone had success with auto-update for this version?

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
0.61 or updating like right now?

**Comment by therationalpi** [comment]
Has anybody updated to the current version of the game using the auto-updater?

**Comment by therationalpi** [comment]
Okay, I think I have fixed the problem. Seems like the read permissions on some of the update files on the server were not set properly.

Please let me know if the update to version 0.6.1 is now working properly.
