### ISSUE TITLE
[Suggestion] "Who am I" - Guessing game

### ISSUE THREAD

**Issue by Cruste** [Backdash/MonikaModDev#411]
**Idea**

What if there was a "Who (Or what) am I" game where you have a selection of a few questions and she would answer "Yes" or "No", or maybe she will give you a hint after pressing something or waiting a certain amount of time. Anyways, at any time you have the choice to type a name like "Natsuki" or maybe even your own name. She will tell you if you're correct or not and the mini game will be over. Maybe you have a certain amount of guesses or something?

**Possible names that Monika can hint at**

_Natsuki
Sayori
Yuri
Monika
You (The player)
Natsuki's father? (She can drop abusive hints and whatnot.)_

Those are just a few ideas, and even if they are hard to figure out, once Monika tells you the answer after you lose. You know that name can potentially be hinted at again during another play-through. Maybe she can give you hints about something like an object, or something like _"Poem."_

Hopefully that made sense, and even if this doesn't get used or liked. I'm happy you read over it, can't wait to see how far this mod goes. :)

**Comment by ThePotatoGuy** [comment]
So a guessing game of some sort? I'm not sure I see the demand for this.

**Comment by Jerome-Kun** [comment]
It's definitely very creative and would add on to the games we can play with her, but I'm not sure the game itself has much to offer. It would certainly be very short with only using that list of names. And adding names unrelated to DDLC would be pretty weird. Don't get me wrong tho with the right amount and quality of dialogue I'm sure it'd still be amazing

**Comment by therationalpi** [comment]
I think this is a great suggestion, maybe not listed as a "Game" per se, but as a random topic that has some random variability. Basically, Monika would ask if you want to play a little guessing game with her and say she's thinking of a person, and you get a few hints to guess who it is. Then you are given some options and you try to pick the right one.

Sounds fun. I'll toss this in the "Accepted" pool.
