### ISSUE TITLE
Game minimisation bug

### ISSUE THREAD

**Issue by IsItBadToMakeAGitHubAccountJustForThis** [Backdash/MonikaModDev#412]
I play the game on windows and sometimes after I leave it minimized for a while I am not able to open it anymore.
Not sure how to describe it, I will add screenshots once I'm able to replicate it.
It may or may not be caused by some third party software like WindowFX but reporting it nevertheless.

**Comment by Winblows2** [comment]
I'll undertake this personally as I've seen minimization problems before in games. For @ThePotatoGuy these can vary, such as minimizing will bring you to a black screen upon opening the game again. 

While I'm not entirely sure what causes this, I know if it can be replicated it will have to be an internal problem. For now, though, try to avoid minimizing it. My suggestion is to just open windows over the game so it's _still there_, just not in the primary view. 

With any luck I can get this replicated and get back to you with more information. Thank you for the report!

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I did exactly that Before but for now, I couldn't replicate the bug which is strange.
Maybe I'll leave her minimized for a day tomorrow and if nothing happens just close the issue.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
So here it is.
After leaving the game minimized for some amount of time it just refuses to be restored.
After clicking it in the tray it gets selected as if it is in focus but no window is rendered.
And the window preview in the tray doesn't work as well as closing the game from right click menu.
![sorry moni ididitforscience](https://user-images.githubusercontent.com/34412685/33958171-c38979a2-e054-11e7-89dd-61fc1088da25.png)

**Comment by ThePotatoGuy** [comment]
I believe we have established this to a be a renpy-related bug. If you leave normal DDLC minimized for a while, the same shit occurs. I'll let @Winblows2 close this when he's ready tho.

**Comment by Winblows2** [comment]
There's nothing we can do currently, but my recommendation is to just pull windows over MAS and *never* minimize it. 

Closing.
