### ISSUE TITLE
Is Monika vegetarian or not?

### ISSUE THREAD

**Issue by MeowMilk** [Backdash/MonikaModDev#417]
I saw Monika talk about chilling on a couch, watching tv and _eating junkfood_, but then later saw her say she's a _vegetarian_. I guess there might be vegetarian junkfood, but im not sure, and i personally think this is a lil weird
Sorry if this doesnt help in any way and she DID mean vegetarian junkfood

**Comment by monikLover** [comment]
Yes, she is a vegan.

**Comment by LordMau** [comment]
I do remember the bot eating meat being something i read in the game before installing the mod.

And I don't know about U.S.A but here in Brazil we use vegetarian to refer to people that doesn't eat meat (fish,chicken,cow,etc...) but eat things that come from it (Milk, Cheese).

So she could be eating things without meat.

**Comment by MeowMilk** [comment]
thanks, i was just a little confused about this

**Comment by SLVRFOX** [comment]
Considering that her reasoning for being vegetarian has to do with the environmental harm of animal farming, I don't see her being willing to consume milk and cheese if she really is vegetarian. Sorry for commenting on a closed issue, I thought that was worth mentioning.
