### ISSUE TITLE
[Suggestion] Console easter egg

### ISSUE THREAD

**Issue by IsItBadToMakeAGitHubAccountJustForThis** [Backdash/MonikaModDev#420]
I got this idea while reading the #214.
Maybe pressing ~ could open a console Monika uses.
This could cause Monika to say she envies the way she needs a lot of work and concentration for operating console and you can do the same thing with a few keystrokes.
The console could accept keywords the same way talking does.
Two most obvious easter eggs would be:
renpy.music.play("") - Changes music. Monika mentions how she can do it for you. Maybe if the game is finished ddlc.ogg could make her mention how it reminds her of her farewell to you.
os.remove("") - Causes a response from Monika.
Those two are just an examples I do believe there are a lot more to come up with.

**Comment by Kiosho** [comment]
Could prove some neat, little eggs definitely.
But, opening the console lets you mess with a game (typically).
You think Monika would allow that? Even if she trusts you, you saw how dangerous it was when she used the console.

**Comment by therationalpi** [comment]
I think this has some potential. We'd need to make this different from the actual dev console, but this could be a cool way for us to add some easter eggs, "cheat codes," and other fun things to the game. Especially if we somehow dropped some clues on how to open it.

Marking this as unsure in the suggestion pool.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I do believe opening the console is a result of messing with the game rather than a cause since Ren'py games (surprise, surprise) don't even have one.
Most of the commands would be harmless like m " " making Monika say entered line and then scold you for messing with her. And harmful ones like os.remove("/game/script.rpy") would be instantly overruled with her getting mad at you and maybe disabling console for you altogether.

**Comment by INXSOriginalSin** [comment]
sorry for reviving an old thread, but this sounds **insanely rad**. 

I thought of some more commands that could (hopefully) come to fruition in the future!

1. "os.add_admin_monika.chr" (This would trigger a dialogue where Monika thanks you for trusting her with admin powers over your PC. obviously this wouldn't do anything in the long run, but hey, sounds neat)

2. "os.webcam_true" (this would simulate your webcam turning on and Monika would comment on your appearance. maybe something like "You're cuter than I thought!. hehehe~". Something along those lines)

3. "give.coffee_Monika.chr" (This would be in reference to the dialogue where she talks about changing Yuris tea set from tea to coffee. Monika would express her appreciation for the effort)

I dunno, these are just some random commands that came to mind. I thought they were kinda clever.

Lovin what you devs are doin with the mod so far!, Also, this is a freakin gnarly suggestion OP

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I personally think they should be actual Ren'py functions and their variations to keep things more or less realistic.

**Comment by mishaor** [comment]
Sandboxed enviroment, i guess?


2017-12-23 15:42 GMT+02:00 IsItBadToMakeAGitHubAccountJustForThis <
notifications@github.com>:

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Nah, the same keywords current talk feature uses but more specific.
