### ISSUE TITLE
[Suggestion] - Snowy weather for animated background?

### ISSUE THREAD

**Issue by Zer0mniac** [Backdash/MonikaModDev#422]
For this time of year it seems pleasant that during the day time (or anytime) it should be snowing in the background and that some of the snow would be caught on the window sill. I don't really know if thats possible but its a neat idea :)

I would attempt to do this myself but I wouldn't even know where to start

**Comment by ThePotatoGuy** [comment]
Seasonal stuff would be nice. If you want to help, see if you can find snowy `webm` files that are public domain that we can use.

**Comment by Zer0mniac** [comment]
I'll get to searching Right away
#392

**Comment by NeonCarnivore** [comment]
I can convert this to the desired resolution/format: 

https://www.youtube.com/watch?v=nfAbHK1QtKM

**Comment by ThePotatoGuy** [comment]
Can you move your comments to #392  since its the general for all holiday art. thanks.
