### ISSUE TITLE
[Suggestion] - Dialogue 

### ISSUE THREAD

**Issue by LordMau** [Backdash/MonikaModDev#423]
I Would like to suggest in the next update a "thank you" option. 

Much of Monika dialogue does deserves that as she gives greats suggestions and also cheer us up.

**Comment by ThePotatoGuy** [comment]
If you have an idea for what this dialogue should be, I suggest you attempt writing one and submitting a pull req. Follow the guide [here](https://github.com/Backdash/MonikaModDev/blob/master/CONTRIBUTING.md) to contribute.
