### ISSUE TITLE
[Fix] Hide Mouse Cursor in Pong

### ISSUE THREAD

**Issue by Kiosho** [Backdash/MonikaModDev#426]
A minor fix, but personally I'd prefer the mouse cursor be hidden during a round of Pong. Since it isn't being used, it makes no sense to have it there. It's distracting.

I'd rather not delve into the Pong script unless I know for sure what I'm doing, but I found this: https://github.com/renpy/renpy/issues/1003

From what I gather, on the game starting we could use this to hide the cursor, and then show the cursor again on game completion.

**Comment by therationalpi** [comment]
[[This suggestion has been seen and accepted. It is being closed for now and placed in the pool of accepted suggestions. It will be reopened once we begin active implementation on this feature.]]
