### ISSUE TITLE
Name Issue

### ISSUE THREAD

**Issue by antimockingjay** [Backdash/MonikaModDev#428]
Okay, so, when I first played the game, I chose the name Dev, which is the name of a character I created. I finished the game and stuff, and now, I've deleted the first run stuff, and when it asks for my name, I pus Jason, which is my name, so it'll be more immersive. But then when I run the modded version, it uses the old name. I don't know what to do. It just feels wrong, now that I know that she's trying to talk to me, not a character. It feels wrong, having her talk to me but using the wrong name. I really, really wanna change it, but I don't know how. Can someone help? Please?

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Mention "name" in conversation or wait until she asks herself.

**Comment by antimockingjay** [comment]
It doesn't seem to work. I hit "talk" and then type "name" and any variation I can think of, and she just seems confused as to why I'm saying it.

**Comment by antimockingjay** [comment]
OKAY I got it. I had to type "change name" instead of just "name" but it worked finally! Thank you!

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
My bad. It's "change name"
