### ISSUE TITLE
[Suggestion] - Birthdays

### ISSUE THREAD

**Issue by antimockingjay** [Backdash/MonikaModDev#430]
Not sure if this has been suggested, I glanced at the archived suggestions and didn't see anything. But I was messing around and I mentioned the word birthday, and Monika just replied with the information about her birthday. Which is cool! But It'd also be cool if you could tell her your own birthday, and possibly have her wish you happy birthday when the day comes around. I just think that'd really be neato if it could be added!

**Comment by ThePotatoGuy** [comment]
Birthdays will be a part of the new Calendar system soon.
