### ISSUE TITLE
Monika stopped talking

### ISSUE THREAD

**Issue by AnIdiotsavant** [Backdash/MonikaModDev#432]
She doesn't talk on her own anymore, I don't know why. How do I fix it?

**Comment by Winblows2** [comment]
What exactly were you doing prior to this happening?

**Comment by therationalpi** [comment]
A fix for this has been implemented for the next bug release. https://github.com/Backdash/MonikaModDev/issues/408

**Comment by Winblows2** [comment]
Ah... So that's what it was.
