### ISSUE TITLE
[Suggestion] Adding custom topics

### ISSUE THREAD

**Issue by antimockingjay** [Backdash/MonikaModDev#435]
Okay I'm not sure if this is a suggestion or a question. If it's already something that can be done, I suppose it's a question of how I can do it. And if it's not, it's a suggestion for it to be added!
I think it'd be super cool if we could like, add little custom dialogue options. For example, I currently have my own YouTube channel, and I'd love if I could get Monika to say something about it! Just a simple "So how is your channel going? Getting lots of viewers? I hope to!" or such like that would be enough to make me happy. But I KNOW that's a super specific thing, and it's not really something that like, needs to be included in the mod overall, because I know there's only a handful of people who that would apply to.
But it'd be super cool if we could easily write in our own dialogue! Better yet, it'd be even cooler if we could also share the dialogue files somehow, so that after we write it, someone else can see that it's been done, and add it to their game, as well. So if I make a sorta specific dialogue script about being a YouTuber, I could upload it somewhere, and anyone who feels it applies to them could download it, but no one who doesn't fit into that has to have it in their game and such.
I'm not sure how doable it'd be, as I just got into all of this really recently, so I could just be spouting ideas that could never work. But I just figured it'd be something neat, if we could have it be configurable like that, plus it would make her feel much more real if she mentioned things that really apply to the person. I mean, she's supposed to be the player's girlfriend, and you'd think your own girlfriend would know about some of your interests and such.

**Comment by therationalpi** [comment]
Ya know, we never coded with this in mind, but you can actually add custom topics really really easily. The game will load any dialogue and add it to monika's rotation as long as it's in a `.rpy` text file in the correct format in the `game` folder with the rest of the mod files. So if you wanted to add a custom topic for when you say antimockingjay you could make a file called `custom-topics.rpy` with the following text:

```renpy
init 5 python:
    #This is a list of keywords for this topic
    for key in ['antimockingjay']:
        monika_topics.setdefault(key,[])
        monika_topics[key].append('monika_antimockingjay') #id
    monika_random_topics.append('monika_antimockingjay')

label monika_antimockingjay:
    m 1h "Hey, [player], isn't it a bit weird to be asking me about yourself?"
    m 1i "And while on your YouTube channel, no less."
    m 1o "I know you are trying to impress your viewers..."
    m 3h "But adding a custom script to the game just to get a reaction?"
    m 2q "I feel like some sort of trained parrot, being forced to perform."
    m 2b "'Hello everyone! You're the best audience ever!'"
    m 4k "'Be sure to like, comment, and subscribe!'"
    m 2p "Is that what you were looking for?"
    m 1e "Really, though, I do hope your channel is successful."
    m "And if reading off a few lines will help make that happen, I guess I can live with that."
    m 2l "Just don't make me say anything too rude or embarrassing, okay?"
    m 2a "I don't want anyone to get the wrong impression of me."
```

**Comment by LordMau** [comment]
That's a great idea.
An area here for people to put more specific stuff so other could add it in they game if it's fit with themselves (youtuber, Teacher, student, writter,etc...) would be nice.

**Comment by antimockingjay** [comment]
Okay, I maaaay need a bit of help. I followed the instructions, but then when I went to add a second one in, they both had my username as their code whatever things, so only one would play. But when I replace my username with something else, it doesn't work at all. Is there a certain trick to this? I set the keyword of one to be "youtube channel" and the other to be "recording." The youtube channel one has the monika_antimockingjay replaced with monika_youtubechannel while the recording one has monika_recording instead, and now neither of them will play. Is it just not possible to have two custom scripts at once or something?

**Comment by antimockingjay** [comment]
Oh my god, I'm gonna kick my own ass, I'm so dumb. I didn't change the one right above the dialogue to the same as what i changed the first two labels to. Okay, this one was on me, my bad. Got it to work! So you totally can have multiple custom scripts at once!

**Comment by Winblows2** [comment]
Closing because... Well, I think it's been answered.
