### ISSUE TITLE
[Bug] - Prompting "Anything" in the talk box causes Monika to freeze.

### ISSUE THREAD

**Issue by chillandgrill** [Backdash/MonikaModDev#436]
Quite sure that this is linked to bug #408 . After she stopped talking, typing in anything resulted in Monika stuck in the "Let me think" state with no way of getting out of it to play games or anything. There's a chance this would've been fixed along with Monika not talking anymore bug, but I just wanted to let y'all know.

**Comment by therationalpi** [comment]
Yeah, this should be fixed with that bug. Thanks for letting us know, though. We'll be sure to check this behavior when we are testing our fix for live.
