### ISSUE TITLE
[Suggestion] - Write With Monika?

### ISSUE THREAD

**Issue by juliathegolden** [Backdash/MonikaModDev#437]
Howdy! I really enjoy the Monika After Story Mod thus far. I'm trying to get the courage to add in some of my own conversation topics, mostly just about things that I want Monika to encourage me some more about, like cleaning and stuff.

But what I would like to suggest is, would it be possible to integrate a basic text editor? I'm not expecting Monika to be able to react to what one writes, but something about her presence reminds me of those distraction free writing programs, and I feel she would love to cheer you on at word count goals and things like that. I remember reading someone suggest an unlockable rain background noise too; that would go well with this.

**Comment by Kiosho** [comment]
@badooga is working on rain, which would appear in the music menu and cause it to rain outside the windows.

**Comment by ThePotatoGuy** [comment]
I believe having a text-editor in game might be out of scope for renpy itself. I'm working on migrating the poem minigame over, so maybe writing poems via madlib style could be a better addition than a basic freetext field.

**Comment by Winblows2** [comment]
Going off what @ThePotatoGuy, I think this is just outside the scope of MAS as well. 

My perspective is that this would be great if it were simple & easy to do, but this is going *way* off the mark. As amazing as it'd be to see Monika cheer you on as you write in a text editor *included with the game*, it just doesn't seem realistically possible.
