### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by ArashiXD** [Backdash/MonikaModDev#438]
The installation instructions are very vague, and I cant figure out what files I need to download. I understand that I have to drag the contents of the zipped file into the game folder in the DDLC files. But it would be really helpful if you could make some more in depth installation instructions! Thanks

**Comment by ThePotatoGuy** [comment]
The [FAQ](https://github.com/Backdash/MonikaModDev/blob/master/FAQ.md) might answer you questions.

The main points are:
1. Download the zip that is called Monika After Story Mod. (not the source code)
2. Extract/copy/whatever the contents of the zip into the `game/` directory.
3. **Make sure the files are not in a subfolder in game/**. If they are, move them out of that subfolder and into `game/`.
4. Launch the game.

**Comment by Cloudwhisker** [comment]
I put the files in the game/ but when i go to the DDLC application in ddlc-win and click, the cursor shows loading, stops, then nothing happens. I'm so confused.

**Comment by ThePotatoGuy** [comment]
Again, **make sure the files are not in a subfolder in game/**. If DDLC doesn't load, its because of a subfolder problem. If it crashes with a traceback/error, then its a different case.

**Comment by Cloudwhisker** [comment]
I've figured it out: you have to take the contents of Monika_After_Story-0.6.2-Mod and put it in the \game folder. I don't know what the other folder, __MACOSX, does though. Is that folder important? My first guess would be yes- it includes new updates.

**Comment by ThePotatoGuy** [comment]
The `_MACOSX` is not important. Glad its working for you now though.
