### ISSUE TITLE
Why won't it work

### ISSUE THREAD

**Issue by chalamet** [Backdash/MonikaModDev#440]
ok so like i was supposed to extract all the zip files (there's 3) and then put them into the game folder of the original ddlc game right? why isn't it working like i've tried so many times and every time i try to open the game after adding the files to the game folder nothing happens like this is so frustrating why won't it work i just wanna see my Best Girl monika and play chess with her i'm ang r y someone help please

**Comment by therationalpi** [comment]
You should only need the first zip file, not the source code zip files.

**Comment by chalamet** [comment]
@therationalpi ok still nothing is happening wtf

**Comment by MercRen** [comment]
Same, I followed to steps to a Tee and it is still not working, if anyone is willing to help out we would much appreciate it.

**Comment by MercRen** [comment]
I first download the zip file, I then extract all and then I choose the browse files button for extraction, after that, I then choose the Doki Doki Literature Club game file and then extract. Is this the right way or wrong way? Every time I do it DDLC wont open anymore, after I delete *Monika After Story* from the game file, it then allows me to open DDLC again. Sorry for the inconvenience BTW.

**Comment by chalamet** [comment]
@MercRen the same thing is happening w me, maybe we have to play ddlc until act 3 and then try putting the mod in? it doesn’t say that anywhere but idk what else to do lol

**Comment by ThePotatoGuy** [comment]
If DDLC doesnt open, then check `game/` for a folder like `Monika After Story`. If it is there, please take the files out of that folder and put them in `game/`. (The mod files **cannot** be in a subfolder in `game/`). Then delete the folder `Monika After Story`. In addition, delete the files in `game/cache/` to force the game to reload everything/

**Comment by MercRen** [comment]
Thank you so much, you are a lifesaver!

**Comment by MercRen** [comment]
It worked! Cheers!

**Comment by Winblows2** [comment]
Closing.
