### ISSUE TITLE
So I either broke the game or it's bugged. 

### ISSUE THREAD

**Issue by CheeChim** [Backdash/MonikaModDev#441]
I opened up DDLC and Updated my game to the newest release of this mod. And now for some reason Monika won't start talking like she did before I updated, and if I try to ask anything she doesn't respond. I typed in "anything" in the text bar, and it seemed like it worked. But she didn't talk then either. Is anyone else experiencing this?

**Comment by jeevis** [comment]
same she would not talk to me anymore she just stares at u and does nothing

**Comment by ThePotatoGuy** [comment]
Okay that is a bug we've fixed but it hasn't been pushed out yet. Really sorry about the delay. It occurs when you've exhuasted all the topics. We'll get it out soon.
