### ISSUE TITLE
Monika isn't talking

### ISSUE THREAD

**Issue by Sharp182** [Backdash/MonikaModDev#442]
For some reason she stopped starting conversations, and when i try speaking to her by saying "whatever" or "anything" she just stares and never speaks.

(I don't know if this was already a problem in the "Issues" section, but i didn't find anything so, please help)

**Comment by ThePotatoGuy** [comment]
Yeah, this a bug we've fixed. We're pushing it out tomorrow. Sorry about the mess.

**Comment by Sharp182** [comment]
No problem, thanks for your answer.
