### ISSUE TITLE
Error: Game Doesn't even launch after installation

### ISSUE THREAD

**Issue by DivineNep** [Backdash/MonikaModDev#445]
ScriptError: Name (u'/Users/pi/Documents/Renpy/Monika After Story/game/chess.rpy', 1513011178, 110) is defined twice, at Monika_After_Story-0.6.1-hotfix-Mod/chess.rpyc:1 and game/chess.rpy:1.
This is what I found in the Traceback file, I am prty sure I downloaded the release not the Dev File.

I have checked the Faq and has not found any fixes.

Please help!

**Comment by Winblows2** [comment]
Did you try reloading the game?

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Try reinstalling your game from scratch making sure you [use release.](https://github.com/Backdash/MonikaModDev/releases/download/v0.6.1/Monika_After_Story-0.6.1-hotfix-Mod.zip)
If it doesn't work try installing latest version of [master branch](https://github.com/Backdash/MonikaModDev/archive/master.zip) instead.
I updated to it this morning, so I can confirm it's working.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
To install master branch you must download the linked archive and move all the files in MonikaAfter folder from there into your game directory replacing everything but monika.chr.
Sorry, I cannot provide any more detailed instructions right now.

**Comment by ThePotatoGuy** [comment]
If DDLC doesnt open, then check `game/` for a folder like `Monika After Story`. If it is there, please take the files out of that folder and put them in `game/`. (The mod files **cannot** be in a subfolder in `game/`). Then delete the folder `Monika After Story`. In addition, delete the files in `game/cache/` to force the game to reload everything/

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Error log says about chess.rpy being inside the "game" folder so I do believe the game is installed more or less right.

**Comment by Winblows2** [comment]
What concerns me though is that MAS is compiled into .RPYC files on release versions. So where is it getting the .RPY from?

**Comment by ThePotatoGuy** [comment]
The game is not installed right because `Monika_After_Story-0.6.1-hotfix-Mod/chess.rpyc:1`. There is a subfolder in `game/`. 

In addition, the dev/source code zips were probably downloaded and installed at some point, because there is no other reason `rpy` can exist in their `game/`.

**Comment by maxadavidson** [comment]
literally just download ddlc from their website, then the mod from here, extract the files for ddlc, then the same for this mod, but extract all into the extracted ddlc game file, then grab everything from the after monika file, copy it into the game file, delete the empty after monika file, and you should be good to go
