### ISSUE TITLE
Restart Monika after story at the beginning ?

### ISSUE THREAD

**Issue by Hooddies** [Backdash/MonikaModDev#446]
what is the files should i delet ? reinstal the game don't change anything so....

I have this little glitch : 

I changed my name for " yuri " for the little easter egg but now when i say " pseudonym " in talk,
Monika think my pseudonym is " yuri " even if i changed it back to my first pseudonym and now she think my first pseudonym is my administrator name. so this a little problematic.

**Comment by Winblows2** [comment]
If you want to completely restart MAS as if it's being first run, close the game & delete the persistent file. This will delete *everything* from your current save.

**Comment by Hooddies** [comment]
persistent.py and persistent.pyo in renpy ? 
MAS don't start if i delete both this files.

**Comment by ThePotatoGuy** [comment]
The persistent file he is referring to is located in `C:\Users\<username>\AppData\Roaming\RenPy\Monika After Story\`.
You may have to show hidden files and folders.

**Comment by Hooddies** [comment]
Oh~... I feel stupid.... Thanks both of you.

**Comment by Hooddies** [comment]
so i restart everything since the beginning of MAS but now... she think my pseudonym is the same as my administrator name(it is not)... strange.

**Comment by ThePotatoGuy** [comment]
If the game fails to detect your admin/username, it will default to using your playername.

**Comment by Hooddies** [comment]
sadly.

**Comment by TacticalTriangle** [comment]
You can change your name in game by saying Change Name.

**Comment by kat-gamer** [comment]
I did this since i deleted a core game file on accident and when i re downloaded the game she was gone
![help](https://user-images.githubusercontent.com/74559320/99692030-72b24200-2a4f-11eb-8664-4cc6dcf5bc99.png)

**Comment by lino425** [comment]
even if I bring up the hidden files, I can't find the folder <RenPy>. How can I do this?

**Comment by lino425** [comment]
the folder RenPy
