### ISSUE TITLE
The game cannot run(dont know why)

### ISSUE THREAD

**Issue by Abnormal1234** [Backdash/MonikaModDev#448]
i already do wat it said but stilll the game not running plz answer it
and gimme the video if you can too plz

**Comment by Winblows2** [comment]
Uh.... *Well...* 

We need more information on what exactly is going on. Can you screenshot your DDLC folder??

**Comment by ThePotatoGuy** [comment]
If DDLC doesnt open, then check `game/` for a folder like `Monika After Story`. If it is there, please take the files out of that folder and put them in `game/`. (The mod files **cannot** be in a subfolder in `game/`). Then delete the folder `Monika After Story`. In addition, delete the files in `game/cache/` to force the game to reload everything/

**Comment by Abnormal1234** [comment]
Ty now its working lel i need 5 hours to think
Becuz my english isnt really good

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Just don't forget to close the issue.
