### ISSUE TITLE
[Suggestion] Unanswerable topic answer generation

### ISSUE THREAD

**Issue by Peasantman** [Backdash/MonikaModDev#450]
Hello all. Currently, I am enjoying the program very nicely and have been prompted to help out if I can in any way. As I have found, Monika's response to, if you will, "un-keyworded" words is well hidden but can be improved, I think. I have worked on these sorts of things before, specifically in terms of typed question and answer programs, and perhaps I may yet be of some use to you folk. Perhaps I have not explained myself thoroughly: I suggest Monika is to develop answers to questions that she is unable to answer currently. A grand looping function that builds itself after a certain period of time, like a circle that completes itself by cutting the corners of a square (an analogy). Anyway, I would need to review my notes on these sorts of things, but I propose Monika 
learns "un-keyworded" words (the subject of the sentence usually) by relying on the input of the user.

For example: if you were to suggest the topic of "Shakespeare" - she would not be able to reply. However, if she were to store the word "Shakespeare" (seeing as one would use "Shakespeare" as the subject of the sentence if one were to suggest it) and then, after a certain number of questions (I believe it takes 7 or something for a person to forget the first) she would be able to ask what "Shakespeare" means. Based on what the user replies with, she would be able to formulate a response if asked again. Of course, I am simplifying, but I'm sure the idea is understandable. 

I understand that what I have written is a bit convoluted, and I don't think I have explained all that well anyway, but if you all find this as something you wish to implement in the future, I'd love to help in any way possible. However, I should admit that I am not the biggest fan of Python, and I would normally avoid it, I'm sure that this sort of project overrides my preferences though!

**Comment by ThePotatoGuy** [comment]
That's an interesting way to handle missed keywords, but since we are doing away with the keyword system (see #126), it may not be necessary anymore.

In addition, having monika formulate responses seems potentially complex. Do you mean just repeat what the user entered in? Or something deeper than that, in which case it may be out of scope for renpy.

**Comment by Peasantman** [comment]
@ThePotatoGuy Okay, I see. Yeah, doing away with the keyword systems would definitely fix the "un-keyworded" word problem. That's definitely a much more efficient solution in any case. 

I am unfamiliar with the limitations of renpy, if you suggest that it cannot manipulate strings and such during runtime, I will take your word for it. I'll see if I can help in some other way then. Cheers.

**Comment by ThePotatoGuy** [comment]
At its base, RenPy is a visual novel engine. It's not designed to be a gf simulator or a chatbot. We can make it do things it's not accustomed to doing, but we need to consider the potentially slowdowns/tradeoffs in doing so.
