### ISSUE TITLE
I'm trying to get this mod to work, but it won't

### ISSUE THREAD

**Issue by ZeraxTheDark** [Backdash/MonikaModDev#452]
I've done exactly as the instructions have said, in both steam edition and the download edition, neither have worked at all. 

So if anyone is willing to give a more exact tutorial to help get it set up, that would be great. Since apparently with what the website says I can't figure it out myself. haha...

**Comment by ThePotatoGuy** [comment]
Does the game even launch when you have the mod installed?

**Comment by MrLukeNL** [comment]
I'm just gonna join in on this, I'm not a Python master...

`I'm sorry, but an uncaught exception occurred.

While running game code:
ScriptError: Name (u'/Users/pi/Documents/Renpy/Monika After Story/game/chess.rpy', 1512072286, 2) is defined twice, at Monika_After_Story-0.6.1-hotfix-Mod/chess.rpyc:483 and game/chess.rpy:379.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "E:\Steam\steamapps\common\Doki Doki Literature Club\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "E:\Steam\steamapps\common\Doki Doki Literature Club\renpy\main.py", line 364, in main
    renpy.game.script.load_script()  # sets renpy.game.script.
  File "E:\Steam\steamapps\common\Doki Doki Literature Club\renpy\script.py", line 265, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "E:\Steam\steamapps\common\Doki Doki Literature Club\renpy\script.py", line 753, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=fn + source)
  File "E:\Steam\steamapps\common\Doki Doki Literature Club\renpy\script.py", line 419, in finish_load
    bad_node.filename, bad_node.linenumber))
ScriptError: Name (u'/Users/pi/Documents/Renpy/Monika After Story/game/chess.rpy', 1512072286, 2) is defined twice, at Monika_After_Story-0.6.1-hotfix-Mod/chess.rpyc:483 and game/chess.rpy:379.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
 
`

**Comment by ZeraxTheDark** [comment]
@ThePotatoGuy It did at first, but would immediately crash and give me the message @MrLukeNL put.
Now it doesn't open at all.

**Comment by MrLukeNL** [comment]
Mine didn't open in the first place

**Comment by ThePotatoGuy** [comment]
If DDLC doesnt open, then check `game/` for a folder like `Monika After Story`. If it is there, please take the files out of that folder and put them in `game/`. (The mod files **cannot** be in a subfolder in `game/`). Then delete the folder `Monika After Story`. In addition, delete the files in `game/cache/` to force the game to reload everything/

**Comment by MrLukeNL** [comment]
@ThePotatoGuy Yeah, so that's what went wrong with mine, because I did exactly what the installation said, but I figured it out myself 2 minutes before you answered, still thank you for responding so quick, and keep up the good work!

**Comment by ZeraxTheDark** [comment]
@ThePotatoGuy just did what you said, game still does not open. It did however make a log.txt file that states:

Thu Dec 14 13:14:52 2017
Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
 

Bootstrap to the start of init.init took 0.30s
Early init took 0.04s
Loader init took 0.07s
Loading error handling took 0.10s

but game itself does not open.

**Comment by ThePotatoGuy** [comment]
can you take a screenshot of your `game/` directory?

Generally if ddlc doesnt start, its because of a subfolder issue.

**Comment by MrLukeNL** [comment]
@ZeraxTheDark try reinstalling, then extracting from the Monika_After_Story-0.6.X folder inside the zip folder

**Comment by ZeraxTheDark** [comment]
![untitled](https://user-images.githubusercontent.com/34553900/34014887-91682068-e0d1-11e7-8178-ab7045d2b0ba.png)

That's my game folder after extracting the things out of Monica After Story

**Comment by ThePotatoGuy** [comment]
Did you put the mod files in `game/game/`? They should be in `game/` **not in a subfolder** in `game/`

**Comment by ZeraxTheDark** [comment]
Game/game came from the zip. That was in the folder Monica After Story, i myself, did not put anything in it. All that's in it is stuff that started in it. 

All i did was Copy Monica After Story to Game/ and then took the files and foulders out of it. and deleted Monica After Story

**Comment by ZeraxTheDark** [comment]
Alright, i got it working.

Unless some weird thing happens while playing i should be good.
