### ISSUE TITLE
Show poem text from DDLC is displayed post-topic

### ISSUE THREAD

**Issue by Xanexed** [Backdash/MonikaModDev#453]
The text in the red box comes up every time after a conversation but no "poem" shows and after some time the next conversation starts and at the end of it she and i will have that same conversation in red with yet again no "poem" showing up. 

![](https://image.prntscr.com/image/evHtqXvjSbaNx98iOcF3nA.png)

**Comment by ThePotatoGuy** [comment]
Try going into the `game/cache/` directory and delete the files in there and relaunch.

**Comment by Xanexed** [comment]
cache was cleared but nothing changed, fresh install after removing all non base files seems to have fixed the problem. not a clue what caused it. Thanks for the reply.

**Comment by ThePotatoGuy** [comment]
Thats good.

We've had one other report of this before but haven't been able to narrow down the cause.
