### ISSUE TITLE
[Bug?] Monika Asking About Instruments

### ISSUE THREAD

**Issue by MLGeoff** [Backdash/MonikaModDev#455]
I just updated to 0.6.2 and was prompted to tell Monika what instrument I played, and I put in Piano.  Then she said -
m "Wow' I've always wanted to try the piano out!"
m "I would love to hear you play for me."
m "Maybe you could teach me how to play, too~"
This is my favourite part - 
m "Oh!  Would a duet between the piano and the piano would sound nice?"
There is a possible typo in that line, but I found the double piano's amusing.  Maybe there could be some different dialogue when players tell Monika that they play piano too.

**Comment by ThePotatoGuy** [comment]
Hmm, this should have been caught by our editors. Thanks for finding this.

**Comment by Zer0mniac** [comment]
I  feel like thats a little contradictory when she says "I've always wanted to try the piano out!" because she's been playing it, so that would mean that has/is trying it out.

And about wanting the player to teach her. She could say that her and the play can learn together

**Comment by MLGeoff** [comment]
That contradiction was the exact reason I found it amusing.
