### ISSUE TITLE
[Bug] - Asking Monika about her hobbies

### ISSUE THREAD

**Issue by aimlesstrainer** [Backdash/MonikaModDev#458]
I used the 'talk function' and said "What are your hobbies?" to which Monika replied "Why do you want to know?", and I answered "I want to know what you like.". Monika then replied with this:
"What would it mean to you if you got to do something **_me_** like?"

I'm not sure if this is intentional or just a typo.
EDIT: this occurred again but with a different line, but I can't remember which one it was :/

**Comment by monikLover** [comment]
This is intentional since the response is from the bot and not from a topic.
