### ISSUE TITLE
Suggestion: Switch to DDLC for Different Route

### ISSUE THREAD

**Issue by KiraTakemi** [Backdash/MonikaModDev#459]
What about having an option to switch to normal DDLC?

I don't know if this is possible, but what if you could back and pick a different route to get different dialogue out of Monika or finish your run (which is my case, I wanted to 100% the game and ended up not finishing the first act)

**Comment by Winblows2** [comment]
Okay, as great as this could be I seriously don't think it'll be considered. 

Making it a discussion so others can weigh in.

**Comment by ThePotatoGuy** [comment]
This is the `Monika After Story` mod, where you get to spend eternity with your gf Monika. atm, we not planning doing a regular vn, and I doubt we'll be doing that in the future.

**Comment by Jerome-Kun** [comment]
What @ThePotatoGuy said makes sense, this is the Monika AFTER story. A end-all romantic ending to spend time with Monika. It'd be kinda weird to go back and I doubt Monika would let you in the first place. Its a good suggestion overall though.

**Comment by therationalpi** [comment]
I will say this, if you want to go back and continue your DDLC game in the future you can always import and merge the new Save data through the settings menu to have monika's future responses reflect that playthrough (assuming it went further than you had before).
