### ISSUE TITLE
Outfit Example

### ISSUE THREAD

**Issue by iHeartWing** [Backdash/MonikaModDev#460]
I don't know if this type of stuff is wanted or needed at all, but I thought I'd give it a shot. This is really rough work, in fact it's more of an example that anything. After an hour of messing around on Photoshop I present 2 low quality examples of Monika in different outfits. ( I realize the lighting is off, I didn't do anything but crop Monika's head from her image, crop the sprites head off, redraw the sprites clothing were their hair was previously, place Monika's head on the other sprites body, and redraw parts of Monika's hair so it fits in better with the new body (At least for the first one))

![monikacasualnoface](https://user-images.githubusercontent.com/34562512/34027473-d5f11150-e111-11e7-9b57-9c29376ec1e9.png)

This second one isn't finished, but I thought I'd include it anyway

![monikadressnoface](https://user-images.githubusercontent.com/34562512/34027482-e6cb332a-e111-11e7-9e8e-033af80c9f27.png)

**Comment by Winblows2** [comment]
This is GREAT! We *really* do need this, and it'd be wonderful to have you help contribute to the mod. All we really need to do is fit these on to Monika sitting and it'd be good to go.

**Comment by therationalpi** [comment]
Really nice stuff!

Our art team, in particular, does almost all of their work on Discord, so please drop in so I can add you to the group:

https://discord.gg/7P5DnJ4

**Comment by Zer0mniac** [comment]
These are amazing!

**Comment by Kiosho** [comment]
Wow, this is incredible! Loving the second outfit especially!
Like Pi said, drop by Discord, we could definitely use more outfits for Monika to switch between.

**Comment by Winblows2** [comment]
Outfits she could wear in casual situations so she isn't restricted to her school uniform all the time.

**Comment by Kiosho** [comment]
It'd be neat if we could gather outfits for her and have her choose a random one each day. However, that'd likely be something far down the line, as in version 1.0.0 or something. Variety is a good thing though.

**Comment by Winblows2** [comment]
I agree.

**Comment by Tymon222** [comment]
I agree.

**Comment by juank713** [comment]
i agree

**Comment by MikuChanAnime** [comment]
I agree

**Comment by MeowMilk** [comment]
Really nice edits, though sorry about this, but the skin color on the face is a little darker than that on the bodies..
It's not all too noticable though, so it's fine ^^"
