### ISSUE TITLE
[Bug] Incorrect gender

### ISSUE THREAD

**Issue by chalamet** [Backdash/MonikaModDev#464]
i thought this was fixed but i told monika that i'm a Girl not a boy and she was like ok and then she started talking about going on a date and she called me her boyfriend monika i am Gay!!!!!!

**Comment by therationalpi** [comment]
Can you check your version in the settings?

**Comment by chalamet** [comment]
@therationalpi 0.6.2

**Comment by therationalpi** [comment]
Great, thanks!

I have a quick question. Did monika call you boyfriend in the same session as you told her your gender, or had you restarted the game?

**Comment by therationalpi** [comment]
This definitely seems to be a bug, but I'm just trying to figure out where the problem lies.

**Comment by chalamet** [comment]
@therationalpi i had restarted the game

**Comment by therationalpi** [comment]
Alright, thanks. I thought this had been fixed, but I will try to figure out what's going on here.

**Comment by therationalpi** [comment]
Hmm, I'm having troubles reproducing this bug. Can you send me your [persistent file](https://www.renpy.org/wiki/renpy/doc/FAQ#Where_does_Ren.27Py_store_my_save_games_and_persistent_data.3F)?

**Comment by chalamet** [comment]
@therationalpi wait omg i'm so bad with this stuff i found the persistent file but when i try to send it here it says they don't support this file type wskdfjkdf

**Comment by therationalpi** [comment]
Oh, sorry, I forgot to say to put it in a zip file first.

**Comment by chalamet** [comment]
[persistent.zip](https://github.com/Backdash/MonikaModDev/files/1564217/persistent.zip)

**Comment by therationalpi** [comment]
Alright, I checked the persistent and for some reason the gender was incorrectly set. I fixed it, so you can see if this gets rid of the problem:

[persistent.zip](https://github.com/Backdash/MonikaModDev/files/1564221/persistent.zip)

**Comment by chalamet** [comment]
@therationalpi thank you that fixed it!
