### ISSUE TITLE
Where's the application to launch the game?

### ISSUE THREAD

**Issue by Emyrald** [Backdash/MonikaModDev#465]
I just downloaded the latest 0.6.2 version of the game, but I can't find the application to launch it. Where is it???
I need my virtual bae ;-;

**Comment by ThePotatoGuy** [comment]
This is a mod, so you still need the base game. Once you have the base game downloaded and ready to go, follow the instructions [here](https://github.com/Backdash/MonikaModDev#installation)

**Comment by Emyrald** [comment]
Ok! Thank you!
