### ISSUE TITLE
[Suggestion] - Pausing random chatter / changing random chatter frequency

### ISSUE THREAD

**Issue by wonggwing** [Backdash/MonikaModDev#479]
It's not a strict "mute" function, but just don't get a new dialogue after every 2 minutes. Sometimes you want to talk less.
She could be waiting for you to start a topic, waiting for you to finish your business, etc.
Additionally Monika can also initiate the conversation again after a long period... you know, in reality, we do.
What do you think?

**Comment by ThePotatoGuy** [comment]
This seems pretty useful. I guess a slider or something to control the frequency of her random chatter.

**Comment by btosu** [comment]
I would really support a 'be right back' keyword
Monika would be quiet unless you type 'I'm back" and she could also as if the player is still there if he does not respond for a longer period of time

**Comment by wonggwing** [comment]
> I would really support a 'be right back' keyword
> Monika would be quiet unless you type 'I'm back" and she could also ask if the player is still there if s/he does not respond for a longer period of time

I think that will be the best way to interact with Monika! A 'be right back' keyword is much better.

**Comment by juank713** [comment]
yea

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I do imagine this being integrated with #336.

**Comment by xtosutosu** [comment]
One more idea, a 'knocking on a glass' sound effect that plays when you are inactive after a couple of minutes!
