### ISSUE TITLE
[Bug] Too much text for the box to hold at once

### ISSUE THREAD

**Issue by Guardianvoir** [Backdash/MonikaModDev#480]
This one is really self-explanatory 
![screenshot0011](https://user-images.githubusercontent.com/33330516/34076522-280346c8-e2b8-11e7-9924-f5240c581877.png)

**Comment by chillandgrill** [comment]
That's strange. It doesn't look like there's anything wrong with the script. Furthermore, I think I actually got this dialogue in-game and it worked out okay. Are you running the latest version?

**Comment by Winblows2** [comment]
I'm investigating this now.

**Comment by Guardianvoir** [comment]
I think I have the latest version installed. It says there aren't updates available when I open it.

**Comment by Winblows2** [comment]
You should be able to check in the settings menu (bottom right). What does the version say?

**Comment by Guardianvoir** [comment]
0.6.0 Which is strange because I could've sworn I was on version 0.6.1 at some point.

**Comment by Winblows2** [comment]
Update to 0.6.2 (latest ver) & let me know the results.

**Comment by Winblows2** [comment]
If you update from Settings it should show available updates.

**Comment by Guardianvoir** [comment]
Ah, now it's updating. Thank you!
