### ISSUE TITLE
[Bug] - Monika only saying old topics in version 0.6.2

### ISSUE THREAD

**Issue by ryanmart** [Backdash/MonikaModDev#481]
Monika only seems to be talking about things I've already heard her talk about.  I've sat here waiting for her to say something new for like 10 topics or so, but nothing has come up.  This has been happening ever since I installed version 0.6.2, so maybe it's related to the fix for her being silent?  Specifically, I've heard her repeat the ones about:
Gender roles, looking into someone's eyes and falling in love, hating Shakespeare, mental illnesses being looked down upon, and a few others I can't remember right now.

**Comment by Winblows2** [comment]
Topics are meant to repeat, so I don't personally see a problem here. Do remember topics are chosen at random if not manually invoked by the player. 

This doesn't sound like a bug, more like a misunderstanding.

**Comment by ryanmart** [comment]
But aren't they only meant to repeat once you've heard all of them?  I'm only getting old topics from her, and it's really annoying.

**Comment by ThePotatoGuy** [comment]
The last update only added like 1 or 2 new topics. If you've been running this mod for a long time and get new updates right away, you're probably out of new topics.

To make sure, upload your `persistent` file here.
If you're on windows, it should be located at `C:\User\<username>\AppData\Roaming\RenPy\Monika After Story`
You might have to turn on show hidden files and folders.

**Comment by ryanmart** [comment]
Sure thing.  I found the persistent file, but how do I upload it?  I'm kinda new to all this.

**Comment by ThePotatoGuy** [comment]
Put the file into a zip and attach it to your comment.

**Comment by ryanmart** [comment]
Okay, here you go.
[persistent.zip](https://github.com/Backdash/MonikaModDev/files/1566148/persistent.zip)

**Comment by ThePotatoGuy** [comment]
Yeah, according to your `persistent`, you've seen every single topic already. Once that occurs the entire pool is reset so you'll start seeing old ones.

**Comment by ryanmart** [comment]
Damn.  That's too bad.  Well, at least it isn't a bug.  Thanks for figuring that out.  By the way, when fixing typos in pre-existing topics, should I commit the changes to content or master?  Because I've gotten conflicting advice on that.
