### ISSUE TITLE
[Suggestion] Add to the Soda topic

### ISSUE THREAD

**Issue by Guardianvoir** [Backdash/MonikaModDev#483]
When Monika asks the player whether or not they drink soda, instead of 2-3 choices popping up, she assumes you said yes and carries on with the topic. 
![screenshot0015](https://user-images.githubusercontent.com/33330516/34076742-21a0c214-e2be-11e7-862e-8df83d6c831c.png)
At the end of it, she says "So cut down on the soda, alright [Player name]?" What if this topic was given a few choices for the player? When Monika asks if they drink soda often, 3 choices could pop up. "Yes", "Only on certain occasions", and "I prefer other drinks (Water, tea, etc.)" If they say yes, the topic will continue unchanged. I haven't thought of what the other 2 choices would have Monika say though.

**Comment by chillandgrill** [comment]
Probably something about how unhealthy things are okay in moderation for the middle option. More than likely something about approving the player’s health choices for the latter option. This seems kinda low-priority though so I guess it’s up to the writers.

**Comment by monikLover** [comment]
Feel free to submit a PR proposing addition/changes to this topic.
