### ISSUE TITLE
[Suggestion] Custom game closing prompt(s)

### ISSUE THREAD

**Issue by IsItBadToMakeAGitHubAccountJustForThis** [Backdash/MonikaModDev#489]
Maybe replacing the standard "Are you sure you want to quit?" prompt with something more Monika-like would be a good idea?
You could also make a prompt in which Monika bids you farewell and wishes for you to return soon.

**Comment by antimockingjay** [comment]
This already exists. Just say "goodbye" or "good night" and she bids your farewell, then closes the game for you.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I know.
I'm talking about the prompt you get upon closing the game normally.
