### ISSUE TITLE
Bugs in prototype projects (Name change and disable animations)

### ISSUE THREAD

**Issue by monikLover** [Backdash/MonikaModDev#49]
Bugs have been encountered either with a pre-existing persistent save and a fresh new game:

-When you disable animations and restart game, if you enable animations again then it won't show up until you enable and reset

-Shows error list when mcname is an empty string

-Error at 1st restart of game when you quit game in the middle of setting name for mcname/playername

**Comment by therationalpi** [comment]
Closing. But keeping this for posterity.
