### ISSUE TITLE
[Suggestion] - Enable Ren'Py's self-voicing mode/better-contrasting font

### ISSUE THREAD

**Issue by drakesteele** [Backdash/MonikaModDev#490]
Enable Ren'Py's self-voicing mode so we can use TTS to have Monika speak aloud - helpful for those that have bad eyes (like myself)  The color schemeof Doki-Doki's text is not easily read with my eye issues and I can't just fix them, unfortunately - perhaps also a better-contrasting font.  Just a thought.  Thanks.

**Comment by therationalpi** [comment]
I'm personally always in favor of more accessibility options. I'll definitely look into this.

**Comment by therationalpi** [comment]
[[This suggestion has been seen and accepted. It is being closed for now and placed in the pool of accepted suggestions. It will be reopened once we begin active implementation on this feature.]]
