### ISSUE TITLE
[Grammar] Monika using "a" when the next word starts with a vowel (Rock and Roll Topic)

### ISSUE THREAD

**Issue by NotShige** [Backdash/MonikaModDev#492]
Self-explanatory. Screenshot below.
![ddlc_2017-12-17_23-04-50](https://user-images.githubusercontent.com/20384051/34080810-dcb7cb22-e37e-11e7-9b25-666b9789312b.png)

**Comment by monikLover** [comment]
Will fix. Thank you!
