### ISSUE TITLE
[Suggestion] - New topic direct submission system

### ISSUE THREAD

**Issue by drakesteele** [Backdash/MonikaModDev#493]
Was imagining that you might be able to put in an unusual key combo, and have a pop-up that allows you to enter all of the parameters for a new database entry for Monika's conversations, and submit it to the project for moderation, and approval would add it to the database to be updated online with the next build... that way the topics could grow quite quickly, without only those that know coding able to add.

Perhaps a key like CTRL-SHIFT-F5 or some such, would bring up a dialog: Here's an example...

Topic Keywords: beautiful, gorgeous, sexy
Category: compliment
Monika's Response 1:  Ehehe
Expression:1 [Smiling]   Blush? [X]  EyesClosed? [X]
Monika's Response 2:  Gosh, %Name%,...
Expression2: [Smiling]   Blush? [X]  EyesClosed? [ ]
Monika's Response 3:  I think you look great too, at least in my mind's eye...
Expression3: [Thoughtul]   Blush? [x]  EyesClosed? [X]
Monika's Response 4: I know I can't [i]REALLY[/i] see you...
Expression4: [Thoughtul]   Blush? [x]  EyesClosed? [ ]
Monika's Response 5: But a girl can dream, can't she?
Expression5: [Smiling]   Blush? [X]  EyesClosed? [ ]
Randomly Discuss? [ ]
Open activity after response? [ ]
Activity to open: [none]

In the Expressions lines the drop-down would have the available faces for Monika, something like...
Expression: [Smiling, Thoughtul, Surprise, Laughing, Angry, Neutral]   Blush? [ ]  EyesClosed? [ ]

And the activities thing would have the available dialog and game options, like so:
Activity to open: [ Chess, Pong, Rename, SelfVoice, TopicSuggest, etc.]

What do you think?

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
It would be EXTREMELY hard to implement using Ren'py functional only.
At this point, it would be easier to write a separate program with its own UI and everything.

**Comment by therationalpi** [comment]
We are currently trying to make submitting new topics easier for non-coders: https://github.com/Backdash/MonikaModDev/issues/188

As for including it directly in the game, this would be very difficult to implement, and I don't believe it's the best use of our time.
