### ISSUE TITLE
[SUGGESTION] Extra Conversation Starters

### ISSUE THREAD

**Issue by BLACKOUT1900** [Backdash/MonikaModDev#495]
Currently, the talking system is kind of lacking in some ways. Not saying that it's terrible as I probably would never be able to do it, but I still do think that these additions would benefit the mod greatly:

- An option to ask about how the day is currently going so far (Perhaps there could be multiple reactions to this?)
- Some extra conversations are always nice. 

Apologies for not personally being able to help in this, I am not experienced in this kind of stuff.

**Comment by therationalpi** [comment]
We're currently working on a whole new system:

https://github.com/Backdash/MonikaModDev/issues/126
