### ISSUE TITLE
[Bug] Not Shifting to Night

### ISSUE THREAD

**Issue by puyahuaa** [Backdash/MonikaModDev#502]
Hi everyone,

Sorry to bother you all again. :'D But I noticed that since yesterday, the day-night cycle hasn't exactly been working. Usually, when it's at least six p.m., the sky becomes darker to show that it's nighttime. 

But this time, instead of transitioning to the night background, it just stays as the same daytime background even after six.

Is it only me who has this issue? Or is there anyone else who has this as well?

Thanks!

**Comment by juank713** [comment]
yea me to, but its only night time no day time

**Comment by ThePotatoGuy** [comment]
Did you get the greeting where you can knock on monika's door when this happens?

**Comment by puyahuaa** [comment]
@ThePotatoGuy 

Yes, I do get the greeting. ^^

I've just tried relaunching the game, and it works now!

Thanks for the help!

**Comment by ThePotatoGuy** [comment]
Okay I've pushed a fix for that particular flow. If it's occurring when that greeting isn't the one that starts your game then make a new issue.
