### ISSUE TITLE
[Suggestion] - The user tells Monika if they celebrate Hanukkah/Christmas/Others 

### ISSUE THREAD

**Issue by chillandgrill** [Backdash/MonikaModDev#504]
In terms of upcoming holiday content, I didn’t see this idea being thrown around so I thought I’d bring it up. The user should be able to tell Monika which holiday they celebrate to determine the kind of backdrop/dialogue they get. For example, if the player were to say they celebrated Christmas, Monika might talk about Santa or the origins of the Christmas tree. On the other hand, if the player selects Hanukkah or other holidays (don’t know much about them), then there’d be dialogue regarding those holidays. Thoughts?

**Comment by ashameimaru** [comment]
As the one that wrote a couple pieces of Hanukkah commentary, it is something at short notice that might not be present so currently I had to make the commentary as an informative observance (acknowledged and celebrated).

I presume that if holidays-at-large are being implemented, I have labeled them appropriately to be easily found to be addressed later.
