### ISSUE TITLE
[Suggestion] Different Locations

### ISSUE THREAD

**Issue by MikuChanAnime** [Backdash/MonikaModDev#509]
Let me start off by saying this is my first post here, so I don't know how things work but anyways.

Maybe add an option to change the locations, since Monika can already change the bedroom to the classroom maybe she could change it to something like a café or something.

**Comment by Winblows2** [comment]
I have some things to add on about this. Firstly, great idea. I love the concept & think it'd work out amazingly if executed right. Here's my idea to improve it:

Make it similar to the music menu. The player can "request" for Monika to change the room to certain locations, but at the same time Monika can choose for herself. Depending on the location, Monika could make a comment on the player's choice. 

For example, if you choose to visit Sayori's room, Monika could make a comment about how you walked in to see her dead body. Alternatively, she could make a comment if you visit your room (Yuri CG, etc.)

Execution as to how is completely up to @ThePotatoGuy and @therationalpi, but these are my thoughts.

**Comment by MikuChanAnime** [comment]
Thanks :D 
I also saw somebody's post about Monika asking the player if the want Coffee or tea and like I said in that post, both of these ideas could be combined into one. Like Monika would only ask the player if they want Coffee/Tea if they are at the Café location.

**Comment by MikuChanAnime** [comment]
bumb
