### ISSUE TITLE
IMPORTANT ANNOUNCEMENT - Roadmap for IP Guideline compliance and repository reset

### ISSUE THREAD

**Issue by therationalpi** [Backdash/MonikaModDev#51]
Okay, big announcement for everyone working on this mod.

To get in compliance with the new IP Guidelines for DDLC, we need to complete a major code overhaul and remove a lot of files from the repository history. We will also need to stop distributing all prior releases of the game.  Before this news dropped, we were very close to the 0.4.0 release, and because of that this will be our roadmap going forward...

## Roadmap

1. All pull requests for the current iteration of Monika After Story must be made to Backdash/MonikaModDev by the end of Thursday.  

2. All accepted changes slated for the 0.4.0 release will be compiled into a 0.4.0 rc, which will be distributed only to active contributors and is not for redistribution. This is purely a reference for future versions.

3. All other accepted changes will be marked as 0.4.1, and will be the basis for migration to version 1.0.0

~~4. A filtered rebase will then remove all original files from our repository and repository history. The resulting repository will no longer have any original DDLC files, and will not be able to compile in Renpy without significant changes. Please plan accordingly. ~~

5. Starting today, I will be beginning a new project, DDLCModTemplate, that anyone may contribute to if they want. This will be a barebones renpy template with hooks into DDLC’s asset files and other resources, specifically designed for anyone wanting to write DDLC fan mods.

~~6. A new repository for MonikaAfterStory will be created, based on DDLCModTemplate, and will be brought up to functional equivalence with version 0.4.1. I will be the owner on this repo, since backdash hasn’t been available to handle permission changes and other duties for managing the project.  ~~

7. Once finished, this will be tested and released publicly as version 1.0.0.

**If you have any questions or concerns regarding this, please respond below.**

**Comment by therationalpi** [comment]
Updated. Backdash has gotten official word from Dan that suggests that we don't have to purge our history, so long as we don't distribute standalone releases in the future. This is very good news, since we don't have to start a new repository or do any major rebasing.

**Comment by Jxhnathan08** [comment]
Update II: MAS has been recently converted to fit the DDLCTemplateMod format. Right now, these things are still in need of being transferred:

- Splash (Logo)
- GUI/Menu (Disable going back to MM on restart, right now it does nothing. Message box?)
- MC response text is slightly messed up. 

Most other things are working properly.

**Comment by therationalpi** [comment]
Awesome work, @Jxhnathan08 ! I'll do some test tomorrow, then open up fresh issues for anything I see.
