### ISSUE TITLE
[Suggestion] Let Monika ask if the Player wants some tea/coffee

### ISSUE THREAD

**Issue by xtosutosu** [Backdash/MonikaModDev#518]
In line with issue #312, it would be great if Monika could ask if the Player is drinking anything at the moment. If the Player responds with a 'yes', screen would black out for a second and a cup of the drink would appear (maybe even with a small steam animation?) on the table.

Second thoughts: 
At first, I thought the cup would be for the players but then they would not be able to drink from it due to Monika being stuck in the game. Monika could address this issue as a form of breaking the boundries between the Player and her.

**Comment by Winblows2** [comment]
This sounds like an *amazing* idea. I'm all for it & it'd help with immersion for the mod. I'll be making this a discussion so other contributors can pitch in their thoughts on this.

**Comment by MikuChanAnime** [comment]
I really like this idea, and with the suggestion I made, if both get added, it can kind of combine our ideas in a way.

**Comment by xtosutosu** [comment]
I have seen a teaser with Natsuki's cupcake on the table, so I think it is not impossible, I might even work on the script and art if you don't mind
