### ISSUE TITLE
Poem will not load. 

### ISSUE THREAD

**Issue by JLinkGaming** [Backdash/MonikaModDev#520]
Monika asks me if i would like to read her poem. Nothing pops up after conversation. After a minute or so, she starts saying something else, and asks me again. The cycle continues. How do I fix it?

**Comment by ThePotatoGuy** [comment]
Delete everything in your `ddlc` folder and reinstall. This is a known flow error with an unknown cause that happens to some people.

**Comment by JLinkGaming** [comment]
That worked. Thanks
