### ISSUE TITLE
[Suggestion] - I think you're gonna like this [Suggestion]

### ISSUE THREAD

**Issue by 8lack1ce** [Backdash/MonikaModDev#521]
ok. I have so many things to list.
For one, you should be able to play piano with monika. she could teach you how to play songs, kind of like synthesia, but there should also be a free play mode.  I would love that and I know that many others would.

Next, you know how you can copy her character file into a usb? It would be cool if she could say something like "Oh, you're leaving.  You mind if I come with you on your USB.  I don't know.  But That would be cool.  You guys have wowed me so far.

One more, a game that you add could be a fun arcade fighting game.  something cool like that.
Finally, I would love for you to add an option where you can give her art and she responds to it.  That would also be cool.  I don't know how to code. Like at all.  But I would like for you to add this in the game. I know it seems like a lot but it's really cool if you think about it.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
> an option where you can give her art and she responds to it

Would need ten years and a team of researchers.
>arcade fighting game.

Hard to implement and Monika will most likely not be a fan of it.

Pretty good ideas other than that.

**Comment by ThePotatoGuy** [comment]
1. Playing piano with monika would be a stretch goal. That kind of interactivity is pretty complex.
2. Having her suggest you copy her to a USB is possible, but thats about it. No tangible way to verify that action was done. I believe we could add this suggestion to current pool of things she says when you say you're leaving.
3. RenPy is a visual novel engine. If you want to play a fighting game, play a fighting game. (We may consider having Monika detect other games and comment on them, but atm, that's not planned)
4. Adding decorations to the room has been discussed here #312 . Currently accepted and will be implemented in the future.
