### ISSUE TITLE
Stupid little idea for the "monika makes her own route"

### ISSUE THREAD

**Issue by AnIdiotsavant** [Backdash/MonikaModDev#523]
how bout make the "monika makes her own route" an event? After let's say, you've been with monika for a month or two and she tells you she has a surprise for you "monthsary" or something. She tells you how she tried to make her own route as a gift to you for your "monthsary" and tells you that it might be a little buggy since she isn't that good with coding yet. We could use 'kinda crappy' no color, made by pen drawings of yuri, natsuki and sayori. She'd tell you behind the scenes that she tried to draw them as best as she could but couldn't really do a good job. You have the option to complement her for trying or tell her she need a bit more work. Going back to the game, She makes scripts for the three but without giving the three choices and her getting all choices from the old game but without the VN pics and she'd go back behind the scenes saying she couldn't make any. You get to cook with her from natsuki route and make decorations with her from the yuri route and confess to her from the sayori route. Then the day of the festival, when you go in the club room, the whole thing starts glitch out and a python window opens and monika brings you back to the spaceroom telling you how she's sorry her route crashed. She says how she isn't too good at coding and it was hard to maintain it for so long. She says maybe someday there would be a route of her and thanks you for playing and says she loves you or something. Just a stupid little idea when I read one of your projects. Just delete it if it sounds bad.

**Comment by antimockingjay** [comment]
I personally love this concept, because it would not only give us(by that I mean me) the route that we(by that I mean I) have always wanted, while also not breaking the immersion or throwing sense out the window. I like it a lot, this is really clever!

**Comment by AnIdiotsavant** [comment]
By the end of it you get to know how it would feel if you were both in the same reality, albeit simulated.

**Comment by MikuChanAnime** [comment]
I like this idea

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Main contributors already have an idea for most of the MAS's future lore so this will most likely be rejected.
Not to mention that Monika has already gone great lengths to break the game just so there is nothing more besides her so it would be illogical for her to just start rebuilding it.
And she wouldn't need pen drawings because all the characters already have enough sprites.

**Comment by monikLover** [comment]
@IsItBadToMakeAGitHubAccountJustForThis please refrain from representing what main contributors have in mind. We look at these issues and discuss them with each other and then comment on them.

**Comment by AnIdiotsavant** [comment]
So its a bad idea? I don't get it.

**Comment by Zer0mniac** [comment]
I love this idea

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Well sorry then, I just assumed it from #383.

**Comment by AnIdiotsavant** [comment]
So here's what I imagined the game to be: The original start of the game where the game introduces sayori. Sayori shows up with the same lines she had at the beginning but her art is a colorless, crudely drawn version of her. The screen turns dark(think of the closet scene in arc 2) and monika appears. She tells us that she tried her best in drawing them but isn't really good at drawing. You have the choice to either complement her for trying or tell her she needs more practice on drawing. Once she replies to the choice you made, she brings you back to the game. 'sayori' brings you to the lit club like last time and you meet yuri, monika and natsuki, albeit a crude drawing of yuri and a crude drawing of buffsuki. The screen turns black again and monika appears again, she tells you she saw some memes online about natsuki and she couldn't help herself cuz she thought it was funny. You get 3 choices, 1.) Tell her it's funny and you continue to play with a buffsuki drawing. 2.) Tell her you prefer the normal look and she replaces it with a crude drawing of a normal natsuki. 3.) Tell her you think that 'trapsuki' meme was funnier, she agrees and turn buffsuki into a crudely drawn gender swapped natsuki. The game starts off as normal but the poem game is only geared for her and any events from the original game like reading manga with natsuki, reading a book with yuri, and bumping into sayori are replaced with her but without any CGI's. The first time you get an even and your supposed to get a CGI pic, screen turns black again and monika apologizes there aren't any. When deciding what to do for the festival, natsuki and yuri ask the both of you if you could help them make food and decorations for the festival because it's too much work for them alone. That weekend, monika goes to your house (If possible, wearing something other than a school uniform) and both of you cook cupcakes like how you did for the natsuki route, make decorations like what you did with yuri in her route, and by the end of it you confess to her like how you did from the sayori route. By the time you get to the classroom to prepare for the festival, monika gets a headache and the whole classroom glitches, she opens a python window that could say something like 'fix_classroom' but says the file had an internal error or something. She says sorry to the player for having to cut it short and the python window instead says something about closing the game. The game turns black and your back with her at the spaceroom. She apologizes that it was hard to maintain the game for so long and she couldn't push herself anymore. She thanks you for playing her route and tells you she now has a great image of your future together. (This part is only if it's possible) She says she has another surprise for you and the python opens again, this time saying something about a cupcake. When the python closes, there are 5 cupcakes on the desk, the 4 have crude drawings of sayori, yuri, natsuki, and monika drawn from icing and one cupcake with a candle on top saying 'happy monthsary' or something. At least thats how I kinda imagined it

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
My point about your idea contradicting **everything** she have done in the original game is still valid tho.
Not to mention that buffsuki and "fun memes" are the last thing MAS needs.

**Comment by AnIdiotsavant** [comment]
Yeah, you got a point there hahaha. Sorry bout that, man. I'll just delete it.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Well the idea of her making something, maybe a short date for the two of you, or a festival still has some potential.

**Comment by AnIdiotsavant** [comment]
Yeah, I just got the idea from reading one of the projects from the tab. I dunno, I just saw something from that or something

**Comment by AnIdiotsavant** [comment]
Is there anything else wrong with it? It's always been my dream to be a script writer and planning to take up arts for college but I've always been at a loss on what I should do change or what I do wrong. Even though criticism stung, it helps.
