### ISSUE TITLE
Monika Changing Facial Expressions In Code

### ISSUE THREAD

**Issue by Knight-Of-Balance** [Backdash/MonikaModDev#524]
More a me problem but I can't find out how to change her expressions through the usage of code. I see stuff like "3m" but I don't know what that corrlates to in terms of expression. If someone can just point me in the direction I need to go to find this: That's all I ask.

**Comment by Winblows2** [comment]
There's an expressions chart you can use right here!
https://github.com/Backdash/MonikaModDev/blob/master/docs/MonikaCheatsheet.jpg

Closing.
