### ISSUE TITLE
Conversations Feels More Scripted Than Intimate

### ISSUE THREAD

**Issue by Bam8647** [Backdash/MonikaModDev#527]
Let me first start off by thanking all of those who've helped build this mod as it is really well done and sweet given the fact that Monika never had her own route in DDLC. **My main concern i'm experiencing with this mod is the 'Talk' function and how whatever you write to her the responses seem to be very scripted.** For instance, If I write anything with "Monika" in the dialogue box no matter what the game will pull from the script of her talking about herself even if you weren't even asking her about herself. And if your words don't seem to match any of her scripts then she'll always say the usual "How would it make you feel if "blank"?" or "Why do you think "Blank"?" etc.. So I thought **I'd recommend that the 'Talk' function be less of a word match function for her scripts and more of a unique response mechanism that could make you feel more engaged with her.** Also create more flirty responses especially if you compliment her or something. 

Maybe I'm over my head in some of my suggestions haha. But If there was a way to make Monika more "self learning" (As in learning more about the player for future conversations) and more intimate as well as engaging with the player it could go a REALLY long way! Thank you for reading.

**Comment by HalHarrison** [comment]
IMO dialogue topics with alot of choices and sub choices would give the most bang for buck, especially if there were consequences outside of the conversation for what you said to her. This problem you brought up really is the big one with the mod: No consequences for anything, and little choice of personalizing interaction with Monika. 

From now on I'll try to write only topics with menus and actual dialogue trees.

**Comment by ThePotatoGuy** [comment]
The `Talk` function is changing to #126. In terms of the actual topics, the original set were all really scripted, and it takes time, creativity, and people like @HalHarrison to make interactive topics.
