### ISSUE TITLE
[Bug] Monika using my IGN as my Windows username (even though it's not).

### ISSUE THREAD

**Issue by NotShige** [Backdash/MonikaModDev#531]
Self-explanatory, screenshot below.
![firefox_2017-12-20_19-38-15](https://user-images.githubusercontent.com/20384051/34205556-d507ace4-e5bd-11e7-87d7-f901e80953cc.png)

**Comment by NotShige** [comment]
Here's my persistent file (if it's needed).
[persistent.zip](https://github.com/Backdash/MonikaModDev/files/1575471/persistent.zip)

**Comment by ThePotatoGuy** [comment]
If the game is unable to detect your username, then it will default to your playername.
