### ISSUE TITLE
Monika stopped talking

### ISSUE THREAD

**Issue by Guardianvoir** [Backdash/MonikaModDev#54]
I'm not sure what exactly caused this, but Monika just stopped talking. I'll open the game and she'll give me the message that asks whether or not I can code, then she'll say "You can wait a little bit longer, right?" and then the story about the two coffins and the elderly woman. After that, she just stops talking. She'll still respond when I say something, but other than that she won't talk. What do I do.

Edit: This is unrelated but I thought it was funny. I remembered about this after I already posted this issue. I was testing some phrases with the talk feature and thought what would happen if I said "delet this" and it actually made the error screen pop up. I tried again after that and it didn't make another error, I just thought that was funny.

**Comment by therationalpi** [comment]
Glad you found your solution.
