### ISSUE TITLE
Music Selection?

### ISSUE THREAD

**Issue by littlemisteruniverse** [Backdash/MonikaModDev#542]
Hey There! I'm new here, and not sure how things work, but i was thinking it'd be neat it we could somehow add in our own music files into the mod. Maybe Monika would ask if we wrote a song for her too or something like that. Just a lil' thought, though!

**Comment by ThePotatoGuy** [comment]
Refer to #309 

It's not very feasible nor practical to incorporate adding your own music to the mod. However, if you have your own original music piece, have an `.ogg` version of that music , and give us permission to use it, then we could see about putting it into the mod.
