### ISSUE TITLE
Broken Image on the joy to my world topic.

### ISSUE THREAD

**Issue by Blubmanful** [Backdash/MonikaModDev#543]
When she is talking about the joy to the world comment, on the line "Ehehe, I hope it's not too cheesy" the picture of Monika isn't there and instead is the default texture of the shadowy small girl figure. Sorry if it's already known or fixed by the time this is posted. If it is just close it. Have a good day, I really like this mod and love to see it get updated!

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I cannot find such line in any topics of neither master nor content branch.
Did you perhaps mean `greeting_visit2`?

>     "Thanks for spending so much time with me, [player]."
>     "Every minute I spend with you is like being in heaven!"
>     "I hope that didn't sound too cheesy, ehehe~"

**Comment by ThePotatoGuy** [comment]
Sorry, that release that you downloaded @Blubmanful was not supposed to be available at that time. Please await the actual release.
