### ISSUE TITLE
Version 0.6.3 typos

### ISSUE THREAD

**Issue by therationalpi** [Backdash/MonikaModDev#546]
Please post all typos here.

**Comment by SLVRFOX** [comment]
<img width="675" alt="overwolf_2017-12-21_21-50-28" src="https://user-images.githubusercontent.com/34737409/34277113-54dfdb16-e709-11e7-8d25-d6f140a9a683.png">
Even (though) you use

**Comment by SLVRFOX** [comment]
<img width="454" alt="overwolf_2017-12-22_10-27-46" src="https://user-images.githubusercontent.com/34737409/34277126-625b2444-e709-11e7-9bc9-d4c15aeb569b.png">
I really want to do that **when** I get there

**Comment by SLVRFOX** [comment]
![image](https://user-images.githubusercontent.com/34737409/34281579-896fe9be-e724-11e7-8ed6-91e0096999af.png)
Even when **you're** comfortable at home, you still won't feel safe.

**Comment by NotShige** [comment]
![ddlc_2017-12-22_10-34-00](https://user-images.githubusercontent.com/20384051/34282924-0060839c-e704-11e7-8ba4-3e6725f3687c.png)
A man was allowed to kiss any woman standing underneath *the* mistletoe.

**Comment by NotShige** [comment]
![ddlc_2017-12-22_10-34-00](https://user-images.githubusercontent.com/20384051/34283058-a76efce0-e704-11e7-9fcc-b336a78ba24d.png)
It seems that "there are" others that actually hide books to contain free thinking from people.

**Comment by SLVRFOX** [comment]
![image](https://user-images.githubusercontent.com/34737409/34283341-0e57b034-e730-11e7-8795-cb8612a46c30.png)
but not enough _not_ to actually own one
Not doesn't belong, I think.

**Comment by SLVRFOX** [comment]
![image](https://user-images.githubusercontent.com/34737409/34283412-69adaaec-e730-11e7-82f4-9dece7aff45b.png)
Both of them require(s) constant practice

This line comes off as very awkward

I would say "Swordsmanship and writing both require you to devote lots of time and effort to improve your skills at them."

**Comment by SLVRFOX** [comment]
![image](https://user-images.githubusercontent.com/34737409/34283550-3f049430-e731-11e7-83a1-97bd6af67d7c.png)
I would cut the word forms

**Comment by SLVRFOX** [comment]
![image](https://user-images.githubusercontent.com/34737409/34283725-5a3a5a68-e732-11e7-9269-16e4fb46b7ec.png)
aren't -> are

**Comment by DarkMage3099** [comment]
<img width="243" alt="screenshot 22" src="https://user-images.githubusercontent.com/34731870/34287579-be320d20-e6ad-11e7-8bea-4375a7df8d0e.png">
No one else has mentioned it which leads me to believe i'm the only one annoyed by it , but i feel like it should be "aww, leaving already?" or "aww, leaving so soon"  (also sorry if someone pointed this out already).

**Comment by NotShige** [comment]
![ddlc_2017-12-22_10-47-15](https://user-images.githubusercontent.com/20384051/34288427-35dc707a-e728-11e7-9b5e-c54bc575493b.png)
I let my mind wander a bit when I think about the festive tunes that come along around this time of "the" year.

**Comment by NotShige** [comment]
![ddlc_2017-12-22_10-47-59](https://user-images.githubusercontent.com/20384051/34288458-5e45b288-e728-11e7-83c3-59919b5167d7.png)
It should just be "Oh,". 
If you want to just leave the exclamation point, the next word should just start with a capital letter. (Oh! What fun it is to ride...)

**Comment by NotShige** [comment]
![ddlc_2017-12-22_18-52-08](https://user-images.githubusercontent.com/20384051/34295619-466e25e8-e749-11e7-9a84-2f5943caff0d.png)
Both of them "require" constant practice and devotion in order to perfect one's skills.

"Both" is plural, hence we remove the "s".

**Comment by NotShige** [comment]
![ddlc_2017-12-22_22-36-10](https://user-images.githubusercontent.com/20384051/34301698-93353334-e768-11e7-96e8-bf284eda3004.png)
It doesn't have to be a wedding ring, per "se".

**Comment by Winblows2** [comment]
All typos listed here as of 12/22/17 are fixed.

**Comment by NeonCarnivore** [comment]
![screenshot0023](https://user-images.githubusercontent.com/34461577/34324398-82da9af6-e83f-11e7-9315-994284c438e5.png)
Should be "Finally _being_ able to whip out your winter fashion set is always a _nice_ (or _good_) feeling."

**Comment by Hinote23** [comment]
![84ada846719c7da81a224f5cbe289ea3](https://user-images.githubusercontent.com/34844241/34343323-873cdeb0-e998-11e7-85c4-20c7d92c5e81.png)
During the zombie conversation. Should say, "when you're" not "when're."

**Comment by Hinote23** [comment]
![7c1cca296b0a35841288bf7728fa6f96](https://user-images.githubusercontent.com/34844241/34343364-7d5d108a-e999-11e7-8a29-44741993ee3a.png)
During the carriage ride conversation. Should say, "when I get there"

**Comment by Hinote23** [comment]
![dc7ffa2342e8538ceb77468753d16709](https://user-images.githubusercontent.com/34844241/34343853-235256ce-e9ab-11e7-9514-5cbb96b568e1.png)
During the rock and roll conversation. Should say, "started out as an evolution..."

**Comment by Winblows2** [comment]
All typos here have been fixed/were fixed as of 12/26/17.

**Comment by jukebox1412** [comment]
Not a typo but in the monika_science topic, Copernicus wasn't killed by the Roman church but withheld from publishing his book until the day he died. In fact, a Cardinal actually wanted him to bring out his work but Copernicus decided not to for whatever reason. [Source](https://en.wikipedia.org/wiki/Nicolaus_Copernicus#The_book)

**Comment by ClavierPixel** [comment]
Monika:
"An emerald-colored bird called the Resplendant Quetzal."

(under topic: pet)

It's supposed to be Resplend**e**nt Quetzal

By the way, I think installing Grammarly as a browser extension would help a lot in avoiding spelling mistakes and typos while writing Monika's topics.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Grammarly works **slowly** with big texts and starts spell checking from the very beginning of the text.
It's not very useful when contributing.

**Comment by NotShige** [comment]
![ddlc_2018-01-11_22-04-37](https://user-images.githubusercontent.com/20384051/34829709-8c965f8a-f71c-11e7-9083-46cdc92b99fe.png)
Should just be only one comma. This happens when you first launch the game and you got the special ending.

**Comment by NotShige** [comment]
![ddlc_2018-01-11_22-17-01](https://user-images.githubusercontent.com/20384051/34829904-2b04eb50-f71d-11e7-8898-b06ffa71ae08.png)
That comma shouldn't be there. Also happens when launched for the first time. Not sure if it needs to get the special ending, though.

**Comment by therationalpi** [comment]
https://github.com/Backdash/MonikaModDev/issues/718

**Comment by NotShige** [comment]
![notepad _2018-01-13_17-47-40](https://user-images.githubusercontent.com/20384051/34904912-e5b6dea0-f889-11e7-8bc1-5212450de2fd.png)
It should have two r's.

**Comment by monikLover** [comment]
Typos fixed as of 1/17/18

**Comment by sirunknownnobody** [comment]
![virtual girl miku speak-u - copy](https://user-images.githubusercontent.com/35646551/35201099-551451bc-fee6-11e7-98b3-21c2ef6d7737.png)

Pretty sure no one's mentioned this one, so I'll just drop this in here. It's from the discussion about Miku and virtual idols.

Something like "The love you've shown me virtually can finally become real" or "The love you've showered me with virtually can finally become real" would probably work better.

**Comment by Kenneth1994N7** [comment]
I dont see anything wrong with that sentence though....

**Comment by sirunknownnobody** [comment]
It's probably just me then ¯\_(ツ)_/¯ you can just ignore me
