### ISSUE TITLE
[Suggestion] Holidays

### ISSUE THREAD

**Issue by MikuChanAnime** [Backdash/MonikaModDev#549]
The Christmas update just released and it got me thinking, there could be a feature where during certain dates/months or something, Monika changes. Like how for Christmas, Monika is wearing a Christmas outfit with the background. Her outfit and the classroom changes on the season. I feel like this would be simple to implement because you already made anniversary dialog, so you could use some of that to implement this.

**Comment by xtosutosu** [comment]
It is already implemented in the Christmas update.
It was released 4 hours ago so you might have missed it.

**Comment by MikuChanAnime** [comment]
I know that the christmas update has already been released, but I mean this would be for other seasons and holidays

**Comment by therationalpi** [comment]
We're already planning to do more holiday content in the future, and we're even working on some engine improvements to make this easier. Look forward to it!
