### ISSUE TITLE
[Bug] Settings are still clickable while the Updater is showing.

### ISSUE THREAD

**Issue by NotShige** [Backdash/MonikaModDev#554]
Screenshot and video below.

![ddlc_2017-12-22_10-03-46](https://user-images.githubusercontent.com/20384051/34282518-e6fff070-e700-11e7-8b10-75fe1a7df9b5.png)
[Video about the problem.](https://www.dropbox.com/s/4kftf4po91tdhrx/2017-12-22%2010-07-44.flv?dl=0)

**Comment by therationalpi** [comment]
Which version are you using? This should be fixed as of version 0.6.3

**Comment by NotShige** [comment]
I'm still updating to 0.6.3. That's probably why.
