### ISSUE TITLE
Daytime Snow Animations Don't Loop (fix included)

### ISSUE THREAD

**Issue by NeonCarnivore** [Backdash/MonikaModDev#561]
I noticed the snow animations for daytime don't loop, and the snow falls up(?). Then I realized that the Window 3 & 4 animations that I submitted were not the correct resolution. Here are the corrected files. Tested and working on my copy. My apologies for the error.

![screenshot0001](https://user-images.githubusercontent.com/34461577/34299160-78326a80-e6ef-11e7-8355-c43be20b83a3.png)

[Snowing_Window_Anims_(Daytime_Fixed).zip](https://github.com/Backdash/MonikaModDev/files/1582527/Snowing_Window_Anims_.Daytime_Fixed.zip)

These files can be copy/pasted into your mod_assets folder if you want to fix the snowfall before the next update.

**Comment by Zer0mniac** [comment]
fixed animation loop :)

[SnowDayfix.zip](https://github.com/Backdash/MonikaModDev/files/1586173/SnowDayfix.zip)

**Comment by therationalpi** [comment]
No longer relevant, as the christmas decorations are no longer active.

**Comment by ThePotatoGuy** [comment]
@Zer0mniac thank you so much for fixing the snow.
