### ISSUE TITLE
How to properly install Monika After Story

### ISSUE THREAD

**Issue by heygo67** [Backdash/MonikaModDev#565]
Hi! I'm sorry, but I'm a little confused on how to properly install Monika After Story. It's probably really easy and I'm overthinking it, but every time I put the files in the DDLC game file, it never seems to work. The game either won't open or will play exactly how the game plays without the mod. Can someone explain to me exactly how to do it? Thank you.

**Comment by DarkMage3099** [comment]
Well I'm not really good at explaining, but I can try my best. First download the latest release (which is the holiday one at the moment), then when it's finished , *DO NOT EXTRACT* just open the folder, click on "monika after story 0.6.3 mod, select ALL of those files and drag them to the game file.....Sorry if that just confused you more

**Comment by ThePotatoGuy** [comment]
If DDLC doesnt open, then check `game/` for a folder like `Monika After Story`. If it is there, please take the files out of that folder and put them in `game/`. (The mod files **cannot** be in a subfolder in `game/`). Then delete the folder `Monika After Story`. In addition, delete the files in `game/cache/` to force the game to reload everything/

**Comment by heygo67** [comment]
@DarkMage3099 @ThePotatoGuy  Thank you both so much! It's working now!!
