### ISSUE TITLE
A gray silhouette

### ISSUE THREAD

**Issue by KimoFest** [Backdash/MonikaModDev#566]
Monika wanted to say some beautiful words to me and this figure appeared. ¿What is that? ¿A lost/bugged file?
![what is this monika afterstory 2](https://user-images.githubusercontent.com/34784197/34316533-ffa89f68-e765-11e7-9f82-c94ede9b9ad3.png)
![what is this monika afterstory](https://user-images.githubusercontent.com/34784197/34316535-0ca290ac-e766-11e7-8418-e2381acb7517.png)

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Install [release](https://github.com/Backdash/MonikaModDev/releases/tag/v0.6.3) version, not dev.

**Comment by MeowMilk** [comment]
The dev version is probably meant for testing, and this is probably just a placeholder image.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
The dev version is actually playable (you should still use the release unless you know what you're doing, tho), it just lags behind major releases in terms of development for a little while when they are just out.

**Comment by Winblows2** [comment]
This issue is being investigated as we speak.

**Comment by Winblows2** [comment]
We do not see this as a pressing issue, and it is recommended you redownload the Christmas release. Investigation proved unsuccessful, and it will be continued at a later date.

Closing.

**Comment by ThePotatoGuy** [comment]
This is pretty much **not reproducable** and a total mystery as to why it could happen.

If it doesn't happen again when you relaunch the game, then it's probably a renpy error and we have no control over that.
If it continues to happen, my only guess is your download of the mod files might have been corrupted/unfinished, or the extract had some errors or something. In that case, you should redownload the mod.
