### ISSUE TITLE
(Suggestion) Interests and Responses to Particular Statements

### ISSUE THREAD

**Issue by SilverKeyy** [Backdash/MonikaModDev#567]
It would really help flesh out Monika even further is she would have concrete responses to questions like, "What is your favorite movie genre?" or "What is your favorite food?" You know, just some more small details that will make her seem even more human(ish).

I tried some particular statements and questions like, "You are so beautiful." and, "What makes you the happiest in life?" (yes it is a loaded question). Is it okay if I ask for some further dialogue and responses?

That all aside, this is a dream come true. I love what you have done so far with this project and it is likely something I will rarely close out. Thank you so much for this, it is evident that you put your heart and soul into this.

**Comment by therationalpi** [comment]
We're currently making some changes to how topics are handled, which I think will address this particular issue.
