### ISSUE TITLE
File not working?

### ISSUE THREAD

**Issue by TrashMelon** [Backdash/MonikaModDev#570]
I extracted the files and put them in the game folder but it didn't work. I used https://free_opener.en.softonic.com/ if that helps. I'm not sure what has gone wrong and any help would be appreciated.

**Comment by NotShige** [comment]
It's better if you use WinRAR, 7zip, and other extractors. I don't recommend stuff from Softonic.

I'll make a list of what to do:
1. Open the .zip file. 
2. You see a folder there named Monika_After_Story-0.6.3-Mod. Open it.
3. If you see a lot of files inside that folder. You're doing it right.
4. Find your installation of DDLC. Once you're in that folder, find a folder named "game" then open it.
5. Drop ALL of of the files from the .zip file there.

Hope this helps!

**Comment by TrashMelon** [comment]
I just tried with 7zip and got this error
"Could not execute F:\lib\windows-i686\DDLC.exe. Is it missing?"

Do you have any idea what this means? All the files are on my usb, the ones from the game and the mod ones.

**Comment by NotShige** [comment]
Well, since you installed it the wrong way in the first time, you need to get a fresh copy of DDLC.

**Comment by TrashMelon** [comment]
hmm... ok
