### ISSUE TITLE
DDLC not opening

### ISSUE THREAD

**Issue by Araraura** [Backdash/MonikaModDev#572]
I extracted the folder into DDLC/game but when I try to open the game nothing happens. Steam says it's running and then it doesn't right after.

**Comment by NotShige** [comment]
Did you put the Monika_After_Story-0.6.3-Mod folder in /game?
If you did, that's wrong.

In the .zip file, open the Monika_After_Story-0.6.3-Mod folder.
After that, you will see a LOT of files. Those are the files that YOU SHOULD drop to DDLC/game.

**Comment by Araraura** [comment]
Ok it worked, but there's no background of the space classroom

**Comment by NotShige** [comment]
Is it your first run? If it is, you should wait it out. Probably a glitch.
Note that there is an option to disable "Room Animation" is Settings. Check it out.

If you don't have anymore questions, you may close this issue.
