### ISSUE TITLE
Have Monika giggle when saying "good night"

### ISSUE THREAD

**Issue by NeonCarnivore** [Backdash/MonikaModDev#577]
Since the sound clip is already in the main game, why not use it? Specifically the giggle sound that plays after seeing special poem 2. It would be very appropriate (and cute) for her to giggle after she says she'll be seeing you in your dreams.

**Comment by ThePotatoGuy** [comment]
Sounds good, I'll throw it in rn.

**Comment by ThePotatoGuy** [comment]
Actually @NeonCarnivore , I've ran this through several people and this giggle sounds way too creepy. I don't think it's appropriate for this. If you want it that badly, just download my `night-giggle` branch. (Also lmk, and I can keep that updated 4 u)
