### ISSUE TITLE
[Bug] Monika "immediately" talks about Depression after talking about Lottery.

### ISSUE THREAD

**Issue by NotShige** [Backdash/MonikaModDev#578]
Explanation and screenshot below.
![2017-12-24_18-49-56](https://user-images.githubusercontent.com/20384051/34325908-4a6f95bc-e8db-11e7-9e29-ba9bece2cc6d.png)

It appears that the Lottery topic doesn't have the "return" line at the last line. That's why Monika talks about Depression immediately (without pausing).
I would make a pull request, but I don't know how GitHub works.

**Comment by ThePotatoGuy** [comment]
This has been noted and fixed.

**Comment by antimockingjay** [comment]
I've found the same thing with the topic of Natsuki's cupcakes continuing into the topic about Monika having haters on social media.
