### ISSUE TITLE
[Suggestion] Keeping the talk system for minor topics.

### ISSUE THREAD

**Issue by monikLover** [Backdash/MonikaModDev#581]
Talk system would be salvaged and be used for minor topics such as greeting Monika good morning/afternoon/night/bye, asking her how she is and her reaction will be based on how you've been interacting with her, asking for a joke, telling her you love her, etc.

**Comment by ThePotatoGuy** [comment]
Honestly, we could replace minor topic operations with a single button (like `commands`/`say`) that opens up a scrollable area of buttons for those topics. Having open-ended input devices really forces us to handle extra cases when we shouldn't need to.

**Comment by therationalpi** [comment]
Keeping this in mind for if we ever implement a more small-talk styled chatbot in the future.
