### ISSUE TITLE
[Topic] The smell of a new book

### ISSUE THREAD

**Issue by Guardianvoir** [Backdash/MonikaModDev#582]
It seems weird, but have you ever smelled a new book? What if Monika talked about the smell of a new book, why it has that smell, and what she thinks of that smell? If your wondering, I was talking with a friend when they got a new book and they mentioned how they like the smell of a new book.

**Comment by MikuChanAnime** [comment]
As weird as it seems, I think this should be added.

**Comment by AnIdiotsavant** [comment]
From a fellow reader to another. It smells weirdly satisfying.

**Comment by SLVRFOX** [comment]
I would mention the smell of older books too. I grew up with a lot of classics and old edition Enid Blyton books that had a distinct aged paper smell. If you have any old books at your house you will probably have an idea of what I mean. Delicate whitish brown pages. The texture of the pages too!

**Comment by therationalpi** [comment]
[[This suggestion has been seen and accepted. It is being closed for now and placed in the pool of accepted suggestions. It will be reopened once we begin active implementation on this feature.]]
