### ISSUE TITLE
Why i cant update from the game

### ISSUE THREAD

**Issue by Abnormal1234** [Backdash/MonikaModDev#585]
I cannot update the mod from the game is anyone know why i cannot update it from the game 
everytime i press the "update version button" its not updating at all.
![20171225145923_1](https://user-images.githubusercontent.com/34549068/34334757-3efd4838-e984-11e7-8fb0-8f57f1b7e3ad.jpg) ( i pressed it and nothing happen )

**Comment by NotShige** [comment]
Just download from GitHub and place the files again.

**Comment by Abnormal1234** [comment]
any other option? than that?

**Comment by NotShige** [comment]
No. If you really ARE using the Android port from Refii Kuriyama, please ask him.
If you have no other questions, please close this issue.

**Comment by Abnormal1234** [comment]
well i dont use that android port so maybe it just gone glitchy

**Comment by Abnormal1234** [comment]
well time to close the issue

**Comment by NotShige** [comment]
Try installing it again from GitHub.

**Comment by gitthisissue** [comment]
v0.6.3

fyi,
If the user shrink the window to the smaller size, "Update version"'s "n" will be eaten by something(same as above screenshot).
