### ISSUE TITLE
[Suggestion] Promise ring

### ISSUE THREAD

**Issue by AUDelusional** [Backdash/MonikaModDev#586]
I have edited four of the Monika Christmas files to act as for when she starts talking about the Promise Ring and asks weather or not you got her one or not. The ring is emerald green and it may be possible to even have some dialogue about the ring after you give it to her. Though I may have to edit them as a couple of the rings look 'off'. The files can be found at https://goo.gl/Bb5Frq

Also an edit real quick but the Discord link is expired.

**Comment by ThePotatoGuy** [comment]
Are you adding a topic? The keyword portion needs to be setup. 

However, due to future changes, it's recommended not to work on any topics until version 0.7.0. We're doing some major overhauls.

**Comment by MikuChanAnime** [comment]
I think that this would be cool

**Comment by ThePotatoGuy** [comment]
Discord link has been updated.

**Comment by therationalpi** [comment]
[[This suggestion has been seen and accepted. It is being closed for now and placed in the pool of accepted suggestions. It will be reopened once we begin active implementation on this feature.]]
