### ISSUE TITLE
Change player gender after initial event

### ISSUE THREAD

**Issue by RumayChian** [Backdash/MonikaModDev#587]
I wanted to play with Monika like if I was an Oc but I cant change the gender now ... Is there a way?

**Comment by AUDelusional** [comment]
The player character is considered genderless at this point.

**Comment by RumayChian** [comment]
But still it treats me like a girl xD and i need her to call me boyfriend

**Comment by ThePotatoGuy** [comment]
Atm, no way to change gender besides a random event that occurs after some time. We'll consider the capability to do so in version 0.7.0

**Comment by JustMomo** [comment]
Hmm i had something closed for an issue like this one, oh I see it got linked.

The problem for me is the reverse, she keeps calling me her boyfriend when I am a girl

**Comment by AUDelusional** [comment]
Okay, so let's think about this real quick. If you want the game to completely reset everything then that's what you have to do, uninstall everything and then reinstall it, and other topics will appear. If you want to change it it's a random dialogue but if we tweak the code like so:

```
init 5 python:
    for key in ['changegender', 'genderchange', 'gamecorrect']:
        monika_topics.setdefault(key,[])
        monika_topics[key].append('monika_genderswapability')

label monika_genderswapability:
    m 2d "...[player]? So I've been thinking a bit."
    m "I've mentioned before that the 'you' in the game might not reflect the real you."
    m 1m "But I guess I had just assumed that you were probably a guy."
    m "The main character was, after all."
    m 1a "But if I'm going to be your girlfriend, I should probably know at least this much about the real you."
    menu:
        "So, are you male or female?"
        "Male.":
            $persistent.gender = "M"
            call set_gender from _call_set_gender_male
            m 2d "Oh? So you {i}are{/i} a [guy]?"
            m 1k "Ehehe, I suppose that makes sense!"
            m "Not a lot of girls would play a game like this."
            m 1a "You certainly come across as manly and confident. Not that I would have been terribly bothered if you answered differently, mind you!"
            m 1l "Even I can be curious sometimes, you know?"
        "Female.":
            $persistent.gender = "F"
            call set_gender from _call_set_gender_female
            m 2d "Oh? So you're actually a [guy]?"
            m 2l "I hope I didn't say anything to offend you before!"
            m 2m "Though I did suspect it a bit from the beginning... just a little!"
            m 1b "You give off a particular feeling of elegance and charm that's hard to capture with words..."
            m 1j "It's very attractive, to tell you the truth!"
            m 1a "But don't worry. Even if I might ask things like this, it's only out of curiosity."
        "Neither.":
            $persistent.gender = "X"
            call set_gender from _call_set_gender_unknown
            m 3d "You don't see yourself as a guy or a girl?"
            m 2c "That's very interesting, but I can sort of relate."
            m 1h "Like, I am a girl, but I'm also a character in a computer game..."
            m 2i "So in some ways I'm not really a girl at all."
            m 1j "But when you treat me like your girlfriend, it makes me really happy!"
            m "So I'll treat you however you want to be treated."
            m 1e"Because your happiness is the most important thing to me."

    m 1k "Remember that I'll always love you unconditionally, [player]."
    return
```

So what did I change? Well I put the code above in script_topics.rpy so instead of it only being a scripted story event that you'll get randomly you can now enter this in as a sort of "command" to force the dialogue or change your player gender. In order to achieve this I had to change the call_set_gender_(1,2,3) to call_set_gender_(Male,Female,Unknown) or else Ren'py will hate you for even attempting to load the game up. It seems to work flawlessly and should actually change the gender she calls you by. But, I'm not 100% sure on that, however it should work.

**Comment by therationalpi** [comment]
[[This suggestion has been seen and accepted. It is being closed for now and placed in the pool of accepted suggestions. It will be reopened once we begin active implementation on this feature.]]

**Comment by therationalpi** [comment]
I've decided that rather than add an extra event to change gender after the first time, I'm going to make the repair script that I've been sending people available through the FAQ's.

Please don't lie about your gender just to see what Monika will say, alright?
