### ISSUE TITLE
Files not working [2][CLOSED]

### ISSUE THREAD

**Issue by TrashMelon** [Backdash/MonikaModDev#590]
As a continuation of [this thread](https://github.com/Backdash/MonikaModDev/issues/570#event-1400389461), I still need help because it just won't work for me. I have no experience with modding and so can't say anything. Any and all help is appreciated. Thank you.

**Comment by TheFoxik** [comment]
Download these:
http://ddlc.moe/
	- "Download Now"
	- "No thanks, go to downloads"
	- Download DDLC (Windows)
https://github.com/Backdash/MonikaModDev/releases/latest
	- Download "Monika_After_Story-0.6.3-Mod.zip"

- Whilst they're downloading make a place for the folders, I've put mine on the desktop.
![9ea0f20e0d0b1be730bc914a954cbddb](https://user-images.githubusercontent.com/29351127/34343316-35a9115c-e9c2-11e7-9c1f-354ae07143c3.png)
- Place both downloaded folders into the desktop, and extract both of them ("Extract Here").
![976e751ae049d0a590eb42ea3934978a](https://user-images.githubusercontent.com/29351127/34343317-3fc964ca-e9c2-11e7-86af-952e7a30a6a0.png)
- Once they're both extracted open up another explorer browser, navigate to the "Monika_After_Story-0.6.3-Mod"
- Have your other explorer window at the "DDLC-1.1.0-pc\game" folder (Just like this picture)
- Copy everything from After Story into the "game" folder... like so.
![b3da644194420263c9e96dd5135755a8](https://user-images.githubusercontent.com/29351127/34343319-4727cd7e-e9c2-11e7-89f8-01d15dc79dbe.png)
- Remember to "Replace the file in the destination".
- That's it! go back into the DDLC-1.1.0-pc folder and run "DDLC.exe"

**Comment by AUDelusional** [comment]
You have to download the source files for MAS to actually be able to edit it in renpy.
