### ISSUE TITLE
Branching Dialogue

### ISSUE THREAD

**Issue by AUDelusional** [Backdash/MonikaModDev#598]
So I know you guys and girls are working on release 7, however I do think that as soon as possible we should get into writing branching dialogue. I've been testing it and it does work in renpy. We should also give the player more options if we're "Bringing Monika closer to reality". Here's an example of what I mean: 
![4622](https://user-images.githubusercontent.com/34827414/34350310-7a15dd00-e9d3-11e7-8a4d-9aa547f87405.JPG)

(Probably could use some better writing, I know, but this is what I have)

**Comment by ThePotatoGuy** [comment]
Yeah, many of our newer topics have been taking advantage of `menu` more often. We're all pretty aware that branching improves interactivity.
