### ISSUE TITLE
[Topic] Monika is simple webmd

### ISSUE THREAD

**Issue by AnIdiotsavant** [Backdash/MonikaModDev#599]
I just went through food poisoning and thought maybe she could have a topic about ailments. You tell her your not feeling well and she asks what hurts. It could range from headaches, stomachaches, chest pain, cramps, stiff neck, sore throat and and other common ailments. Once you type in what you're feeling, she gives you some advice on how to deal with it and she hopes it helps.

**Comment by ThePotatoGuy** [comment]
This could be a potential reason to keep #581 . 

Although I feel the scope of handling medical diagnoses would quickly grow out of control.

**Comment by LurekSelturus** [comment]
Yeah, I think we cannot give Monika, and thus, us the responsabilty of making medical diagnoses. It could really be dangerous.

**Comment by ThePotatoGuy** [comment]
Oh yeah that's true. This is clearly going to be taken seriously when it shouldn't. Good point.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I actually like the idea.
And knowing Monika, it would only be natural for her to understand that without medical education her advices could only make things worse so it would be reasonable for her not to go any further than expressing her concerns about player, trying to comfort them and advising them to see the doctor as soon as possible.

**Comment by AUDelusional** [comment]
Would something like this work. (For the record I use numbers as a basis for testing, but they are easily removable)

`init 5 python:
    for key in ['15448', 'sick']:
        monika_topics.setdefault(key,[])
        monika_topics[key].append('monika_sick')
        
label monika_sick:
    m 1i "You're feeling sick?"
    m 1i "I wish I could help but so many websites are unreliable, especially concerning sicknesses"
    m 1i "I'd recommend seeing a doctor right away, even if it's online. They have doctors that contact you through the phone and help."
    m 1i "I hope you get better soon though."
    m 1a "After all, I wouldn't want my sweetheart sick when I cross over."
    return`

**Comment by AnIdiotsavant** [comment]
I'm sorry if ThePotatoGuy thought of monika giving prescriptions. What I meant was that she could give some way to relieve the pain like if you have a stomachache, lying down, resting with a hot compress on out stomachs or something. If you got a cold, she tells you to put a cold face towel on your forehead to release the excess heat or something. Prescriptions are something a little too dangerous to give out so easily unless your a doctor or from a family of doctors.
