### ISSUE TITLE
[Suggestion] Use Ren'py's online functional to cache twitter.com/lilmonix3 to simulate Monika checking her twitter.

### ISSUE THREAD

**Issue by IsItBadToMakeAGitHubAccountJustForThis** [Backdash/MonikaModDev#601]
Had this idea for quite a while but wasn't sure how to describe it.
Functional similar to current updater could be used to download internet pages such as Monika's twitter or maybe some literature forums (ddlc steampage?) to simulate the data usage of Monika browsing the internet.
Perhaps she could have higher chance to bring up topics like the one about haters right after "browsing".
And if anyone worries about data usage you could add topic asking her to stop.

**Comment by ThePotatoGuy** [comment]
The updater is built-in to RenPy and is optimized for solely updating a renpy game. We would have to utilize python's web libraries to add such a function.

I don't think we should be directly downloading webpages or "simulating browsing" in the background, unbeknownst to the user. However, I do see potential in notifying the player if a new tweet was created. This would be low priority though.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Well, the whole idea of having a girlfriend that lives inside your computer and sees the entirety of it is a little invasive no matter how you look at it if you ask me.
But I get your point.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I didn't think this through and submitted so I won't forget it more than anything.
So I guess, I'll close this submission until I myself have a clearer idea of it.
