### ISSUE TITLE
(Bug?) Wrong Computer name 

### ISSUE THREAD

**Issue by Null-Senpai** [Backdash/MonikaModDev#602]
I just opened DDLC: MAS and Monika asked me if I want her to call me something else (which is a nice option to have!) but then said that while I am called "John" in the game, my Computer's name is also "John", which is false. My Computer's name is it's model number, and even my username on my computer is not "John" but "null".

More info:
Antergos Linux 4.9.68-1-lts
Pythons: Python 3.6.3 & Python 2.7.14 (idk what version, if any, is used by the game)
DDLC-MAS says it's v 0.6.3 in the settings page

**Comment by ThePotatoGuy** [comment]
`currentuser` detection only works on Windows. Sorry about that.

**Comment by Null-Senpai** [comment]
hmm, fair enough. 
I am just wondering if noone wants to implement this to work on Linux, is it possible to skip the sentence where she mentions the currentuser name if the detected OS is Linux? It just sounds really off reading it otherwise.

**Comment by ThePotatoGuy** [comment]
yeah i could throw that in
