### ISSUE TITLE
Thinks I have 2 different names but they're the same

### ISSUE THREAD

**Issue by ethancedrik** [Backdash/MonikaModDev#604]
I didn't seem to have this issue before, but I'm now getting messages stating that I have 2 different names, the names it gives me are "Ethan" and "ethan". 

In the final completion of the main game Monika always called me by "Ethan", with the first letter of my name capital like I entered it. I assume the game was able to determine that they were the same.

I am signed into a Microsoft account, and even though my name on my Microsoft account starts with a captial "E", my C:\users folder has my name starting with a lowercase E, and I tried changing my name in game through Monika and it stated that it was the same.

For some reason Monika After Story believes that I have 2 different names even though they are the same, and I'm not even sure if I can easily fix that. This may be a new occurrence as well given I'm just now seeing it

**Comment by ThePotatoGuy** [comment]
Are you getting this issue when displaying the `pen name` topic?

**Comment by ThePotatoGuy** [comment]
Okay well, I'll just push the fix for pen name

**Comment by ethancedrik** [comment]
Sorry about the delayed response, yeah
[image: Inline image 1]

It happens in that topic

**Comment by ethancedrik** [comment]
Sorry about the delayed response, yeah
[![https://gyazo.com/cc928726f4580f1c60e85374005358bd](https://i.gyazo.com/cc928726f4580f1c60e85374005358bd.png)](https://gyazo.com/cc928726f4580f1c60e85374005358bd)

It does happen in the `pen name` topic.

**Comment by ThePotatoGuy** [comment]
alright good, just fixed that.
