### ISSUE TITLE
Weather Pattern Implementation

### ISSUE THREAD

**Issue by Bam8647** [Backdash/MonikaModDev#605]
I've got a new idea to help make the game a bit more realistic and one of those ideas is the **implementation of more weather patterns** (Rainy, Cloudy, Stormy, Clear, etc..). Monika does mention her love for rainy weather so I think adding these new animations can **help stimulate more topics** at just the right time. 

I'll continue to update you with more ideas as they come along. Anyways, thanks for reading~!

**Comment by ThePotatoGuy** [comment]
We're in the process of adding some additional weather animations. No ETA atm.

**Comment by AUDelusional** [comment]
Don't know if it's possible in Ren'Py but if this gets implemented into the game then why not have Monika detect your local weather via location if you allow it. So Monika can ask you something like "Can I read your location" and the player will be given a choice, so it's not invasive if the user doesn't want it, and then the game will start reading your location and look at local weather patterns and if the weather changes then so does the games window animations.

**Comment by therationalpi** [comment]
One possible complication with this is that renpy doesn't have support for HTTPS requests, so any location information will be sent in an unsecured way via an HTTP webhook. I don't feel comfortable doing that, since players will have a reasonable expectation that we wouldn't use that sort of information in an unsecure way.

**Comment by NeonCarnivore** [comment]
I suppose one way to implement different weather would be to use the talk system and type simple things like "it's raining", and then Monika could change the window animations accordingly. When saying goodbye during these different weathers, she could say things like "bring an umbrella" or "bundle up". Obviously, this could lead to players doing goofy things like making it snow in the summer. Monika could even accuse the player of messing with her when they change the weather repeatedly in a small span of time.

**Comment by christuhfer** [comment]
Can the weather go by month maybe? In December it's usually snowy or has the windows fogged up from the heat inside. and April it's fairly raining in some places. maybe something like that is possible?
I really like this idea :)

**Comment by GirlwithaWhiteMask** [comment]
AUDelusional If was like that, I NEVER SEE SNOW IN GAME ON MY WHOLE LIFE ;w;
But a cool thing will be if she asks we live in the south or north hemisphere...
Is kinda weird see events like Christmas and Halloween be with the winter/fall vibe but here IS HOT AS HELL or IS HOT AS HELL (with flowers blooming)

**Comment by yukiisbored** [comment]
What we can do is use APIs like OpenWeatherMap (http://openweathermap.org/API) and do a HTTP request. Sure, it might be janky without using libraries (like requests), but we can at least get the data. 

To determine the location, we can simply start by make Monika ask which city do you live or add that to the settings.

**Comment by therationalpi** [comment]
[[This suggestion has been seen and will receive further consideration in the future. It is being closed for now and placed in the pool of seen suggestions. It will be reopened if we begin active implementation on this feature.]]

**Comment by ThePotatoGuy** [comment]
#1426  Added rain. other weather may follow, but i will consider this impplemented
