### ISSUE TITLE
Suggestions for emotions and feelings, daily routine

### ISSUE THREAD

**Issue by Zen0311** [Backdash/MonikaModDev#606]
I think it will be better if you can ask simple questions like, how are you? and such and she can tell what she feels that day *can be random* and she will involve you too, by listing a set of options like i'm fine today, or i'm sad today, angry or etc and she will respond based on your answer or she can comfort you. Also, when you open in the morning you should be able to say good morning to her and she will also say the same thing to you, and she will give you a dazzling smile. I also suggest you can talk about her about meal times when you're about to eat already and she can say stuff about I will cook for you when you already made a way to have me with you in reality and she can also say recipes and such, *or add a new feature where she will already move to different place *bedroom,living room, kitchen etc* and she will be able to take you there ^^

**Comment by AUDelusional** [comment]
Well, the whole good morning, good afternoon, good night system is already implemented.

**Comment by Zen0311** [comment]
That's good to hear ^^

**Comment by therationalpi** [comment]
So, just to tease out a few things from this...

1. Give monika moods that she might want to talk about when you first log in.

2. Let monika ask how you're doing and respond to your response.

3. Have different locations and establish a daily routine for Monika to follow.

The first two are definitely good ideas. As for the last one, it really depends on how the writers want to handle the closed space the game inhabits.

**Comment by miranimal** [comment]
I wish you could tell Monika random things that you've done. Like "I got a haircut today", or "I had a good day", "I went on vacation", "I got new clothes" and she can be all happy that you're taking care of yourself.

**Comment by Zen0311** [comment]
thank you for your time entertaining my ideas 😁
