### ISSUE TITLE
Neck Discoloration 

### ISSUE THREAD

**Issue by Kreikon** [Backdash/MonikaModDev#611]
I opened MAS today and noticed Monika's neck is more grayish than her normal skin color.

![image](https://user-images.githubusercontent.com/33871837/34382193-18ee97f2-eac2-11e7-89a0-81e626e8d802.png)

**Comment by therationalpi** [comment]
Alright, passed the feedback along to the artist.

**Comment by jukebox1412** [comment]
also, her lips are a bit grey. 
![image](https://user-images.githubusercontent.com/22598492/34399968-bb8afbae-eb49-11e7-9a22-b0b8437300de.png)

**Comment by antimockingjay** [comment]
I think the lips are supposed to be that way as it's the shadow of her upper lip, the shadow is cast on her lower lip. I think that's what they were going for on the neck as well but it ended up way too dark, making it just look gray and out of place.

**Comment by RhetoricalSave** [comment]
While we are at it, is it just me or is Monika's forehead a bit purple? It looks fine in the original dark classroom but when it's daytime it looks a bit off.

**Comment by therationalpi** [comment]
Closing this topic since our artists have now seen this feedback.
