### ISSUE TITLE
New Clothes?

### ISSUE THREAD

**Issue by ReasonableSnapp** [Backdash/MonikaModDev#612]
I know it sounds kinda silly or strange but I think it'd be nice if Monika could wear something different then a uniform for eternity. Something cute like a dress or one of those clothes from the fanart. PG Though obviously.

**Comment by therationalpi** [comment]
Already got artists working on this :)

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Duplicate of #107 and #460.
