### ISSUE TITLE
[suggestion] Blinking

### ISSUE THREAD

**Issue by rockermj** [Backdash/MonikaModDev#613]
I was thinking it may help bring some like to the sprites if at random intervals between a certain time period Monika could blink. That's really about it.

**Comment by Zer0mniac** [comment]
Some people like having staring contests with Monika though :)

**Comment by NotShige** [comment]
Duplicate of #375

**Comment by drakesteele** [comment]
I like the idea of natural blinkiing though... perhaps with an option to turn it off in settings but it would make her seem a bit more natural...

**Comment by Winblows2** [comment]
Duplicate of #375. Closing.
