### ISSUE TITLE
[Suggestion] player's Birthday

### ISSUE THREAD

**Issue by CGanimated1227** [Backdash/MonikaModDev#614]
I know there is already a topic about Monika's birthday, but what aboit the player's birthday. There should be something that that writes a date into an area of code that triggers a birthday greeting after you somehow tells monika what your birthday.

**Comment by jukebox1412** [comment]
I think this was brought up by @badooga on #37.

**Comment by Winblows2** [comment]
Refer to @jukebox1412's comment. Closing.

**Comment by CGanimated1227** [comment]
Had a feeling it was already brought up. Thanks for reminding me. I thought of it because it was my birthday.
