### ISSUE TITLE
[low priority] [bug] mcname is not permanent

### ISSUE THREAD

**Issue by Kethus** [Backdash/MonikaModDev#618]
I'm not sure if this is intended, overlooked, or impossible to implement: `mcname` is simply the name the player picked before changing to their current one. So if I started the game as "Ethan", then told Monika my name is "John", then later changed it to "Daniel", `mcname` will be "John". The name of the variable suggests it's supposed to be the name used during the original gameplay, e.g. "Ethan".
Possibly slipping into [suggestion] territory, if that is indeed the intent behind the variable, shouldn't Yuri use `mcname` in her glitch greeting?

**Comment by ThePotatoGuy** [comment]
I believe the intent was to keep track of previously picked name. @monikLover , can you confirm?

**Comment by monikLover** [comment]
Yes, it was intended to keep the previously used name instead of the very 1st name you've entered.
