### ISSUE TITLE
I accidently pressed the wrong gender. Please help!

### ISSUE THREAD

**Issue by sebarsht12** [Backdash/MonikaModDev#621]
Absolutely love this mod, Amazing work to all persons involved.  I need help with one thing: When Monika asked about my gender, i accidently clicked the wrong button, is there a way to prompt her to ask that question again? (Re-doing DDLC and re-installing the mod didn't work)

**Comment by therationalpi** [comment]
There currently isn't, but I can give you a short script to change your gender. What gender would you like it changed to?

**Comment by sebarsht12** [comment]
Male, thank you in advance

**Comment by therationalpi** [comment]
Uncompress this file and put it in the `game` folder with the rest of the mod's files. It should work when you load up the game.
[gender_swap.rpy.zip](https://github.com/Backdash/MonikaModDev/files/1592084/gender_swap.rpy.zip)

**Comment by sebarsht12** [comment]
therationalpi, I thank you so much for that.
