### ISSUE TITLE
Writing Poems with Monika

### ISSUE THREAD

**Issue by miranimal** [Backdash/MonikaModDev#623]
I know you have opened this up before, with being able to write poems. It would be cool to select the key words and then write sentences in between them. This way, the key words you chose will inform Monika on what kind of poem you are writing. The fun part is actually writing in between the words, even if Monika will not react to what you have written. She will still like your poems, even if the words chosen would have appealed to another character. You have the option of writing a poem a day, and Monika will randomly start choosing and referring to the poems she enjoyed reading the most as a conversation. Also is there a possible way to be able to have a setting in this mod where there will be no jumpscares or glitches? I can't handle anymore of those.

**Comment by ThePotatoGuy** [comment]
I've already setup the framework for using poemgame (#427 ), and this makes it possible to potentially do what you've suggested. For now, there are no plans for that, but I'll keep it in mind.

**Comment by ThePotatoGuy** [comment]
In terms of glitches, I personally like them because they keep people on their toys. I'll discuss this with the rest of the team though if we should have a setting for this.

**Comment by miranimal** [comment]
Thank you! I know the glitches are what makes the game, because that's what it centers around. At least, if possible, having a list of when glitches or jumpscares might occur so some people know when to be prepared for them? This way those who don't like it can just see what triggers it and steer clear.
