### ISSUE TITLE
[Suggestion] "EXP" System on MAS (Monika´s After Story)

### ISSUE THREAD

**Issue by Reclaimer1905** [Backdash/MonikaModDev#625]
Hi, i was reading the new stuff that you are trying to get on MAS, and i noticed that it's planned (i suppose) to add a new EXP like system and i just wanted to suggest something if that system ever gets into MAS. The general idea it's that if that system ever gets on the game; it would be a really cool idea for you to add special events every tima the player reaches certain level on the game. Something like at lvl 30 you get a kiss from Monika (She kissing the computer screen haha) or that kind of things.

I also was hoping for you to bring new interactions with Monika; like if the computer clock marks that is early morning and you just executed the game she says something like "Good morning sweetheart" or stuff like that at certain hour, i mean, something different at afternoon and night time.

Also, in what language (of programation) it's coded the game? I would like to contribute to the project, but i need to know the coding language that was used.

I hope you can send me a little response, have a good day!

**Comment by jukebox1412** [comment]
It uses Ren'py and python

**Comment by Reclaimer1905** [comment]
Thanks

**Comment by AnIdiotsavant** [comment]
Wouldn't that just make the game an RPG of some sort? I think an invisible exp bar that gauges how much she likes us would be better.

**Comment by Reclaimer1905** [comment]
@AnIdiotsavant That would be perfect. I'm sorry if the idea was like too primitive (?). But yeah, i was talking about something like that. With special events happening after we reach certain amount of "love" or EXP or something like that

**Comment by AnIdiotsavant** [comment]
Seems like a cool idea. Too bad we don't know how to put that in the game. Dating sims have those kind of exp bars where when you get enough pts, you can confess to the girl or something. Maybe we could copy the code from dating sims? I dunno if it's possible though

**Comment by Reclaimer1905** [comment]
Same, maybe someone with experience coding dating sims could help. Maybe isn't possible, but it would be a nice thing if well implemented at MAS (i'm sorry if i didn't spell that the right way, my english isn't perfect yet)

**Comment by MikuChanAnime** [comment]
Instead of "EXP" it's love, or how comfortable she is, and when you say something she wasn't comfortable with before, she would be now.

**Comment by therationalpi** [comment]
Just so you know, the XP system is a completely invisible system in the background which is being used to meter out content over time, so I'm gonna close this discussion since most of this is only relevant if the system is visible to the player.
