### ISSUE TITLE
ch30_nope

### ISSUE THREAD

**Issue by jukebox1412** [Backdash/MonikaModDev#626]
In script-ch30.rpy under label ch30_nope, i feel like the if else statements should be switched since if you've rejected monika, you would get a way softer reaction then if you hadn't. Dunno if that's actually how the code works though. Also the part after the if-else statement refers to something that only occurs in the else part: 3h "If you do that, I won't stop at just deleting one directory next time."

**Comment by ThePotatoGuy** [comment]
`rejected_monika` is set in `script-introduction` when you _dont_ say you love her. If you've already rejected her, it makes more sense for her to dismiss your deletion of her character file as trivial. If you said you loved her, the impact of you deleting her file would be greater.
