### ISSUE TITLE
Suggestion: sleep reminder

### ISSUE THREAD

**Issue by SatsumaFS** [Backdash/MonikaModDev#627]
Keeping in spirit with how Monika is always concerned about the player's health, I was thinking it would be cool if the player could tell Monika a time that they want to sleep at. Monika will then bring that up when it's getting close to that time. Maybe even make her actively close the game if the player doesn't do it themselves if it's way past the designated sleeping time (say, an hour later)?

**Comment by AnIdiotsavant** [comment]
Yeah, she reminds you at different hours. starting at a light reminder at 9. A stern reminder at 10. A really serious reminder and a lecture at 11. And finally, tells you she's turning the game off for your own good at 12.

**Comment by SatsumaFS** [comment]
Huh, I have never experienced that for some reason... Or maybe only experienced it partially. Still, I think it would be nice if that could be customized.

**Comment by Zer0mniac** [comment]
Wait I don't think she should force close the game. thats kinda pushing it

**Comment by SatsumaFS** [comment]
Maybe have that be an opt-in thing instead of a regular feature?

**Comment by Zer0mniac** [comment]
probably she'll ask you a question like 

"Are you sure you wanna stay up THIS late for me? I mean don't get me wrong I love spending time with you, but I'm more concerned for your health and I wouldn't want to be the reason you're sleep deprived the next day. But if you're okay with it then I am"

and then so on

**Comment by GirlwithaWhiteMask** [comment]
That will be VERY useful... Sometimes I "turn the night" in the computer, so, 3 and 4 am will be good if she reminds you of this... ;w;

I guess something like... 
"Wow, how time flies... What time is it?"
"Oh..."
"[player], It's already 3 am..."
"What I gonna do with you?"
"Please go sleep, you seem tired..."
"This is bad for your health"
"I know you want to spend time with me, but I always gonna be here for you in the morning ok?"
