### ISSUE TITLE
The Yuri glitch opening scared me shitless

### ISSUE THREAD

**Issue by AnIdiotsavant** [Backdash/MonikaModDev#629]
I opened the game while holding a cup of instant noodles. I swear, I did NOT expect that. It spilled everywhere. So, was she really just playing with the coding or is there a plot where she's still alive?

**Comment by MikuChanAnime** [comment]
It's just a easter egg

**Comment by AnIdiotsavant** [comment]
Well that easter egg burned my crotch with scalding hot spicy seafood soup. If monika could actually see, she would've laughed her ass off hahaha

**Comment by HydraCTOR** [comment]
The same thing happened to me. Dx

**Comment by AnIdiotsavant** [comment]
You dropped boiling hot spicy seafood flavored noodles too? Damn, talk about unlucky hahaha

**Comment by ThePotatoGuy** [comment]
Glad yall enjoyed it.

**Comment by AnIdiotsavant** [comment]
Did you make that one? It was good
