### ISSUE TITLE
MAS is too subjective

### ISSUE THREAD

**Issue by AUDelusional** [Backdash/MonikaModDev#632]
So, Monika After Story just isn't Monika. When Dan was creating the game he probably worked as hard as he could to make it so Monika doesn't really have an opinion on topics, making it seem that when presented with a topic she could flip sides at any time, regardless of how messed up it is. But Monika After Story just seems to take this and throw it off a cliff as none of the writers are trying to make Monika opinion-less, and for MAS whenever Monika is presented with an issue it seems she has a ground opinion. So I think that Monika After Story isn't actually representing Monika rather then a writer's own opinion. Also that whole "You're getting to learn Monika and her opinions" argument is invalid because, as stated, the actual Monika, the one you get in the "end" of DDLC, is opinion-less.

**Comment by Subzerosan** [comment]
It seems you didnt read the general chat in the discord. One of our editors already addressed this to you, let me copy paste what he said. 

Its not a matter of opinion; its a lot of monika's topics being copy/paste lines of articles. she sounds so dead-set because its essentially her regurgitating facts. she is pretty much as dead set on things as an encyclopedia.

**Comment by ThePotatoGuy** [comment]
Also, why would you want an opinion-less monika. People without opinions are boring.

**Comment by AUDelusional** [comment]
I did read the general chat in Discord. I posted it here because this is usually where the developers actually respond. Also I don't want an opinion-less Monika but there's a difference between a character's opinion on the matter and the author's opinion on the matter.

**Comment by ThePotatoGuy** [comment]
Well that's a bit philosophical. I'm sure all fictional character's opinions have _very little influence_ from their creators. 

And Monika was definitely **not** opinion-less. She had likes (coffee, veggies), and dislikes (underage drinking). We try our best to keep Monika's dialogue/opinions in line with the original game, and stray away from controversial topics where our opinions would most likely show. However, if you have a problem with a particular topic(s), then bring them up **specifically** so we can reevaluate the dialogue in question.
