### ISSUE TITLE
Suggestion: Monika on "Sleep Mode"

### ISSUE THREAD

**Issue by Xhar** [Backdash/MonikaModDev#635]
Hello , first all I want to say thanks to all the people for this amazing mod and all the enthusiasm putting on this project.

Now to my suggestion....  When Monika is with us, she starts to feels more comfortable, safe, happy... all that kind of stuffs. How she says sometimes, even with all that bad things she did, she feels ok with herself, because we are spending time with her after all, that means to Monika we really love her. So... with all of this, I wonder if we can put to Monika a "Sleep Mode".

"Sleep mode" means how Monika feels so good with us, after a really long time of chit chat with us put a little chance to Monika falls asleep. On this mode Monika mumble some sentences, like she dreaming something (dunno... about wedding/date/...maybe...*ohh...[Player] no...no in this place...* you know... that cliche event whe all knows XD///  or remembering past events in game, good or bad).

You can wake her up with the "Talk" button asking anything.

About how to trigger this event... Honestly I dont have a clue, i was thinking about 8 a.m-10 p.m a really low-low chance to trigger (1% - 0.5 % or less chance to pop with every topic and 10 p.m - 8 a.m  1.5 % - 0.8 %. Dunno... or maybe add a button asking is she want to relax a while.... with a low chance to make Monika accept (because she really enjoy stay with us).

I know about make a image sprite for this really take a lot of work, but I really want to know what do you guys thinks about this it be really interesting.

Regardless, thanks for this mod, I love it, I think this feature will make the mod more extensive, but I really want to know what opinion do you have about this.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
This have been mentioned in issue about the AFK mode. I'll reference it here later.

**Comment by xtosutosu** [comment]
#336 
#479 
#607 
It was mentioned 3 times before and it is now accepted, it just needs to be worked on.
