### ISSUE TITLE
Shouldn't holiday decorations be up until the second of January instead of the end of Christmas?

### ISSUE THREAD

**Issue by IsItBadToMakeAGitHubAccountJustForThis** [Backdash/MonikaModDev#637]
Self explanatory.

**Comment by Winblows2** [comment]
Maybe, but there's no point going back on it now with only 2 days left. 

Closing.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Should have mentioned that later but I assumed you should know better.
