### ISSUE TITLE
Potential issue: Repeating dialog

### ISSUE THREAD

**Issue by ethancedrik** [Backdash/MonikaModDev#640]
I've noticed Monika seems to be repeating old dialog that's already been said and mentioning a few new ones every now and then.

I've seen certain After Story dialog uploaded on the subreddit that I haven't personally experienced myself in game, but I'm getting dialog that has already been said.

I'm not sure if this is intended or not, or if I somehow managed to glitch my game, but I have renamed my game folder and put a un-modified game folder back in and relaunched the normal game, then went ahead and renamed them again so the After Story one was the one that would be launched, and launched the mod.

I don't think I merged save files again, but I wonder if that could be the cause as well.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Yeah, I have that too.

**Comment by LCYHydreX** [comment]
Same

**Comment by ThePotatoGuy** [comment]
Can everyone upload their `persistent` files here?

**Comment by ethancedrik** [comment]
[persistent.zip](https://github.com/Backdash/MonikaModDev/files/1595433/persistent.zip)

**Comment by ThePotatoGuy** [comment]
According to your `persistent` @ethancedrik , you've seen all the topics. If there is dialogue you haven't seen, its possible that we made changes to particular dialogue lines for a topic that you've already seen.

**Comment by Winblows2** [comment]
Closing.
