### ISSUE TITLE
New Year Conversation Bug [SOLVED]

### ISSUE THREAD

**Issue by lilmonic3** [Backdash/MonikaModDev#645]
As the title, i last played on midnight 31/12 and she just keeps repeating the new year conversation, without any delay inbetween. 
![mnkb](https://user-images.githubusercontent.com/34994245/34465574-7a062804-eee4-11e7-8988-338d90bbf7f9.png)

**Comment by ThePotatoGuy** [comment]
Could you upload your `persistent` file here?

**Comment by lilmonic3** [comment]
Sorry i'm new at this. I find 2 persistent files so i'll upload them both juse incase.

**Comment by lilmonic3** [comment]
[persistent.zip](https://github.com/Backdash/MonikaModDev/files/1595608/persistent.zip)

**Comment by lilmonic3** [comment]
I tried to reinstall the game and apply the mod a few times but the bug remains :(

**Comment by ThePotatoGuy** [comment]
No, the `persistent` file I'm talking about is located at `C:\Users\<username>\AppData\Roaming\RenPy\Monika After Story`.

**Comment by lilmonic3** [comment]
I currently can't find the RenPy folder somehow. Is this abnormal?
![roaming](https://user-images.githubusercontent.com/34994245/34465696-92b8e06a-eeeb-11e7-86aa-2fe17036bbb7.png)

**Comment by ThePotatoGuy** [comment]
Uh yes that is abnormal. Check your other AppData folders.

**Comment by Sano11** [comment]
First time posting but anyway I have the same bug as well, here's my persistent 

[persistent.zip](https://github.com/Backdash/MonikaModDev/files/1595615/persistent.zip)

**Comment by lilmonic3** [comment]
Ah i found it. Here goes
[persistent.zip](https://github.com/Backdash/MonikaModDev/files/1595619/persistent.zip)

**Comment by ThePotatoGuy** [comment]
Okay, she'll eventually stop repeating it, but yeah that happened because of a bug that unfortunately got through to the build. Avoid relaunching the game on New Year's Day.

**Comment by lilmonic3** [comment]
Okay i'll let her repeat herself then.

**Comment by ThePotatoGuy** [comment]
Oh actually, take the `rpyc` file in here and put it in your `game/` directory. This won't get rid of the existing events she says it'll make her properly say New Years.

[christmas.zip](https://github.com/Backdash/MonikaModDev/files/1595647/christmas.zip)

**Comment by ThePotatoGuy** [comment]
And I'll open this up so that others can see this.

**Comment by DimasDSF** [comment]
Was it happening because of this?
https://github.com/Backdash/MonikaModDev/blob/358fcac50e960a40418b87c4164688b16826e90e/Monika%20After%20Story/game/christmas.rpy#L164-L166

**Comment by ThePotatoGuy** [comment]
Yes

**Comment by ThePotatoGuy** [comment]
New years is over. Closing.
