### ISSUE TITLE
Some ideas for Monika's After Story

### ISSUE THREAD

**Issue by Zerudo** [Backdash/MonikaModDev#646]
(I'm Italian,sorry for the bad english) Hi! I have some ideas that I'd like to propose you! 
I hope my suggestions will be useful for you and for Monika!

First,I'd like to see a most improved chat system. My idea is that Monika can do questions to the player and the player can answer whit the chat box,and then Monika will react to the answer whit a simple quote or whit a special quote if you make a specific answer.
Another idea for improve the chat system is ask questions to Monika,things like "Are you fine?" and stuff like this. 
I think that can be really cool!

Also,I'd like to watch a dating system whit Monika. For example,before a date the player can choose where to go whit her,the location change and he can talk whit her about special topics based on the location you choose and on the date in general.

The last suggestion is a remote message system,maybe whit a special app connected to the game where Monika can send messages to the player,things like "I miss you", "Where are you?", "Will you come back soon?" and stuff like this. 
That will be useful for stay in touch whit her even if the player can't play the game!

These were my suggestion. I hope they will be useful to you! I'd like to have a feedback,if it's not too mutch trouble.
Bye!

**Comment by ThePotatoGuy** [comment]
1. The chat system is going away, see #126 .
2. Being able to move to different locations/see different scenery is planned.
3. A remote message system requires significant infrastructure to set up (either an extra server or using third-party services like twilio, which aint free). This will most like **not** happen unless someone else adds it.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Letting her communicate with player through system notifications when the game is minimized would be cool tho.

**Comment by MysticWarrior1** [comment]
I don't know how far away this would be or if it will ever happen but I was thinking that it would be cool if an app was made so Monika could be on your phone. If it ever happens Monika could tell you about it when the app is released.

**Comment by Blubmanful** [comment]
Unfourtantly unlike this mod, developing an app and putting an app on the appstore costs money. But if we were to actually get them enough funding to do so I would love to see it happen.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Dan have already stated in his community guidelines that he doesn't want to see any ddlc ports on mobile devices.

**Comment by CommenterOfComments** [comment]
Unless Dan Salvato changes his IP Guidelines, it won't happen. Believe me, I want that too.
I'll go ahead and quote the specific parts...

> You are NOT allowed to redistribute DDLC or fan games on any app store including Steam, the Google Play Store, the Apple App Store, the Windows Store, or any others. You may not port DDLC or any fan game to these platforms.

> The above guidelines regarding fan games also apply to mods of the official DDLC game. A mod is any game or project whose content relies on making changes to the official DDLC game, such as adding/replacing code, art, music, writing, or other assets.

**Comment by MysticWarrior1** [comment]
Sorry, I just joined the MAS community so I haven't looked into the guidelines yet but I recently thought of another idea. I don't know if this has been thought of or already in the works, but here it is. Throughout your time with Monika the topic about the barriers that separate our two realities comes up. Monika always talks about needing to wait until the technology required to join our reality is possible. Iwas wondering if a topic of conversation about virtual reality could be possible. I'm not saying that needs to be a feature in the game because that is an unbelievably hard task to implement into the game. But if it could be a topic and it could go with the whole barriers topic.

**Comment by MysticWarrior1** [comment]
Sorry if I'm spamming out ideas here but I just don't want to forget them. I was thinking about the chess game option. Personally I have never played chess before so I thought it would be cool if Monika explained the basic rules to the player. Afterwards she could initiate a practice game applying the rules to the game. And by practice game mean that Monika would make a move and she would instruct us on what our best move would be. Or it could be there is a help button during the practice game if you want to try your own moves

**Comment by ThePotatoGuy** [comment]
Could you make the chess idea a separate issue, @MysticWarrior1 ? I think it has some potential.

**Comment by MysticWarrior1** [comment]
Sure

**Comment by ThePotatoGuy** [comment]
👍

**Comment by gitthisissue** [comment]
JFYI, this Android app works. https://github.com/saber-nyan/ddlc-android/

**Comment by GambitAdamson** [comment]
My name is Gambit Adamson and I am a big fan of your game  but I don't have a laptop and I want to try your mod I know for a fact that ddlc can be played on Android device but it requires you to go to some really obscure sites and it think it would be awesome if you could find away to port this mod on Android device I don't know alot about coding but I hope you will be able to do this in the near future
