### ISSUE TITLE
Discord link?

### ISSUE THREAD

**Issue by LikeTheRogue** [Backdash/MonikaModDev#648]
Hello! I just downloaded this mod and love the idea behind it! I'd really like to contribute to the project but it seems the existing Discord link is down. Would I be able to grab a newer/updated invite to the server? Thanks!

**Comment by ThePotatoGuy** [comment]
We had some server mishaps so invites are closed at the moment. We'll let you know when they're back up. 
Thanks for your patience.

**Comment by LikeTheRogue** [comment]
Cool, thanks!

**Comment by ThePotatoGuy** [comment]
@LikeTheRogue , new discord link is up. Thanks for your patience.
