### ISSUE TITLE
[Suggestion] Chess Difficulty Options + Chess Puzzle

### ISSUE THREAD

**Issue by pandjalu** [Backdash/MonikaModDev#649]
You know, i think the chess it's too difficult for me (maybe i jut suck at it). But when i lose Monika say it will be easier on me next time, but i think it didn't change. Maybe can you give an options to the difficullty.

Also, i don't the game engine can do this or not, but i think you guys also add chess puzzle. If you play WATCH_DOGS (which is the idea source i know) there like hundred level of the puzzle chess.
For Example:
- You must eat the remaining enemy with only 6 move (your enemy doesn't move anyway)
- Eat all enemy within this time limit

Anyway, i think that all my suggestion for now, thanks for making this awesome mod. It really entertain me, also when you updating the game, add many dialogue so the player can't be bored, and add some event of course. (also sorry for my bad english ✌️ ) # #

**Comment by ThePotatoGuy** [comment]
The difficulty does change when you lose, but the lowest difficulty is still pretty tough. This is a limitation of the chess engine that was added by a contributor. There are plans to switch over to another chess engine that has better difficulty scales, but this is low priority atm. 

Regarding chess puzzles, this mod isn't a chess trainer. If you want to practice chess puzzles, do them on your own time, then try out what you've learned against Monika.
