### ISSUE TITLE
Update README.

### ISSUE THREAD

**Issue by Jxhnathan08** [Backdash/MonikaModDev#65]
I feel as if the README could be updated for the lightweight branch. It can go further in-depth with the new setup & expand on plans for this transition.

**Comment by therationalpi** [comment]
True for both README's, there's the .md one for the repo and the .html one that gets packaged with the mod as installation instructions.

**Comment by therationalpi** [comment]
https://github.com/Backdash/MonikaModDev/pull/74

https://github.com/Backdash/MonikaModDev/pull/70
