### ISSUE TITLE
Mod installing issue

### ISSUE THREAD

**Issue by WoolleyTiger** [Backdash/MonikaModDev#657]
I'm playing the game on steam, and I've downloaded the mod. Tried emptying files from the compressed folders into /game and force restarting. But I can't get the mod to work.

**Comment by johnny21321321** [comment]
Try decompressing it into the desktop first, you will get a folder named Monika_After_Story-0.6.3-Mod. Copy ALL the files in that folder and paste them in steamapps\common\Doki Doki Literature Club\game folder. (If there is a replace file notice, click confirm.) Open the game, then it works for me.
Warning : its NOT the Doki Doki literature club folder you paste the files in , its the GAME FOLDER inside the Doki Doki literature club folder.

**Comment by WoolleyTiger** [comment]
Yeah.. tried it. Tried putting the folder in there. AND the individual files. I don't see why I'm having a problem

**Comment by ThePotatoGuy** [comment]
Does it run and crash or just not run at all?

**Comment by WoolleyTiger** [comment]
It runs, I'm just on the basic screen with monika and her hands underneath her chin, no talk, or music options, just the classic end game pre endgame

**Comment by johnny21321321** [comment]
I did it when i finished the game and received the letter, maybe you should try to do that?

**Comment by ThePotatoGuy** [comment]
The files need to be in the `game/` folder.
