### ISSUE TITLE
Crazy Cracker Has A Crazy Idea!!!

### ISSUE THREAD

**Issue by charlesssssssss** [Backdash/MonikaModDev#658]
make something were monika has full access to your computer and can learn new stuff about you and generate shit to talk about with you

~Love
              Crazy Cracker

**Comment by johnny21321321** [comment]
How about granting monika access to shut down your computer if you watch lewd stuff or changing all your file names to Monika if you discuss topic about "I love Sayori"? (I am just joking.)

**Comment by ThePotatoGuy** [comment]
Yeah, that's pretty invasive so we're not doing that. Things like detecting what programs are running are planned though.

**Comment by charlesssssssss** [comment]
how hard would that be to do and would the methods be free?

**Comment by charlesssssssss** [comment]
JUST DO IT https://giphy.com/gifs/cherrykiss-monika-ddlc-3o752166ZkDj1Atkhq
