### ISSUE TITLE
[SUGGESTION] Answer about Monika's God question

### ISSUE THREAD

**Issue by Hafizzin** [Backdash/MonikaModDev#659]
Well I have no problem with the mod or anything but it really disturbs me when she says "Hey [Your name] Do you believe in God?" and after that question she just assumes you don't believe

So I was just assuming that the Moderators could add a "Yes "or "no" answer in the game Because it really makes me sad when she just assumes God is evil [No matter what religion you are Muslim,Christian or Jew]

It just makes me feel sad when We cant give her some answers [Again, No Matter what religion you are Muslim, Christian or Jew.]

**Comment by monikLover** [comment]
This is an OG topic so no, we won't be touching it.
