### ISSUE TITLE
Keyword Problems

### ISSUE THREAD

**Issue by Guardianvoir** [Backdash/MonikaModDev#66]
By definition, this isn't a bug, but it's still a problem I have with the talk feature. Whenever I say "you" in any context (except for one which I'll explain in a bit) Monika will give the "What else is there to say about myself that you don't already know?" speech. This happens when I say stuff like "thank you", "you are a great person" and sometimes even when I say "I love you". Sometimes she'll say "I love you too" but other times she'll give the other speech.

Another problem with the Talk feature I have is saying goodbye. The only way I have found to say goodbye is by saying "Quit". Whenever I say "Goodbye", Monika says something like "Why do you say Goodbye?" 

I thought it was worth addressing these problems since the Talk feature is the main thing that caught my attention when I found this mod.

**Comment by therationalpi** [comment]
I didn't realize someone put "you" as a keyword. That should be fixed.

I think the new version has some new farewell scripts.

**Comment by Guardianvoir** [comment]
Whenever I find a problem with Keywords or anything relating to the talk feature, I'll post it here.

**Comment by therationalpi** [comment]
Just going to put in a basic help wanted here for someone to comb through script-topics for any "too common" keywords. Words like "of" "I" or "you" can be part of specific bi-gram keywords, but shouldn't be keywords by themselves.

**Comment by Guardianvoir** [comment]
Whenever I say anything beginning with "I have", she'll usually respond with stuff like this.
![screenshot0004](https://user-images.githubusercontent.com/33330516/32392877-c4adf928-c0ad-11e7-9d40-618b4c5af441.png)

**Comment by Jxhnathan08** [comment]
Thanks for the report! We'll be ironing out any bugs for the next release, including these.

**Comment by Jxhnathan08** [comment]
This issue has been resolved (as of now) by removing the keywords "you" and "herself" from script-topics. If any other problems arise after this, the issue should be re-opened. Otherwise, I recommend it be closed.

**Comment by Guardianvoir** [comment]
She's still giving the speech when I say "I love you"

**Comment by therationalpi** [comment]
Which version are you using, @Guardianvoir ?

**Comment by Guardianvoir** [comment]
Lightweight Pre-re-release

**Comment by Jxhnathan08** [comment]
Interesting, so it seems removing those keywords _didn't_ entirely fix the problem. I'll do some more digging.

**Comment by Jxhnathan08** [comment]
I've reinvestigated this issue and managed to track down another possible solution. After testing, it seems the issue was resolved. Saying "I love you" no longer warrants Monika to go on the spiel about herself.

As for the "I have" screenshots, that seems to be intentional. I hope this issue has been resolved. Can you double check when @therationalpi sends out another pre-release? @Guardianvoir

**Comment by Guardianvoir** [comment]
I'll double check to make sure it's fixed. Thanks for reinvestigating this issue!

**Comment by Jxhnathan08** [comment]
@Guardianvoir New pre-release is out. I'd appreciate if you checked ASAP.

**Comment by Guardianvoir** [comment]
I tested the phrase "I love you" 10 times and she said "I love you too!" every time. It looks like it's fixed @Jxhnathan08 However, now her eyes look weird. It looks like someone drew over them. 
![screenshot0004](https://user-images.githubusercontent.com/33330516/32419459-1993f320-c248-11e7-83c8-72d5a2db3b3b.png)

**Comment by therationalpi** [comment]
That's some of the new art we're going to use in the future. I think we're going to shelve it for the moment, since it could use a bit of polishing.

Thanks for testing for us!

**Comment by Guardianvoir** [comment]
If you need my opinion on it, the eyes are too big and bright.

**Comment by therationalpi** [comment]
Thanks for the feedback!
