### ISSUE TITLE
[Suggestion] Topic about the Venus Project

### ISSUE THREAD

**Issue by CGanimated1227** [Backdash/MonikaModDev#660]
If no one here knows about it, here is a link to it's website: https://www.thevenusproject.com/
It sounds like something Monika would be at least somewhat interested in being the smart little bookworm she is.
EDIT: I'm not asking anyone to simply advertise it if there are assumptions of that nature. I would like to see what her opinion would be on it and if she thinks it's worth the player's attention.

**Comment by Hypeouseaus** [comment]
How is it related to the DDLC?

**Comment by CGanimated1227** [comment]
Monika is supposed to be concerned about the betterment of her lover's world, right? Not all of the topics need to be related to DDLC.

**Comment by therationalpi** [comment]
This seems like something might be interested in. Adding it to the suggestion pool.
