### ISSUE TITLE
Prototype of new song #2

### ISSUE THREAD

**Issue by Reclaimer1905** [Backdash/MonikaModDev#661]
Made another song, hope you like it. 

[Song#2.zip](https://github.com/Backdash/MonikaModDev/files/1599454/Song.2.zip)

**Comment by ThePotatoGuy** [comment]
With this tune, I have the same sentiments as I said earlier in #654 . 

I want to open this and the other issue up for discussion, cause honestly I'm not sure where to go with this. I like both sounds and can envision them as a bgm for a legit VN scene, but it's hard to place that in the mod right now in its current state.

**Comment by Subzerosan** [comment]
Yeah this and your other song is better off as bgm for different scenes rather than the space background.
