### ISSUE TITLE
[Suggestion] - Compose a song with Monika

### ISSUE THREAD

**Issue by QazseWsxdr** [Backdash/MonikaModDev#665]
The player and Monika could compose a song together, maybe taking turns every few bars - I'm fairly sure it wouldn't be too hard to program an AI that does that right? And you could save your songs in a library in game and listen to them whenever you want. Maybe start with simple functionalities first, like the ability to compose only for a single melodic line for piano. I'm sorry if I'm not getting the idea across clearly but I hope you understand what I mean. I think it would be a great idea.

**Comment by Blubmanful** [comment]
If it’s possible it probably wouldn’t turn out too well, but then again I’m not sure what base they would use for the piano so it very much could be possible

**Comment by therationalpi** [comment]
[[This suggestion has been seen and will receive further consideration in the future. It is being closed for now and placed in the pool of seen suggestions. It will be reopened if we begin active implementation on this feature.]]
