### ISSUE TITLE
Need Help On How To Mod Original DDLC

### ISSUE THREAD

**Issue by Bam8647** [Backdash/MonikaModDev#666]
Okay, So I thought I'd give it a shot at customizing my own mod from the initial mod template but i'm having trouble in following the steps under the **Welcome to the modification club** headline (https://github.com/therationalpi/DDLCModTemplate). I downloaded the most recent Ren'py SDK 6.99.12 but then i'm unsure as to which mod template I should download, so i just downloaded the one from that page since obviously i'm wanting to make my mod from the original game and not "MonikaAfterStory". Now that i've downloaded Ren'py, the mod template, and DDLC where exactly do i need to place the files in order to begin building my own mod and still run the game? **I keep getting puzzled about steps 3 and 4.**

If anyone can help, it would be greatly appreciated!

**Comment by ThePotatoGuy** [comment]
In Renpy, go to preferences and change the project directory to the directory containing the folder where you have ddlc + mod template installed. Renpy should detect it and show an option to launch.

**Comment by Bam8647** [comment]
Okay so should I place the mod template into the DDLC download file before doing so? If so would i place the mod template in the renpy folder?

**Comment by Bam8647** [comment]
I'm able to change the project directory to the DDLC file containing the mod template in the /game directory, yet for some reason Ren'py isn't showing me any of the files from the game i can go into. The only scripts that appear are the default scripts related to the Ren'py program itself. Super Confused as to why its doing this.

**Comment by ThePotatoGuy** [comment]
Okay the way I have things setup:
1. RenPy sdk extracted/installed in one folder.
2. DDLC + mod template / mod stuff in another folder (not in the Renpy one).
3. RenPy's project folder is set to the folder containing the folder in step 2.

**Comment by Bam8647** [comment]
Okay so placing the mod template along side the main files instead of in the renpy folder helped fixed one of my problems haha. Yet now when i try to launch the build, it says that the DDLC download is missing the archived files.. I'm able to view some of the scripts though. ugh. I appreciate the time you're taking out of your day to help me man haha, this is my first time modding so bear with me.

**Comment by monikLover** [comment]
@Bam8647 there's actually a server dedicated to modding DDLC. https://discord.gg/kpFy9 go here and there'll be some fellas willing to help ya through it :ok_hand:
