### ISSUE TITLE
[code]File "game/MonikaModDev-0.6.3/original_scripts/script-ch30.rpy", line 136: indentation mismatch.  Ren'Py Version: Ren'Py 6.99.12.4.2187 [/code]

### ISSUE THREAD

**Issue by Ganmany** [Backdash/MonikaModDev#667]
Hi, this is my first time installing mods to an original game and I'm confused on what the error means and how to fix it. Any help would be appreciated !

Thanks :)

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Looks like you have installed the repository instead of a release version.
Anything you might download aside from the [release versions](https://github.com/Backdash/MonikaModDev/releases) is intended for development purposes only and nobody can guarantee it working.
Please reinstall your mod using the latest release.

**Comment by Ganmany** [comment]
Hi thanks for helping, but the problem is, I DID download and installed my files from the released version(latest release) and even tho I redownload it, I still got the same error message :( 
(even used the link u gave and still has the same message)

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Try reinstalling it from the ground up.
.rpy files should not even exist in your game folder as long as you installed everything correctly.

**Comment by ThePotatoGuy** [comment]
@Ganmany fyi, you did **not** install the release version. You've downloaded the repo (or source code zip), as evidenced by `MonikaModDev` and `original-scripts` being in your path. The in-game updater does **not** work for development versions. Unless you are doing dev, use the **release** version (`Monika_After_Story-###-Mod.zip`).
