### ISSUE TITLE
School uniform topic contradictory with the Christmas event

### ISSUE THREAD

**Issue by Sano11** [Backdash/MonikaModDev#668]
![untitled](https://user-images.githubusercontent.com/34994824/34553163-931f4c82-f158-11e7-9d68-1c17ca9e1a88.jpg)

I know that this topic was in the main game, but I feel it doesn't make sense anymore because of the Christmas event costume.

**Comment by ThePotatoGuy** [comment]
The Christmas event was only for a limited time, so the topic is still appropriate. Once we have different clothes, then we can remove it.
