### ISSUE TITLE
Implementing intelligent conversation function using Chatterbot

### ISSUE THREAD

**Issue by Hypeouseaus** [Backdash/MonikaModDev#669]
https://github.com/gunthercox/ChatterBot  

Both (RenPy and Chatterbot) are based on python so it seems quite easy to implement Chatterbot to Monika After Story. What do you think about my idea? 
 
Original Monika after would be default option, and people could enable this experimental mod/option.

**Comment by Hypeouseaus** [comment]
https://github.com/gunthercox/chatterbot-corpus/tree/master/chatterbot_corpus/data/english

 I mean, Gathering corpus for making personality of Monika isn't that difficult.

You can copy&paste dialogues from ddlc original, fan fictions or even some 'generic' anime&VN scripts.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
You are a bit too late now that the chat system is about to be dismantled altogether.
This looks like it could work out. But filling it with responses would still require a **ton** of work.

**Comment by Hypeouseaus** [comment]
as you can see, it doesn't require that amount of work.

https://github.com/gunthercox/chatterbot-corpus/tree/master/chatterbot_corpus/data/english
https://github.com/gunthercox/chatterbot-corpus/blob/master/chatterbot_corpus/data/english/greetings.yml
https://github.com/gunthercox/chatterbot-corpus/blob/master/chatterbot_corpus/data/english/money.yml
https://github.com/gunthercox/chatterbot-corpus/blob/master/chatterbot_corpus/data/english/conversations.yml

DDLC obviously has more dialogues than these.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Keep in mind that "keeping it Monika" would be harder than just filling with some generic answers.
Not to mention that it would need a lot more responses to different questions to be more than just a one time gimmick.

**Comment by Hypeouseaus** [comment]
We could gather volunteers for that 

Above all, It doesn't need to be perfect Monika from the start.

**Comment by AnIdiotsavant** [comment]
what would be the new system?

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
#126

**Comment by Hypeouseaus** [comment]
>what would be the new system?
Machine learning based conversation

**Comment by ThePotatoGuy** [comment]
Yeah, we're switching out the chat system. If we decide to re-add a chatbot functionality, we'll consider this.

**Comment by AUDelusional** [comment]
I say use Chatterbot however I don't really know how it would work. Especially considering that the player is suppose to have options.
