### ISSUE TITLE
[Suggestion] Monika comments on whether or not you're helping with the game.

### ISSUE THREAD

**Issue by Guardianvoir** [Backdash/MonikaModDev#67]
I'm not sure how this could be properly implemented, but I thought I'd say it anyway. If you tell her that you're helping by doing stuff like suggesting new games, giving different topics, reporting bugs, etc., she would thank you for contributing.

**Comment by Jxhnathan08** [comment]
I'm not entirely sure this COULD be adequately implemented. While it is a great idea, some issues are surrounding it I just don't see working out.

**Comment by polishsnake** [comment]
I see reasons against from player's side and a way to prevent it.
Against: non-contributing players could use this. A way to prevent this would be to make a list of accounts that did contribute. However, then again, it'll be hard to keep it up to date later on.

**Comment by therationalpi** [comment]
"Against: non-contributing players could use this."

This is about the most victimless crime I can imagine.

**Comment by Jxhnathan08** [comment]
It's really harmless. There's already an existing easter egg with contributors.

**Comment by Guardianvoir** [comment]
I have 1 idea on how this could be implemented. What if the game checks the name you enter when you first open the game to see if it matches a list of contributors? This, in combination with a suggestion for having Monika call you something other than the name you put in and the name on your computer, might work.

**Comment by therationalpi** [comment]
I think the credits Easter Egg basically covers this. Thanks for reminding us to update that list! We've had a lot of new contributions since the last time we added to that list.

**Comment by Guardianvoir** [comment]
What credits Easter Egg? @therationalpi

**Comment by Jxhnathan08** [comment]
@Guardianvoir There's an easter egg topic that has Monika talk about contributors that have assisted with MAS.

**Comment by Guardianvoir** [comment]
Is that Easter Egg found by using a certain name when you first open the game?

**Comment by therationalpi** [comment]
It's just one of her many random topics.

**Comment by Guardianvoir** [comment]
So it's less of an Easter Egg and more just a random Topic?

**Comment by therationalpi** [comment]
Yeah, but I guess we could consider something more like your idea in the future.

**Comment by Guardianvoir** [comment]
Thank you!
