### ISSUE TITLE
[Small Suggestion] Make Monika blush when we complimented her +1 ♫

### ISSUE THREAD

**Issue by GirlwithaWhiteMask** [Backdash/MonikaModDev#671]
Idk... 

Monika seems to be the one who likes these "us" sometimes, but I imagine her don't take been these very well... >.<

Idk how you guys do it but I guess "Keywords" like:
Pretty
Cute
Sweetheart
Sugarcube
Honey
...
This is getting very cheesy I know >///u///<

I think she will be surprised and stay blushing and say "Thank you"
Maybe if we do it multiple times she say to us stop because "she going to melt" or "feels like her heart is burning/exploding" 
I see this one kinda out of character but maybe she says "It's cruel to us these her like that because she REALLY want hug/kiss us"

♪ Another silly and sweet one ♫
If we say "Everyday I imagine a future where I can be with you"
She will sing "In my hand, there is a pen that will write a poem of me and you"
Maybe just if we keep and say "The ink flows down into a dark puddle"
And she finishes "Just move your hand - write the way into his heart!
But in this world of infinite choices
What will it take just to find that special day? (x2)"

**Comment by Danymations** [comment]
A blushing Monika would be cute and fun to make. We'll see what we can do!

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
A bit OOC indeed.
Monika is the one to take such compliments more calmly as referenced in her "d-did you say kiss?" topic.
Tho I agree that adding a blush expression or would certainly be useful.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I think she would rather respond by thanking you, telling you she's flattered and/or complimenting you in return.
