### ISSUE TITLE
Some small word changes

### ISSUE THREAD

**Issue by ethancedrik** [Backdash/MonikaModDev#673]
In monika_fahrenheit451, change "there're" to something else such as "there's", "their", or the long form "there are" as although "there're" might still be proper English, the other options sound and read a lot better.

In monika_icecream, change "favourite" to "favorite", and "flavoured" to "flavored" to better reflect the rest of her dialog written by Dan in game which is in American English.

**Comment by monikLover** [comment]
Fixed the 2nd one. 1st one is from an older version.
