### ISSUE TITLE
[Bug] Lottery topic incorrectly plays topic after it as well

### ISSUE THREAD

**Issue by MadHaetter** [Backdash/MonikaModDev#675]
Monika does not correctly return after her Lottery (monika_lottery) topic, she says the next topic in line the innovation topic (monika_innovation).

I have tried redoing the topic, restarting DDLC and re-installing the mod + restarting and the issue persists through.

Having had a look at the code at https://github.com/Backdash/MonikaModDev/blob/master/Monika%20After%20Story/game/script-topics.rpy  I am unable to see why she would say both topics one after the other as the return was seemingly written the same.

I will be testing other topics and if any others do this as well I will update this.
  monika_cupcake does this as well.

**Comment by ThePotatoGuy** [comment]
Bug has already been fixed #578 . However it is not in the current build.
