### ISSUE TITLE
[Suggestion] - More areas/ Build up an area

### ISSUE THREAD

**Issue by DisLEXyA** [Backdash/MonikaModDev#676]
I was thinking that a great addition to this mod, that might make it better than it already is, would be if you could add maybe more areas to go to, such as a kitchen, or a bedroom (no bedroom scenarios though, unless you want to add that, lol) I just really get bored of the same room sometimes, so maybe more areas might encourage players to interact with the game more. You could maybe also add a cooking activity where you can cook with or for Monika. Please take this into consideration, and thank you for your time, and this amazing mod. ^-^

**Comment by AUDelusional** [comment]
Kind of already being done...

**Comment by MikuChanAnime** [comment]
Yeah..
#509
