### ISSUE TITLE
I cant open the game

### ISSUE THREAD

**Issue by WendyStudiosYT** [Backdash/MonikaModDev#677]
how do I open the game file?

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
- Download the base game from the [ddlc.moe](http://ddlc.moe/).
- Unpack the game to somewhere on your PC.
- Then download the [latest release](https://github.com/Backdash/MonikaModDev/releases) (the zip archive not the source code).
- In this archive, you will find the folder named Monika_After_Story_*version*-Mod. Extract it somewhere on your computer.
- Open the base game folder. In this folder, you will find the folder named "game".
- Copy all the files found inside the Monika_After_Story_*version*-Mod folder into the "game" folder.
That should be it. From there the game could be launched from DDLC.exe.
