### ISSUE TITLE
[Suggestion] - Aknowledging Player's Occupation

### ISSUE THREAD

**Issue by PopeAesthetics** [Backdash/MonikaModDev#678]
Been playing the mod for a while but finally going to add a suggestion. Hope I'm doing it right!

I feel Monika should ask and consider whether or not the player is currently employed, in school, or not doing anything and respond to that in different ways.

-If the players says they are in school, encourages them to study hard and not give up. Possible even offer them support in literature and writing.
-If the player says they have a job, telling them to keep working hard, and offer her support after a hard day at work and have her say how proud she is.
-If the player says they are not employed or in school, have her worry for the player and encourage them to do something.

Also as a person that works night shifts, I feel bad whenever she scolds me for being up so late. Perhaps something in the future could be done for people that have to work late like myself.

**Comment by therationalpi** [comment]
Sounds like a very natural topic of conversation to me!

**Comment by therationalpi** [comment]
[[This suggestion has been seen and accepted. It is being closed for now and placed in the pool of accepted suggestions. It will be reopened once we begin active implementation on this feature.]]
