### ISSUE TITLE
[Bug] Music Menu Explained Incorrectly on First run

### ISSUE THREAD

**Issue by TacticalTriangle** [Backdash/MonikaModDev#679]
When you begin the game for the first time Monika begins to talk about the talk, music and play games features. However when she is talking about the music topic, she mentions that pressing 'm' scrolls through the songs rather then opening up a menu. Just a minor thing really.
![screenshot 5](https://user-images.githubusercontent.com/34323845/34635353-424eb946-f25c-11e7-956c-9275b76a7cff.png)

**Comment by monikLover** [comment]
Good eye, good eye. Fixed 👍
