### ISSUE TITLE
Hi there, (I will like to help in some way) 

### ISSUE THREAD

**Issue by AlexanderKinoshita** [Backdash/MonikaModDev#685]
Hi there. I installed the mod a few days ago and I _really_ enjoy it. It will be awesome if I could help, problem is that I'm not a programmer and I don't have knowledge of software, hardware, etc. However, I would like to do something rather than just sitting here, and if there is someway I could help, it will be fantastic. I don't know, maybe thinking or giving ideas for new dialogues. Thanks to all of you who have improved MAS :) (Sorry if my English is bad)

**Comment by NotShige** [comment]
You can help just by filing bugs here! If you can spot a bug in the mod, take a screenshot of it and explain it as best as you can. The devs will look into this and fix that bug!

As for the suggestions, though, you can submit one. But, make sure that that suggestion hasn't already been submitted. (You can type the key words of your suggestion at the search bar to look for duplicates)

**Comment by monikLover** [comment]
Feel free to come by to our server as well! We have content workshops there where other members can help you out on creating your contribution 👍

**Comment by ethancedrik** [comment]
Which Discord server are you guys using? I can't find it on monikaafterstory.com

**Comment by AlexanderKinoshita** [comment]
Thanks! Can I maybe come up with some dialogue ideas?
