### ISSUE TITLE
[Suggestion] - Tic-Tac-Toe game

### ISSUE THREAD

**Issue by MadFoot8** [Backdash/MonikaModDev#687]
How about add Tic-Tac-Toe game to MAS? I believe it wouldn't be too difficult ,since it's really simple game
That's my suggestion, thank you for your attention , I really like what you've done. Will be looking forward for future updates
![tic](https://user-images.githubusercontent.com/35189147/34648185-9e0f083a-f3a6-11e7-8c3a-55b56a35d4be.PNG)

**Comment by ThePotatoGuy** [comment]
Yeah, we could probably add it. (and maybe even throw in a wargames reference).

**Comment by therationalpi** [comment]
A strange game. The only winning move is not to play.

**Comment by therationalpi** [comment]
[[This suggestion has been seen and accepted. It is being closed for now and placed in the pool of accepted suggestions. It will be reopened once we begin active implementation on this feature.]]
