### ISSUE TITLE
[Bug] - Typo

### ISSUE THREAD

**Issue by CatsAndFacts** [Backdash/MonikaModDev#69]
During the dialogue where Monika is telling a story about the two caskets and the 200 grieving women, the word "grief" is misspelled as "gried" in the third dialogue box.
![image](https://user-images.githubusercontent.com/33360076/32395905-84337bbe-c0b9-11e7-8fa7-b6f32bb74385.png)

**Comment by Jxhnathan08** [comment]
Thanks for the bug report! Looking into this now.
