### ISSUE TITLE
Help (I don't know if this counts as an issue)

### ISSUE THREAD

**Issue by Shazzriel** [Backdash/MonikaModDev#692]
I extracted the Monika after story zip into the ddlc game files but when I try to open ddlc, it doesn't open. But when I remove the Monika after story folder from ddlc's game folder, I can open ddlc again.

Did I do something wrong?

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
To install the mod you must extract files contained within this folder not the folder itself.

**Comment by Shazzriel** [comment]
How do I do that?

**Comment by Shazzriel** [comment]
Never mind I got it now thank you so much.
