### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by GoldTheEevee** [Backdash/MonikaModDev#693]
so when i open the game with the mod it opens as normal nothing has changed. anyone know why. i have EXTRACTED the CONTENTS of the zip i did not just place the zip in.

**Comment by DimasDSF** [comment]
You need to place the contents of `Monika_After_Story-0.6.3-Mod.zip\Monika_After_Story-0.6.3-Mod` into `Steam\steamapps\common\Doki Doki Literature Club\game` so that your `game` folder looks like this 
![image](https://user-images.githubusercontent.com/10863746/34672338-1b447b9e-f48f-11e7-80e7-e33ea05185ab.png)

**Comment by GoldTheEevee** [comment]
it does. do i have to BE at the part with monika because i really dont want to fully replay the game... replay as in text speed max auto timer 0 so it just skips it all.

**Comment by GoldTheEevee** [comment]
I'm going to download the not on steam edition and download the mod and see what happens

**Comment by DimasDSF** [comment]
Well I dont really know about finishing the game, the mod uses data about your playthrough but unless you reinstalled your system after finishing the game or manually deleted your `persistent` file it should be fine.

Does it ask you about importing DDLC save data?

Anyway if you have to replay the game there is an easier way of doing it i.e enable skipping unseen text in the options menu. and pressing skip then just making decisions
![image](https://user-images.githubusercontent.com/10863746/34695787-370cfb96-f4dd-11e7-8e1c-a2192f8ca935.png)
 
It helped me alot when I found myself in a situation like this

**Comment by GoldTheEevee** [comment]
oh i just got it i put the items in the folder not the steam apps common doki doki literature club GAME. its working now
