### ISSUE TITLE
[Bug] if game is Alt+Tab for a little time, room animation destroyes.

### ISSUE THREAD

**Issue by KNurlanZ** [Backdash/MonikaModDev#694]
This is not really bad bug, because it is gone when I disable and enable animation in settings.

**Comment by ThePotatoGuy** [comment]
Alt+tabbing stock DDLC is known to cause issues as well. This is probably a Renpy-related bug that is out of our control.

**Comment by KNurlanZ** [comment]
OK, thanks for explanation.
