### ISSUE TITLE
[Suggestion] If in Characters file still saved other characters they can remove Monika for a while

### ISSUE THREAD

**Issue by KNurlanZ** [Backdash/MonikaModDev#695]

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Not sure what you mean. Could you provide a better description?

**Comment by KNurlanZ** [comment]
Well... Once, when I entered the game, Yuri came for a little time... And maybe you can improve this and take a little time to anyone, but then, Monika will delete them all again.
P.S. I reached good ending and all other characters stayed in the folder, then I put the monika.chr and downloaded your mod.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
~~I don't want to spoil too much but judging from the variables set by this event it was not Yuri.~~
MAS is currently aimed at Monika and Monika only.
Not to mention that there are too many combinations of possible file manipulations to implement decent .chr manipulation mechanic.

**Comment by KNurlanZ** [comment]
Well, then what about:
If in game files will be files of other girls, when you enter the mod, Monika jumpscares and says something like:
I thought there will be only me and you!
Then she deletes them and says:
That's better, no one will disturb us.

**Comment by therationalpi** [comment]
[[This suggestion has been seen and will receive further consideration in the future. It is being closed for now and placed in the pool of seen suggestions. It will be reopened if we begin active implementation on this feature.]]

**Comment by ThePotatoGuy** [comment]
[[Rejecting this. for the time being, I think having character file stuff isnt worth it atm]]
