### ISSUE TITLE
Add appropriate tags to topics

### ISSUE THREAD

**Issue by therationalpi** [Backdash/MonikaModDev#699]
A lot of the topics for the prompt-system in the `next-release` branch don't have appropriate tags yet and are just marked "Random" as a placeholder. These need to have appropriate tags like "philosophy" and "monika" etc to make sifting through the large number of them easier.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Any rules or general guides on how to tag topics?

**Comment by therationalpi** [comment]
Finished as of: https://github.com/Backdash/MonikaModDev/commit/81ca83b59fcce299c0cfe866f45c3f4fd0af4b25
