### ISSUE TITLE
[Suggestion] Player Microphone Interaction

### ISSUE THREAD

**Issue by AUDelusional** [Backdash/MonikaModDev#709]
So, I think the player should be able to communicate with Monika using their microphone. Considering the new update is supposedly suppose to get rid of keywords I think this would work either more. Python hosts a speech recognition library so it should be easy to implement into Ren'Py as Ren'Py is built off Python. https://pypi.python.org/pypi/SpeechRecognition/

**Comment by ThePotatoGuy** [comment]
From the wheel file size, it looks like this library is 31MB. That's just way too extra for this. The impact of adding such a large library could dramatically increase load times.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
This gives off some Talking Angela vibes.

**Comment by gitthisissue** [comment]
Your SpeechRecognition library use Google API. It requires internet to function.
Why not use Windows' built-in function?

https://pypi.python.org/pypi/winspeech

Talking Angela... talking Monica, huh? That'll be nice, except I don't have microphone.

**Comment by ThePotatoGuy** [comment]
That `winspeech` library is small enough to use. We'll have to see the feasibility of adding wheel files as python-packages first though.

**Comment by therationalpi** [comment]
The problem with the windows thing is that it's a platform-specific function, and I think it's important for the game to be as consistent across platforms as possible. Including a major feature like speech-detection that's only available on Windows wouldn't be good...

**Comment by GoldTheEevee** [comment]
i know i am just a random person with no program skills but would this FORCE the player to use a mic because then some people can't always use a mic. i am just suggesting this but there should be a option to use keyboard

**Comment by AUDelusional** [comment]
Where'd you get the idea that this would force people to use a microphone? Using a microphone is optional, that should be obvious.

**Comment by therationalpi** [comment]
[[This suggestion has been seen and will receive further consideration in the future. It is being closed for now and placed in the pool of seen suggestions. It will be reopened if we begin active implementation on this feature.]]

**Comment by ThePotatoGuy** [comment]
[[Rejecting this because speech recognition is just out of scope for us]] 

We are open to people adding this as external submod development
