### ISSUE TITLE
[suggestion] Project Libitina Topic + Adding More Things Like "surprise.txt"

### ISSUE THREAD

**Issue by pandjalu** [Backdash/MonikaModDev#711]
Can you guys add more dialog about this project?
 Also add more for add things like that

**Comment by therationalpi** [comment]
It's difficult for us to add good content regarding libitina because very little has been confirmed by Dan.

**Comment by pandjalu** [comment]
i mean someday after it release, can you guys do it?

**Comment by therationalpi** [comment]
We'll do our best.

**Comment by pandjalu** [comment]
hey, also what about adding more things like "surprise.txt"?

**Comment by therationalpi** [comment]
Definitely on our to-do list.

**Comment by pandjalu** [comment]
1 thing, how do i contribute like writing topic or something like that? because i didn't know how to coding

**Comment by monikLover** [comment]
Go ahead and read our contributing guide in the readme. It'll show you how you can create your topics.
