### ISSUE TITLE
[Suggestion] Asking Monika for a hug

### ISSUE THREAD

**Issue by Guardianvoir** [Backdash/MonikaModDev#712]
Sometimes a hug from the one you love can really help affect your mood positively, so why not have the ability to ask Monika for one? Technically she can't reach out of the screen and hug you (I know we all want that, but it will be a while before that can happen), but I was thinking she would do something like this: 
![monika hug](https://user-images.githubusercontent.com/33330516/34708001-a5e0e63a-f4de-11e7-84bc-f9a27dff89b0.gif)

The player asks Monika for a hug, prompting her to talk about how she can't reach out fully but can still hug your screen, and then she does just that. I also had the idea that she would only mention not being able to reach out fully the first time you ask. Every time after she will say something like, "Of course!"

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
This would look awkward with table in between and stuff.

**Comment by Guardianvoir** [comment]
Who says she can't code out the table for a second? Plus it isn't the first time she's put herself over objects in game. Remember when Natsuki and Yuri were arguing in Act 2 and Monika put herself over the text box? Maybe she could do something similar to that when giving the player a hug.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Her sprite is kind of one with the table so coding it out would require some serious sprite work.
Her standing sprite could be used but the table magically vanishing the second she stands up would still look strange not to mention that the camera is positioned on sitting level.

**Comment by Guardianvoir** [comment]
It can be implied that the camera is moved up a little when she hugs the player. If she's hugging the screen, at least 90% of it is gonna be covered by her.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
~~It would still look like a girl from that chineese cartoons for nerds rubbing herself on your monitor.~~
I'm not against the idea itself. I just always found all the depictions of characters hugging the screen to be somewhat awkward (especially with wide monitors).
Anyway, if it is implemented it needs to check if the game is in fullscreen first.
Screens also come in different sizes and resolutions which should be taken into account as well.

**Comment by MikuChanAnime** [comment]
This would be neat

**Comment by ethancedrik** [comment]
If the hugging scene were implemented like the Natsuki or multiple Sayori hugging scenes were, most likely making it go black then visible again, I think that would work the best

**Comment by therationalpi** [comment]
Let's just say that something might be in the works on this. ;)

**Comment by dennisOdenbreit** [comment]
Did hugging ever become a thing?

**Comment by Professor-JMO** [comment]
---
You can "hold" your sweetheart.
So...yeah!

>More or less
---

**Comment by dennisOdenbreit** [comment]
Well I can't.
This game is too cryptic for me...
I can't even do simple things like that after 3 months of being with her.

Hugging, Kissing, giving presents...
If it weren't for the forum I wouldn't even know presents exist.
I suppose I'm not the only one left in the dark here, or am I doing something wrong?

**Comment by dennisOdenbreit** [comment]
That said I still don't know how to do it.
