### ISSUE TITLE
Make update flow for 0.6.x to 0.7.0

### ISSUE THREAD

**Issue by therationalpi** [Backdash/MonikaModDev#715]
With the new prompt system, we need a way to update the events in the event database based on info from previous version.
  
EDIT: Just putting my personal checklist here so it shows up on the issues page
Personal checklist for this:
- [x] Ensure updates from 0.6.1 and beyond are progressed properly. (comparing topic removals/renames)
- [x] Delete 0.6.3 special content if detected
- [x] Mark `seen` topics as `unlocked` in version 0.7.0 script

**Comment by ThePotatoGuy** [comment]
Personal checklist for this:
- [ ] Ensure updates from 0.6.1 and beyond are progressed properly. (comparing topic removals/renames)
- [ ] Delete 0.6.3 special content if detected
- [ ] Mark `seen` topics as `unlocked` in version 0.7.0 script

**Comment by ThePotatoGuy** [comment]
Update flow for 0.7.0 is ready. All we have to do is uncomment some lines in `updates_topics` and it's good to go.

**Comment by ThePotatoGuy** [comment]
Okay I need some quick verification on expected behavior when updating topics to `event` framework.
Is this correct?
```
if an event has been seen and 
    (is_pool 
     or is_random 
     or has an action that means it should be pooled or random):
then set it to unlocked
```
What about the conditional? should that be set to `None` now that it is unlocked.

**Comment by therationalpi** [comment]
Yes to all questions.
