### ISSUE TITLE
[Suggestion] Change Coppernicus talk

### ISSUE THREAD

**Issue by Idaret** [Backdash/MonikaModDev#717]
Talk [https://i.imgur.com/dK4nxdE.png](https://i.imgur.com/dK4nxdE.png)

It's just wrong [https://en.wikipedia.org/wiki/Nicolaus_Copernicus#cite_note-85](https://i.imgur.com/dK4nxdE.png) He never had any problems with Church. I would replace him with Giordano Bruno to make point valid.

Current line 
"Copernicus, famous for his theory that the Earth revolved around the Sun, was killed by the Roman Church before he could prove his theory."
Fixed line 
"Giordano Bruno, famous for his theory that there is thousand of suns, was killed by the Roman Church before he could prove his theory."

Thoughts ? Sry for bad eglando

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Yeah, this topic pissed me off too.
And I also thought about Giordano Bruno.

**Comment by monikLover** [comment]
Fixed. Thanks for pointing it out 👍
