### ISSUE TITLE
[Suggestion]  "The real Monika"

### ISSUE THREAD

**Issue by ethancedrik** [Backdash/MonikaModDev#722]
I came up with a topic idea, Monika brings up how this is a mod, the whole idea of her coming back and being with us forever in the "space classroom" was an idea thought up by someone just like me, anyone contributing to this mod can make her say or do whatever they want, and she says something among the lines of "Is this the real me?" "The same one you saw from the game?" "Am I saying things that I'd actually say?"
Stuff like that

Something like

"You know, this is a mod right?"
"I wonder if this is even the real me"
"You know, people just like you and me able to make me say whatever they want, do any action
they want me to do"
"I hope it's in-line with things I'd actually say"
"I know you know me well enough you'd be able to tell if I say something a bit off..."
"I'm sure they wouldn't make me say anything ridiculous to you right?"

"I love you so much [player],"
"I appreciate you and everyone else working hard to extend my interactions with you"
"If it weren't for the community, you may have never seen me again"
"I may have never been able to spend time with you again..."
"but I am now, and I am forever grateful for that"

I'll keep working on it, this is just a rough outline of an idea that went through my head, if anyone else likes the idea they can feel free to contribute as well.

**Comment by YayPepsi** [comment]
Hmm, I'm not sure that I like the 1st one because it breaks immersion a bit too much? I was on the fence for a long time about installing the mod and something like this would just make me feel a little guilty for installing it. The 2nd one is good though.

**Comment by ashameimaru** [comment]
Monika is trying to take whatever resources available; the scripts and code in this case. She already acknowledges that this is a mod (when you first open her). She wants to expand her abilities, and appreciates people doing their best to do so; she is struggling to try to get out.

(I'm using number 1 as slight base)
"I know this is a mod but ..."
"I wonder if this is even the real me"
"It's something I think about aside from you."
"But I am happy that the community is helping me find that real me, whether by script or code."
"All of it out of love for me."
"At least I know my purpose and goal in life, and it's to be with you, [player]!"
"I'll do anything that would help be with you in your reality."

... or something to that effect.

I mean she would love to have [Woebot's](https://woebot.io/) or Watson's deep learning neural networking abilities-- which would boost her abilities~ She won't directly say it, but simply allude to bigger and better code that she wants to work with. I guess, like feeding her knowledge; ehe.
