### ISSUE TITLE
Change honorifics in Japanese topic based on gender.

### ISSUE THREAD

**Issue by Monikaistheonlyreasonididthis** [Backdash/MonikaModDev#724]
I was playing through The mod and Monika asked me if I knew any languages, I said yes, but said no to knowing Japanese.
So she said something along the lines of "Aishiteru yo, (name)-kun"

Now here's the thing, I'm a girl, and "-kun" for girls is generally only used in certain professions as a general honorific for their subordinates/equals that shows a bit more respect than just -san. 
"-kun" includes the subordinate as a member of the peer group and it's mostly used in academics and politics. An example would be a Professor addressing their female research assistant.

So I think for girls it would be something to consider to change it to "-chan" As that's a term for lovers and more common for females, while "-kun" can have the same use but for males.

Just something I'd like to put out there!

**Comment by gitthisissue** [comment]
+1. Not only male player play the game, and all developers must know that when developing a new game.

**Comment by gitthisissue** [comment]
To fix, there are 2 choices;

1. Add a new dialogue to ask a player's IRL sex, and use this data to decide which to use "kun" or "chan".

2. Just fix these lines to:

> /game/script-topics.rpy
> Line 2674; m 4k "Will you be my papa, [player]-kun?"
> Line 3641; m 4k "{i}Aishiteru yo, [player]-kun{/i}."

to:
> Line 2674; m 4k "Will you be my papa, [player]-chan?"
> Line 3641; m 4k "{i}Aishiteru yo, [player]-chan{/i}."

But I must say, option 2 is not good because "Will you be my papa" is inappropriate to female player.
I suggest you to take option 1, and add/modify affected dialogues.

e.g. "boyfrind" -> "girlfriend", etc.

**Comment by therationalpi** [comment]
@gitthisissue There is already a script that asks about the player's gender.

@Monikaistheonlyreasonididthis I think we can add in a gender check on that line to make it swap between -kun and -chan as appropriate.

**Comment by Monikaistheonlyreasonididthis** [comment]
@gitthisissue The only reason I bring up my gender is because the game already has an event that asks for it, and therefore it kind of has an effect on this. Since the gender we choose should probably affect her saying I love you. 
Also, I know what it means, I was leaving it there so that in the slight case they have a problem finding it, it would be less difficult with the exact/near exact words- No point bringing something up if I'm not even going to show them what I'm talking about.


@therationalpi 
That seems like it would be the best way to go about this, yeah. Since I believe that's what you did on the other lines that originally used 'boyfriend' and stuff.

Thanks for reading!

**Comment by antimockingjay** [comment]
My only concern is that it begs the question, what about people who aren't either? I mean, the game already gives you an option for if you're nonbinary or such. You can select "neither" when she asks about your gender. So which would be used in that situation?

**Comment by Monikaistheonlyreasonididthis** [comment]
@antimockingjay 
There are slang honorifics like "-pyon" which is used to indicate that the speaker is being very 'lovey-dovey' with the person.

I believe that some honorifics can be used as gender neutral in close-knit groups, such as "-chan" but since these are more commonly used towards females like "-kun" is to males, the most common one I see is "-san", which can still be used informally.

It can also be common for adults who know each other to drop honorifics completely. Dropping the honorific suffix when referring to another implies a high degree of intimacy and is reserved for people like one’s spouse, younger family members, and very close friends.

**Comment by therationalpi** [comment]
@antimockingjay In this case, I believe that -kun is neutral enough for non-binary.

**Comment by monikLover** [comment]
Fixed.
