### ISSUE TITLE
[ongoing] Flow stuck in ch21_m_start (Do you want to read my poem now?)

### ISSUE THREAD

**Issue by ThePotatoGuy** [Backdash/MonikaModDev#725]
This bug is starting to show up more frequently, so we should keep tabs on where and how people are getting stuck in this flow.

The general dialogue most people get stuck on is this:
```
m 1a "Anyway, do you want to read my poem now?"
m 1e "Don't worry, I'm not very good..."
mc "You sound pretty confident for someone who claims to not be very good."
m 1j "Well...that's 'cause I have to sound confident."
m 1b "That doesn't mean I always feel that way, you know?"
mc "I see..."
mc "Well, let's read it then."
return
```

This section is located in label `ch21_m_start` in `script-poemresponses2.rpy`. The return effectively ends the renpy script and causes the mod to get stuck. The puzzling factor about this is _how_ one can even reach this flow. It's part of the stock game and is not `call`d nor `jump`d anywhere in the mod. 

Due to the uniqueness of this bug, I'm making this issue as a central post to gather information about how people encounter this bug in hopes of fixing it one day. Anyone who gets this bug, please comment with the following details:
1. How long you've had the mod installed?
2. What was the dialogue before this bug was encountered?
3. Does it occur when you relaunch the game?
UPDATE: 2018-01-10:
4. Did you have another mod installed prior to this one?

_more questions may be added_

EDIT: Issues this covers:
#721 #520 #453

**Comment by MikuChanAnime** [comment]
I made a post about this like 6 hours ago
#721

**Comment by MikuChanAnime** [comment]
Wait....
I think I know the cause. It's when you uninstall the mod, install **ANOTHER** mod, uninstall that one, then re-install this one. I hade the Make everyone happy mod installed, then re-installed this mod to find this happening... maybe it's because of the 2 different scripts? idk

**Comment by NotShige** [comment]
^ **YES**. I did that thing as well. I installed "Doki Doki Literature Club!!! 1.1.0(mo)", saved, installed MAS again, imported from save file, and that keeps occuring to me.

Well, I'm glad that it's not just me. I thought that it was just the side effect of the mod. (I'm sure it is, though)

**Comment by ethancedrik** [comment]
I typically keep my files in the game folder and in the %APPDATA%\renpy folder in separate folders, then rename them to the default so when I launch the game they don't conflict and I can easily switch between mods with no issue
[![https://gyazo.com/f7de8a4321d5e22162fc48b306950baa](https://i.gyazo.com/f7de8a4321d5e22162fc48b306950baa.png)](https://gyazo.com/f7de8a4321d5e22162fc48b306950baa)
[![https://gyazo.com/a5cd6277fe05c1cd3036c4fdd20fe524](https://i.gyazo.com/a5cd6277fe05c1cd3036c4fdd20fe524.png)](https://gyazo.com/a5cd6277fe05c1cd3036c4fdd20fe524)

**Comment by MikuChanAnime** [comment]
I don't know how that would work on mac, as I use a MacBook Air

**Comment by NotShige** [comment]
@MikuChanAnime Actually, just make multiple copies of DDLC and install the mods on each folder.

If you plan on using a mod but want your saves intact, just rename the save folders to something else. They're stored on ```~/Library/RenPy```. And if you want to use another save file for another mod, just rename the other folder to the default save folder name, and rename the other to something else.

**Comment by ThePotatoGuy** [comment]
Thanks for the information, guys. If it's a side effect of installing additional mods, it's hard to figure out what we can do to mitigate this without building a mod launcher/switcher or something.

**Comment by MikuChanAnime** [comment]
That actually wouldn't be a bad idea. But it would be another project that's different than MAS

**Comment by therationalpi** [comment]
Okay, just to be clear on this...MAS never changes your DDLC saves. We import non-destructively so that you can always go back to DDLC or run that mod separately.

But it looks like some other mods do change the original DDLC save and that makes those saves incompatible with MAS and possibly takes away backwards compatibility with DDLC. That's not something we can actually do anything about. I would suggest bringing this up with the authors of those mods, and maybe suggest they use a save-import system like we use. This is already available in the DDLC Mod Template, and they can talk to me if they need help implementing it.
