### ISSUE TITLE
Suggestion - new game hangman

### ISSUE THREAD

**Issue by kaido1224** [Backdash/MonikaModDev#726]
Just a suggestion to maybe create the game hangman. You can put all kinds of easter eggs in here whenever someone like sayori's name happens to be the word. Even if you don't make it into an actual game to play you could put it in there as a gag (maybe on april fools day) and have monika make a remark about it being in poor taste.

I'd program it myself but I'm a SQL developer and don't have much experience or time to learn python/renpy at the moment.

**Comment by kaido1224** [comment]
You could even hide the changing Monika's clothes new material i saw you guys kicking around on the game. If you get the word wardrobe correct you unlock being able to change her outfits. Maybe have Monika bring up a conversation something like...

"Speaking of wardrobe, remember when i said i wish i was able to wear more than just this outfit?Well now i can!" 

Just a thought.

**Comment by ThePotatoGuy** [comment]
Hangman has already been added and will be released in 0.7.0.

**Comment by kaido1224** [comment]
Ah my bad

**Comment by Bam8647** [comment]
Poor Sayori Hehe~

**Comment by kaido1224** [comment]
Closed because it's already been done.
