### ISSUE TITLE
Hour detection

### ISSUE THREAD

**Issue by gitthisissue** [Backdash/MonikaModDev#728]
In issue #678, I saw this line: "Also as a person that works night shifts, I feel bad whenever she scolds me for being up so late."

Does this mod, or the base game, detect computer's time(hour)?
If so, can I "adjust" it because my computer hour is not same as real life hour.

e.g. My PC's base time is UTC, but my IRL hour is +2.

**Comment by gitthisissue** [comment]
Some settings like "ClockOffsetHour: 5" "ClockOffsetHour: -5" will be nice.

**Comment by ThePotatoGuy** [comment]
The game does detect your pc time. If you use a different time setting on your computer and it's not the same as your irl time, maybe you should change your computer's time. This game isn't the only program that relies heavily on your time settings.
