### ISSUE TITLE
[Suggestion] Easter egg (Spoilers for possible new content)

### ISSUE THREAD

**Issue by Guardianvoir** [Backdash/MonikaModDev#73]
I thought of this while looking at a subreddit called Just Monika when I came acroos this picture (It was labeled with "If Monika won't let me have my harem ending...") 
![uguu7xe](https://user-images.githubusercontent.com/33330516/32401435-a25333a2-c0e4-11e7-9c5d-50abd8c543a8.png)

So it gave me an idea. What if you added an easter egg where if the game detects multiple copies of Monika's character file in the character folder, multiple Monika's will show up the next time you open the game? This is more of a joke feature, which is why I labeled it [Suggestion (kinda)]

**Comment by Jxhnathan08** [comment]
This is definitely possible. I'll bring it up with other contributors, thanks!

**Comment by therationalpi** [comment]
This would be a fun easter egg. I'm marking this as a spoiler, in case we do choose to add it.

**Comment by Guardianvoir** [comment]
I have a question. If I were to try this Easter Egg and it's not implemented, would the game give me the end screen it usually does when the character files are messed with? The one where it just says "end" and shows Sayori hanging herself when you open the game.

**Comment by Jxhnathan08** [comment]
No. Monika doesn't run on the .chr file like she did in DDLC. Deleting it without the easter egg implemented would just remove the .chr file from _your_ downloaded copy of MAS. 

I've tried deleting it before, so.

**Comment by TheKaiSenpai** [comment]
It would be interesting if you could possibly allow other characters to "visit" Monika by temporarily moving their .chr file into the characters folder, or at least have them pop in every now and again.  Though perhaps that would take away from the "Just Monika" aesthetic.

**Comment by therationalpi** [comment]
I want to be cautious in messing with the .chr file stuff, since adding/removing those can potentially mess up the experience if a player decides to revert our mod.

**Comment by therationalpi** [comment]
Closing this for now, but we might come back to this idea for an easter egg in the future.
