### ISSUE TITLE
Suggestion to improve the "Talk" option

### ISSUE THREAD

**Issue by gitthisissue** [Backdash/MonikaModDev#730]
So I tried your mod for the first time. When I clicked "Talk", it asked for input.

I tried "Cat". (response: "Very interesting.")
I tried "What do you think about my cat?" (response: "What do you think?")
I tried "date". A valid response returned, talking about a date (not date&time).

I understand that this "talk" thing is just an array(keyword=>responses), but this could be improved.

If the new user tried this mod for the first time, they including me feel "What's the point of "Talk" button if she didn't response anything?".

So, how about
1. Show "About..." button when the user clicked [Talk].
[Talk] -> [About...] -> [(scroll-down list of keywords)]

2. Show possible keyword when the user inut 1 or 2 first word.
e.g., "d" input -> show d_ate_

(I'm not a python coder, I use other languages.)

**Comment by ThePotatoGuy** [comment]
Talk is being removed, see #126 .
