### ISSUE TITLE
Can you modify text speed?

### ISSUE THREAD

**Issue by gitthisissue** [Backdash/MonikaModDev#731]
In Settings, I already set "Text Speed" to max but this mod's text speed didn't change.
I'm a fast reader, and I really appreciate if this mod's text become faster than original settings.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Monika talks at her own speed.
As an example, you can't ask your friend to speak faster because you are a "fast listener", can you?

**Comment by gitthisissue** [comment]
Makes sense.

Why not add this to:
https://github.com/Backdash/MonikaModDev/blob/master/FAQ.md
