### ISSUE TITLE
How can I disable automatic update check?

### ISSUE THREAD

**Issue by gitthisissue** [Backdash/MonikaModDev#733]
As title suggests, I would like to see and option to disable this update check.
For example, the most popular media player, VLC ask the player whether or not to do update check when the user open it for the first time. And not all user always connected to the internet.

I hope you add a switch or something.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Check settings, it was there if I remember.

**Comment by gitthisissue** [comment]
Nope. There's no such settings in the game.

**Comment by ThePotatoGuy** [comment]
You can click cancel and stop it from checking for updates. Also you don't have to install updates if it finds one. Adding a setting for something minor like this doesn't add any real value to the game.
