### ISSUE TITLE
[Suggestion] - pokemon refresh but for Monika!

### ISSUE THREAD

**Issue by sookavitch** [Backdash/MonikaModDev#736]
Will it be possible for us to be able to pat Monika like how pokemon refresh in pokemon sun and moon does? 
Probably a new box can be added alongside "talk" "music" and "play" and it can be called something like "interact"
The idea is for the pointer to become a mini hand that can 'touch' Monika 
In pokemon refresh, there are areas on the pokemon's body that they will like when pet, especially like it or really hate it: in Monika's case it can be:
1. Any part being touched she will like it
2. Stroke her hair she will love it
3. Banned areas will prompt a dialogue of her not liking it
Dialogue wise, probably on the first time we utilize the interact function she will feel surprised on something that apparently touched her from nowhere being the mini hand and a dialogue will be initiated where she will recognise the player is trying to initiate physical interaction that will otherwise be impossible to be done and appreciates it. If possible, facial expressions can also be added it similar to pokemon refresh when the pokemons are happy or sad depending on where the player tried to interact physically. 
I mean this is the closest way i can think of for the player to be able to reach Monika and make her happier i guess
Thank you guys for this amazing mod

**Comment by JustinHerschel** [comment]
I think most people would find this function a bit creepy. Not to say that it is a bad idea, but it would be a bit weird to pet a person like you would a Pokemon.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I like the idea but with Ren'py's very basic animation potential would it even be possible?

**Comment by ThePotatoGuy** [comment]
#1161 will be the main issue for all things related to clicking monika
