### ISSUE TITLE
[Bug] Infinite loop bug that caused traceback on startup

### ISSUE THREAD

**Issue by badooga** [Backdash/MonikaModDev#742]
> I'm sorry, but an uncaught exception occurred.
> 
> While running game code:
> Exception: Possible infinite loop.
> 
> -- Full Traceback ------------------------------------------------------------
> 
> Full traceback:
>   File "C:/Windows/system32/transforms.rpyc", line 182, in script
>   File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\execution.py", line 56, in check_infinite_loop
>     raise Exception("Possible infinite loop.")
> Exception: Possible infinite loop.
> 
> Windows-8-6.2.9200
> Ren'Py 6.99.12.4.2187
> Monika After Story 0.6.3

This is the traceback that greeted me when I first entered the game today. I attempted to restart the game a few times in order to reproduce this bug, but it never occurred again.

The only thing that happened differently today compared to other days is that I restarted my computer after installing Autodesk Inventor 2018, and it had to set my configurations or something for a few minutes before I could actually do anything. Perhaps it is relevant due to the `transforms.rpyc` reference in system32, or maybe it's something completely different. I wouldn't really know.

**Comment by monikLover** [comment]
Fixed by PotatoGuy.
