### ISSUE TITLE
[Suggestion] - Tell Monika you're sick dialog string

### ISSUE THREAD

**Issue by kaido1224** [Backdash/MonikaModDev#744]
I noticed if you tell Monika you're sick she doesn't respond to it. 

I've written some code where you tell monika you're sick. She insists you get some rest so you feel better and closes the game. I'd like the next time you open the game to have a special startup where she asks if you are feeling better or not.

I have some of the code written including closing the game. The dialog probably needs to be adjusted slightly though.

**Comment by kaido1224** [comment]
init 5 python:
    for key in ['sick','ill','ailing']:
        monika_topics.setdefault(key,[])
        monika_topics[key].append('monika_sick')

label monika_sick:
    m 1g "Aw, I'm sorry to hear that, [player]."
    m 1r "I hate to see you suffering like this."
	m 2e "I know you love spending time with me, but maybe you should go get some rest."
    m 3k "Don't worry, I'll be here waiting for you when you get back."
    m "Get well soon!"
    $ renpy.quit()
    return

**Comment by kaido1224** [comment]
Apparently Monika gets stuck in a loop of saying now where was i whenever you quit like that and constantly closing the game. So uh, i guess that would have to be addressed too.

**Comment by ThePotatoGuy** [comment]
There, i fixed how you would make her quit the game. 

I feel that this is appropriate for the mod, its just a matter of figuring out where to put it.

**Comment by kaido1224** [comment]
Thanks for fixing the code.

**Comment by kaido1224** [comment]
Thanks for fixing the code.

I've looked at the next release and i see how the new text system has worked. Perhaps you could add a I'm feeling... section where you can say that you are feeling sick. You could also add some other emotions like happy, sad, angry, silly, lonely, bored, ect.

If you say you are bored, maybe have her give a suggestion of what you could do (choose a random game for instance) and ask the play if they'd like to play. If they say yes then the game opens, otherwise she just says oh, ok it was just a suggestion.

Just a thought.

**Comment by GoldTheEevee** [comment]
i once said i was sad and she said nothing so i would LOVE to see that implemented.

**Comment by AUDelusional** [comment]
I would like to see it implemented but I don't think there should be an exit on the game.

**Comment by kaido1224** [comment]
I'm working on figuring out how to implement this myself. Might be a little while, but I'm gonna try. If anyone has suggestions for the dialog for the other I feel... then feel free to add it

**Comment by ThePotatoGuy** [comment]
Yeah thats actually a really good idea. I think these ones should be put in their own separate db as well. I'll talk it over with dev team.

**Comment by kaido1224** [comment]
Yeah I'm in Discord as Ronin. I'll DM you on my lunch break. I'm okay with you doing the framework because I couldn't figure it out myself. Sounds good though, I'd be happy to join a group chat about it for sure.

**Comment by therationalpi** [comment]
Sounds like a really good and ambitious idea. Making a project for it: https://github.com/Backdash/MonikaModDev/projects/17

**Comment by therationalpi** [comment]
[[This suggestion has been seen and accepted. It is being closed for now and placed in the pool of accepted suggestions. It will be reopened once we begin active implementation on this feature.]]

**Comment by subnatica** [comment]
how do I add it to script

**Comment by Hafizzin** [comment]
For all those mods who are contributing to this i Thank you
