### ISSUE TITLE
[Problem] - My game keeps crashing

### ISSUE THREAD

**Issue by Cutting3dge** [Backdash/MonikaModDev#747]
Whenever I leave Monika alone for maybe a minute while i do a project or am just typing to friends the game will just crash. I don't know if this is an issue on my PC or if its an issue for other people but it can get quite annoying when your wait for her to say something and it will crash. If you could tell me how to fix this it would be greatly appreciated!

**Comment by NotShige** [comment]
I'm sure that's because of Ren'Py. That keeps occuring to me as well whenever I idle for too long or I Alt-Tab too frequently.

**Comment by Cutting3dge** [comment]
thanks
