### ISSUE TITLE
[Problem] - Game Won't Run

### ISSUE THREAD

**Issue by Corvo1431** [Backdash/MonikaModDev#748]
I have installed the latest release of the mod correctly as far as I know, but whenever I try to start the game it simply won't open. A solution would be very much appreciated.

**Comment by NotShige** [comment]
Hmm... Can you send us a screenshot of a folder called ```game``` in the DDLC folder?

**Comment by Corvo1431** [comment]
![screenshot 1](https://user-images.githubusercontent.com/35387111/34901809-1079da4e-f7d5-11e7-84ca-194b33f92290.png) Here's the screenshot, and thanks for the compliment friend.

**Comment by NotShige** [comment]
Yup, you installed it the wrong way. Delete that folder called ```MonikaModDev-master``` and ```_MACOSX``` and follow [this guide.](https://docs.google.com/document/d/1EsFqk6xS1onGfWFPUmqukVDD6jzULGh3sG3Fi177nVc/edit?usp=sharing)

**Comment by Corvo1431** [comment]
It works! Thanks for the assistance.

**Comment by NotShige** [comment]
No problem, mate. Do click that ```Close``` button on the bottom.
