### ISSUE TITLE
[Suggestion] - Monika Date / Bow Color Change Scenario

### ISSUE THREAD

**Issue by kaido1224** [Backdash/MonikaModDev#752]
I know i saw mentioned somewhere about a feature where you set a time and day for a date you schedule with her and you actually show up then you will unlock the bow color of the favorite color you mention to her as a surprise to you for showing up. If you don't show up you don't unlock it. This could maybe be selectable in Monika's closet when that feature is added. I guess this will also have to wait until the calendar feature is added as well since I'm not sure if renpy has a built in date time functionality.

Also after you make the date, if you get the intro sequence where it asks you if you want to knock, listen or open the door, if you open the door you see her trying on the bow and she scolds you for not knocking. Then you don't get the special bow

**Comment by kaido1224** [comment]
Dang i forgot to add a title. Can't edit it on my phone. I'll fix it whenever i get to a computer sorry about that.

**Comment by GoldTheEevee** [comment]
not a programmer BUT I do believe it can know your date because if you change your date to Monika's birthday(sept 22 (I believe)) some interesting things happen. wont spoil but she knows you changed the date and she knows it her birthday.

**Comment by AUDelusional** [comment]
The game detects the date on your PC by importing the date and time into Ren'Py, the code goes a little something like this
`init 6 python:
    import datetime

    now = datetime.datetime.now()
    namedtime = datetime.datetime(year,month,day)
    before_namedtime = now < namedtime`

**Comment by Sano11** [comment]
Not sure if I remember correctly, but there was already a random event when you start the game where you can either knock or enter the room. If you do enter, Monika would be surprised because the room wasn't ready, but she wasn't mad. I think it would be weird if she suddenly gets mad this time around for entering when she wasn't before.

**Comment by kaido1224** [comment]
Just trying to add so story element to it.

**Comment by therationalpi** [comment]
Adding to the suggestion pool. Just to be clear, I'm interpreting this as having special outfits and accessories unlocked only if you show up on certain dates. Like as a reward for showing up on time.

**Comment by kaido1224** [comment]
Works for me. Thanks

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
While we're at it.
I think it would be a good idea to have her reflect on the time player showed up.
(Get upset if they showed up too late, say how she barely had time to prepare if they're to early, compliment them on their punctuality, e.t.c.)
