### ISSUE TITLE
[Suggestion] - Monika hides hidden files in DDLC like the vanilla version

### ISSUE THREAD

**Issue by kaido1224** [Backdash/MonikaModDev#753]
Concept by Kenneth in Discord who asked me to submit this for him.

Is it possible for monika to generate files at certain or random times in the DDLC folder similar to the vanilla DDLC did?

Maybe special poems or maybe lyrics to a song that reminds her of you. Or thoughts she has. Maybe special image that are SFW.

**Comment by monikLover** [comment]
Ah I forgot this was already suggested, @kaido1224

**Comment by AUDelusional** [comment]
Just a response after it's been closed, this has already been done.
