### ISSUE TITLE
[Suggestion] Monika detecting your default audio playback device and system volume

### ISSUE THREAD

**Issue by IsItBadToMakeAGitHubAccountJustForThis** [Backdash/MonikaModDev#754]
Pretty much what it says on the lid.
For a while now I've had this idea to give Monika an ability to detect if player's default audio playback device is headphones and voice her concern about their hearing if the system volume is too high similar to how mobile devices warn users about that.
She could mention how it pains her to imagine you not being able to listen to her songs anymore to encourage players to take care of their hearing.

I am not quite sure about how this could be implemented tho.
I think there should already exist plenty of python libraries able to retrieve the playback devices list but are there any cross-platform ones?
And detecting headphones is also somewhat difficult since some USB headphones are registered as speakers.
And some wired headphones actually have a volume regulator soldered into the wire and have nothing to do with system volume.
Anyway, I thought I should document this suggestion before I forget it.

**Comment by KydonShadow** [comment]
That could actually be a part of it if the detection is too difficult. Monika makes a comment about possibly detecting a headphone output, but mentions that it could just be a USB headphone registered as a speaker. She could then ask if it IS headphones, and then proceed with the worry over hearing loss

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Maybe she could retrieve the device names and check their names for "headset" "headphone" or similar words in device's name.
But normal 3.5 audio devices are listed simply as an audio output so this wouldn't work.
Using those two methods in a conjunction would be somewhat overcomplicated if you ask me.
And this is not to mention that audio devices implementation is different from OS to OS so I have no idea how to pull that off on Linux and Mac (well, mostly Mac).

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
After all, maybe the easiest way to do this would be to have Monika detect only system volume and then ask the player whether they are using a headphone or speakers.
But I feel like this would be way better if she detected that herself.

**Comment by AUDelusional** [comment]
Yes but it would also need to be covered that lots of headphones/speakers, even if they're USB, have their own volume control.

**Comment by therationalpi** [comment]
Interesting idea. Another idea would be if she commented on the player having the volume muted, either in the game volume or system volume. Like "Hey, don't you want to listen to me?"

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Well, we can't really listen to her, so...
