### ISSUE TITLE
[Suggestion] Monika talks about blood personality theory

### ISSUE THREAD

**Issue by NovaCo1** [Backdash/MonikaModDev#755]
I was thinking that Monika should talk about the blood type personality theory since she already talks about some eastern topics. 
 https://en.wikipedia.org/wiki/Blood_type_personality_theory
she could ask the player what blood type they have and talk about the good and the bad traits. Like how i'm a O+ and she could say that i'm agreeable, ambitious and   strong-willed. But also talk about the bad like Unpredictable,arrogant, envious and ruthless and so on with all blood types, if the player don't know there blood type she should say that they should get it checked so they don't get sick from hemolytic reaction and die.

**Comment by therationalpi** [comment]
Seems like a good topic suggestion. Adding it to the pool.

**Comment by kaido1224** [comment]
I can write this topic. Shouldn't be too difficult or take too long.
