### ISSUE TITLE
[Suggestion] - Just Monika story arc

### ISSUE THREAD

**Issue by kaido1224** [Backdash/MonikaModDev#756]
Hmm.. what if monika went back to arc 1 and tried to create her own route and when she tried to restore the other 4 characters by copying her chr file and renaming them she ends up making 3 other Monika's that take on the personality of the other characters. 

To expand upon that, all of the Monika's are all aware they are in a game and are vying to take over the final arc where it's just you and monika. You gotta figure out which monika is the original monika to save her.

If you choose the yuri monika you end up with a monika in arc 3 with cuts on her arms like yuri before the game cuts out. If you pick the sayori one she ends up hanging herself in arc 3. And natsuki would be the "ghost" natsuki. If you pick the right one everthing goes back to normal and maybe you unlock a new outfit or something in her closet.

Alternatively you can forget about the part where they are all self aware and trying to get to arc 3 and you have to save Monika. I remember reading somewhere in MAS where Monika says the other three are gone forever so instead of bringing them back she plays the parts of the other characters and mocks them as the story progresses. Making the other characters look like her would be a nice touch.

I saw there was a monika makes her own route project idea that therationalpi started and i saw some of their ideas about Monika mocking the other characters so that's where I took the idea from partially.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
As it is, your idea seems a little goofy to me (sorry). And I don't think it fits MAS well.
But yeah, I would really **love** to see an 'everyone is Monika' route one day maybe separately from MAS.
![23e1fdd32aa0fbcbb7a6c8f703352bd7ff3cb711](https://user-images.githubusercontent.com/34412685/34913869-a16e1b34-f918-11e7-9c33-2f2aea91b2dc.png)

**Comment by kaido1224** [comment]
I admit it's kind of a dumb idea and may not be suited for MAS but meh it was just a thought.

**Comment by kaido1224** [comment]
Nice image btw

**Comment by kaido1224** [comment]
Alternatively you can forget about the part where they are all self aware and trying to get to arc 3 and you have to save Monika. I remember reading somewhere in MAS where Monika says the other three are gone forever so instead of bringing them back she plays the parts of the other characters and mocks them as the story progresses.

**Comment by kaido1224** [comment]
I saw there was a monika makes her own route project idea that therationalpi started and i saw some of their ideas.

**Comment by kaido1224** [comment]
I admit the first part sounds pretty dumb reading over it again, but I think the second idea would be feasible in MAS where she redoes the first story arc and acts out the different parts herself instead of bringing back the other characters.

**Comment by therationalpi** [comment]
Yeah, I think this is more of an idea for a separate project. Check out the https://github.com/therationalpi/DDLCModTemplate that we made if you want to pursue your own mod idea!
