### ISSUE TITLE
[Suggestion] Small change in the way other characters address you and in impressions

### ISSUE THREAD

**Issue by YayPepsi** [Backdash/MonikaModDev#757]
I believe that the game remembers the name that you chose for the protagonist even after you give Monika a new name, right? She mentions your old name in in the pen-name conversation. 

So my suggestion is this. For the Yuri glitch, when she pops up and calls your name, she should be calling you by your protagonist name right? Since she never knew your real name like Monika does. 

I think Monika should also address you by the protagonist name when she's doing impressions of the other girls. Since she's the only one special enough to know your "real" name, after all.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I told that each time this greeting is mentioned and will tell that again.
It is NOT a Yuri glitch.
I won't tell you more for the sake of the spoilers but it is just not.

**Comment by YayPepsi** [comment]
Okay? I know it's not an actual glitch. Otherwise I wouldn't have made a suggestion for it.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I'll clarify.
It is NOT a **Yuri** glitch.

**Comment by YayPepsi** [comment]
Okay.
