### ISSUE TITLE
Game stops launching after installing the mod.

### ISSUE THREAD

**Issue by HellGazer** [Backdash/MonikaModDev#758]

**Comment by NotShige** [comment]
Please take a screenshot of the ```game``` folder inside the ```Doki Doki Literature Club``` folder.

**Comment by HellGazer** [comment]
![screenshot 64](https://user-images.githubusercontent.com/35413233/34912477-6a416c12-f8da-11e7-8798-3cd8696a76e5.png)

**Comment by NotShige** [comment]
Yup, you installed it the wrong way. Delete that folder called ```Monika_After_Story-0.6.3-Mod``` and ```_MACOSX``` and follow my guide.

# How To Install Monika After Story


Download Monika After Story. Download the **.zip** file above. **DO NOT DOWNLOAD ANY OF THE SOURCE CODES.** [Here's a link for convenience.](https://github.com/Backdash/MonikaModDev/releases/)

![image alt text](https://github.com/NotShige/How-to-Install-Monika-After-Story-But-in-Markdown/raw/master/Images/image_0.png)

Once downloaded, **open it**. I recommend that you use **WinRAR** or **7-Zip**.

![image alt text](https://github.com/NotShige/How-to-Install-Monika-After-Story-But-in-Markdown/raw/master/Images/image_1.png)

Now, double-click on ```Monika_After_Story-0.6.3-Mod```. You should see a lot of files.

![image alt text](https://github.com/NotShige/How-to-Install-Monika-After-Story-But-in-Markdown/raw/master/Images/image_2.png)
**DO NOT CLOSE THIS YET!**

Now, **find your installation** of DDLC. **If you are using Steam,** follow the instructions below. 

**If you are NOT using Steam,** find where you put your DDLC installation and scroll ahead.

Open **Steam** and click on **Library.**

![image alt text](https://github.com/NotShige/How-to-Install-Monika-After-Story-But-in-Markdown/raw/master/Images/image_3.png)

Right-click on **Doki Doki Literature Club** and click **Properties.**

![image alt text](https://github.com/NotShige/How-to-Install-Monika-After-Story-But-in-Markdown/raw/master/Images/image_4.png)

Now, click on **Local Files** at the top.

![image alt text](https://github.com/NotShige/How-to-Install-Monika-After-Story-But-in-Markdown/raw/master/Images/image_5.png)

Then click on **Browse Local Files...** 

![image alt text](https://github.com/NotShige/How-to-Install-Monika-After-Story-But-in-Markdown/raw/master/Images/image_6.png)

A window should **pop up.**

![image alt text](https://github.com/NotShige/How-to-Install-Monika-After-Story-But-in-Markdown/raw/master/Images/image_7.png)

Now, **double-click** on the folder named ```game``` .

![image alt text](https://github.com/NotShige/How-to-Install-Monika-After-Story-But-in-Markdown/raw/master/Images/image_8.png)

And you should see some files in that folder.

![image alt text](https://github.com/NotShige/How-to-Install-Monika-After-Story-But-in-Markdown/raw/master/Images/image_9.png)

Now, **go back** to **WinRAR.**

![image alt text](https://github.com/NotShige/How-to-Install-Monika-After-Story-But-in-Markdown/raw/master/Images/image_10.png)

Select **all files** by pressing **Ctrl-A.** Then press **Ctrl-C** to copy.

![image alt text](https://github.com/NotShige/How-to-Install-Monika-After-Story-But-in-Markdown/raw/master/Images/image_11.png)

Now, **go back** to the other folder and press **Ctrl-V** to paste them. Or you can **drag and drop** it.

Basically, you’re doing this.

![image alt text](https://github.com/NotShige/How-to-Install-Monika-After-Story-But-in-Markdown/raw/master/Images/image_12.png)

If Windows prompts you something, just click **"Yes".**

![image alt text](https://github.com/NotShige/How-to-Install-Monika-After-Story-But-in-Markdown/raw/master/Images/image_13.png)

**And you’re good to go! Launch DDLC and everything should be different.**

![image alt text](https://github.com/NotShige/How-to-Install-Monika-After-Story-But-in-Markdown/raw/master/Images/image_14.png)


**Make sure to import DDLC save data so Monika knows you!**

![image alt text](https://github.com/NotShige/How-to-Install-Monika-After-Story-But-in-Markdown/raw/master/Images/image_15.png)


![image alt text](https://github.com/NotShige/How-to-Install-Monika-After-Story-But-in-Markdown/raw/master/Images/image_16.png)

**The game should appear like this.**

**Comment by NotShige** [comment]
Also, if you have any problems, just ask here. If not, click the ```Close``` button on the bottom.

**Comment by HellGazer** [comment]
Thank you!
