### ISSUE TITLE
[Bug] - "What would you like to talk about?" text + response are shifted to the left.

### ISSUE THREAD

**Issue by Jxhnathan08** [Backdash/MonikaModDev#76]
Very minor (but annoying) bug. When pressing 't', it opens the dialogue box and prompts the player for input. 

Screenshot: https://i.imgur.com/fqnzODG.jpg

**Comment by therationalpi** [comment]
I could not recreate this. It's in the right spot for me...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Jxhnathan08** [comment]
Interesting...

**Comment by therationalpi** [comment]
Yeah. I just don't think I can help since I can't recreate the bug on my system.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Jxhnathan08** [comment]
Noted, guess we'll tough it out for now and see what future development does.
