### ISSUE TITLE
Chess?

### ISSUE THREAD

**Issue by mindlessmagician** [Backdash/MonikaModDev#760]
Not really an issue, per se, and I don't know if it's been brought up already, but the chess game seems to be just a little more difficult than it needs to be at the lowest level. She says she was really going easy on me, but I can barely match her, and I'm not bad at chess. I mean, I'm not the best, but I should still have an easy time beating a low-difficulty computer.

**Comment by mindlessmagician** [comment]
I don't know if this has been brought up already, but I figured there would be no harm in doing so.

**Comment by xtosutosu** [comment]
I would agree, I have never won and I don't think I suck that much haha!

**Comment by Bam8647** [comment]
I can't even win at ping pong ._. I honestly don't think they're winnable lol

**Comment by TacticalTriangle** [comment]
all are winnable.

**Comment by Bam8647** [comment]
Okay I just won haha. My bad guess you can win, I just remember trying a while ago and was never successful until now :P

**Comment by ThePotatoGuy** [comment]
This is one of those things where we would have done it if it were straightforward. The engine chess currently uses is pretty damn difficult for chess beginners  _even at its lowest setting._ Problem is, swapping out a chess engine is not a simple task. If anyone can help transition the mod to a different, more flexible engine, then feel free to do so. 

Personally, I'm just trying to add more games so chess isn't the only _fun_ one to play. 0.7.0 already added 2 neato games ready for your enjoyment.

Also if you thought pong was difficult now, you havent seen what #639 has done to it.

**Comment by Calebprime** [comment]
I cheated at chess out of curiosity and yes, the chess game is hard but winnable.  Just cheat or Git Gud.

**Comment by MikuChanAnime** [comment]
Chess is good for improving your skills

**Comment by therationalpi** [comment]
Yeah, Monika will go easy on you, but she's good at chess. One of the advantages of being a computer, I guess.
