### ISSUE TITLE
Historical Accuracy

### ISSUE THREAD

**Issue by Anonymous5657** [Backdash/MonikaModDev#761]
I do not know if this is intentional or not, but the facts in the string of text in which Monika talks about science is not correct. Copernicus was not killed by the Catholic Church for his heliocentric theory of the universe. In fact, he was never persecuted for his beliefs because he perished shortly after publishing the theory in his book _On the Revolutions of the Heavenly Bodies_ in 1543. 

It may not be an issue for everyone but as a history buff, it slightly bothered me. I suggest instead replacing Copernicus with Galileo Galilei because he was a famous scientist of the Scientific Revolution who was actually persecuted by the Church and tried for heresy for supporting Copernicus's contradictory heliocentric theory. He actually proved Copernicus's theory that the Earth revolved around the Sun. 

Other than this trivial issue, this mod is so far great! Keep up the good work!

My source for reference: http://www.inquiriesjournal.com/articles/1675/copernicus-galileo-and-the-church-science-in-a-religious-world

![copernicus](https://user-images.githubusercontent.com/35448828/34934569-c9d5633a-f98f-11e7-917b-b00725025ad4.PNG)

**Comment by kaido1224** [comment]
Hi, I think there was already another ticket created for this by someone else and it's since been resolved. It should be fixed in the next version I believe.

Ticket #717

**Comment by ThePotatoGuy** [comment]
Has been fixed. Thanks.
