### ISSUE TITLE
[Suggestion] - Play Janken (Rock Paper Scissors) with Monika

### ISSUE THREAD

**Issue by kaido1224** [Backdash/MonikaModDev#762]
Not sure how fun this would be to anyone but just a thought.

http://jet.wikia.com/wiki/Janken

I'm sure this would be fairly easy to program, the graphics might be a challenge though.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Is usual RPS not good enough anymore?

**Comment by kaido1224** [comment]
Works for me, was just going with the whole Japanese thing.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Doesn't Monika herself mention that the game is kinda supposed to be set in Japan but in actuality feels more like US?
BTW there is already an issue opened for game suggestions.

**Comment by kaido1224** [comment]
dang it. I'll close it then as a duplicate. Thanks for letting me know.

Yeah she does mention it in Vanilla DDLC.

**Comment by kaido1224** [comment]
duplicate of #55

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I was sure there is one big issue for all the game suggestions tho.
Am I starting to imagine things?

**Comment by kaido1224** [comment]
No, it was on ticket #55.
