### ISSUE TITLE
[Suggestion] Compliments and going on a date

### ISSUE THREAD

**Issue by cordwill** [Backdash/MonikaModDev#763]
responses for complementing her, like saying something about her eyes and hair and just other general flirty things. Dates would be cool, like what was did with the Christmas thing, but the environment gets changed depending on what type of date if that would be possible, and maybe even an outfit change for different types of dates.

**Comment by kaido1224** [comment]
In the next version the chat bot is changing from a keyword based one to a a menu based one. I don't think there is anything built in currently for complementing her, but I don't think it's a bad idea to add such a thing though. Up to the devs though.

**Comment by therationalpi** [comment]
Great suggestions. Adding them to the pool.

Just to be clear, here are the two suggestions:

* More topics where you compliment Monika on stuff

* Major events where you go on a date with Monika, and she dresses up for the occasion/decorates the room
