### ISSUE TITLE
Illogical responses

### ISSUE THREAD

**Issue by ddlcisbestgame** [Backdash/MonikaModDev#767]
When I was playing just now, Monika brought up the 'orchestral music' topic, where she asked me if I listened to orchestral music, before asking me if I played an instrument. I selected 'Yes', and she wanted to know which instrument it was, so I typed in 'piano', an instrument which she coincidentally also plays as we learn through the storyline. However, she then began to talk about piano as if she had never played it before ('Wow, I've always wanted to try the piano out'). Lastly, she also says: 'Oh! Would a duet between the piano and the piano sound nice?'. Those responses could work for other instruments, however in the case of the piano they do not make sense and should be adjusted accordingly. Thanks

**Comment by MikuChanAnime** [comment]
The dialog tree doesn't branch out like that.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
It is already fixed. Wait for the next build.

**Comment by kaido1224** [comment]
Beat me to it @IsItBadToMakeAGitHubAccountJustForThis. I was just about to paste the code in saying it was fixed in version 7, but I guess it's not necessary.
