### ISSUE TITLE
Event Labels in next release script-topics.rpy assigned to wrong labels.

### ISSUE THREAD

**Issue by kaido1224** [Backdash/MonikaModDev#769]
I was looking through the script-topics.rpy in the upcoming release and noticed a few of the topics have the wrong event labels.

Notably - 
```
init 5 python:
    addEvent(Event(eventlabel="monika_mentalillness",category=['random'],prompt="Monika's route",random=True))

label monika_route:
```

and 

```
init 5 python:
    addEvent(Event(eventlabel="monika_horror",category=['drinks'],prompt="Yuri's wine",random=True))

label monika_wine:
```

If I come across any others I'll let you know.

**Comment by therationalpi** [comment]
Good catch.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I caught two or three instances of that in #713 but forgot to mention it.

**Comment by kaido1224** [comment]
I'll go through the scripts again today and see if I can find any others and report them here @IsItBadToMakeAGitHubAccountJustForThis, I got you.

**Comment by kaido1224** [comment]
Made a pull request for this in Content.

I went through script-topics.rpy and didn't see any others off hand.

https://github.com/Backdash/MonikaModDev/pull/779

**Comment by kaido1224** [comment]
The changes have been merged so I'm gonna go ahead and close this.
