### ISSUE TITLE
[Bug] - Main Menu button doesn't give message box.

### ISSUE THREAD

**Issue by Jxhnathan08** [Backdash/MonikaModDev#77]
This was present in the master branch. When attempting to exit to the main menu, Monika was supposed to pop up a dialogue box telling the player they'd just end up back in the space room. 

However, due to the mod template, this no longer works.

**Comment by ThePotatoGuy** [comment]
Does it just not do anything when you hit main menu or does the regular "you will use unsaved progress" dialogue show up?

I tried exiting to main menu and received the "unsaved progress" dialogue, and when when accepted, the game crashed upon trying to load a label that didn't exist.

This could be related.

**Comment by therationalpi** [comment]
This is was fixed in screens.rpy which is not included in lightweight...

https://github.com/Backdash/MonikaModDev/commit/d5a2453c791bb34927af93a4564cd30e68dc5b39 

I think this might be a good opportunity to test out using overrides.rpy, since it's a one line fix and is a silly reason to include the full screens.rpy file

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Jxhnathan08** [comment]
Not entirely sure how overrides.rpy works, but I'll mention it in the Discord and see what others come up with.

**Comment by therationalpi** [comment]
Actually, if you bring over screens.rpy over from master it should fix both this issue and the input box issue.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Jxhnathan08** [comment]
Would we be allowed to do so?

**Comment by therationalpi** [comment]
Yeah. We'll probably be changing more in there in the future anyway. I'll still try to keep my eyes open for a chance to use overrides

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Jxhnathan08** [comment]
Working on it now.

**Comment by therationalpi** [comment]
Importing screens.rpy fixed this. closing this issue
