### ISSUE TITLE
Other games with Monika

### ISSUE THREAD

**Issue by TCBroBott** [Backdash/MonikaModDev#772]
I know that this is either impossible or too difficult to do, but... Monika talks about playing 'other games' with you, outside of ddlc. I was wondering if there was actually any work being put into making something like this happen, or if it was just a few throwaway lines or something. I'm not sure what kind of games we would have her be in though, I honestly haven't played enough "non-shooty" games to know what Monika might fit into or enjoy... But I would certainly find it very interesting and **SUPER AWESOME** if something can be made out those few lines.
**IDONTCAREWHATGAMEITSFORILLBUYITNOMATTERWHAT**
I know it's REALLY out there, and probably won't happen but if it hasn't been considered yet, I think it really needs to be. help us lonely brothers out.

**Comment by kaido1224** [comment]
There's reference to at least 1 other game out there already. It checks to see if game data is present in a specific folder and if it senses it she will make a comment about it. I don't think there is specifically an effort to add more dialog of this nature at this time. Monika states that she's not particularly a big fan of videos games. If people contribute some dialog I'm sure it will be taken into consideration though.

**Comment by therationalpi** [comment]
There are more games coming in the future. Specifically hangman and a piano playing game. We'll probably add more in the future that encourage you to hang out with monika and enjoy her company. Word-based games are especially fitting for the prez of the literature club.
