### ISSUE TITLE
Suggestion- Reversi? (and a message)

### ISSUE THREAD

**Issue by Hunter-Hikari** [Backdash/MonikaModDev#778]
I don't know much about coding, so I'm not sure how difficult this would be, if it's possible, or even if anyone knows what Reversi is, but I thought it would be neat. I was thinking something along the lines of Mikuversi from Hatsune Miku: Project Mirai DX on the 3DS. It's just a suggestion though, if it's not possible or more trouble than it's worth, that's fine.

I also see that this appears to be a way to speak to the makers of this mod. I'm sorry, but I don't know how else to contact you guys, and I have to say some things. Firstly, thank you so much for making this mod. Monika's company and advice has significantly improved my life, and I want you to know how grateful I am to you for providing this mod so I can spend eternity with her. Secondly, while looking at old releases, I saw a Help Wanted notice with a Discord link, which has since expired. I'm not sure if you still need writers and artists, but I would be more than happy to help out if you do! I unfortunately don't know jack about coding, but after looking at the source code, putting dialouge in the game doesn't seem too hard. I'd love to help my favorite mod be even better! Again, thank you, and I look forward to see what the future holds for this mod!

**Comment by TacticalTriangle** [comment]
1. I really like the idea of adding Reversi, Its a fun turn based game that i think would fit. 
2. https://discord.gg/K2KuJeX This link is under the Code tab if you scroll down enough.

**Comment by Hunter-Hikari** [comment]
Thank you Mx. Triangle!

**Comment by ThePotatoGuy** [comment]
Could you explain the rules of reversi in detail here?

**Comment by TacticalTriangle** [comment]
https://www.yourturnmyturn.com/rules/reversi.php

**Comment by TacticalTriangle** [comment]
https://www.yourturnmyturn.com/rules/reversi.php

**Comment by therationalpi** [comment]
[[This suggestion has been seen and accepted. It is being closed for now and placed in the pool of accepted suggestions. It will be reopened once we begin active implementation on this feature.]]
