### ISSUE TITLE
It wont run!

### ISSUE THREAD

**Issue by Korarin** [Backdash/MonikaModDev#780]
I try to run it, but DDLC will simply not start when this mod is places in the game folder.

**Comment by ThePotatoGuy** [comment]
If DDLC doesnt open, then check `game/` for a folder like `Monika After Story`. If it is there, please take the files out of that folder and put them in `game/`. (The mod files **cannot** be in a subfolder in `game/`). Then delete the folder `Monika After Story`. In addition, delete the files in `game/cache/` to force the game to reload everything/

**Comment by Korarin** [comment]
Thank you!! Now it works, an my conscience is saved!
18 januari 2018 02:35:13 +01:00, skrev ThePotatoGuy <notifications@github.com>:
