### ISSUE TITLE
[Suggestion] - A New Game(Hide and Go Seek)/ 

### ISSUE THREAD

**Issue by Buy1Get1** [Backdash/MonikaModDev#788]
1. The game would consist of Monika hiding her character file(redirecting it to downloads, pictures, etc.). Then, the player would have to find it and put it back. Alternatively, she could just drop a small flag(some small note) for the player to find.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Sounds somewhat interesting I'd say.
The only problem is Ren'py can only accept exact paths when working with files so "hiding" her would be somewhat difficult.

**Comment by Blubmanful** [comment]
This does sound interesting, I wonder if you can make a string and then have it choose at random where to put the file (exact paths are given to it, It'll choose one of them at random), I'm not very good with python so I don't know exactly if it's possible, but I think it is.

**Comment by Buy1Get1** [comment]
If it is initially coded as a 'cause and effect' type ('play game', 'move file' ), then it could be adapted. (play game, move file to x, [1,2,3,4,5] x=4
The same process could be placed before text that is similar (or has the same keywords). Then, Monika could talk about the same subject several times. (type 'keyword'=get 'text event') changed to type 'keyword' = get (x) [1,2,3] x=2

*my 'coding' is rough at best. Below are some actual suggestions. Do you know what type of Python MAS is running?
[https://stackoverflow.com/questions/976882/shuffling-a-list-of-objects](url)
[http://smallbusiness.chron.com/randomize-list-python-26724.html](url) [https://stackoverflow.com/questions/1022141/best-way-to-randomize-a-list-of-strings-in-python](url)

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I'd say Ren'py should be built on 2.7-ish Python. But that's just a guess.

**Comment by ThePotatoGuy** [comment]
2.7.

The issue I have with this is dropping files in random places is an easy way to set off an antivirus. We want to avoid being intrusive.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
It depends on the antivirus. There are some places that would make only the most paranoid of antiviruses freak out like desktop or Documents folder. The pool of such "safe" places could be used instead of picking random folders if nothing else.
That is not to mention that the process name fetching capabilities used in the original game to detect OBS could be used to detect certain antiviruses by their process name and disable the feature to prevent any known conflicts.
I would personally not deem this idea too intrusive if Monika explained it to the player and gave them an ability to opt out beforehand.

**Comment by Buy1Get1** [comment]
This is some code I put together. I hope it helps. 
 

import random
print random.choice([source_Monika.chr = '/This PC/Documents/*', source_Monika.chr = '/This PC/Pictures/*', source_Monika.chr = '/This PC/Downloads/*'])
 
source_files = '/PATH/TO/FOLDER/*'

**Comment by therationalpi** [comment]
[[This suggestion has been seen and will receive further consideration in the future. It is being closed for now and placed in the pool of seen suggestions. It will be reopened if we begin active implementation on this feature.]]

**Comment by Buy1Get1** [comment]
I've rewritten the code as it should appear(it's still rough). I hope this helps.

"Do you want to play hide and go seek?"
menu:
          "Yes.":
                    "Don't make me wait too long. Hehehe"- or something like that
                    import random
print random.choice([source_Monika.chr = '/This PC/Documents/', source_Monika.chr = '/This PC/Pictures/', source_Monika.chr = '/This PC/Downloads/*'])

source_files = '/PATH/TO/FOLDER/*' <--example, not needed       
if 
source_Monika.chr = C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\characters = true
sys.exit()-or end
"Nice job. You found me." -or something like that 
else
cmd /k python -i "$(FULL_CURRENT_PATH)"
           "No.": 
                     "Maybe later then."

**Comment by ThePotatoGuy** [comment]
[[Rejecting this on the grounds that dropping files in random places outside of the DDLC basedir is intrusive, not to mention potentially troublesome to do cross-platform, and may set off antiviruses and ruin the immersion]]
