### ISSUE TITLE
[Suggestion] - Be Able to Describe Your Appearance to Monika

### ISSUE THREAD

**Issue by PMelol** [Backdash/MonikaModDev#789]
Don't know if anyone else thinks this would be a decent feature, but it would be cool if we could describe our hair color, eye color, weight, etc. to her so she has a better idea of what we look like. Then she can comment on how she appreciates each feature, for instance, "Ah, I can get lost in deep brown eyes" etc. etc.

**Comment by therationalpi** [comment]
[[This suggestion has been seen and accepted. It is being closed for now and placed in the pool of accepted suggestions. It will be reopened once we begin active implementation on this feature.]]
