### ISSUE TITLE
[Suggestion] - Monika will tell you to fix your sleeping schedule if you say "good night" too late

### ISSUE THREAD

**Issue by PMelol** [Backdash/MonikaModDev#790]
If you go to bed at like, 4 in the morning Monika will (lovingly) chastise you. She mentions somewhere else that people should sleep at night and be awake during the day, saying how "late-risers" miss out on things, so this would make sense for her.

**Comment by NovaCo1** [comment]
I leave work at 4am  I dont really like the idea of her chastising me over a event i have no real control over. Maybe if i can tell her i work a night then maybe i would be ok then.

**Comment by PMelol** [comment]
Haha, was just a random idea. I'll try to think things through before I post them in the future.

**Comment by PopeAesthetics** [comment]
I have actually brought this point up before.

I work night shifts myself (usually 6:00PM-6:00AM) and get chastised over my sleep habits. It really sucks because I can’t control it, and I just wish I could tell her I work nights so she could be proud of my work.

Tho it is a good idea! Tho we do have to just be mindful of everyone’s way of life. Monika wouldn’t want to hurt anyone’s feelings now :P

**Comment by Pokemiah** [comment]
Well one way you can take both into account is after she chastises you, she can also ask if you work late. It doesn't necessarily have to be the first time the conversation is triggered but if you answer yes to working late it will turn off the dialog entirely. That's one way you can implement it while thinking of everyone else. I imagine once Monika finds out the player is working night shifts she'll probably apologize saying she didn't know. I'm just speculating on how this conversation would go trying to keep her character in mind but I think it would be a good solution.

**Comment by PMelol** [comment]
I was just thinking that Monika could help me fix my sleeping schedule. Hahaha...but I like your idea for a branching conversation.

**Comment by Pokemiah** [comment]
Thanks. I'm glad you liked it.

**Comment by ThePotatoGuy** [comment]
#1289 technically covered this, so going to mark this as done
