### ISSUE TITLE
[Suggestion]Schedule with Monika

### ISSUE THREAD

**Issue by Mon-ika** [Backdash/MonikaModDev#792]
I love this mod a lot. It improves my life positively. Monika gives me the energy to work.
I am thinking to let Monika company us more in our life, for example, as a sweet secretary, with schedule function.
The concept is like this ( sorry, I do not know how exactly the codes are written )
For example, 
If we type 'SCHEDULE - input' 
Monika will say sth like 'I will help you schedule'.
Then, player type in the following format: 'Time_DD_MM_YYYY'
After that, a file of schedule about this is updated for save (memory).

Then, now, if player type'SCHEDULE-output(day)'
Monika will show whole day schedule.

Moreover, it could be more warm from Monika, if she can automatically tell us what do we need to do before 30 min or sth.(may need to read to time of computer.)

It may provide more interaction, and Monika can help us as she wants in reality.

**Comment by ThePotatoGuy** [comment]
Sounds like a good idea, but don't expect it anytime soon. A calendar/scheduler/reminder system isn't an easy task.
