### ISSUE TITLE
[Suggestion] Sing with monika

### ISSUE THREAD

**Issue by queue5** [Backdash/MonikaModDev#793]
I had this idea when messing around with clever bot that when you type in some lyrics to a well known song like "yesterday" by the Beatles, clever bot will sing along. I think it would be pretty romantic to do that and maybe  at the end of the song Monika will comment on the song or the band. Or at the very least you could simply quote a song and she'll react to it.
![screenshot 61](https://user-images.githubusercontent.com/35611448/35169362-e609d514-fd21-11e7-9edf-90789bfd33d2.png)

**Comment by Ulvsblakk** [comment]
I like this idea. I could create a pull request and add in the script. What songs would you like her to have knowledge of?

**Comment by kaido1224** [comment]
Might run into issues of copyright infringement.

**Comment by Blubmanful** [comment]
That’s generally why if we did it it would have to be limited to the song
Your Reality, and then find songs that wouldn’t immediately end up in a
copyright claim.

**Comment by kaido1224** [comment]
Fair point.

**Comment by queue5** [comment]
To answer Ulvsblakk I was thinking really classic love songs especially by the Beatles like "I need you" "you like me too much" and "Till there was you" I doubt there would be any copyright issue's if we're merely quoting a song as well as crediting the artists making them. I didn't mean actually playing the song if that's what you thought. also Is there a way for monika to use the internet to use key words? that way she won't be limited to hand-picked songs and if you are specific enough she'll catch on or make it so if you say "sing (song)" she'll start maybe the first few lines and you go back and forth with her.

**Comment by ThePotatoGuy** [comment]
Talk is being replaced (#126 ), but this might be a good reason to keep some of the functionality.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I'd say that if this feature ever gets implemented it should use the framework similar to #628 where the lyrics would be fetched from a separate text file(s) with more simple and lightweight syntaxis.
A specialized framework would allow for a more flexible implementation, and allowing the users to easily add their own lyrics could solve some potential copyright issues.

**Comment by kaido1224** [comment]
That's not a bad idea.

**Comment by PMelol** [comment]
I do like this idea.

**Comment by therationalpi** [comment]
[[This suggestion has been seen and will receive further consideration in the future. It is being closed for now and placed in the pool of seen suggestions. It will be reopened if we begin active implementation on this feature.]]
