### ISSUE TITLE
Monika's AI

### ISSUE THREAD

**Issue by Ulvsblakk** [Backdash/MonikaModDev#794]
Sorry if this is the wrong place to post this. I couldn't find any way to message a user. I read about the project on turning Monika into a strong AI. I would love to help. I'm relativity new to coding, but I've been picking it up pretty quickly. If you guys need help with it, I'd love to collaborate. 

~Ulvsblakk

**Comment by kaido1224** [comment]
Join the discord server.

https://discord.gg/MRKPk4

**Comment by Ulvsblakk** [comment]
I'm on the server. I can't find anyone though.
