### ISSUE TITLE
[Suggestion] - Music and Dialog

### ISSUE THREAD

**Issue by spikeman168** [Backdash/MonikaModDev#795]
There should be an easy way to add your own music into the game. Like, instead of the basic music, I can add in music into a folder or something, and it would show up on the music menu.
There should also be a way to add your own dialog to Monika, that way, In between updates, people can send tim adding their own personalized dialog, of course, dialog already in the mod wouldn't be editable.

**Comment by Blubmanful** [comment]
From what I remember someone already suggested the first idea, which
couldn’t work because of how RenPY works with its files. The second one can
technically already be done just not through the program itself but by just
editing the script file

**Comment by spikeman168** [comment]
Well, I've looked into the script file, but it's all obfuscated, I can't edit it.

**Comment by kaido1224** [comment]
If you want to edit the files you either need to download a branch in github or decompile the files. The branches in github are already decompiled. 

If the extension is .rpyc it's a compiled file. If it's .rpy it's uncompiled.

**Comment by spikeman168** [comment]
Okay, thanks.
