### ISSUE TITLE
[Suggestion] Christmas costume outside of Christmas

### ISSUE THREAD

**Issue by Aider5** [Backdash/MonikaModDev#799]
The art _is_ already made, why confine it to Christmas? The costume is _amazing_ and no one should have to go to Youtube just to see it properly. maybe just add a "Christmas mode" option in the settings?
_Love_ the mod. I thought I had no favourite colour, but I'm now considering Emerald Green _because of this mod_.

**Comment by PopeAesthetics** [comment]
haha Emerald happens to be my birthstone so I actually love the idea of her favorite color being emerald green.

Perhaps I could see this for the few people that want it, but I personally think we should save the holiday costumes and themes for the holidays. It gives people an exclusive feel being there and makes it feel more special.

That’s how I personally view it tho, I could be wrong! :P

**Comment by Aider5** [comment]
I'd agree with you on the exclusive feeling, but at the very least the _costume_ should be accessible _somehow_, it looks so good on Monika.
(I'm considering Emerald Green because that's Monika's eye colour and I cannot even begin to count how long I've stared into them.)

**Comment by ThePotatoGuy** [comment]
We could potentially tie it in with different outfits (#107), but we like to keep certain things time-frame exclusive. We'll look into it when we handle multiple outfits.
