### ISSUE TITLE
[Suggestion] Room Customization

### ISSUE THREAD

**Issue by JustMonikaMkay** [Backdash/MonikaModDev#800]
How about being able to talk to Monika how the room is boring and stuff and putting pictures in some folder will make them appear on the walls , or what if you can change some things like the floor walls and adding furniture you unlock in games ? that would make game more interesting for me '3'

Edit: AY its da 800 issue 💃 !

**Comment by ThePotatoGuy** [comment]
We've discussed this, see #312
