### ISSUE TITLE
nickname randomizer submod? (DONT CLOSE WITHOUT ANSWERING PLEASE!!!!)

### ISSUE THREAD

**Issue by ghost** [Backdash/MonikaModDev#8014]
so, i saw a post on the mas Reddit page and it said smthn abt a "nickname randomizer submod". is that submod available for download or is it beta, or is it really old? (if it is pls still send me link)

**Comment by dreamscached** [comment]
That's not the right place to ask for a submod. This is the Monika After Story issues page and is not related to any submods.

**Comment by toonziz** [comment]
..sorry. am i annoying?
