### ISSUE TITLE
Monika doesn't appear

### ISSUE THREAD

**Issue by wesdfwws** [Backdash/MonikaModDev#8018]
Another problem I found was when I managed to open the game this message appeared

![Captura de Ecrã (390)](https://user-images.githubusercontent.com/92184364/136623788-a3958f0d-0c83-4e6a-b49a-120b87d88912.png)

I've already looked for these files but they don't exist. And whatever my answers (whether import the saved files or not) the game opens but Monika doesn't appear

![Captura de Ecrã (389)](https://user-images.githubusercontent.com/92184364/136623468-048086bc-1238-4b99-93be-2734991a1de9.png)

**Comment by ThePotatoGuy** [comment]
Was this a first launch or did this just happen out of nowhere?
