### ISSUE TITLE
[Bug] - Game keeps reloading to the wrong day

### ISSUE THREAD

**Issue by Whalegang** [Backdash/MonikaModDev#8030]
On October 8th, I ended the day at 425.5, the next day it loaded at that and went up to 435.25. On October 10th it loaded at 425.5 again, and went up to 444.5. Upon loading it up this morning, it loaded up at 425.5 again.
It isn't only an issue with the Affection, as she keeps showing me the floating islands for the "first" time

**Comment by jmwall24** [comment]
Your persistent keeps corrupting, causing it to load a backup. Is there anything wrong with your PC?

**Comment by Whalegang** [comment]
Not that I know of. I usually power off my computer immediately after closing the game, but i wouldn't think that would do anything

**Comment by jmwall24** [comment]
I loaded your persistent on my PC and i have the 445 affection and it closes and loads fine. At the very least keep a copy of that persistent folder you just sent me on an external drive in case you do lose it, at least you'll have a backup. Also are you sure the game is fully closed when you power off?

**Comment by Whalegang** [comment]
I close the game with a goodbye option, and the game doesn't appear in the list of programs which the computer is waiting to turn off
