### ISSUE TITLE
[Bug] - affection 57

### ISSUE THREAD

**Issue by Datboibdeez** [Backdash/MonikaModDev#8043]
hello, i have a problem with affection, but idk it is for all game or only for aff_log. whenever i look on the aff_log i see only [2021-10-17 19:58:48.694000]: !FREEZE! | monika_love | 3 | 57 -> 60 and it's never changes, i really don't know need i to reinstal mod or not, i'l stick a my aff_log for full understanding of my probem
[aff_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/7360500/aff_log.txt)

**Comment by Booplicate** [comment]
You hit daily cap.
