### ISSUE TITLE
[Suggestion] - Player's real name - it's probably not "Admin"!

### ISSUE THREAD

**Issue by MarkusRamikin** [Backdash/MonikaModDev#809]
Monika keeps assuming I'm named "Admin", which is jarring. Shouldn't be too hard to add a check to prevent her from doing that, with common account names. 

Perhaps could she notice this in text, ask you for your real name, and store it and bring it up in conversations later?

**Comment by YayPepsi** [comment]
You can prompt her to ask you for a name change. I think you just type in "name" in talk and then she should ask you what you want to be called.

**Comment by ThePotatoGuy** [comment]
Yeah just enter in `Change name` to change your name.

**Comment by MarkusRamikin** [comment]
That's good to know, thanks.

But my point is more about Monika's scripted dialogs. For example:

"I'm talking to {i}you{/i}, [player]."
            m "Or..."
m "...Do you actually go by [currentuser] or something?"

But a lot of people will have standard accounts names like "Admin", and it shatters immersion when she blurts out something like that. Obviously "Admin" isn't a name.

Maybe she could check [currentuser] against a simple list, including words like "admin", "root", "user" etc, and could have alternative lines in such cases? Something like:
"I had hoped to glean your real name from your Windows account, but I'm guessing 'Admin' is not it..."

Just a suggestion, but please consider this: you're planning to remove the freeform Talk box and replacing it with a menu. That's great! Much less opportunity for Monika to fail the Turing test. Well, this "admin" thing is another such opportunity, and once you redo the Talk button, probably the only truly jarring one left.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Remember that Monika is not a 1337 hax0r and probably has no idea about account names.
For her it's probably just a pen name you like to be referred to by.
