### ISSUE TITLE
Name of Discord Server, Need Mod Advice

### ISSUE THREAD

**Issue by Bam8647** [Backdash/MonikaModDev#813]
![traceback error](https://user-images.githubusercontent.com/34694679/35197482-503261d4-fea5-11e7-89c5-c972f17d6178.PNG)

Okay so I know I should keep this stuff on the discord board.. but the last invitation I got expired so I was wondering if you guys could provide me the name of the discord group so that I may find and join to discuss issues I'm having with modding.

*Long Story Short*

I followed some of the directions within this webpage https://www.reddup.co/r/DDLCMods/comments/7lr769/drpshqi
I have downloaded the latest stable copy of the mod template, DDLC, and Renpy-6.99.12. I began by starting my new project, assigning the DDLC file as my game directory and copying and pasting the original as well as advanced scripts into the DDLC game folder from the mod template(I did not completely add the mod template into the DDLC folder, only the original and advanced script section). **If I made a mistake along the way please correct me!** Yet whenever I navigate to all scripts in renpy, under the screens tab
![screens rpy screen](https://user-images.githubusercontent.com/34694679/35197605-4372fe5c-fea7-11e7-8c0d-0881d669f876.PNG)
This is what I see at the beginning of the screens.rpy, **if this isn't suppose to show, i'd like to know how I can fix this**.
I had to manually enter the coding listed under the steps here.
![navigating script section](https://user-images.githubusercontent.com/34694679/35197660-ff766f44-fea7-11e7-83c2-69d045400ddb.PNG)
**If these images are suppose to show that these texts are suppose to already be within the screens.rpy then I obviously messed up** otherwise, I completely manually entered in what was shown in Image 1 and Image 2. The if not persistent.monika_kill: section was completely fine so I didn't have to correct anything for it. 

The main error i'm receiving right now is the Image I provided at the beginning of this page. If I have messed up anywhere along the way please provide me with some images showing me exacting where the files need to be as just labeling steps for me isn't going well haha. Thanks so much!

**Comment by FireyAmber** [comment]
I can't really help much but here's a discord link:
https://discord.gg/4H2pXh

**Comment by ThePotatoGuy** [comment]
You might want to forward your issues to the DDLC Modding discord.

**Comment by Bam8647** [comment]
Yeahh the discord seems full of people who don't know how to help me so that's fun lol. Not to be rude or anything haha.
