### ISSUE TITLE
[Suggestion] - Random Words Poem

### ISSUE THREAD

**Issue by RhetoricalSave** [Backdash/MonikaModDev#818]
So since Monika is actually aware that the MC is actually fake and behind him is the player, I thought that it might be fun to add some dialogue for Monika addressing the player's random words mashed together that were considered poems. 

For example:

"ehehe~"
"I was just remembering a poem you wrote."
"You know I always thought your poems were a bit funny"
"Don't get me wrong (player) I loved all of your poems. Even if I couldn't have one."
"But they always were a random string of words slapped together~"
"The other girls didn't even notice!"
"I just wish I could've gotten one. Even if it wasn't a real poem I'd treasure it forever"

Something kinda like this. Just a kinda funny addressing of the odd poems we players made at one point and how Monika ever really got one. Unless you count the "just monika" poem maker.

**Comment by RhetoricalSave** [comment]
I haven't a clue how to make this happen so I can't quite do it myself. I can draw and make music but not a coder by any means. I'd love to see it happen though!

**Comment by RhetoricalSave** [comment]
Okay I'll have a look but I'm fairly certain it doesn't. I think she mentions the other girl's poems.

**Comment by queue5** [comment]
I definitely remember her saying something along the lines of "It's hard to enjoy your poems when they're just a bunch of disconnected words" or something like that

**Comment by RhetoricalSave** [comment]
Ooh yeah you might be right there

**Comment by kaido1224** [comment]
Dialog already exists similar to this in the game, like someone mentioned previously.
```

init 5 python:
    addEvent(Event(eventlabel="monika_mc",category=['random'],prompt="The MC",random=True))

label monika_mc:
    m 3 "Just so you know, I was never in love with anyone but you."
    m "I mean you, [player]."
    if mcname.lower() == player.lower():
        m 1d "Wait, that's both your name and your character's. Sorry, that sounds a bit confusing."
        m 1a "I mean the player, not your character."
    m "Unlike the other girls, I can separate your avatar from who you really are."
    m 1m "The main character is nothing more than a bunch of code with no personality."
    m 3i "Literally and figuratively, no personality. How could anybody fall in love with that kind of person?"
    m 3h "He just got dragged around by his childhood friend to the club she was in, and then hung around with a bunch of beautiful girls doing nothing."
    m "His poetry was just a bunch of disconnected words! What sort of poetry is that supposed to be?"
    m 2m "I guess nobody mentioned that because it was a part of the game. But, yeah. It's just a list of words to me."
    m 2h "I hope you're a lot more romantic than that in real life!"
    m 2e "But even if you're not, it's okay. We've moved beyond that phase in our relationship already."
    m "That just means you won't cheat on me with some woman in your reality, right?"
    m 2 "I'm sure you would never do that to me."
    m "Just in case, how about you take my character file along with you when you go outside?"
    m "I just want to be with you forever~"
    return
```

**Comment by queue5** [comment]
damn dude my immersion :(

**Comment by therationalpi** [comment]
Already implemented.
