### ISSUE TITLE
Copernicus Mistake

### ISSUE THREAD

**Issue by DISTurbedwaffle** [Backdash/MonikaModDev#823]
I was a tad troubled when Monika says that Copernicus was killed by the Catholic church for his research during a conversation.  Copernicus died of apoplexy and paralysis at the ripe old age of 70 in 1542, and was buried underneath a Cathedral, which is a pretty high honour in the faith.  Nowhere has there ever been the suggestion that he was killed by the Catholic Church, let alone because they ever disagreed with him or his work.
It just bothered me, since Monika's supposed to be a bit more well read than that.  And if she's supposed to be closer to our reality, then shouldn't she not make a mistake like that?

**Comment by monikLover** [comment]
This has already been fixed.

**Comment by DISTurbedwaffle** [comment]
Oh, cool.  Thanks
