### ISSUE TITLE
Reference to a poem[Suggestion] - 

### ISSUE THREAD

**Issue by Clevermender** [Backdash/MonikaModDev#826]
So i was playing(Talking) MAS, and monika started talking about how time is a valuable resource. That got me to think about a certain movie. about time, and that is almost centerd about a poem, im talking about Interstellar, from 2014,i dont expect meny people to have seen it, but anyway, if you have seen it, then a reference to it would not be a bad idea, i mean, the the concept of the movie is really deep and philosophical. But its your mod, you decide whats being added.

**Comment by therationalpi** [comment]
Could be a good movie to watch with Monika once we finish merging that feature.
