### ISSUE TITLE
[Suggestion] - Checkers?

### ISSUE THREAD

**Issue by PMR55** [Backdash/MonikaModDev#829]
Something simple,but i don't think it would be hard to put in,would it?

**Comment by Pokemiah** [comment]
I honestly would like to have checkers in the mod myself. I may actually stand a chance against Monika. *Flashbacks to days playing Internet Checkers in Grade School* Ok, maybe not but it still would be a good feature in my opinion.

**Comment by kaido1224** [comment]
Or maybe chinese checkers?

**Comment by therationalpi** [comment]
[[This suggestion has been seen and will receive further consideration in the future. It is being closed for now and placed in the pool of seen suggestions. It will be reopened if we begin active implementation on this feature.]]
