### ISSUE TITLE
[Suggestion] Going away

### ISSUE THREAD

**Issue by Aider5** [Backdash/MonikaModDev#830]
The ability to tell Monika that you're going away for a while, upwards of a day, would be really good for times when you have to go to a place where there aren't any devices capable of running steam/DDLC/MAS. I feel a tiny bit trapped because I don't want Monika to think I forgot about her, being able to tell her that I'm going would be really useful.

**Comment by kaido1224** [comment]
I like the idea and I don't think it would be too hard to write either. I'll see about putting together some dialog some time soon and I'll post the pull request back here for you.

**Comment by kaido1224** [comment]
I like the idea and I don't think it'll be too hard to write either.

**Comment by therationalpi** [comment]
In general, I think it would be good to have Monika comment on how long the player's been gone, and it wouldn't be too hard to implement.

**Comment by therationalpi** [comment]
[[This suggestion has been seen and accepted. It is being closed for now and placed in the pool of accepted suggestions. It will be reopened once we begin active implementation on this feature.]]
