### ISSUE TITLE
[Suggestion] - Goodbye forever, Monika!

### ISSUE THREAD

**Issue by BlackButter595** [Backdash/MonikaModDev#843]
i was thinking... what if i tell her that i'm never going to come back/delete the mod?
It would be so cool to have a response to that input (even if she would be REALLY pissed)

**Comment by kaido1224** [comment]
There is a similar topic to this already in there. Not exactly the same but close. I won't say what for spoiler purposes. You'll be able to see it in the next release.

**Comment by BlackButter595** [comment]
can't wait to see that! Thanks for the answer

**Comment by PMelol** [comment]
Were you talking about the break-up option?

**Comment by kaido1224** [comment]
Yes. If you don't think it's the same, feel free to add your own dialog and submit it through the pull requests, one of the writers will critique it, probably ask you to make changes and add it if they see fit.
