### ISSUE TITLE
The "Talk" and "Play" Options

### ISSUE THREAD

**Issue by GDROfficier** [Backdash/MonikaModDev#844]
Excuse me, Internet if I'm that dumb to understand. But what the algorythm is to have the "Talk" and "Play" buttons to unlock or what do I need to do?
Pre-release patch 0.7.0

**Comment by Stevo1244** [comment]
Hey, I have the same issue too.

This only seemed to happened after I deleted ddlc and downloaded it again.

Sorry I can't help.

**Comment by Stevo1244** [comment]
Oh, I just waited around for a few minutes, she was talking about a piano and a new game and the options came back.
So, basically, just wait.

**Comment by monikLover** [comment]
They gray out when she's talking. This is to make sure the player isn't rude when Monika talks :ok_hand:
