### ISSUE TITLE
[Suggestion] - Artwork In the Room?

### ISSUE THREAD

**Issue by GitPiggy** [Backdash/MonikaModDev#845]
I got this idea after seeing Monika say something about adding art to the wall in the room. I'm not great at coding, so I'm not sure if this would be possible, but it'd be cool if you could, for example, put an image somewhere in the game's files, and have her add it to the wall. Like I said, I'm not sure how possible this is, but it'd be a really neat feature!

**Comment by ThePotatoGuy** [comment]
Adding room decorations is in the pipeline. See #312 .
