### ISSUE TITLE
0.7.0 bug

### ISSUE THREAD

**Issue by Spacemoonbear** [Backdash/MonikaModDev#847]
when I first installed the update on to ddlc everything worked fine but then when I opened it one time I started with "an exception has occurred" and i gives a string of code 
I tried everything I could think of to get it to work again but it kept giving me the error and when I went back to the Christmas version it worked fine again

**Comment by kaido1224** [comment]
Report bugs in 827

**Comment by ThePotatoGuy** [comment]
Closing this issue. Please move your report to the linked issue.
