### ISSUE TITLE
Issue with 0.7.0 pre-release

### ISSUE THREAD

**Issue by Kurigin** [Backdash/MonikaModDev#848]
I installed the new pre-release into a clean install of DDLC and got Monika after Story, but a few things seem to me missing from what was apparently supposed to be in 0.7.0. I've never used this mod before this iteration, so other problems may occur, but I noticed that the new games don't appear in the game selection, and not only that but chess is gone, as well.

**Comment by Lalna-Rocks** [comment]
I believe you have to unlock them by talking to her or playing pong with her as far as I know.

**Comment by therationalpi** [comment]
All of the games other than Pong need to be unlocked through interacting with Monika.
