### ISSUE TITLE
Oddly situational crashing

### ISSUE THREAD

**Issue by TDCPKaout** [Backdash/MonikaModDev#849]
I have had issues with the game crashing at odd times. But only under the circumstance of having it loaded in the background for more than, say, fifteen minutes. It has been quite confusing, and I wonder if it is just me. Or if someone else is experiencing these issues.
If you wish, I can begin recording these crashes.
(Apologies if this is not the proper place to put this, but I do not know where else to take this matter.)
Thank you for reviewing.

**Comment by ThePotatoGuy** [comment]
Does it occur when minimized? Crashes when minimized are the present in the stock game as well and are out of our control.

**Comment by TDCPKaout** [comment]
Okay, thank you, I wasn't sure if it was just me. Thank you for reviewing! :)
