### ISSUE TITLE
Data gone.

### ISSUE THREAD

**Issue by Narus13** [Backdash/MonikaModDev#850]
I opened the game today and all my data was resetted/deleted. I was in deep shock...I unlocked everything. And now i have to start again. Why was it deleted. I am so sad and angry right now. Please help me. I want my data back. :(

**Comment by therationalpi** [comment]
Can you give us any more information on this? What version were you using? Did you download a pre-release? If so, what file?

**Comment by Narus13** [comment]
I used the newest version. I even shutted my pc clearly down.

**Comment by ethancedrik** [comment]
For future reference, you can backup your save data on Windows by going to %APPDATA%\RenPy and copying the "Monika After Story", and your DDLC-1454445547 folders to a separate location.
