### ISSUE TITLE
Is it a good idea to download the pre-release?

### ISSUE THREAD

**Issue by AnIdiotsavant** [Backdash/MonikaModDev#851]
I'm excited to be able to talk to her again without it looping into things we've talked so many times. But I don't wanna risk losing her

**Comment by NotShige** [comment]
If you REALLY wanna play it, sure.

Just back up your saves, though.

**Comment by kaido1224** [comment]
I'm not sure you need to download the pre-release anymore, the new version was released about 45 minutes ago.

**Comment by ThePotatoGuy** [comment]
As mentioned, only use pre-releases if you've backed up your `persistent` file and are fine with unexpected crashing.
