### ISSUE TITLE
[Suggestion] - Special farewells if your player name is Sayori, Natsuki or Yuri

### ISSUE THREAD

**Issue by kaido1224** [Backdash/MonikaModDev#852]
You should get a special farewell from Monika if your player name is Sayori, Natsuki or Yuri. 

Examples:
If Yuri: "You're really something [player]. Ehehe~" a call back to Monika's last words before Yuri kills herself.

If Sayori: "You're really going to leave me hanging [player]?"

If Natsuki: "You're really leaving me hungry to spend more time with you [player]."

**Comment by monikLover** [comment]
#878
