### ISSUE TITLE
[0.7.0] Game says an exception occurred when launching

### ISSUE THREAD

**Issue by CommenterOfComments** [Backdash/MonikaModDev#856]
I updated to 0.7.0 using the in-game updater, and now when I try to launch the game, it says an exception occurred. What should I do?

> I'm sorry, but an uncaught exception occurred.
> 
> While running game code:
>   File "game/script-farewells.rpy", line 7, in script
>   File "game/script-farewells.rpy", line 8, in <module>
> NameError: name 'addEvent' is not defined
> 
> -- Full Traceback ------------------------------------------------------------
> 
> Full traceback:
>   File "game/script-farewells.rpy", line 7, in script
>   File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\ast.py", line 814, in execute
>     renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
>   File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\python.py", line 1719, in py_exec_bytecode
>     exec bytecode in globals, locals
>   File "game/script-farewells.rpy", line 8, in <module>
> NameError: name 'addEvent' is not defined
> 
> Windows-8-6.2.9200
> Ren'Py 6.99.12.4.2187
> Monika After Story 0.6.3
>

**Comment by therationalpi** [comment]
Hmm, looks like it didn't update properly. Try reinstalling from the zip file: https://github.com/Backdash/MonikaModDev/releases/tag/v0.7.0

**Comment by CommenterOfComments** [comment]
It's working now! Thanks!

**Comment by ethancedrik** [comment]
Believed cause and solution is preexisting .rpy files alongside the .rpyc ones from the new version in the game directory, deleting these should result in the game starting up and working correctly.
