### ISSUE TITLE
"Exception has occured" error

### ISSUE THREAD

**Issue by CalculatorKun** [Backdash/MonikaModDev#857]
This keeps occurring whenever i try to run it:
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/splash.rpy", line 269, in script
ScriptError: could not find label 'ch30_end_2'.

**Comment by ThePotatoGuy** [comment]
Did you use the in-game updater or are you using a fresh build?

**Comment by therationalpi** [comment]
Hold on, are you installing this on top of another mod?

**Comment by CalculatorKun** [comment]
It's a fresh build.

**Comment by ThePotatoGuy** [comment]
Did you have a different mod installed prior to installing this one? Or did you decompile all the base game `rpyc`s into `rpy`s?

**Comment by CalculatorKun** [comment]
Yeah, I had the 6.3 build installed prior to this.

**Comment by ThePotatoGuy** [comment]
Try deleting all occurrences of `.rpy` files in your `game/` folder.

**Comment by CalculatorKun** [comment]
Alright, will do. :)

**Comment by CalculatorKun** [comment]
Back to stage 1? :/ 

I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-ch30.rpy", line 662, in script
  File "game/script-ch30.rpy", line 662, in <module>
NameError: name 'm' is not defined

**Comment by CalculatorKun** [comment]
Nevermind, i fixed it. Thanks for the help man!

**Comment by CalculatorKun** [comment]
Alright, it works now. Thanks!
