### ISSUE TITLE
playing Piano with non-english keyboard layout

### ISSUE THREAD

**Issue by Akito1998** [Backdash/MonikaModDev#858]
It's quite inconvenient to play the piano with a non-english keyboard layout, I have a german one for example so 'Z' and 'Y' are switched, so accidently pressing 'Z' while playing and leaving the piano could happen quite often.
There's a similar problem with the brackets '[' and ']' their position is taken by 'Ü' and '+' which obvisously don't work.

I've seen in the code that the keys are directly mapped to the letters: `D5 = pygame.K_y` for example.
I don't know python myself, but maybe it is possible to check for scancodes instead to stay independent of the keyboard layout?

**Comment by ThePotatoGuy** [comment]
Checking scancodes won't work since `pygame` makes scancodes and keycodes equal. However, in the next version I'll add a thing where you can set the keys to whatever configuration you want.

**Comment by ThePotatoGuy** [comment]
Closing in favor of organized/checklist issue
