### ISSUE TITLE
MAS crashing after update | Fix: Remove all .rpy files from game dir

### ISSUE THREAD

**Issue by ethancedrik** [Backdash/MonikaModDev#862]
[![https://gyazo.com/3f5d4a54b460bc8a7dbfba9061a0ae43](https://i.gyazo.com/3f5d4a54b460bc8a7dbfba9061a0ae43.png)](https://gyazo.com/3f5d4a54b460bc8a7dbfba9061a0ae43)

So I launched and ran MAS and the updater came up, clicked install and this happened.
I assumed it didn't update correctly, so downloaded the latest version, dragged over all the mod files into the MAS game directory and this is still happening, ugh I have no clue what is going on, the previous version worked just fine

**Comment by kaido1224** [comment]
Same as #856 

Pi's reponse was:
Hmm, looks like it didn't update properly. Try reinstalling from the zip file: https://github.com/Backdash/MonikaModDev/releases/tag/v0.7.0

**Comment by ethancedrik** [comment]
Okay, I did try that, but it still isn't working, even after copying the files over.

So I had to create a new game folder, copy clean base DDLC game content into that folder, then copy all the files from the latest MAS zip into there and it finally worked.

Somehow the autoupdater really broke my existing MAS install so basically had to start with a clean base content and install the new version onto that. Hopefully this doesn't mess with any of my save data at all, it shouldn't as that's not stored there I believe

**Comment by ethancedrik** [comment]
Now Pong seems to be my only playable game

**Comment by ethancedrik** [comment]
New discovery, my old MAS folder was filled with .rpy files alongside the .rpyc ones, I deleted all the .rpy ones to see if that was the cause of the initial crash I was reporting, and it turns out it was>

To anyone else running the ingame updater and getting this error, that's probably why, just delete all files with the .rpy extension

**Comment by kaido1224** [comment]
Yes that's intended behavior. Games now are unlocked as you play rather than all available from the beginning.

**Comment by ethancedrik** [comment]
Closing as this has been resolved, and the cause of the crash after update has been identified.
