### ISSUE TITLE
[Suggestion] Game Suggestion - Mad Libs

### ISSUE THREAD

**Issue by badooga** [Backdash/MonikaModDev#864]
Just as the title says. Monika would ask for some words of whatever types are necessary, the player would type them in (with the spacebar not being allowed, as she'd only ask for one word at a time), and then she'd read out the resulting Mad Lib with the player's choices added in via text interpolation.

The real challenge would lie in rejecting words if they aren't the correct word type (e.x. the player types in a noun when a verb is requested), if they are(n't) plural (nouns only) or if they aren't the correct tense (verbs only). However, this filtering doesn't necessarily have to be a thing at all, except for certain words maybe being filtered by Monika (e.x. the curse words she'd previously scold the player for typing in as a keyword); it's not like Monika saying a few nonsensical things is the end of the world, you know?

Not only can existing Mad Libs be taken from internet sources or somewhere else, but it's also possible to write custom DDLC/Monika-related Mad Libs (maybe even a few messed up Mab Libs to be a part of the name Easter Eggs?); the story possibilities are pretty much endless.

**Comment by kaido1224** [comment]
This idea has already been suggested and accepted.

see #689

**Comment by badooga** [comment]
oof
