### ISSUE TITLE
Pong is the only playable game on Windows 10

### ISSUE THREAD

**Issue by ethancedrik** [Backdash/MonikaModDev#866]
So I have MAS v0.7.0 working and Pong is now my only playable game, and I am running on Windows and Ren'Py identifies my system as Windows so at least chess, which worked for me before the update should show up.

[![https://gyazo.com/216d188342ab5416b0f3961eec8e43a6](https://i.gyazo.com/216d188342ab5416b0f3961eec8e43a6.jpg)](https://gyazo.com/216d188342ab5416b0f3961eec8e43a6)

Not sure why it's wanting to give me all these issues, hopefully this is the last one. All the files from the latest zip are all in my game folder, I've checked this multiple times and copied them over multiple times just to be sure.

Here is my save data as well

[MASSaveData.zip](https://github.com/Backdash/MonikaModDev/files/1674952/MASSaveData.zip)

**Comment by kaido1224** [comment]
I just answered on your other ticket that games are now unlockable as you play as opposed to being available at the beginning.

**Comment by ethancedrik** [comment]
Yeah, that's embarrassing, just now saw that, asked in a Discord server and was told that was something that another person didn't experience so I immediately went off that.

Closing now
