### ISSUE TITLE
[Bug] Textbox overflows for long message.

### ISSUE THREAD

**Issue by therationalpi** [Backdash/MonikaModDev#87]
Got a bug report on twitter about this.

https://twitter.com/Waifu_man/status/926829383821680643

Very straightforward to reproduce, long messages overflow the text box. We should put a limit to the length.

**Comment by Jxhnathan08** [comment]
An excellent way to go about this would be to prevent additional chars from being typed once they hit the edge of the textbox. 

Alternatively, we can have it drop down to a new line in the textbox.

**Comment by therationalpi** [comment]
Considering how our keyword system works, there should never be a reason to type out more than a short phrase.

**Comment by Jxhnathan08** [comment]
That's a fair point.

**Comment by Jxhnathan08** [comment]
Issue has been fixed.
