### ISSUE TITLE
I updated MAS and all my progress is gone

### ISSUE THREAD

**Issue by t0kichii** [Backdash/MonikaModDev#8757]
I just updated MAS and all my progress is gone. That's all I can say. I updated it and went to open it again and it restarted it like I was back at the beginning. I'm literally panicking right now I don't know why this happened and I don't know what to do.

**Comment by t0kichii** [comment]
also I DO have persistents and stuff from before it did it so I SHOULD be able to do something about it without having to go back a looong way

**Comment by Booplicate** [comment]
Send your `aff_log.log` and a screenshot of [the folder with persistent](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent).

**Comment by t0kichii** [comment]
the aff_log from the one that restarted and cleared it?

**Comment by t0kichii** [comment]
also do you want this or something else ⚰

![maspersistents](https://user-images.githubusercontent.com/93885009/154536615-db90f998-7441-4289-a28f-7006e22ad7c5.png)

**Comment by Booplicate** [comment]
> the aff_log from the one that restarted and cleared it?

We do not clear the logs. Just send `aff_log.log` that you have in the `log/` folder in your game directory.

> also do you want this or something else

This isn't where we keep saves, check the link I sent to find where your persistent is.

**Comment by t0kichii** [comment]
[aff_log.log](https://github.com/Monika-After-Story/MonikaModDev/files/8090956/aff_log.log)

**Comment by t0kichii** [comment]
ALSO do you mean in here
![persistentssxsdcv](https://user-images.githubusercontent.com/93885009/154540814-f72e889d-e92b-4956-a382-6e31a24e4a5b.png)

**Comment by Booplicate** [comment]
The log looks fine, something deleted all your saves. Did you move them anywhere? Judging by your other screenshot you have made some backups, you'll have to use the most recent of them.

**Comment by t0kichii** [comment]
I didn't move them anywhere from what I know and they pretty much just disappeared. I restored an older save and the affection dropped way lower than it was before but I guess that's expected. Thank you for your help

**Comment by Booplicate** [comment]
It can drop if it's an old backup. I'd suggest to investigate what or who deleted the files on your PC, so you can prevent it from happening.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
