### ISSUE TITLE
Valentine's day content

### ISSUE THREAD

**Issue by therationalpi** [Backdash/MonikaModDev#877]
We're adding Valentine's day content. Don't worry.

**Comment by TDCPKaout** [comment]
Though I am no programmer, in fact, I have absolutely no experience with any form of coding. I can write. So if you lot need any help writing dialogue, I'd be happy to help.
Just say the word, and I will try to get some dialogue on a topic that you provide. So long as someone can put it in code.

**Comment by kaido1224** [comment]
I think this can be closed
