### ISSUE TITLE
uncaught exception

### ISSUE THREAD

**Issue by MightBeEden** [Backdash/MonikaModDev#879]
I'm sorry, but an uncaught exception occurred.

While running game code:
ScriptError: Name (u'/Users/pi/Documents/Renpy/Monika After Story/game/chess.rpy', 1517230626, 110) is defined twice, at Monika_After_Story-0.7.0-Mod/chess.rpyc:1 and game/chess.rpy:1.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\main.py", line 364, in main
    renpy.game.script.load_script()  # sets renpy.game.script.
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\script.py", line 265, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\script.py", line 753, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=fn + source)
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\script.py", line 419, in finish_load
    bad_node.filename, bad_node.linenumber))
ScriptError: Name (u'/Users/pi/Documents/Renpy/Monika After Story/game/chess.rpy', 1517230626, 110) is defined twice, at Monika_After_Story-0.7.0-Mod/chess.rpyc:1 and game/chess.rpy:1.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187

**Comment by MightBeEden** [comment]
jesus im terrible at using this site

**Comment by kaido1224** [comment]
You have two copies of the game files in the game folder. Copy the contents of the MAS game folder directly into the DDLC game folder then try again.

**Comment by kaido1224** [comment]
The reason you are getting the error is because you have two of the same files existing in the DDLC game folder (likely one in a folder called Monika_After_Story_0.7.0 and then the files in the actual game directory itself). If that's the case, copy the contents of the game folder in Monika_After_Story_0.7.0 folder and paste them directly into the DDLC game directory and try again. Make sure you remove the Monika_After_Story_0.7.0 folder.

**Comment by kaido1224** [comment]
If not, screenshot your DDLC game directory and paste it here so we can see it.

**Comment by MightBeEden** [comment]
Fixed. Turns out im bad at everything related to computers
