### ISSUE TITLE
[bug] Uninstallation instructions don't work - singleton.py missing

### ISSUE THREAD

**Issue by MarkusRamikin** [Backdash/MonikaModDev#881]
This happened after I deleted all the mod's files, as per uninstalling instructions from the readme:

> I'm sorry, but an uncaught exception occurred.
> 
> While running game code:
>   File "game/definitions.rpy", line 6, in <module>
> ImportError: No module named singleton
> 
> -- Full Traceback ------------------------------------------------------------
> 
> Full traceback:
>   File "C:\Gry\DDLC-1.1.0-pc\renpy\bootstrap.py", line 295, in bootstrap
>     renpy.main.main()
>   File "C:\Gry\DDLC-1.1.0-pc\renpy\main.py", line 364, in main
>     renpy.game.script.load_script()  # sets renpy.game.script.
>   File "C:\Gry\DDLC-1.1.0-pc\renpy\script.py", line 265, in load_script
>     self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
>   File "C:\Gry\DDLC-1.1.0-pc\renpy\script.py", line 753, in load_appropriate_file
>     self.finish_load(stmts, initcode, filename=fn + source)
>   File "C:\Gry\DDLC-1.1.0-pc\renpy\script.py", line 445, in finish_load
>     node.early_execute()
>   File "C:\Gry\DDLC-1.1.0-pc\renpy\ast.py", line 865, in early_execute
>     renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
>   File "C:\Gry\DDLC-1.1.0-pc\renpy\python.py", line 1719, in py_exec_bytecode
>     exec bytecode in globals, locals
>   File "game/definitions.rpy", line 6, in <module>
> ImportError: No module named singleton
> 
> Windows-8-6.2.9200
> Ren'Py 6.99.12.4.2187

I do vaguely remember 1 file being overwritten when I first installed the mod, so of course this would happen. Just a heads-up. Obviously I'll handle this by restoring the file from the game's install zip, but I figured you'd want to know the uninstallation instructions will now mislead people.

As far as I can tell, the mod doesn't modify singleton.py. If I'm right, there's no point including it in the mod files.

**Comment by therationalpi** [comment]
Yeah, the file is included to deal with how Mac and Linux handle merging folders of the same name.

We're considering changing the way we distribute the mod, but in the meantime I'll try to make the uninstallation clearer.

**Comment by MarkusRamikin** [comment]
For what it's worth, I like the zip distribution. I like the control.
