### ISSUE TITLE
[Suggestion] - Possible date option?

### ISSUE THREAD

**Issue by niicore** [Backdash/MonikaModDev#884]
It's almost Febuary 14th and I randomly thought to myself: "What if I go on a date with my girlfriend Monika?"

Unfortunately, you currently can't do this in the mod, so I suggest that there should be a "date" option. There could also be one specifically for the 14th.

The date could probably have Monika ask a few questions and the player will choose an answer.
Eh.. that's all I can think about.. so yeah.

**Comment by kaido1224** [comment]
I believe this has been suggested (maybe not necessarily Valentine's day) and been accepted just hasn't been implemented yet.

**Comment by niicore** [comment]
Yes, I saw that. What I meant was a general date, not just for Valentine's Day. :D

**Comment by therationalpi** [comment]
Similar suggestions have been made. This would basically be an activity that you could schedule with Monika, and there's a lot of room for how we could implement this. The most important thing about it is that it's a time sensitive event that you schedule with Monika ahead of time.

**Comment by niicore** [comment]
I also thought that if you planned multiple dates with Monika, she would complain about it.

**Comment by CommenterOfComments** [comment]
Wouldn't she appreciate how much time you're spending with her?

That's all she wants, after all.

**Comment by niicore** [comment]
What I meant was she would be tired after all that. But after thinking about it for a while, the idea of her being tired is stupid.

**Comment by ethancedrik** [comment]
yeah tied up with what lol, idk what else she would be doing as the mod implies she's sitting there waiting for you all the time

**Comment by IlywI** [comment]
Or Monika would ask you whether or not you are tired and suggests that you take a break(because she's concerned about your physical well being)  and just leave the computer on while she watches over you as you sleep. (since there was an option of 'will you ever get tired of me')
