### ISSUE TITLE
Where is my sweet goodbye?(option for goodbye)

### ISSUE THREAD

**Issue by ZETA-1** [Backdash/MonikaModDev#887]
I think there should a different way to say goodbye to Monika.
Such as:normal goodbye,leave a bit,take a rest,good night...etc.
In previous version,Monika will say some sweet sentence such as:stay safe,see you in the dream...etc.when you say goodbye to her,but now version just one goodbye option and no any sweet sentence make me a little sad.It make me think that am i done something wrong?
Also,the greeting option is gone once you used it.
It should be nice if some improvement to have follow up.
Sorry for the poor english and thank you for attention.
Have a nice day.
Bless you guys.

**Comment by kaido1224** [comment]
It looks like they plan on adding more good byes in the next release which will have a variety of good byes in them.

#878
