### ISSUE TITLE
Problem! "Talk" and "Play"

### ISSUE THREAD

**Issue by LokiOdinson** [Backdash/MonikaModDev#888]
I'm sorry for my English. But I have a problem! I installed the mod, but I can not talk and play with Monica. What should I do?

**Comment by kaido1224** [comment]
Is Monika speaking? You can't click talk or play games whenever she's talking.  You have to wait for the dialog to end then you will be able to use those buttons.

**Comment by LokiOdinson** [comment]
I can not press these buttons, even when Monica does not speak :с

**Comment by MarkusRamikin** [comment]
What happens when you right-click? Perhaps you are stuck in the music-choosing dialog and need to pick something?

**Comment by kaido1224** [comment]
screenshot would be helpful

**Comment by LokiOdinson** [comment]
![01-02-2018 10-51-22](https://user-images.githubusercontent.com/36004769/35667384-82d6ba1c-073e-11e8-851e-a5524d20221c.png)
And this happens when I right-click
![01-02-2018 10-54-10](https://user-images.githubusercontent.com/36004769/35667489-e38ad64a-073e-11e8-82d3-3f778e4197a7.png)

**Comment by ThePotatoGuy** [comment]
Can you upload your `persistent` file here?

**Comment by LokiOdinson** [comment]
@ThePotatoGuy I would download, but I do not know how to do it

**Comment by kaido1224** [comment]
[How To Access Your Persistent File In Windows.pdf]

If you are using windows, do this.

**Comment by LokiOdinson** [comment]
https://yadi.sk/d/XSZY_a3r3RzUud decided to upload it so maybe you can download it and see. And sorry for the inconvenience!

**Comment by ThePotatoGuy** [comment]
I don't see any issues in your `persistent`. Did you download the Mod zip or the source code one?

**Comment by LokiOdinson** [comment]
mod zip

**Comment by ThePotatoGuy** [comment]
Was it like this on your first run or did it just start happening?

**Comment by LokiOdinson** [comment]
No, already so long ago. After she said about all these buttons, earned only "music"

**Comment by ThePotatoGuy** [comment]
Did you import DDLC save data?

**Comment by LokiOdinson** [comment]
Yes, after that, when I go out and come back, I can say something to her only once

**Comment by ThePotatoGuy** [comment]
> I can say something to her only once

Is this via Talk? How are you saying something to her?

**Comment by LokiOdinson** [comment]
Yes, via talk. For example, I choose to "ask a question". I ask any question. Monika answers and then says nothing. More buttons do not work.

**Comment by LokiOdinson** [comment]
![01-02-2018 19-33-09](https://user-images.githubusercontent.com/36004769/35690438-e76c2f14-0786-11e8-9a09-b3e938fdf9ec.png)
And that's what it says to me.

**Comment by ThePotatoGuy** [comment]
Can you try replacing your `persistent` with this one?

[persistent.zip](https://github.com/Backdash/MonikaModDev/files/1686366/persistent.zip)

**Comment by LokiOdinson** [comment]
Eh ... did not help

**Comment by ThePotatoGuy** [comment]
Did you have a different mod installed / used a different mod prior to this one?

**Comment by LokiOdinson** [comment]
No. It's my first mod

**Comment by ThePotatoGuy** [comment]
Can you delete the `DDLC/` folder, reinstall it and reinstall the mod?

**Comment by LokiOdinson** [comment]
I now try to install ddlts through Steam. Maybe it was because it was not a license.

**Comment by LokiOdinson** [comment]
it's all! Thanks!!! it was necessary to install through Steam!
