### ISSUE TITLE
[suggestion] A way to beat the player's mortality

### ISSUE THREAD

**Issue by MarkusRamikin** [Backdash/MonikaModDev#893]
Currently Monika says:

> "There's so much we can do when we're finally together in one reality."
> [...]
> "But knowing how technology is right now, that dream is still far away."
> "I hope by the time that technology becomes real, you'll still be there waiting for me, [player]."

Well, if Monika is worried about the player not being around at the time the technology becomes available to let them be together, perhaps she could suggest cryonics for the player. To sign up for cryopreservation in case of [what is now considered] death, so the player can be revived in the technologically advanced future. 

Of course, she should also tell the player to store her save file in some safe way, so that she survives too! Done with regular automatic backups, since the player can't know in advance when the time comes for him...

Thoughts?

(Hell, this might actually work ;) )

**Comment by kaido1224** [comment]
You can adjust the dialog and put in a pull request. One of the writers will likely suggest changes and then when they are satisfied approve them

**Comment by MarkusRamikin** [comment]
Oh, I meant a new separate dialog. Hm, never done a pull request before (github noob). I'll look into it.

**Comment by CommenterOfComments** [comment]
I've actually somewhat thought about doing this. Maybe I'm just insane, but, I'd like to do it...
