### ISSUE TITLE
[Suggestion] New topic: Internet access

### ISSUE THREAD

**Issue by ethancedrik** [Backdash/MonikaModDev#894]
This is another idea that came into my head, a topic talking about how you need the internet to do a lot of things, to send a message/stay in touch and contact with loved ones, friends and family, to access online schoolwork, to watch the latest uploads from your favorite content creators/youtubers, and so much more, but one thing you don't need to have internet access for is to spend time with your lovely amazing girlfriend Monika.

Don't quite have all the lines of how it would go in my head yet, but it could be a quick little topic she could bring up, thought I'd throw this out there.

**Comment by kaido1224** [comment]
Why do you need internet access to spend time with monika?
