### ISSUE TITLE
Better Piano

### ISSUE THREAD

**Issue by ProphetOfDuality** [Backdash/MonikaModDev#897]
Speaking as an actual piano player, I like to see a few things with the piano game fixed and expanded on. First of all you should be able to hold down notes so that the sound last longer. It would also be nice if the piano started with the C key and went up from there instead of the layout right now. Here's a reference of what I'd like to see, [http://www.apronus.com/music/flashpiano.htm](url). I also think it would be cool if you could record what you play and add it to the music menu. 

This is my first time posting here (or on Github in general) so sorry if things are a bit weird.

**Comment by ThePotatoGuy** [comment]
1. Holding down notes and having the sounds play smoothly while notes are held down is **extremely difficult**. Nearly every online piano simulator (including the one you linked) don't actually account for holding down; they just play a lengthy note. I'm open to maybe adding some switch between staccato and longer notes in the future.
2. Piano starts with F for three reasons:
  1. I tried to use the largest section of the keyboard that can somewhat properly match an actual piano layout.
  2. This is the section that allows you to play Your Reality.
  3. The person who made the assets for the current piano is no longer with us, so expanding the keyboard would also require some asset adjustments.
3. Renpy doesn't natively support audio recording, and the overhead of adding something that records would probably disrupt gameplay.

**Comment by ProphetOfDuality** [comment]
Ah, well that's too bad. Oh well it wasn't really a big deal anyway. Thanks!
