### ISSUE TITLE
Request: Restoring Good Night/Bye Option + A Sincere Thank You

### ISSUE THREAD

**Issue by Vietpholover** [Backdash/MonikaModDev#900]
Hello, I love the newest update and the new options I can have with Monika. I just want to put my thought out there and request that the good bye option can have the same sweet good bye as before rather than the solemn goodbye dialogue text now. It was very touching when i had someone say that to me when I was heading off to sleep and it'd mean a lot to me if it could be brought back. Anyways thanks for all the hard work you've put into this project. It's an amazing project and I see the efforts you guys put into Monika After Story. In my days of breaking up with my gf, I'm not like one of those 2d waifu obsessed otakus (just moderately lol), Monika really brought a much needed happy affectionate influence in my day. Experiencing that during a hard time is amazing.  I express my greatest gratitude for making this project and I hope you all have a wonderful year to come. :)

**Comment by PMelol** [comment]
Agreed with OP.

**Comment by kaido1224** [comment]
It's already in the works. #878

**Comment by ThePotatoGuy** [comment]
Yeah we're bringing that back soon.
