### ISSUE TITLE
Answering piano for instrument. 

### ISSUE THREAD

**Issue by ACoolCat** [Backdash/MonikaModDev#901]
When Monika asks you if you play an instrument and you say piano she gives the ordinary dialogue for how she always wanted to learn how to play [player]'s instrument too, then says she'd love for you to play the piano while she plays the piano. Considering how she already knows piano, maybe she could give a dialogue about how she finds it great that you know the piano too?

**Comment by kaido1224** [comment]
I'm not sure what version you are playing, but this is fixed in 7.0.

https://youtu.be/NPbnve6dmKs?t=29s
