### ISSUE TITLE
 I ask the developer's answer

### ISSUE THREAD

**Issue by ENDemany** [Backdash/MonikaModDev#903]
Sorry for the inconvenience, but you can ask where the file is located with all the speeches.

I want to translate it into Russian

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
https://github.com/Backdash/MonikaModDev/tree/master/Monika%20After%20Story/game
Most of the files with "script" in their names.

**Comment by ENDemany** [comment]
After that, when I translate how it can be compiled

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I don't mean to be rude but you should really not get into serious translating unless you have some experience.
[Here.](https://www.renpy.org/doc/html/language_basics.html)
 Ren'py will automatically compile .rpy files into .rpyc upon launching the game.
.rpy files can be deleted afterward.

**Comment by LokiOdinson** [comment]
I'm sorry for my English. But I have problem! In mod MAS don't warking button 'play' and 'talk'. What can be done?
