### ISSUE TITLE
Rock and rock topic seems heavily unpolished

### ISSUE THREAD

**Issue by MarkusRamikin** [Backdash/MonikaModDev#904]
This entire dialog seems kinda off to me. I might be stepping on someone's toes here, but here goes nothing:

> "You wanna know a cool form of literature?"
> "Rock and roll!"
> "That's right. Rock and roll!"
> "It's disheartening to know that most people think that rock and roll is just a bunch of noises."
> "To tell you the truth, I judged rock too."
> "They're no different from poems, actually."

"They" referring to what, grammatically? The word "songs" is not used until that point, just "rock", singular. I'd change it to "It's no different from poetry, actually."

> "It's disheartening to know that most people think that rock and roll is just a bunch of noises."

1. "Just noise" would sound better. 2. False, rock and roll was popular, appreciated by the mainstream, and so are at least some genres of rock now. She probably means that some people see it as simple and shallow, but "noise" implies dislike of the sound itself. 3. Why is Monika invested in other people's opinions enough to find this disheartening? Doesn't sound like her, what with her generic contempt for human life etc in other dialogs.

> "To tell you the truth, I judged rock too."

When? What changed? No transition.

Also, "rock" or "rock and roll"? Related, yes, but these are different things, different eras, and the way Monika uses them interchangeably sounds a little confused.

> It's kinda funny how rock and roll started out as an evolution of blues and jazz music.

Why is it funny?

> "Most rock songs convey a story through symbolisms"

Do they? "most" rock songs, really? I'd suggest something more defensible, like "many good rock songs". Also, "symbolisms", plural?

And of course the elephant in the room: 

> "You wanna know a cool form of literature?"

Herp derp. Rock is not a form of literature, and I'd expect this intelligent girl to be more precise with her langauge. She means fiction? Storytelling?

Here's an example of how I'd rewrite it all, with some added flavors here and there: 

> "We've been discussing literature so much, but do you want know a cool form of expression?"
> "Rock music!"
> "That's right. Rock music!"
> "There are people who think there's not much to it, just simple-minded entertainment, its popularity riding on easy-to-enjoy instruments like the guitar."
> "You know the 'Money for Nothing' song by Dire Straits? That's kind of what they're singing about there."
> "But rock music is not that far from poetry, actually."
> "Some of the best songs convey a story through symbolism, which most listeners wouldn't understand the first time they hear one."
> "In fact, like writing a good poem, composing lyrics is hard."
> "There's the same potential for subtext and wordplay and metaphor."
> "But most of all, you need to have a clear and concise message reflected in every element of the song."
> "And all of this has to be structured to work well with the melody and rhythm and the instruments."
> "Now when you put all that together, you have yourself a masterpiece!"
> "I've been thinking though..."
> "I want to try writing a rock song for a change."
> "Ahaha! That isn't something you'd expect coming from someone like me."
> "But I told you I like jazz music, right?"
> "Well, rock and roll started out as an evolution of blues and jazz."
> "That became what we now call rock music, with a number of sub-genres as well."
> "Metal, hard rock, classical rock, and more! Hm, I wonder if you are a metalhead, [player]..."
> "Ah, I've been rambling for a while now. Sorry, sorry."
> "If you wanna blast some good 'ol rock 'n roll, go ahead, [player]."
> "Even if you turn up the volume all the way, I'll gladly listen with you. Ehehe!"

(I'm gonna learn how make pull requests Real Soon Now (tm) ;) )

**Comment by kaido1224** [comment]
https://github.com/Backdash/MonikaModDev/blob/master/CONTRIBUTING.md

**Comment by kaido1224** [comment]
Make sure you put dialog changes and new dialog in the content branch, not master.
