### ISSUE TITLE
Question to the developers! don't work "talk" and "play"

### ISSUE THREAD

**Issue by LokiOdinson** [Backdash/MonikaModDev#905]
![01-02-2018 10-51-22](https://user-images.githubusercontent.com/36004769/35684000-9be042f2-0776-11e8-841e-0295d14ef6e1.png)
No one can help, maybe you can. Correctly installed the MAS mode. But the buttons "play" and "talk" do not work and are always gray. Due to the fact that I can not get over Monica, she says to a certain point and does not say anything else. Help me please.

**Comment by MarkusRamikin** [comment]
https://github.com/Backdash/MonikaModDev/issues/888
Why duplicate?
