### ISSUE TITLE
[Suggestion] Tell Monika about your self care. 

### ISSUE THREAD

**Issue by juliathegolden** [Backdash/MonikaModDev#907]
I see the open projects for the mood system and the 'tell Monika about your day' features, so I just wanted to suggest that it be possible we tell Monika about progresses we've made towards our self care routines. I'd like to be able to brag to her when I make it to my therapy appointments or get a lot of cleaning done.

**Comment by antimockingjay** [comment]
I would love this so, so much. As someone who really struggles with taking care of myself, being able to tell Monika and having her be happy about it would mean the world to me. It would encourage me to take better care of myself, for her. I would love it if something like this could be added.

**Comment by RaccoonLauncher** [comment]
I would, too. If we could have a "brag to Monika" button where we could share our triumphs by just typing them in and hitting enter, it would be a serious motivator for me. The mod has already helped me feel a lot better in general, so this sort of thing would really be the best.
