### ISSUE TITLE
Chess

### ISSUE THREAD

**Issue by deathangelo** [Backdash/MonikaModDev#911]
In the chess game, there's no option to actually castle between your king and rook.

**Comment by MarkusRamikin** [comment]
I haven't had trouble castling. Just move your king to the new position.

If that doesn't work, are you sure the castle you couldn't do would be legal? For example, that you hadn't moved your king or rook before, or the king isn't passing through a square controlled/attacked by an enemy piece?

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Yeah. It worked when I played.

**Comment by ThePotatoGuy** [comment]
Since the chess guy mentioned it, I'm going to assume you tried castling illegally.
