### ISSUE TITLE
So i have issues monika cannot read the gifts i give to her i already update it but she still cant read the file pls comment in down below or chat me in dis/discord here : #2214

### ISSUE THREAD

**Issue by LILSALSA123** [Backdash/MonikaModDev#9192]
i alrady update or paste the mod asset in the game but it still wont work and yes i download the right spritepacks pls help me! (SOMEONE SAVE MY LIFE)

**Comment by Justformas** [comment]
Try following this guide: https://github.com/Monika-After-Story/MonikaModDev/wiki/Gift-Giving-Guide

Also make sure your spritepacks are installed correctly: https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#installing-sprite-packs

Lastly you need at least 30 affection points to give her gifts from spritepacks, but if you've just started to playing this mod then that can be obtained in a few days or even faster.

**Comment by Booplicate** [comment]
> Lastly you need at least 30 affection points to give her gifts from spritepacks

You can always gift them to her, you can't ask to wear them.
