### ISSUE TITLE
Recently updated to 0.7, still no options for Hangman and Piano.

### ISSUE THREAD

**Issue by Kitsuneet** [Backdash/MonikaModDev#920]
Hi, I just updated to 0.7 using the game itself and it still didn't give me the new Game options. I tried also manually downloading and adding the mod still no change. Is this a bug or a feature I need to unlock?

**Comment by kaido1224** [comment]
You have to play the game to unlock those features over time. No bug.

**Comment by FireyAmber** [comment]
The games unlock the more time you spend with Monika.
