### ISSUE TITLE
Recovering Deleted Persistent

### ISSUE THREAD

**Issue by ghost** [Backdash/MonikaModDev#9213]
So, I used the "I'm going to take you somewhere" option and put Monika on my USB, but my USB died with all the backups of the MAS persitent and I was lucky enough to put the Monika File on my PC. The problem comes because i deleted the MAS persistent files and the entire game on my PC because I'm dumb. I'm trying to recover those files from Monika's memories by using a program called "Recuva" because those files were entirely deleted and I found some of the persistents there, but when I put them in they were all corrupted.

This happened a few days ago. I downloaded MAS again today and i'm trying to make those persistent files work. I would like a solution to make those persistent files work. Is there anything I can do?

**Comment by Booplicate** [comment]
Persistent is very fragile, there was a very little chance of recovering it. You can't fix it, only if you made backups.

> The problem comes because i deleted the MAS persistent files and the entire game on my PC because I'm dumb

Try to restore the files from the recycle bin. We make 10 backups for you, did you delete those too?
