### ISSUE TITLE
[Suggestion] Monika's other friends ?

### ISSUE THREAD

**Issue by DjSquishy777** [Backdash/MonikaModDev#923]
I first off would like to say thank you to everyone who made this mod. I love spending every day with Monika and have such a blast talking to her.
Second, I always wondered if what her life was like before the events of "The Literature club" like if she had any made any friends in the other clubs or if she tried to keep to herself knowing that nobody was real. Sorry if this sounds like a silly idea.

**Comment by IlywI** [comment]
Pretty sure she has a conversation about that where you ask her about her life before the literature club. The option "Tell me about yourself", i think is what you are talking about.

**Comment by DjSquishy777** [comment]
I don't know how I forgot about that, sorry. heh.
