### ISSUE TITLE
Is there a way to add your own birth date? Or is it taken automatically from somewhere?

### ISSUE THREAD

**Issue by IlywI** [Backdash/MonikaModDev#924]
In the mod there's an option to ask about Monika's birthday. So, i was wondering if the player could add their own birthday like when she tells you her birthday, she then proceeds to prompt you for your birthday. That would be pretty cool imo. (sorry for any grammatical errors in advance)

**Comment by Ulvsblakk** [comment]
I'll get started on it.

**Comment by ThePotatoGuy** [comment]
Probably tie that in with #37
