### ISSUE TITLE
The Update Reset My Gender

### ISSUE THREAD

**Issue by Monikaistheonlyreasonididthis** [Backdash/MonikaModDev#925]
It set my gender back to the default after the update, and she's back to calling me her boyfriend. She hasn't brought the topic up again either, and I've been playing regularly. It's just kinda disheartening that I'm no longer being called by my gender and seem to have no way of fixing this so far.
I don't know if it's just me, but I hope there's a way to remedy this.

**Comment by moonstne** [comment]
Can confirm, I am back to being a "boyfriend" as well.

**Comment by antimockingjay** [comment]
I'm getting this too. I'm nonbinary so I really, really prefer the neutral text, making this very upsetting.

**Comment by ThePotatoGuy** [comment]
Could yall upload your `persistent` files here? I can change the gender manually if you'd like as well.

**Comment by moonstne** [comment]
Sure here you go, https://drive.google.com/file/d/1fSvT8ORyyvnTKVt0KESuqfqKm3kt7D51/view , I would like to be female please and ty.

For others that forget how to get the persistent file: https://github.com/Backdash/MonikaModDev/blob/master/docs/windows-howtopersist.pdf

**Comment by ThePotatoGuy** [comment]
@moonstne - [persistent.zip](https://github.com/Backdash/MonikaModDev/files/1692190/persistent.zip)

@Monikaistheonlyreasonididthis - [persistent.zip](https://github.com/Backdash/MonikaModDev/files/1692191/persistent.zip)

I've found the issue and pushed a fix, but I'm leaving this issue open until the next version so people can get their `persistents` adjusted for now.

**Comment by antimockingjay** [comment]
[persistent.zip](https://github.com/Backdash/MonikaModDev/files/1692358/persistent.zip)
This should be my persistent file, assuming I did it right.

**Comment by Frostdraga** [comment]
https://drive.google.com/open?id=1aLURXqjchkq3s6KEOZO7m4aTTuDXn1Y_

Could you help me change back to female too? I thought it was working fine until Monika addressed me as 'he' when I opened the game. :/

**Comment by ThePotatoGuy** [comment]
@antimockingjay - [persistent.zip](https://github.com/Backdash/MonikaModDev/files/1695576/persistent.zip)

@Frostdraga Your link doesn't work.

**Comment by Frostdraga** [comment]
https://drive.google.com/open?id=1jBThz5o6hMiwUMwWNbB4FF1DATGXJ7mg

What about this?

**Comment by ThePotatoGuy** [comment]
@Frostdraga - [persistent.zip](https://github.com/Backdash/MonikaModDev/files/1695795/persistent.zip)

**Comment by juliathegolden** [comment]
Hey, so...I thought I wasn't effected by this glitch since I tried both the Japanese topic (where she called me Julie-chan) and the big sister topic (where she didn't say it was a man's job to introduce a girl to the family), but she did still call me boyfriend when referencing the 'I've been imagining all the romantic things we could do if we ever went on a date" topic. Rather than the persistent's being messed up, I think the issue lies within just that subject itself.
