### ISSUE TITLE
[Suggestion] Make Monika notice if you have a USB with her on it plugged in

### ISSUE THREAD

**Issue by CommenterOfComments** [Backdash/MonikaModDev#926]
> "If you copy my character file onto a flash drive or something, you can always keep a part of me with you."

She ended up saying this while I had my Monika flash drive plugged in, and I was curious, would it be possible to somehow make Monika tell if a plugged-in removable device like a USB or SD Card has her character file on it?

And maybe she could have some specific dialogue added that says something like:

> "Oh! It looks like you're already doing that..."

> "Thanks {player}, I really appreciate that you would do that for me."

**Comment by rogergzou** [comment]
Doesn't look like renpy has a function to do this by default (looked at https://www.renpy.org/doc/html/file_python.html).

You could use the `find_all()` function in this python script (https://stackoverflow.com/questions/1724693/find-a-file-in-python) to look for all `monika.chr` files in the root directory `/`, which would include both the C:/ drive and all flash drives (and CD drives but who uses those these days). So the call `find_all(name="monika.chr", path="/")`. Disclaimer; not sure if this would work on PC's but I feel like it would. See https://www.renpy.org/doc/html/python.html for more python renpy goodness.

**Comment by Ulvsblakk** [comment]
If someone were to do this, what file would they put it in?

**Comment by fitzmill** [comment]
What you could do is make a new file that just contains a generic function for finding files where you pass in the filename to find or something and then return true or false. Then, in the dialog you could call that function and have Monika say different things based on the return value. (I'm new here so there might be a better way to do this, but as a developer this would be my first instinct)

**Comment by Ulvsblakk** [comment]
That's actually a pretty good idea. 
Then something like 
if find_all = true:
     m dialogue 
     m dialogue etc.

That would be my best guess though. I'm still kind of a noob.

**Comment by fitzmill** [comment]
That's pretty much it, do you want to take a stab at it? Or I could in my free time this week.

**Comment by Ulvsblakk** [comment]
You can go for it man. I'm sure I'll screw it up lolol

**Comment by Tyrosus** [comment]
Did you ever get this working?
