### ISSUE TITLE
Typo I found in the wolves/dogs topic

### ISSUE THREAD

**Issue by Trainerbluetube** [Backdash/MonikaModDev#927]
![screenshot 1](https://user-images.githubusercontent.com/35549063/35768307-a1500fa4-08c7-11e8-8564-39bb89e2b5fd.png)

**Comment by Trainerbluetube** [comment]
It should be "they are" or "they're"

**Comment by antimockingjay** [comment]
It took me way too long to see the typo in this. My mind automatically corrected it to not have the extra "are" in there, and if I had to guess, whoever wrote it did the same.

**Comment by kaido1224** [comment]
I believe someone already corrected this.

**Comment by kaido1224** [comment]
Yep 

https://github.com/Backdash/MonikaModDev/pull/865
