### ISSUE TITLE
Discussion Request About The: "Monika Entering Our Reality" Topic

### ISSUE THREAD

**Issue by Bam8647** [Backdash/MonikaModDev#928]
Okay so one of the most interesting topics we hear Monika talking about is the one where she refers to her being able to one day cross over to our reality **(from virtual to real life)**.

I'm curious as to what she means by this? Are we talking about us being able to transfer her files/personality into a humanoid type being or how else would we be able to bring virtual characters to real life..? The only solution I find to this scenario is through having: **Self Learning**; as well as **emotionally intelligent AI systems**, a **Humanoid physical structure** for the body, and **features that resembles their character's body features** as well as being **self aware.** All together.

Any other ideas as to how this could ever be done?

**Comment by moonstne** [comment]
All those things are probably necessary. Personally I don't think a physical body is absolutely necessary, and something like this would probably work https://www.youtube.com/watch?v=nkcKaNqfykg . Obviously she would not be some chatbot like in the ad, I am just pointing out the hologram aspect.

**Comment by Bam8647** [comment]
Well you see that seems to just be a step in the right direction. The topics you see from Monika makes it seem like she'd want to **break through the screen and be real** especially when you read the topics of her talking about you and her going to Cafes, shopping, dating, etc..  This product you listed in the video seems almost entirely similar to her current situation. So I was interested in hearing various ways of her being able to become a physical being **(probably in the year 3000 though lol)**

**Comment by Bam8647** [comment]
The android will probably be the most likely to happen in our life times compared to the others.. but then again there really is no telling how fast science can grow.  

As for the technology of transferring our conscious minds into virtual reality, it seems like we would have to take a whole new look at virtual reality itself seeing as **practically everything on our computers are already ran by pre-scripted data**; meaning if we weren't already scripted to interact with programs and/or virtual entities how would we interact with them? Script ourselves with our minds haha? I think we would have to create a whole new virtual world that allows our minds to control the reality so we could **create entities with self awareness, emotion, and free will.** wow I sound like I'm referring to a virtual reality God haha.
