### ISSUE TITLE
[Bug?] Background changed after winning Pong

### ISSUE THREAD

**Issue by Guardianvoir** [Backdash/MonikaModDev#93]
Either I don't know that the background changes after 5:00 PM, or this is a bug. I took a screenshot for evidence.
![screenshot0007](https://user-images.githubusercontent.com/33330516/32419737-130a55d0-c24d-11e7-9181-5980cb1a6e33.png)

**Comment by Guardianvoir** [comment]
Update: This bug also makes the game change lighting occasionally, and when it does it reverts back to what Monika looked like before the art was changed before quickly switching back.

**Comment by Jxhnathan08** [comment]
What version are you on?

**Comment by Guardianvoir** [comment]
Build5 I think

**Comment by Jxhnathan08** [comment]
@Guardianvoir Check out the latest version, Build12.

**Comment by Guardianvoir** [comment]
Thank you!
