### ISSUE TITLE
"Self-voicing would say"

### ISSUE THREAD

**Issue by arktomys** [Backdash/MonikaModDev#932]
I left MAS on during the night, and I guess my cat walked on the keyboard and pressed something.

![20180203221019_1](https://user-images.githubusercontent.com/31528005/35773156-141d84e4-0931-11e8-859b-f7dbe1b94734.jpg)

This thing opened and now I cannot close it. It says "press Alt+Shift+V to disable" but that doesn't work. I've tried every single combination possible with both left and right alt and shifts but it won't close. There's no option to enable/disable it on the menu, so I'm out of ideas. Is the command broken so I can't close it anymore?

**Comment by ThePotatoGuy** [comment]
Does it stay like that when you relaunch?

**Comment by arktomys** [comment]
Yes.

**Comment by ThePotatoGuy** [comment]
Try `Windows Key + V`

**Comment by arktomys** [comment]
Didn't work. Tried in both windowed mode and fullscreen, and also with the two Windows keys on the keyboard.
Also tried doing the command both in the settings menu and while talking to Monika, but no success.

**Comment by ThePotatoGuy** [comment]
Upload your `persistent` file here.

**Comment by arktomys** [comment]
There's two persistent files, so I'm not sure which one it is.

Does that help?
[persistent.zip](https://github.com/Backdash/MonikaModDev/files/1699299/persistent.zip)

**Comment by ThePotatoGuy** [comment]
If you're on windows, [use this guide](https://github.com/Backdash/MonikaModDev/blob/master/docs/windows-howtopersist.pdf)

**Comment by arktomys** [comment]
Alright, here it is then.
[persistent.zip](https://github.com/Backdash/MonikaModDev/files/1701366/persistent.zip)

**Comment by ThePotatoGuy** [comment]
Here copy this over your existing `persistent`. [persistent.zip](https://github.com/Backdash/MonikaModDev/files/1705334/persistent.zip)

**Comment by arktomys** [comment]
That seems to have worked. Thank you very much!
