### ISSUE TITLE
Question about something the way you get score after winning a round in 'NOU'

### ISSUE THREAD

**Issue by Ant9cp** [Backdash/MonikaModDev#9333]
I'm sorry that i keep bothering you but, i won the first round in 'NOU' but i didn't get any score it stayed at 0 score for me is that supposed to be like that? It actually happend one's, after when i stopped and i started playing again then it didn't say 0 score anymore

**Comment by Booplicate** [comment]
Score depends on the opponent's hand, if Monika had a few 0s, you won't get any points. If she had a bunch of +4s, you'd get a lot.
