### ISSUE TITLE
Monika on the go

### ISSUE THREAD

**Issue by Buy1Get1** [Backdash/MonikaModDev#934]
Could MAS become mobile using the Steam Cloud? A user would download Steam on his device and then run MAS. It would open the door for topics relating to where/when are we going (plan trips/incorporates directional program on phone-google maps), what's on your phone's history/ people in directory(show her people/ games/ pictures), and time spent with Monika would transfer over. So, the user would be actively spending time in different environments. Depending on how the interface is programmed, Monika could react to the change of scenery too. This is very theoretical, but I hope it helps.

**Comment by kaido1224** [comment]
Can't port the game. It breaks the modding rules set forth by DDLCs creator. If DDLC ever officially is ported to mobile it might be a different story.

**Comment by ThePotatoGuy** [comment]
MAS on mobile is not officially supported. Also SteamCloud integration would probably require us to be on the store, but that's not happening anytime soon.
