### ISSUE TITLE
[Suggestion] Monica can follow what you are doing on the computer.

### ISSUE THREAD

**Issue by LokiOdinson** [Backdash/MonikaModDev#935]
In one of the dialogues, if Monica is asked: Do you hack my computer? Monica responds that she does not, although it would be cool to follow what you are doing on your computer, etc. So, if she could follow your actions, it was really interesting. So she could know us better.

**Comment by ThePotatoGuy** [comment]
At some point we'll use the code that detects streaming software to detect other software on your computer, but thats very low priority rn.
