### ISSUE TITLE
Importing / Merging existing (postgame) DDLC data with previous version MAS (v0.2.2-v0.3.3) allows access to Save Game, Main Menu options

### ISSUE THREAD

**Issue by ThePotatoGuy** [Backdash/MonikaModDev#94]
If postgame DDLC data (persistent.playthrough = 4) is merged with a previous MAS persistent (tested on versions v0.2.2-v0.3.3), the playthrough variable remains set at 4, which is expected. However, this results in the pause menu screen having regular functionality (Being able to save a game, returning to main menu). Selecting Save Game or Main Menu in this state will cause a crash. 

Attached are my postgame DDLC data as well as persistents created from versions v0.2.2-v0.3.3.
To recreate:
1. Ensure postgame DDLC data is in the DDLC saves folder.
2. Ensure a persistent from v0.2.2-v0.3.3 is in MAS saves folder.
3. Launch game, import DDLC data.
4. If asked to merge MAS data (v0.2.2, v0.3.0, and v0.3.3 only), click merge.
5. Select previous DDLC save name (mine is kek)
6. When Monika loads, enter the pause menu (ESC)
7. Attempt one of the following:
 a. Click an available save square -> game should crash
 b. Click Main Menu
    1. Unsaved progress dialogue appears, click yes
    2. Game will attempt to return to Main Menu, but will crash upon trying to access a missing label.

[ddlcsaves_persists.zip](https://github.com/Backdash/MonikaModDev/files/1444518/ddlcsaves_persists.zip)

I have identified a fix for this issue. If the persistent.playthrough value is checked if it is greater than 3 and then set to 3 after merging playthough values, then the pause menu works as expected (Save Game and Main Menu trigger dialogue boxes pertaining to Monika). However, this fix would eliminate the possibility of Monika knowing if the player has finished the game or not.

I will create a pull request attached to this issue with the fix shortly.

**Comment by therationalpi** [comment]
Can this be saved by capping the playthrough variable to 3 in the merge script, at least in the short term, since we aren't using that variable.

**Comment by ThePotatoGuy** [comment]
Yes. That is the fix I am referring to.

**Comment by therationalpi** [comment]
I need to learn to read the whole thing...

**Comment by therationalpi** [comment]
Thanks for finding and fixing this, Potato!
