### ISSUE TITLE
Buttons in "Unseen text" and "Ask a question" look all weird

### ISSUE THREAD

**Issue by Lazor1234** [Backdash/MonikaModDev#940]
So i just recently downloaded the new update for "MAS" and I'm having trouble with the text appearing in the boxes and its really annoying me. Whenever I click on both of the options the corners of the selection boxes show but no text   ##appears.
![bug 1](https://user-images.githubusercontent.com/36141418/35783991-348f9a04-09d7-11e8-93ae-e5cfa95f6791.PNG)
![bug 2](https://user-images.githubusercontent.com/36141418/35783992-3599eefe-09d7-11e8-9071-b24ba73af375.PNG)

**Comment by ThePotatoGuy** [comment]
Probably a borked install. Try reinstalling the mod.

**Comment by Lazor1234** [comment]
@ThePotatoGuy Ive already done it 5 times. Nothing fixes the issue.

**Comment by Ulvsblakk** [comment]
Maybe one of your gui files is messed up. download that folder specifically and replace your current one. It might help.

**Comment by ThePotatoGuy** [comment]
Hard to say whats causing this, but I'll leave this up incase other people get the same issue. Maybe then we can figure out whats wrong.

**Comment by ArchWindswirl** [comment]
I'm having the same issue!

**Comment by ThePotatoGuy** [comment]
What's your OS?

**Comment by Olliesama** [comment]
Just pointing out that the window of the game looks like a real old windows 95 theme/OS.
