### ISSUE TITLE
[Suggestion] Saying goodnight 

### ISSUE THREAD

**Issue by PopeAesthetics** [Backdash/MonikaModDev#943]
I understand the swap over to the prompt system, but I feel that we lost a bit of connection with Monika when implementing the goodbye feature. 

I use to love telling Monika Goodnight, just for her to tell me she hoped I slept well and that she would be seeing me in my dreams. I think adding in more flexibility as to how we say bye to Monika and what she says back would make her sound a lot more fleshed out.

**Comment by ThePotatoGuy** [comment]
We're putting that back in soon. See #878
