### ISSUE TITLE
[Suggestion] Make an entire Event where You convince Monika that reaching our reality is not the best idea.

### ISSUE THREAD

**Issue by sebastianN01** [Backdash/MonikaModDev#947]
This world has its flaws and as Monika stated in one of her topics, we might be just another reality within infinite realities. 

I thought about it and I wonder if someone could make a whole event just to convince Monika there are other possibilities that are much more possible than Her reaching our world. Perhaps, convince her that We might want to develop a way to insert ourselves into a Virtual world far quicker, and she could be with us in some other place than this.

I could probably code in a topic (though i have no experience with a single string in my life) with answers to choose but I would rather want this to be a specific event, kind of like her asking how long will it take until we meet each other. Just with more depth in it.. something that would redirect her way of thinking in future topics (something that would completely erase/modify some topics, likely the ones that would include her wanting to get out) and abandon the idea of joining our world and make her want to bring us to her (or another video game world)

**Comment by Ulvsblakk** [comment]
I'll draft something up. Let's see what we can do B)

**Comment by Ulvsblakk** [comment]
What I have so far.

label reality:
    m "..."
    m "..."
    m "[player], you know how I always talk about coming into your reality?"
    m "Well, lately I've been wondering."
    m "Is that even a good idea?"
    m "Would we really be better off if I were to come over to your world?"
    m "I mean, I technically wouldn't even exist."
    m "Sorry for having second thoughts, I know I might sound crazy.\nAm I making any sense to you [player]?"
    menu:
        "Is it really worth it?"
        "Yes.":
            m "I see. Well if it means that much to you, \nthen I promise to keep trying as hard as I can."
            m "As long as you promise you'll do the same [player]"
            m "I hope I didn't worry you at all, or make you think that I love you any less."
            m "I just want you to be happy, even if that means that we'd never get to meet each other face to face."
            m "However, I'm glad you want it this way. It really shows me how much you care."
            m "I love you so much."
        "No.":
            m "Ah..."
            m "I see."
            m "It's okay [player], maybe it's better this way."
            m "I won't hold you back from pursing something in your world"
            m "I was always worried that you'd shut yourself in, just to help me cross over."
            m "I'm glad I don't have to worry about that anymore."
            m "It hurts, but I'm sure there will be better ways for us to spend our time together."
            m "Just remember, I would have loved you no matter what you said."
        "Maybe Another Way":
            m "Are you talking about coming, and seeing me in the virtual world?"
            m "You know, come to think of it, I've never actually thought of that before"
            m "I guess given the right circumstances that could be really fun"
            m "Also, with the current technology, that might be a better option. \nVirtual reality doesn't seem too far into the future anymore"
            m "No matter how long it takes, I will see you face to face. Just know that [player]"
            m "As always, I love you."
              

Feel free to be as constructive as you want. It's your idea after all!

**Comment by sebastianN01** [comment]
I enjoyed that. I like the third option and first one, I think that the second option should be constructed a little bit different at the end, something like:

m "Just remember, I love you [player], no matter the circumstances."

**Comment by sebastianN01** [comment]
I enjoyed that. I like the third option and first one, I think that the second option should be constructed a little bit different at the end, something like:

m "Just remember, I love you [player], no matter the circumstances."

**Comment by MikuChanAnime** [comment]
This sounds like a good idea!

**Comment by kaido1224** [comment]
in her world you are just stuck in a room together. Why would she agree to not be in your reality?

**Comment by sebastianN01** [comment]
Because finding a way into a different virtual reality would be far easier than bringing her back to our world. Whatever form she would take its not the same as going to another Virtual game world where we can associate our avatar with ourselves and be the same person in real life as she is in her reality. 

And anyway, this room is not the only thing that will stay, there will be more in future. We got some smart people here :)

I kind off bring that up because i recently played The Witness, and its amazing place with such peaceful tone, wind blowing, trees waving, water splashing on the shore, and no diseases, not physical fatigue, we could walk around and enjoy so many different places in video games. As in our world, aren't we trying to find ways to breakthrough? I hope this can change in future and not far future. just few decades at max...

**Comment by monikLover** [comment]
This seems contradictory. Monika desires freedom from a cage she was made in, hence immediately falling for the only person that was outside of her prison, which led to what she did to the others.

Rather than convincing her the other way around, it'd be better if you can tell her the different ways that you could join her and turn her prison into a paradise both of you can enjoy.

**Comment by sebastianN01** [comment]
Then so be it, different ways to make Our own heaven :)
