### ISSUE TITLE
Is It possible To Add Your Own Topics In Ren'py

### ISSUE THREAD

**Issue by Bam8647** [Backdash/MonikaModDev#948]
Don't worry I finally figured out how to get the mod ball rolling haha.

But compared to the original DDLC files, I haven't been able to access MAS scripts..? Is this locked from editing even if it's a download? Is there a way I could keep my own copy of MAS to be able to access the scripts?

**Comment by kaido1224** [comment]
[How To Setup MAS For Development Environment.pdf](https://github.com/Backdash/MonikaModDev/files/1697576/How.To.Setup.MAS.For.Development.Environment.pdf)
