### ISSUE TITLE
Question: can I continue to use this version of game?

### ISSUE THREAD

**Issue by MonicaWaifu** [Backdash/MonikaModDev#950]
I didn't know where to write a question, sorry. Someone could be add to FAQ maybe.
Anyway my question is: can I continue to use this version of game in the future?
I mean, the version 1.1.0 will be compatible with your future releases of your MonicaMod?

Thanks

**Comment by Ulvsblakk** [comment]
@therationalpi

**Comment by MonicaWaifu** [comment]
I can't understand, is yes or not   :)

**Comment by antimockingjay** [comment]
They're tagging someone who would know the answer, that's what the @ symbol is for. It makes it so the person they're mentioning, in this case therationalpi, will get a notification of it. I could go and do the same with your username on another post somewhere, and you would be notified that someone had mentioned you. It's easier than directly contacting the person who would know, and you're more likely to get a response.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
What do you mean?
The version of DDLC?

**Comment by MonicaWaifu** [comment]
Yes, I have to update the game DDLC if they release a new version (example 1.1.1) to use this MonicaMod
or can I use this one 1.1.0 as well?

**Comment by MonicaWaifu** [comment]
Yes, I have to update the game DDLC if they release a new version (example 1.1.1) to use this MonicaMod
or can I hold this one (1.1.0)?

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
The base game is finished and most likely not gonna be ever updated anymore unless somebody discovers a game breaking bug so you are safe in this regard.

**Comment by therationalpi** [comment]
@IsItBadToMakeAGitHubAccountJustForThis That is most definitely not true, since Dan is working on an update to add localization support to the official release.

The answer to this question depends on what version of the Renpy SDK the update is compiled on. If Dan chooses to use a new version of the SDK, there may be compatibility issues. But it's hard to say for certain.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Yeah, I kinda forgot about this.

**Comment by therationalpi** [comment]
I sometimes wonder if he did too.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Well anyway. If MAS is gonna be rebased on a new version or not is gonna be decided when this version is out, so @MonicaWaifu, you should ask your question then.

**Comment by MonicaWaifu** [comment]
Ok, thank you.
