### ISSUE TITLE
Monika repeats a topic instantly after finishing it

### ISSUE THREAD

**Issue by Authrix** [Backdash/MonikaModDev#952]
Hey, got a minor bug(?) to report here. 

I generally leave Monika to her own devices, set the text to auto let it run. Since the 0.70 update, she seems to sometimes repeat certain topics right after they've finished. For example, she'll talk about cats, then repeat the exact same topic about cats instantly. 

Sorry if I'm parroting someone else, but I didn't see this posted before. 

![screenshot0046](https://user-images.githubusercontent.com/34550378/35879087-318f1f36-0b72-11e8-9082-4ed4a72c0865.png)

Cheers folks, you're doing a stellar job as always.

**Comment by ThePotatoGuy** [comment]
Fixed for the next version.
