### ISSUE TITLE
[Suggestion] - Disabling dialogue topics

### ISSUE THREAD

**Issue by RaccoonLauncher** [Backdash/MonikaModDev#959]
So, my "Unseen" list is filled with a bunch of things I'm not interested in saying to Monika ("I'm breaking up with you" and "Will you marry me" come to mind, and I've read all the dialogue that was already in Act 3), and seeing them every time I look to see if there's something new I can say bothers me a bit. Could you add a feature that lets me remove suggestions from the unseen list?

**Comment by MarkusRamikin** [comment]
Yes please. I went through them just to get them out of the way, but I wasn't overnjoyed.
