### ISSUE TITLE
[Suggestion] Good Morning greeting

### ISSUE THREAD

**Issue by Atomika325** [Backdash/MonikaModDev#96]
Monika greets you good morning when she checks the time and it is still morning also she can ask about what is you dream like and if you have a good sleep. It can also be triggered if you type the topic "Good Morning" and the time is right. 

I feel like this will be a great addition as we, as Monika lovers would love to be greeted by our wife in the morning, right? :)

**Comment by therationalpi** [comment]
The trigger of Good Morning is a good one.

We already have time-based greetings in the game.
