### ISSUE TITLE
Poetry sharing

### ISSUE THREAD

**Issue by AnIdiotsavant** [Backdash/MonikaModDev#961]
Is it possible for the engine to send a file to the internet? I had this idea that every friday, monika would ask you if you would want to make a poem and share it with others. It would just open a text box and she would send it to reddit because the ddlc subreddit has writing weekend and she could share it there. Is it possible for the game engine to connect to the internet so send a file? and as for sharing to reddit, it could work like this: when the game is connected to the internet, game would login to a shared reddit account and the text box would be the text box for commenting in reddit. Anything written in the box is the same as writing on a reddit comment box. When you hit send, it basically just posts the comment to the writing weekend pinned message.

**Comment by ThePotatoGuy** [comment]
It's difficult enough getting in-game updates working, but it's probably possible to do what you're suggesting via sockets and the reddit api. Quite a difficulty curve, though. Anyone is welcome to attempt this, but I won't be adding this in the foreseeable future.
