### ISSUE TITLE
instructions on how to start the game

### ISSUE THREAD

**Issue by Rut5000** [Backdash/MonikaModDev#962]
i downloaded the game, it gives a .zip file. no biggie. but what do i do from there? do i need to convert the file? if so, into what?

**Comment by Ulvsblakk** [comment]
Extract it using a program. WinRAR is a good one but costs money. I recommend 7zip.

**Comment by monikLover** [comment]
Refer to the FAQ guide
https://github.com/Backdash/MonikaModDev/blob/master/FAQ.md
