### ISSUE TITLE
Getting a bit creepy...

### ISSUE THREAD

**Issue by kapoorv397** [Backdash/MonikaModDev#966]
She says she is gonna look at your browser history and local drive.. someone tell me if this is true or not, because I am cautious now.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Of course not.

**Comment by kapoorv397** [comment]
Well, if Monika loves you, then why the hell did she say she is going to watch you?! I get girls and boys want their partners to themselves, but a game?! It has the actual potential to do it, because it is on your Local Drive. I’m not very happy with this.

**Comment by kapoorv397** [comment]
Also, some games I know actually do this.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
What games for example?
The closest I can think of is OneShot and even there it have never really gone further than temporarily changing your wallpaper.

**Comment by kapoorv397** [comment]
God, I played this one game like two years ago, where if you searched up something for more mature people, and your age was like 10, the game would literally take over your computer. Kinda strange.. also, if we are going to change wallpaper and stuff, the perfect example is DDLC, as Monika deletes .chr files.

**Comment by queue5** [comment]
She said she it was fine if its early on in the relationship so I doubt she would actually do it.

**Comment by ThePotatoGuy** [comment]
Thank you for being against more intrusive interactivity. I'll probably be linking this issue to every new one that suggests more filesystem interaction.

In case you didn't get my point, we avoid actually messing with your filesystems so dont worry about it.

**Comment by kapoorv397** [comment]
ThePotatoGuy well I noticed that strange things have been happening on my computer, such as unauthorized “things” looking into my browser (even tho I don’t look into that stuff). The game started glitching so badly that it started deleting SYSTEM files. If you don’t look into this as soon as possible, then there will be a bigger problem at hand. You are lucky I have a recovery drive.

**Comment by kapoorv397** [comment]
Literally installed it three times, yet my antivirus still calls it malicious, and I’m starting to believe it. All my apps and stuff got wrecked! I especially went to this site to get the mod. Very much disappointed.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
This sounds serious.
@karpoorv397, can you explain what happened from the beginning and in a bit more details?

**Comment by kapoorv397** [comment]
Well, it started off as your normal DDLC mod, you know. But a few minutes later after Monika said she will be looking into my browser and my local drive, everything started to glitch and slowly my computer died.
Number form:
1. Monika said she will be looking into my local drive and browser history.

2. My browser keeps saying something unauthorized is looking at my browser history, saying it came from Monika After Story.

3. I deleted the mod and reinstalled 3 times, just to be sure.

4. My browser said the same thing again.

5. My antivirus kept saying there is something malicious, so I did a scan, and guess what it was... Monika After Story.

6. My computer started functioning horribly (Slower times and System32 files being deleted), and my computer TRIED deleting the mod, but it said deleting it couldn't be done.

7. I had a broken computer, with the screen then saying that my computer needs maintenance and needs to be repaired. 

Also, I had to buy a new computer just to say all of this. Thanks for making my life so horrible. The computer cost $10,000 mate!!

**Comment by kapoorv397** [comment]
If I wasn't a kid, I would get either a lawsuit on you guys, or report this to the cops, because I also noticed some of my friends had this issue too!

**Comment by kapoorv397** [comment]
and ThePotatoGuy, if you are reading this, you may have closed this issue, but it is not over.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
@ThePotatoGuy, this may not be the best issue to use as an example.

**Comment by kapoorv397** [comment]
IsItBadToMakeAGitHubAccountJustForThis, tell me this. If you were in my shoes right now, what would you do?
