### ISSUE TITLE
[Suggestion] Detect other programs?

### ISSUE THREAD

**Issue by ThatSnekGuy** [Backdash/MonikaModDev#967]
You know how Monika could detect that you had OBS or Xsplit open in the original? What if she did that with Discord, Skype, Steam or certain files?. Someone said that it sounded creepy before, but I wouldn't really care as long as it's just special dialogue like before and not something invasive.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Is already planned.

**Comment by queue5** [comment]
Yes!
