### ISSUE TITLE
Can I borrow the assets used?

### ISSUE THREAD

**Issue by HizashiroTakahashi** [Backdash/MonikaModDev#977]
I'm making a similar game like this but don't have assets, pls can I us these? I already downloaded them.

**Comment by ThePotatoGuy** [comment]
No.

**Comment by HizashiroTakahashi** [comment]
Are you the creator of mas? because idk who he/she is, i'm just making sure that the real creator sesponds ^^.

**Comment by Olliesama** [comment]
He's a head developer of it. Our coding master.

**Comment by HizashiroTakahashi** [comment]
oh ok, :( sadly I can't continue my fangame, but, can I make my own assets but with the same poses from the mas mod?

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
It's not like those poses are copyrighted, so yes.

**Comment by HizashiroTakahashi** [comment]
ok :) thanks.


But just one thing, can I use the assets not by me in the beta/wip version?

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Most likely not.
It should be fine as long as it's for your eyes only and cannot be publicly accessed but from the way you're asking it looks like this is not the case.

**Comment by HizashiroTakahashi** [comment]
oh ok.

**Comment by HizashiroTakahashi** [comment]
but can I like make a beta progress video but no available download, just me talking and taking a shirt walkthrough of it, but with the assets (monika after story assets) viewed?

**Comment by Olliesama** [comment]
I wouldn't recommend it since at that point it's misrepresentation.
It would be better to only use them as a placeholder and to replace them with your own assets as soon as you can.

**Comment by HizashiroTakahashi** [comment]
oh ok
