### ISSUE TITLE
Version 0.5.0 Typos

### ISSUE THREAD

**Issue by Ezr91aeL** [Backdash/MonikaModDev#98]
I've opened this issues thread to have a place where we can signal all the misspell and the other little issues in the game.

In particular I have one to signal:
https://imgur.com/AOhfmqI
It's in the part where she speaks about Mythology, she says sacrfice instead of sacrifice. (version 0.5.0 preview)

**Comment by Jxhnathan08** [comment]
Hmm, I could've sworn typos were fixed.

Noted, this will be fixed ASAP.

**Comment by Jxhnathan08** [comment]
Typo has been fixed. Please let us know about other things you find! @Ezr91aeL

**Comment by Jxhnathan08** [comment]
Also, if this will serve as a misspells/typo issue.. Please change the title accordingly!

**Comment by Sloogen** [comment]
She says "aganist" rather than "against" when you say the word pong to her.

**Comment by Jxhnathan08** [comment]
Fixed @Sloogen

**Comment by therationalpi** [comment]
Closing this for the current version. We'll probably have more typos to fix for version 0.5.1, though.
