### ISSUE TITLE
[Suggestion] - Giving Monika gifts

### ISSUE THREAD

**Issue by RaccoonLauncher** [Backdash/MonikaModDev#982]
Monika's dialogue saying she hoped she could add coffee one day made me realize: What if we could give her coffee? It could be another option to give Monika gifts, like coffee, flowers, cupcakes, or even completely oddball things. Maybe it could be time-limited, so the gifts would really be something special, and not cheapened, and she could have special dialogue for each gift, and possibly different dialogue for giving the same gift multiple times (so we could have a chain of dialogue that's related to past dialogue for coffee, and a chain for flowers, or for various things, but the list would be randomized, so it might be a few days between times when you can give her coffee). I think this would add a lot, and be something great to look forward to on a periodic basis, as well as serving as several long-term mini-storylines. And maybe certain dialogue could unlock certain gifts-for example, after she tells us soda is unhealthy, we could give her some soda, and she could reluctantly admit that she really enjoys it the first time, then tell a story about it the second time, and so on.

**Comment by AnIdiotsavant** [comment]
why not give her an actual gift? Like, we make a file to manually put in a specific folder. And the next time we open the game, she says special dialogue to thank us for it.

**Comment by AnIdiotsavant** [comment]
For example. For valentines, you wanna give her chocolate, right? So you download a file here called "chocolate.chr" and add it to the character files. When the game reads this file, the game opens with some chocolate on the desk with her fingers smudged with them. She thanks you for the chocolate and for spending time with her on valentines. The next time you open the game, the chocolate is gone but the wrapper is still in the desk. She says she finished it but wanted to keep the wrapper as a memento. Now you got a chocolate wrapper stuck in the desk permanently

**Comment by RaccoonLauncher** [comment]
That would be amazing! And each gift could serve as a piece of scenery, too, to make the room customizable to that extent... Wow.

**Comment by monikLover** [comment]
@AnIdiotsavant We already had something in the works for V-Day update before this issue was posted

**Comment by AnIdiotsavant** [comment]
the, welp :P
