### ISSUE TITLE
[Suggestion] - The Fan pack

### ISSUE THREAD

**Issue by DjSquishy777** [Backdash/MonikaModDev#983]
I think i'd be funny if she talked about it if you bought it....

**Comment by Olliesama** [comment]
Just a contributer, but have taken note of your suggestion.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Doesn't she already?

**Comment by Olliesama** [comment]
Not that I'm aware of.

**Comment by TacticalTriangle** [comment]
This was suggested #357 . It was accepted but not implemented yet.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I thought she had a topic where she checked for the booklet pdf and then talked about Dan.

**Comment by monikLover** [comment]
The 1st submission of this idea was rejected since it was written in a very poorly way.
