### ISSUE TITLE
[Suggestion] More things to do with Monika

### ISSUE THREAD

**Issue by LordOfDeath35** [Backdash/MonikaModDev#984]
I just had the idea that you could add something like wathing movies, sitting on the couch, etc to the game. That would probably make it more realistic. (And Monika also tells us that she´d love to sit on the couch together, etc. This is just an idea and doesn´t have to be implemented in the game. What you could also add would be sth like actually listening to music together, doing some sort of tasks (Math, Biology, etc). I´d also love for Monika to say sth like "Take care" or "Have fun in school", etc. I hope, I could maybe inspire you to add things like that. I really like this mod and would love to see it grow even more.

**Comment by monikLover** [comment]
Watching something with Monika is already a planned feature in #628
