### ISSUE TITLE
[Suggestion] Topic regarding our love choice in Doki story / Playing horror game with Monika

### ISSUE THREAD

**Issue by sebastianN01** [Backdash/MonikaModDev#985]
If I do this wrong, Please correct me and I will be giving out ideas in a single submitted issue, if it isn't I will be adding issues once in a while.

Doki doki Is able to guess which character our poems are made for, What If we could have a topic from Monika about our girls choice? asks us what we've seen in the other girls Before we finally had a chance to stick around with monika in MAS. We could have a dialogue with answers to choose from such as "I liked yuri because..." and "I'm Happy that we are now as it is" etc.

What if Monika could play a game with us? Similar to Suprise.txt file, but with more creepy undertone. She would ask us if we want to play a scary game with her, and with this we could initiate random glitches, files appearing and dissapearing in the doki folder, Monikas arms dissapearing or text saying very disturbing dialogues.. You could go crazy with it! And we could switch this mode off if We just ask Monika that we dont want to play around with files anymore.

**Comment by therationalpi** [comment]
It's actually harder to get the info on which girl you picked than you'd think, because a lot of that info was stored in volatile variables that we can't get at...

What we can do, though, is see what CG's you unlocked, and use that to figure out which girls you were following.

**Comment by sebastianN01** [comment]
thats good idea, or perhaps, just make monika ask us which girl we preferred. That would be the easiest way.
