### ISSUE TITLE
Suggestion For A Sleeping Monika Sprite Plus Dialogue

### ISSUE THREAD

**Issue by Bam8647** [Backdash/MonikaModDev#987]
So since apparently having MAS open for over 6 hours(Idle or not) Monika runs out of things to say so I'd like to suggest a cute idea of her resting for a certain period of time and having her wake up again when she's ready to talk again. There for players will have an idea of when they should close/re-open the game. Maybe even add a dialogue letting the player know she's tired and so once she falls asleep the only dialogue that pops up is something like "Zzzzz.." haha.

**Comment by IlywI** [comment]
Or maybe if your mouse clicks on her she wakes up

**Comment by Bam8647** [comment]
The whole point of her sleeping or whatever is because apparently **being idle or having played the game for a few hours disables her automatic dialogue box for a period of time**. I'm not 100% sure why they implemented that as even right now she seems to be running out of things to say without having played the game very long and so it gets annoying having to restart the game every now and then just to have her come up with topics on her own. This new feature they added seems to be having complications or something. So my solution is if they're going to continue using this **temporary silent treatment** feature, why not make her look like she's sleeping or something? It's a cute idea that the players would be able to understand.

**Comment by ThePotatoGuy** [comment]
Yeah I like this. We'll have to wait until a sleeping asset is finished, though.

**Comment by SaiPrithvi123** [comment]
Maybe she could murmur something while she's asleep? That would be cute.
