### ISSUE TITLE
Have You Ever Written A Story?

### ISSUE THREAD

**Issue by littlemisteruniverse** [Backdash/MonikaModDev#988]
After playing for a while and seeing the topic on how Monika asks if you've ever written a story and that she'd love to read one if you have, I thought it'd be neat if you could program it so she could recognize a .txt file in the game folder, like how she knows when you put a new .chr file in the characters folder, if that's possible. Just a thought!

**Comment by ThePotatoGuy** [comment]
I don't think we could get monika to comment on the content of a story. That's just way too variable.
