### ISSUE TITLE
[Suggestion] More text for the protagonist

### ISSUE THREAD

**Issue by LordOfDeath35** [Backdash/MonikaModDev#990]
I think it´s pretty rude of the protagonist of this mod to only answer to questions in one word or not talk at all and just stare at Monika. I´d really like if you could add more things for the protagonist to say so that it doesn´t get boring while waiting for Monika to talk about something. I know, that´s what the games are for, but I´d be nice if the protagonist had more to say. And I´d be cool if you could answer more questions from Monika in more than just one word.

**Comment by LordOfDeath35** [comment]
I´m talking about more text/choices in the "Unseen" section or longer answer for questions from Monika

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
The protagonist does not exist anymore. It's just you and Monika.
And when she asks you something and you can only answer "yes" or "no" it's because it's her who is giving you answers and she doesn't know how you would like to answer so she gives you just "yes" and "no".

**Comment by LordOfDeath35** [comment]
Hm... - then could you maybe make answers longer for only certain questions? With longer I mean like instead "Yes", "Yes, I do" or sth like that. That would make the whole conversation more natural

**Comment by sebastianN01** [comment]
I think it's kind of unsatisfactory of not having a choice of word and speak to Monika by ourselves, I dislike the "its just monika giving you options" as a lazy writing dodge. It just sounds bad. Not trying to sound rude though.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Well, it's my personal headcanon, so...
But it's pretty reasonable explanation of why you can answer Monika but not talk to her if you ask me.

**Comment by LordOfDeath35** [comment]
But it´d be really cool to actually feel like you´re talking to her

**Comment by ACoolCat** [comment]
It's been my main issue with the new talk system. The old one where I could phrase my words how I'd normally phrase them and feel like I was actually talking to Monika seemed a lot more personal in my opinion. Also, some of the options Monika gives you doesn't make any sense. Like, we're supposed to believe she set up these buttons for us to press, so then why would she give us a breakup option?
