### ISSUE TITLE
[Suggestion] Go, the board game

### ISSUE THREAD

**Issue by MarkusRamikin** [Backdash/MonikaModDev#991]
Gnugo should be relatively easy to implement, but apparently there are stronger open source engines out there:

https://www.quora.com/What-is-the-strongest-open-source-Go-AI

I find the chess implementation in MAS to be a great success. I enjoy how I can just sit down and play, with automatically adjusted difficulty, without needing to control a gazillion of options like in dedicated chess programs. Having Go as an option as well would be lovely.

**Comment by kaido1224** [comment]
Although I think this is a good idea I don't know how many people who play MAS know how to play go. It would probably have to be written on how to play the game.
