### ISSUE TITLE
[Suggestion] Topic about books, you read

### ISSUE THREAD

**Issue by LordOfDeath35** [Backdash/MonikaModDev#993]
I´d really like the mod to have a topic about the books that you read. Monika mentions it quite often that she´d like to talk about the books you read, so I think that this would be a great addition to the game. Of course it would be near impossible to add every single book. Instead you could give a choice of genre andd add like 5 books to each genre. I know that this will take a long time but it would also be really cool. Please consider adding it to the mod in the future.

**Comment by ThePotatoGuy** [comment]
[[ We'll repoen this when we look into it]]
