### ISSUE TITLE
[Suggestion] A way to avoid Monika repeating the same message

### ISSUE THREAD

**Issue by LordOfDeath35** [Backdash/MonikaModDev#995]
I just thought a bit about it. If you´re implementing a diary from Monika, maybe you could code it in a way that everything that happened on one day is written in the diary and won´t be repeated. This could be acomplished through coding it the way that every topic which is written/moved to the diary won´t be repeated because the "random topic" thing you have in your code is not allwoed to pic topics that have been moved there. This is only a thought of mine and I´m not sure if it would work. You can try it if you want.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
There actually already is a feature to keep topics from repeating. If you are getting repeated topics it means that either she is out of new topics or the feature is bugged.
BTW. As far as I know, the diary is going to use this feature itself.

**Comment by LordOfDeath35** [comment]
Ok - I didn´t know that - just wanted to give my opinion on it
