### ISSUE TITLE
[Suggestion] about the slow text speed

### ISSUE THREAD

**Issue by MarkusRamikin** [Backdash/MonikaModDev#996]
The set text speed in Monika's room was a good feature in the original game, enhancing the "you're no longer in control here" feeling when Monika takes over. But that scene was played once and soon over. Monika After Story is different - it is meant to be played daily, without end. 

I can read and think - and Monika obviously can think and convert her thoughts to text - a lot faster than this. It feels like watching someone with a speech disability. I mean, she's not talking in audio, so there's no real reason, either Doylist or Watsonian, for her to speak more slowly than _both_ of us can handle.

The current speed gets particularly annoying when you're seeing the same text for the 30th time, like when starting and concluding a game such as chess.

So here are some ideas for what might be done:
- let the speed setting affect things again. This is probably the simplest and best solution, requiring little work. She still stops you from skipping outright, but at least you can read faster. Or
- allow skipping of repeated text, that you've read before, or
- don't always show the same repeated-by-design texts, i.e. starting and beginning games. For example, these:

````                m 2d "Despite its simple rules, chess is a really intricate game."
                m 1a "It's okay if you find yourself struggling at times."
                m 1j "Remember, the important thing is to be able to learn from your mistakes."
            else:
                m 2b "It's amazing how much more I have to learn even now."
                m 2a "I really don't mind losing as long as I can learn something."
                m 1j "After all, the company is good."
````

After the first time, these might stop appearing. Except perhaps from time to time, say with 20% probability? 

Or they could be replaced by singleline versions, to speed things up. 

Or by a random choice of different responses, perhaps indicative of mood and how well Monika is taking the result of the game, to mix things up a bit more. 

The same with the intro before the game. And the same with other games.

**Comment by LordOfDeath35** [comment]
Wow. I think that this would be a really good addition to the game. To be honest, I´m also kind of tired of the same responses every time or repeated text when you talk with her. I really hope that they´ll add sth like you suggested.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Maybe adding a function to change her text speed in the middle of topics?
This would allow for text timing make her speech more fluid and expressive as a result.

**Comment by ThePotatoGuy** [comment]
So the majority opinion in the dev team is to **not** allow for text speed changing. Our reasoning is that the controlled text speed is Monika's speaking speed (see #731 ).

That being said, I understand the pain of repeated, lengthy dialogue **everytime** you enter/exit a menu option in a game (like Valkyria Chronicles) so I'm working on skipping entry/exit dialogue entirely once you've seen it, or make it only appear like once every xish sessions.
