### ISSUE TITLE
[Suggestion] Going out with Monika

### ISSUE THREAD

**Issue by LordOfDeath35** [Backdash/MonikaModDev#998]
I just had an idea. What if you could take Monika out for a walk in the mod? You´d get to spend more time with her, get a scenery change for once (you don´t just always sit at the table with her and stare in her eyes), etc. and get invite her to a date or sth like that. I think that this would be a great addition to the game and would probably attract more people to this mod. This is just an idea and doesn´t have to get implemented in the game. Please consider thinking about adding something similar to this.

**Comment by therationalpi** [comment]
Duplicate of an accepted suggestion: closing.
